### ISSUE TITLE
About page: Implement Updates

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1000]
Please update https://mozillafestival.org/about based on revised design mockups based in issue: https://github.com/mozilla/mozillafestival.org/issues/983

**Comment by Saallen** [comment]
HEY
Design looks great and ready to go live but the photo of mark should be 
![snap-fore-msurman c45cce6ceade](https://user-images.githubusercontent.com/10194015/43084554-d4208c7a-8e90-11e8-8b2e-a53c645aa7d0.jpg)

**Comment by Saallen** [comment]
Plus 🎆 on issue 1000 🍾

**Comment by mmmavis** [comment]
@Saallen we updated Mark's photo on the team page few weeks ago. Do we wanna use the same photo? Or the one you included above?

https://mozillafestival.org/team/production

**Comment by sabrinang** [comment]
We have changed it to match the hi-res leadership photo https://foundation.mozilla.org/about/leadership/

**Comment by sabrinang** [comment]
note: from our discussion, we are leaving mark's photo as is (lilac shirt headshot)

**Comment by mmmavis** [comment]
Live now! https://mozillafestival.org/about

**Comment by mmmavis** [comment]
Reopening - seems like the old page is still cached. Will close this ticket again once I am able to see updated version of about page live.

**Comment by mmmavis** [comment]
Okay here we go - https://mozillafestival.org/about
