### ISSUE TITLE
Why Come to MozFest page: Implement Updates

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1001]
Please update https://mozillafestival.org/expect based on revised design mockups based in issue: https://github.com/mozilla/mozillafestival.org/issues/982

@Saallen We are changing the name for this section, would you also want to change the URL to match it?

**Comment by mmmavis** [comment]
Hey @Saallen two questions 

1. What URL do we want to change it to?
2. How do we wanna handle traffic coming to https://mozillafestival.org/expect ? 404? Redirect? Or?

**Comment by mmmavis** [comment]
Per discussion

> What URL do we want to change it to?

`/why-come-to-mozfest`

> How do we wanna handle traffic coming to https://mozillafestival.org/expect ? 404? Redirect? Or?

Redirect `/expect` to `/why-come-to-mozfest`

**Comment by mmmavis** [comment]
Live! https://mozillafestival.org/why-come-to-mozfest
