### ISSUE TITLE
Home page: Implement Updates

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1007]
Please update https://mozillafestival.org/ based on revised design mockups based in issue: https://github.com/mozilla/mozillafestival.org/issues/962

**Comment by mmmavis** [comment]
@sabrinang @Saallen when do we want this updated homepage design to go live? Will it be after August 1 since the CTA on [the design](https://redpen.io/cs6aa0082d55d20d65) is "get tickets" instead of "submit proposal"?

**Comment by sabrinang** [comment]
We would need to update the homepage to close proposals after August 1st submission deadline. With the proposal CTAs removed, I assumed it would get replaced with get tickets CTA next. 

@Saallen to provide desired date to go live and confirm CTA

**Comment by Saallen** [comment]
Hello @mmmavis and @sabrinang 
I think if we move the CTA for proposals around now,  it will confuse ppl esp in the last few days.
I think we should make this page live as the very last thing you do on Aug 1st Mavis.

I would advise just removing the proposal form page from the website and keeping that url live  until the Friday, as there is always stragglers. Then it closed forver on Friday
