### ISSUE TITLE
Typo on Main page

### ISSUE THREAD

**Issue by KGorr** [mozilla/mozillafestival.org#1016]
"explore the intersecton of the web"

Intersection is missing the "i"

<img width="997" alt="screen shot 2018-07-27 at 9 07 43 am" src="https://user-images.githubusercontent.com/14793388/43332237-a25abd84-917c-11e8-9f36-a704636783b7.png">
 
@mmmavis

**Comment by devshiva619** [comment]
@KGorr can I work on this?

**Comment by sabrinang** [comment]
The homepage https://mozillafestival.org/ has been updated as call for proposals has closed. This design version excludes the what is MozFest like section so this typo is gone too - closing issue.
