### ISSUE TITLE
Close CFP: Homepage and Spaces page updates

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1018]
Global updates to be made:
- remove `Submit your session now for MozFest 2018!
Submission deadline is August 1.` top bar
- remove `proposals` from navigation

Homepage updates to be made:
- remove `Submit Your Session Now` cta button 
- change Join Us at MozFest section's body copy to `Get your ticket for MozFest weekend.` button copy to `Buy Tickets` that links to https://mozillafestival.org/tickets

Space page updates to be made:
- remove `Propose a Session` button from https://mozillafestival.org/spaces

by EOD PDT August 1st

**Comment by mmmavis** [comment]
Done and live: https://mozillafestival.org/
