### ISSUE TITLE
Close CFP: Proposals page updates

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1019]
Update copy on proposals page to indicate that CFP is now closed (reference [last year](https://github.com/mozilla/mozillafestival.org/issues/657#issuecomment-318754720)). 
Show closing message by EOD PDT August 1

**Comment by sabrinang** [comment]
Copy:

**The MozFest 2018 Call for Proposals has ended.**
Curation takes place [here on Github](https://github.com/MozillaFoundation/mozfest-program-2018) during the month of August. If you submitted a session, expect to hear from us in September. Thank you to everyone who proposed a session!

**Comment by mmmavis** [comment]
Just a correction in the link included above - repo should link to https://github.com/MozillaFestival/mozfest-program-2018 instead

**Comment by mmmavis** [comment]
Changes are live https://mozillafestival.org/proposals
