### ISSUE TITLE
Team page: Add Art & Data Experience Wranglers

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1022]
Update the team page with Art & Data wrangler bios and profile photos.

Bios here: https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0

Photos (500x500) here: https://drive.google.com/open?id=1Bf6Jts4aVP5O8bcA8fZoYcuM9PdM5Nk7

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team/wranglers
