### ISSUE TITLE
Team page: Add Gaming MozFest Experience Wranglers

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1023]
Update the team page with Gaming MozFest wrangler bios and profile photos.

Bios and photos to be collected.

**Comment by mmmavis** [comment]
Copy ticket is here: https://github.com/mozilla/mozillafestival.org/issues/1021

**Comment by gideonthomas** [comment]
Closing to have a single ticket with all the content updates to the `/team` page
