### ISSUE TITLE
Home page: Feature Theme Content

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1025]
Feature the theme this year, `Data and You`, in a section on the website to introduce and contextualize it at the festival for attendees.

Create copy that includes a description which may include a link to a blog post.

**Comment by gideonthomas** [comment]
@zee-moz is it possible to get copy for this by the end of next week?

**Comment by gideonthomas** [comment]
Moving to the next heartbeat.

**Comment by zee-moz** [comment]
@gideonthomas @sabrinang @Saallen can you let me know the word limit for this? Are we also adding images or anything else? And do you have a blog post in mind that you're hoping to link to, or is that also part of the content that needs creating? :)

**Comment by Saallen** [comment]
Hey lets go with 120 words max

**Comment by Saallen** [comment]
Let me answer the blog question tomorrow

**Comment by Saallen** [comment]
@zee-moz any update here??

**Comment by zee-moz** [comment]
Draft text is here, sent out for review 8/31. @Saallen @KevZawacki  reviewed, no word from @Lottarao
If we can go ahead without Lotta's feedback, then this is good to go.  
https://docs.google.com/document/d/1O1fn5JGI09COZnK8HDLm8sorHYpGkhcErVIsGYqsOro/edit

**Comment by Saallen** [comment]
Lets go with Kevin having shared this with Lotta- approved

**Comment by gideonthomas** [comment]
Thanks @Saallen and @zee-moz! Filed design ticket: https://github.com/mozilla/mozillafestival.org/issues/1092
