### ISSUE TITLE
About page: Update Printed Guide Link

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1026]
- Update link to the guidebook schedule and decide where it is linked (navigation?)
- Update link to the printed festival guide and decide where it is linked (hosted on issuu?)

**Comment by gideonthomas** [comment]
@sabrinang does https://github.com/mozilla/mozillafestival.org/issues/1059 cover the first point? If so, can we scope this issue to just be about the link to the printed guide, and assign someone to provide copy?

**Comment by sabrinang** [comment]
@gideonthomas 

Yes, the other issue does cover linking to the schedule now. 

+1 this issue can be about uploading the printed festival guide https://github.com/mozilla/mozillafestival.org/issues/1031 (which will be finalized Oct 5) on to https://issuu.com/mozfest so it can be linked to with provided copy.

**Comment by gideonthomas** [comment]
Perfect, I put this in the final milestone for MozFest since it's a small task that is blocked by content and production of the printed guide.

**Comment by gideonthomas** [comment]
@Saallen let me know when you have the issuu link to the festival guide.

**Comment by Saallen** [comment]
![screen shot 2018-10-17 at 19 56 06](https://user-images.githubusercontent.com/10194015/47109651-b9b52400-d246-11e8-99f1-476786cfd325.png)
Yahhh its live

**Comment by gideonthomas** [comment]
Awesome, @Saallen what is the link to it?

**Comment by gideonthomas** [comment]
in the meantime, @sabrinang do you have a suggestion as to where you would want the online festival guide to be linked?

**Comment by sabrinang** [comment]
@gideonthomas 
It was previous linked from the old What to Expect page but since we don't have it anymore the About page would make sense.

I found the link here: https://issuu.com/mozfest/docs/mozilla-festival-2018-festival_guid
The URL is missing an e and the double page spreads are uploaded as a page. Do you need the guide to exported differently or something you can fix in Issu?

**Comment by gideonthomas** [comment]
Thanks @sabrinang, @Saallen are you able to fix that in issu?

**Comment by sabrinang** [comment]
@Saallen Here is the online pdf as single pages: https://drive.google.com/open?id=1sxxqW-zUZnAIRKdYLmBtw_auoGRh1cR7

**Comment by gideonthomas** [comment]
@Saallen let me know when it's uploaded (with the link)

**Comment by Saallen** [comment]
Updated https://issuu.com/home/published/mozillafestivalguide

**Comment by gideonthomas** [comment]
@mmmavis could you add a button like the one Natalie designed here: https://github.com/mozilla/mozillafestival.org/issues/1029#issuecomment-430803406 and add it below the hero text. The button should say "View the 2018 Festival Guide" and link out to https://issuu.com/mozfest/docs/mozillafestivalguide

**Comment by mmmavis** [comment]
Done!
