### ISSUE TITLE
Sponsors page: 2018 Sponsors and Categories

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1027]
More sponsors will join us as we get closer to MozFest. Collect an ongoing list of the 2018 sponsors along with their sponsorship type.

This will be seen on https://mozillafestival.org/team/sponsors

**Comment by gideonthomas** [comment]
@sabrinang, who can be responsible for gathering this data here? Can we do it in sets so that we add a set of sponsors once per heartbeat? The data collection process can happen throughout each heartbeat though.

**Comment by sabrinang** [comment]
@gideonthomas 

The fundraising team @jessiekeating and @jcbarajas are gathering sponsors for MozFest 2018 so they will provide content a new 2018 section on https://mozillafestival.org/team/sponsors 

We have not coordinated how often we want to update the page or when but we can update in sets each heartbeat if we have content ready.

**Comment by consuelamckenzie** [comment]
Production and the sponsorship team meet on Fridays, we will discuss and update this feed with the forward plan. @gideonthomas @sabrinang @jcbarajas @jessiekeating

**Comment by gideonthomas** [comment]
Thanks @consuelamckenzie, would you be able to take point on that and update this thread as content comes in? On the website, we will take the content from this ticket and update it once every two weeks.

**Comment by gideonthomas** [comment]
@consuelamckenzie just a note from @Saallen, the photos need to be high res. Could you also provide an update (based on feedback from @jcbarajas) on how you would like the layout to be (e.g. are we showing tiers of sponsors, is there an order to the sponsors, etc.).

**Comment by Saallen** [comment]
I can responde in regards to layout- yes we would like them in their tiers @gideonthomas

**Comment by gideonthomas** [comment]
Awesome, thanks @Saallen, would you also be able to check out the link for Sticker Mule posted above? It links to a hexagon sticker website on stickermule instead of the main stickermule page.

**Comment by Saallen** [comment]
Hey @gideonthomas checked and they requested
 logo: https://www.stickermule.com/assets/images/stores/sticker_mule/press/downloads/logo-colored/Sticker-Mule-logo-SVG-e614db0061.zip

link: https://mule.to/mozfest-2018

**Comment by gideonthomas** [comment]
Got it! I'll manage this comment to curate all the sponsors in one place. Please continue to add sponsors in this thread.

### Sponsor List
Name | Image | Link |
--- | --- | --- |
Sticker Mule | [Image](https://www.stickermule.com/assets/images/stores/sticker_mule/press/downloads/logo-colored/Sticker-Mule-logo-SVG-e614db0061.zip) | [Link](mule.to/mozfest-2018) |

**Comment by consuelamckenzie** [comment]
@sabrinang @gideonthomas 
Box and Apple are still pending answers, but at this point are seen as a bonus. The sponsorship team are set on these sponsors for Mozfest 2018;-

Name | Image | Partnership Type | Link
-- | -- | -- | --

Sticker Mule | [Image](https://www.stickermule.com/assets/images/stores/sticker_mule/press/downloads/logo-colored/Sticker-Mule-logo-SVG-e614db0061.zip) | Closing Party Partner | [Link](https://mule.to/mozfest-2018)
Private Internet Access | [Image](https://drive.google.com/open?id=1-qpa-oANqW6xFgtitQc2VZyUlSTpRihe) | Presenting Festival Partner | [Link](https://www.privateinternetaccess.com)
Internet Society | [Image](https://assets.internetsociety.org/Styleguide/#page/029105C2-BD06-4184-9C413CD5BAB15B76) | Science Fair Partner | [Link](https://www.internetsociety.org/)
Samsung | [Image](https://drive.google.com/open?id=1SDf1_ndD_cH42uBU39QZJ6iYvhyqHZ9s) | Youth Zone Partner |[ Link](https:/`/www.samsung.com/uk/apps/samsung-internet)

**Comment by gideonthomas** [comment]
Filed implementation ticket: https://github.com/mozilla/mozillafestival.org/issues/1118
