### ISSUE TITLE
Home page: Live Weekend Content

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1029]
Update the home page to feature live content to drive participation. Scope out what this content is and how we will implement it.

**Ideas**
- Dialogues and Debates live stream
- connect to foundation.mozilla.org? (Alan)
- feature remote participation content? (Jen C)

**Comment by marcwalsh** [comment]
@sabrinang that's an interesting topic about live streams on the Mozilla Festival page.

We'll most likely be streaming to YouTube which we could embed on the site. There's a couple of ways it would work:

- Individual live streams for each talk / panel (would require updating the website for each stream)
- Day Streams (Updated overnight and we turn off the stream at the end of each day, but a website update will be needed overnight)
- Two Day Stream (Needs content overnight, so if there's an issue overnight it wouldn't look great!)

I'm currently talking to the closed captioning provide to see about getting captions added onto the YouTube video. There might be a cost implication if we need this stream running between talks / overnight.

**Comment by gideonthomas** [comment]
@marcwalsh are there any updates on this?

**Comment by gideonthomas** [comment]
Ok perfect, thanks @marcwalsh! Just so I understand the scope of work, are we embedding this video (wherever it's hosted) on the MozFest website, or are we just going to link to it, or something else?

**Comment by marcwalsh** [comment]
@gideonthomas @mmmavis - I'm meeting with Andy K later this week to confirm this, however the easiest way of implimenting this would be to embed the Mozilla YouTube Channel Stream. 

This means a single video across the weekend that the AV team are able to stop and start the stream without requiring a change to the website over the weekend. 

I'll send you the link / embed code once confirmed.

**Comment by gideonthomas** [comment]
Thanks @marcwalsh! @sabrinang where would you place the embedded video on the homepage?

**Comment by mmmavis** [comment]
Hey @marcwalsh Andy already forwarded the embed code to me. And yes, I'd like to know where we want to place it.

@gideonthomas we should check with cade to make sure MozFest site can handle that much traffic (if we are planning to direct a ton of people to the site to watch D&D live stream)

**Comment by marcwalsh** [comment]
@mmmavis @gideonthomas 

I had a chat with Andy yesterday and we agreed that using the Mozilla Channel Live stream would be better than having two different embed codes for each day. One, to avoid any pushes over the festival weekned and also becuase there might be caching issues where the embedded video may not update for some users.

New embed code is below. This should be pushed as close to the festival as possible, as it will show anything that is live on the Mozilla YouTube channel.

`<iframe width="560" height="315" src="https://www.youtube.com/embed/live_stream?channel=UCajipi80aORRDz6gZ8ZyCWw&autoplay=1" frameborder="0" allowfullscreen></iframe>`

**Comment by gideonthomas** [comment]
@natalieworth we want to replace the play button on the mozillafestival.org page to a button (or text above a button with shorter text) that says something like "Watch the Dialogues and Debates Live" which will open up the video (as the play button currently does) to the live stream. Is this something you can design?

**Comment by natalieworth** [comment]
Updated the button design:

<img width="946" alt="screen shot 2018-10-17 at 2 42 36 pm" src="https://user-images.githubusercontent.com/14876567/47118587-8a89bd00-d21c-11e8-8f12-a15155e45706.png">

**Comment by gideonthomas** [comment]
@Saallen how does that look? ^

**Comment by Saallen** [comment]
Will it have that hero in the background? as would rather not have three guys ......

Otherwise, I think it looks great- thanks

**Comment by natalieworth** [comment]
@Saallen I like having the mozfest video still run in the background? Is that okay? I think it's a nice effect.

**Comment by gideonthomas** [comment]
yep, the background in the hero is outdated...it will still be whats currently on mozillafestival.org

@mmmavis would you be able to add the button @natalieworth designed above? It should still open up the video, but the video shown should be from the embed code you have.

**Comment by gideonthomas** [comment]
Done
