### ISSUE TITLE
Festival (Printed) Guide Content Meta-Ticket

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1031]
This is a meta-ticket for all the printed Festival Guide content.

**Kick off meeting on August 9th:**
- determine an outline of the content
- determine who is writing the content
- determine who is edit/proofreading

**Content:**
-  To be determined

**Timeline:**
[Aug 13-Sept 7] Creating content and writing copy
[Sept 7] Content deadline and copy draft
[Sept 14] Print Concept Specifications + Pagination Outline
[Sept 21] Copy revisions & Design draft version 1
[Sept 28] Copy editing & Design revision version 2
[Oct 5] Final review and export finalized files 
[Oct 8] Send to print

**Reference:** 
2017 Github Meta Ticket: https://github.com/mozilla/mozillafestival.org/issues/691
2016 Github Meta Ticket: https://github.com/MozillaFoundation/Mozfest2016_production/issues?q=is%3Aissue+festival+guide+is%3Aclosed+label%3A%22Festival+Guide%22

2017 Festival Guide on Issuu: https://issuu.com/mozfest/docs/mozfest_2017_festival_guide/
2016 Festival Guide on Issuu: https://issuu.com/mozfest/docs/mozfest-2016

**Comment by sabrinang** [comment]
Note: We should have the sponsors finalized too (latest Sept 28) to be printed on the guide too
Example from last year:
![20171027-mozfest-swag-18](https://user-images.githubusercontent.com/2492510/32967993-7d894d4e-cb94-11e7-8ef0-5749eae94246.jpg)

**Comment by sabrinang** [comment]
@Saallen @consuelamckenzie @marcwalsh 
I started a doc for Thursday's meeting on content [here](https://docs.google.com/document/d/1_VQ4ye6r_8JJ6RAXhATcMXOTciUq0owStN-tkPPEPms/edit). This is evolving from the content structure from last year and included ideas of what to update to fit 2018. 

Please come with ideas or add to the doc before the meeting for the festival guide so we can consolidate ideas on Thursday and start filing content issues for the next milestone on Monday.

**Comment by gideonthomas** [comment]
Deadline for content and review set for September 9, 2018.

**Comment by Saallen** [comment]
@zee-moz any update here

**Comment by zee-moz** [comment]
@Saallen @gideonthomas content should be ready for review by 9/6. 9/9 is a Sunday, so is the business day deadline actually 9/10, a Monday?

**Comment by gideonthomas** [comment]
yes, if the reviewed content is ready by Monday, that would be great. @Saallen does that work for you?

**Comment by zee-moz** [comment]
@gideonthomas @sabrinang @Saallen 

Hi all, here's the document with the [first draft program copy](https://docs.google.com/document/d/1E7hHGmiqRS9ggZR71TQPNEpdY0BlNfi7IiaQTyO4Abk/edit#). A few notes: 

- I recommend using an insert to highlight MozFest House activities, and add inserts to those guides distributed before the festival weekend only.  MozFest House is name-checked in the welcome pages, but I think devoting a full page to something most people who have the guide (weekend attendees) will have already missed is a recipe for disappointment or confusion 😞 
- I've grouped the wranglers bios with the full space narratives-- this connects the people with the work and ideas more directly. I also think these narrative snapshots of the teams' thinking about each issue is key framing for the experience, and will be something for readers to return to after the festival. 
- Both the experience descriptions and the space narratives could be edited for length, but I am VERY wary about making changes to these as they represent each team and their voice. I can def. do it, but will defer to the production team (and the original authors) about making edits
- Sabrina and I discussed shortening the Wrangler bios, and I could edit these, but am cautious about misrepresenting anyone
- I've added an number of options for fun random "activity" pages. Can certainly brainstorm more if these aren't interesting enough.

Thanks! 😸

**Comment by zee-moz** [comment]
@Saallen I reviewed your suggestions and made edits. i've pinged @KevZawacki about a few stylistic things. 

@sabrinang as we are using the shorter descriptions to introduce each wrangler section, we may need some icons for the space graphic (which I think is a nice element, and which we should keep for this year, but I personally wouldn't repeat the exact same copy in the graphic and the heading)

**Comment by Saallen** [comment]
This is not completed yet
Needs input from 
-[ ]  @KGorr on how to stay engaged
-[ ] @consuelamckenzie  for sponsorship
-[ ] @consuelamckenzie for manifesto
- [ ] Final review by me

**Comment by KGorr** [comment]
Added suggestions to my section. Thanks!

**Comment by zee-moz** [comment]
I've reviewed, and I think it's good! The one thing to confirm is that we're doing "internet" and not "Internet" per @KevZawacki 's recommendation (this is how it appears on our blogs). I think that's fine, but pieces like Mark's letter on the website use "Internet."  Do we need to make a decision and be consistent for all MozFest comms? CC @Saallen

**Comment by Saallen** [comment]
Confirming approval for the guide content @sabrinang @gideonthomas 
Lets move forward and make all I into i.....Kevins comms were we are not consistant and its has changed so leave all content on wesbite as it

**Comment by gideonthomas** [comment]
Closing this since we've created the festival guide.
