### ISSUE TITLE
Crash Bug: session proposal submission crashes server when GitHub is down

### ISSUE THREAD

**Issue by cadecairos** [mozilla/mozillafestival.org#1036]
The Github outage today triggered a crash in the mozillafestival site. It seems if the HTTP request to GitHub fails it takes down the server.

Here's a stacktrace

```
 console.log("[Error posting to Github] Response status HTTP " + response.statusCode + ", Github error message: " + response.body.message, response.body.errors);
 ^

 TypeError: Cannot read property 'message' of undefined
 at Request._callback (/app/public/build/server.bundle.js:1818:138)
 at Request.self.callback (/app/node_modules/request/request.js:185:22)
 at emitTwo (events.js:126:13)
 at Request.emit (events.js:214:7)
 at Request.<anonymous> (/app/node_modules/request/request.js:1157:10)
 at emitOne (events.js:116:13)
 at Request.emit (events.js:211:7)
 at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1079:12)
 at Object.onceWrapper (events.js:313:30)
 at emitNone (events.js:111:20)
 Process exited with status 1
 at=error code=H13 desc="Connection closed without response" method=POST path="/add-proposal" host=mozillafestival-org-production.herokuapp.com request_id=33438c5f-906c-4d78-b213-3f2f6ca3ac12 dyno=web.1 connect=0ms service=8739ms status=503 bytes=0 protocol=https
```

@alanmoo

**Comment by mmmavis** [comment]
Thanks for letting me know @cadecairos @alanmoo . I just checked our master Google Spreadsheet and it seems like only 1 person wasn't able to submit his/her proposal to GitHub (that person tried 3 times and gave up/). I'll manual post for that person.

**Comment by marcwalsh** [comment]
@mmmavis We had a few people raise this on festival@, I've asked them to resubmit their sessions so hopefully they will do this! Unless they would have got a confirmation for their submission but it wasn't pushed to GitHub?

M

**Comment by mmmavis** [comment]
@cadecairos I'll check out the code to make sure GitHub outage won't take down our site again.

**Comment by mmmavis** [comment]
Fixed!
