### ISSUE TITLE
QA- link Get tickets to mozfest/tickets

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1041]
Since the ticket page is live on the website mozfest.org/tickets

can link in this section
![screen shot 2018-08-02 at 10 45 12](https://user-images.githubusercontent.com/10194015/43576407-2a241b66-9641-11e8-9a4c-7c264e54b5e7.png)

link to mozfest.org/tickets too?

for @mmmavis

**Comment by mmmavis** [comment]
Done!
