### ISSUE TITLE
QA: Home page Dialogue and Debates section

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1044]
Revise copy on home page for the Dialogue and Debates section to make it more clear it is from previous years and not the speaker line up for this year.

**Suggestions:**
Kevin: Revising the homepage copy to: "Here are just a few *from past years.*"

Zannah: I think "here are a few from the past years" in subheading text is great-- BUT  in the event that people don't read the subheading, I think a "Selected Past Speakers" heading would be good.

**Comment by KevZawacki** [comment]
@sabrinang Smart! Perhaps the hed can be: **Past 'Dialogues & Debates' Speakers**

**Comment by zee-moz** [comment]
@KevZawack @sabrinang I think Past 'Dialogues & Debates' Speakers sounds good. Can we make this change, as I still think the current heading is misleading and ticket buyers might be disappointed.

**Comment by zee-moz** [comment]
@KevZawack @sabrinang I think Past 'Dialogues & Debates' Speakers sounds good. Can we make this change, as I still think the current heading is misleading and ticket buyers might be disappointed.

**Comment by sabrinang** [comment]
Yes, triaged in this milestone today and changes will be made soon

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/
