### ISSUE TITLE
Content: Participation Guidelines

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1045]
### Description
Language for participation guidelines. This will be used in the Festival Guide, space info booths and posters throughout the MozFest weekend and a version will be at MozFest House. If the language is changed from last year it may need to be approved by Larissa from the D&I team.
_____________
**Content from 2017**

The Mozilla Festival respects Mozilla's community participation guidelines. These guidelines cover our behaviour as participants, facilitators, wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

How to treat each other:
Be respectful and value each other’s ideas, styles and viewpoints.
Be direct but professional; we cannot withhold hard truths.
Be inclusive and help new perspectives be heard.
Appreciate and accommodate our many cultural practices, attitudes and beliefs.
Be open to learning from others.
Lead by example and match your actions with your words.

The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org or call +44 (0) 207 855 3030.

_____________
If this is unchanged we have https://github.com/mozilla/mozillafestival.org/issues/731 l10n ticket for this to be in these 7 languages:

    de
    es
    fr
    it
    hi-IN
    pt-BR
    zh-TW

**Comment by sabrinang** [comment]
Note: email may change here and number is the same

**Comment by gideonthomas** [comment]
@Saallen, are we localizing the participation guidelines in Swahili?

**Comment by Saallen** [comment]
yes @gideonthomas

**Comment by gideonthomas** [comment]
Pushing this to the next milestone as we're blocked on `sw` translations

**Comment by gideonthomas** [comment]
Done, strings found in https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_design_assets.lang
