### ISSUE TITLE
Revive, remove, or update /location page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1047]
I can't remember if the [location page](https://mozillafestival.org/location/) is kept live on purpose or we forget to remove it. Thoughts @Saallen ? Should we revive, remove, or update this page? Currently this page is not linked anywhere on the site.

**Comment by sabrinang** [comment]
Note: Sarah mentioned once we have updated the Contact Us page with location information we can _remove_ the /location page.

**Comment by gideonthomas** [comment]
Consolidating this into https://github.com/mozilla/mozillafestival.org/issues/1075.
