### ISSUE TITLE
Update MozFest section on Foundation site

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1053]
https://foundation.mozilla.org/participate/

![screenshot_2018-08-08 participate](https://user-images.githubusercontent.com/2896608/43867572-a29daf08-9b1e-11e8-860b-958d7c1e9b7f.png)

Two issues I found:

1. The deadline listed there is wrong (August 31st). A fix has been filed and it should go live soon.
2. Now that CFP has ended. Should we update that section so it mentions our new CTA?

/cc @sabrinang @Saallen

**Comment by Saallen** [comment]
Yes please @mmmavis 

cc @consuelamckenzie as an FYI

**Comment by sabrinang** [comment]
I'd suggest directing people to https://mozillafestival.org/tickets as the new CTA

**Comment by sabrinang** [comment]
@zee-moz Can you provide copy for a get tickets CTA on the Foundation website? see https://foundation.mozilla.org/participate/ for length reference

**Comment by zee-moz** [comment]
@sabrinang OK if i get you to this by Friday?

**Comment by sabrinang** [comment]
@zee-moz Yup, sounds good

**Comment by alanmoo** [comment]
This page is being relaunched this week, and will have smaller content cards for each item. Let's keep it around 35 words.

![](https://user-images.githubusercontent.com/1068783/44357681-7d905d80-a467-11e8-9f4a-aabff4ebf911.png)
