### ISSUE TITLE
Space page: Update New Experiences 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1055]
Experiences to be added to the website

- [x] Art + Data #1054
- [x] Gaming MozFest #1021

**Comment by mmmavis** [comment]
Art + Data description has been added to the site: https://mozillafestival.org/spaces . I'm gonna close this ticket since description for "Gaming MozFest" is still WIP and we already have a separate ticket for that [here](https://github.com/mozilla/mozillafestival.org/issues/1023)

**Comment by mmmavis** [comment]
Reopening - didn't realize [this ticket](https://github.com/mozilla/mozillafestival.org/issues/1021) is for wrangler bio & photo, not for adding the experience description

**Comment by gideonthomas** [comment]
Moving to the next heartbeat since the content isn't ready for this.

**Comment by gideonthomas** [comment]
Content for Gaming MozFest experience:

> Every day, many of us are pressured into offering up pieces of personal data in order to participate on the internet. To sign up for a social network we need to provide our full name. To download a gaming app we need to provide access to our phone’s contact list. What kinds of trade-offs do we make when we hand over that data? What are we really getting in exchange? How can consent exist in this system? Tracked is a large-scale game designed for MozFest 2018 centered on the festival theme of “Your Data and You.” The game will engage players in various activities throughout the festival space, demonstrating the various trade-offs we each make when it comes to our data. As participants are encouraged to quantify, document, and report on various pieces of information throughout the game, the hope is that they will also reflect on the choices we are constantly making about our data.

**Comment by mmmavis** [comment]
Yay done! https://mozillafestival.org/spaces
