### ISSUE TITLE
Schedule Page: Content and Copy

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1058]
Instead of linking to guidebook directly, create a /schedule page on our website to describe and contextualize the schedule to include:
- information on how to use the schedule
  - example: accounts on Guidebook aren’t needed in order to view schedule
- information and links for both desktop/webpage version & mobile apps

**Comment by gideonthomas** [comment]
@zee-moz are we able to get copy for this by Tuesday Aug 21?

**Comment by Saallen** [comment]
@zee-moz any update here?

**Comment by zee-moz** [comment]
@Saallen @gideonthomas  I don't believe that this is one of the things that was on my list, per our meeting last week. I see the assignments have changed multiple times. If you want me to do this task, I need more info about the content, as well as word limits.

**Comment by zee-moz** [comment]
Current text is here, sent out for review 8/31. @KevZawacki  and @Saallen  reviewed, no response from @Lottarao. If we don't need Lotta's approval, then this is good to go. 👍 
https://docs.google.com/document/d/1O1fn5JGI09COZnK8HDLm8sorHYpGkhcErVIsGYqsOro/edit

**Comment by gideonthomas** [comment]
@Saallen would you be able to set a deadline for this content?

**Comment by gideonthomas** [comment]
@Saallen to provide this content by Friday Oct 5

**Comment by Saallen** [comment]
Title of page: MozFest 2018 Schedule

Content

Celebrate what you love about the web, and discover new ways to collaborate to make the internet a better, healthier place. At MozFest we have 320 sessions and counting taking place at MozFest weekend. We are using Guidebook as our scheduling tool to share the sessions, bios of facilitators, and help you decide how to spend your Saturday and Sunday at the festival. You can access Guidebook by downloading the app to your phone or visiting the scheduling page on your browser, Firefox of course :). If you dont wish to use Guidebook please note we will be displaying the schedule at info booths on each floor over the festival weekend.

**Comment by gideonthomas** [comment]
Thanks @Saallen, moving to the design ticket
