### ISSUE TITLE
Schedule page: Design Mockups

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1060]
Based on copy and content from: https://github.com/mozilla/mozillafestival.org/issues/1058 create a mockup of how this information is designed and formatted on the website.

**Comment by Saallen** [comment]
I updated issue #1058

**Comment by gideonthomas** [comment]
### Copy

Title of page: MozFest 2018 Schedule

Content

Celebrate what you love about the web, and discover new ways to collaborate to make the internet a better, healthier place. 

This year we have over 300 sessions taking place over MozFest weekend, not to mention the 18 events you can attend at MozFest House.
 We are using Guidebook as our scheduling tool to share the sessions, bios of facilitators, and help you decide who to spend your time Saturday and Sunday during the weekend at Ravensbourne.

You can access Guidebook by [downloading the app](https://guidebook.com/g/mozfest18/) to your phone or visit the [schedule](https://guidebook.com/guide/147793/) on your browser, Firefox of course. If you don't wish to use Guidebook please note we will be displaying the schedule at info booths on each floor over the festival weekend.

**Comment by gideonthomas** [comment]
@sabrinang do you have bandwidth to do this this week? Or should we get help with this?

**Comment by sabrinang** [comment]
I don't think the schedules will be displayed at the info booths, they were not used last year for schedules and one side usually faces the wall so it isn't seen. We may want to exclude that sentence unless that is an intentional plan for all wranglers but it is misleading.

@gideonthomas Yes I'll work on this

**Comment by sabrinang** [comment]
@Saallen @gideonthomas Please review redpen here: https://redpen.io/nm7ed6b29d80c70eb5

- I excluded "at info booths"
- instead of linking withing the body copy, I used buttons to highlight the CTAs 
   - we should use direct links to the to app downloads (instead of it being 3 clicks away)

<img width="503" alt="image" src="https://user-images.githubusercontent.com/2492510/46760151-1d0ee700-cc86-11e8-9528-c084e9910e15.png">

**Comment by xmatthewx** [comment]
This looks great. I'd consider moving the buttons up above the paragraphs. I feel like users will be looking for the schedule. All the narrative feels supplemental. On mobile, those buttons will be pretty low down.

**Comment by natalieworth** [comment]
@gideonthomas @Saallen I moved the buttons to the top of the content. Just awaiting final approval from @Saallen : 

- Just to note that I increased the spacing between the title and "View Online Schedule" to make it feel more balanced with the rest of the content (but disregard if it's inconsistent with other pages @mmmavis )

![mozilla-festival_schedule copy 2x-100](https://user-images.githubusercontent.com/14876567/46768171-17240080-cc9c-11e8-93e1-3abaa55440af.jpg)

**Comment by gideonthomas** [comment]
Perfect, thanks all! @Saallen - for review, the navigation is currently too busy to add "Schedule". Instead, design suggested we add a bar at the top of the website and a button. Question for you -- should we replace the play button with the "View Schedule" button, or just not have the "View Schedule" button and just have the bar at the top?

Comp is here: https://redpen.io/qa14fe83adafdfaca2. Ignore that background/nav which is outdated.

**Comment by Saallen** [comment]
Yes love that great idea @gideonthomas 
I actually dont mind here- so will let the designers make the decision for user experience

**Comment by gideonthomas** [comment]
Thanks! Moved to dev phase: https://github.com/mozilla/mozillafestival.org/issues/1059
