### ISSUE TITLE
Contact Us page: Revise with location copy and info

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1062]
https://mozillafestival.org/contact

As we intend to remove the outdated Location page https://github.com/mozilla/mozillafestival.org/issues/1047 (you can reference it live here: https://mozillafestival.org/location), we can revise the _Contact Us_ page to feature location information instead.

**Comment by Saallen** [comment]
@sabrinang 
On the contact page please update
- [ ]  If the footer says get in touch- we should amend the title of the page to be get in touch or amend the footer to match get in contact header
-[ ]. We should add addresses of MozFest house and MozFest weekend here
- [ ] remove sign up for emails section

**Comment by Saallen** [comment]
Yes,-please-
