### ISSUE TITLE
Localise Participation Guidelines in Swahili

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1063]
We have this text in French, Spanish, German and Hindu already from previous years. This year, we are supporting Swahili so we need to localise this text.

### Copy

> **Participation Guides**
>
> The Mozilla Festival respects Mozilla's community participation guidelines. These guidelines cover our behaviour as participants, facilitators, wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.
> 
> How to treat each other:
> Be respectful and value each other’s ideas, styles and viewpoints.
> Be direct but professional; we cannot withhold hard truths.
> Be inclusive and help new perspectives be heard.
> Appreciate and accommodate our many cultural practices, attitudes and beliefs.
> Be open to learning from others.
> Lead by example and match your actions with your words.
> 
> The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.
> 
> Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org or call +44 (0) 207 855 3030.

**Comment by gideonthomas** [comment]
Hi @TheoChevalier, any updates on this?

**Comment by TheoChevalier** [comment]
Hi!

Swahili translations will appear here:
https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_design_assets.lang&action=translate&show
And here: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_design_assets.lang&action=review

Status can be tracked here: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_design_assets.lang

Is there a deadline I can set in Pontoon?

**Comment by gideonthomas** [comment]
cc @Saallen to set a deadline for Swahili translations.

**Comment by Saallen** [comment]
I approached three support networks last week to see if we can move this piece forward.
If we dont head back from this by Sept 7th - we should proceed without Swahilli

**Comment by gideonthomas** [comment]
This is done! Thanks all :)
