### ISSUE TITLE
Remove last year's wranglers' access to Guidebook

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1066]
Remove last year’s wranglers’ access to Guidebook. https://builder.guidebook.com/#/organizations/3408267/users

**Comment by mmmavis** [comment]
Done.

I've removed everyone except Sarah, Marc, Esme, Sabrina, and myself. All of us have admin rights on our Guidebook Mozilla Foundation account.

/cc @marcwalsh as fyi

**Comment by consuelamckenzie** [comment]
Hi Mavis,

Can you remove Esme and add me?

Consuela

**Comment by mmmavis** [comment]
yup just did 👍
