### ISSUE TITLE
Location of MozFest areas at Ravensbourne

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1068]
We need to confirm areas so we can display them on guidebook and printed wayfinding materials.

Main content:
- Floor number for spaces (thematic learning hubs)
- Floor number or location for experiences (if these have a physical location)
- Floor and room number of accepted sessions 

Other content:
- Registration
- Dialogues & Debates Stage
- Main Stage
- #MozHelp
- Quiet Space
- Lunch
- Info Booth
- Coffee
- Water
- Toilets

**Comment by sabrinang** [comment]
This will help inform these design assets: 
Wayfinding: Floor Plan Maps https://github.com/MozillaFoundation/mozfest-design-2018/issues/42
Floor Stickers https://github.com/MozillaFoundation/mozfest-design-2018/issues/60
Space and Floor Banners https://github.com/MozillaFoundation/mozfest-design-2018/issues/41

**Comment by gideonthomas** [comment]
This should be ready by Monday Sep 24 by @Saallen

**Comment by gideonthomas** [comment]
Deadline pushed to Wednesday Sep 26

**Comment by gideonthomas** [comment]
Thanks @Saallen, I've updated tickets that need this info.
