### ISSUE TITLE
Google Search Console Access 🕵️‍♂️

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#1070]
Hey @mmmavis,

It looks like we haven't attached the domain to Google's [Search Console](https://www.google.com/webmasters/tools/home?hl=en). It just requires a HTML tag to be added to the header of the home page. 

This will allow us to be able to review the SEO data Google has on us and hopefully make some nicer looking rich cards and remove pages from being searchable.

When you have a free moment would you be able to impliment this please? I'll mark this as an enhancement as there is no rush and a nice to have.

**Comment by mmmavis** [comment]
@gideonthomas can you give me access to the Search Console Property once it's been set up? Thanks!

**Comment by gideonthomas** [comment]
will do!

**Comment by marcwalsh** [comment]
@gideonthomas could you grant access for me as well please? 

Cheers! :)

**Comment by gideonthomas** [comment]
Added @marcwalsh, @mmmavis, and @Saallen. Let me know if anyone needs access (and what type of access - view or view/edit).
