### ISSUE TITLE
[DESIGN] Contact Us page: Update copy

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1074]
Content ticket: https://github.com/mozilla/mozillafestival.org/issues/1062

All changes happen to `/contact`

TODOs:
1. Change title to "GET IN TOUCH"
2. Remove the text "Sign up here to receive festival news and updates by email."
3. Add addresses to MozFest House, and MozFest under a "Contact Info" section (copy by Sarah)

**Comment by gideonthomas** [comment]
Lol sorry, what I said wasn't clear. I just meant that the title "Contact Info" was determined by Sarah.

**Comment by Saallen** [comment]
@gideonthomas @sabrinang 
We have now positioned this page as a "Get in contact" so we need to share ways for people to contact us.....email, twitter, location and phone number

The sectio heading **Make it better** doesnt make any sense to this page

Can you amend this section?

- [ ] Remove Make it better-  
- [ ]  Amend title to **Email us**
Please add- 
- [ ] You can reach us with all enquiries at festival@mozilla.org. During the festival weekend we will have a local emergency number, which will be updated closer to the event. 

Please drop further down the page. We welcome suggestions to improve Mozilla festival. It's a collaborative event and your feedback matters. Email us [hyperlinefestival@mozilla.orh]

**Comment by gideonthomas** [comment]
Hi @sabrinang, I've moved it over to the next heartbeat to accommodate this change. Just to re-iterate what @Saallen mentions above, I added comments in the redpen. Let me know if you have any questions.

**Comment by sabrinang** [comment]
Here are design mockups for the contact us page:

option 1: https://redpen.io/tr7cd472386695f4a8
- dividers with feedback near the footer

option 2: https://redpen.io/gm577a2428d0ee5018
- highlighted box for feedback and email/social near the footer

**Comment by gideonthomas** [comment]
Thanks @sabrinang! @Saallen, which one looks better to you (personally I prefer option 1)?

**Comment by gideonthomas** [comment]
@Saallen, just checking in to find out the status of this.

**Comment by gideonthomas** [comment]
Thanks @sabrinang and @Saallen!
