### ISSUE TITLE
[DEV] Update Contact Us page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1075]
Design ticket: https://github.com/mozilla/mozillafestival.org/issues/1074

All changes happen to /contact

Design comp: https://redpen.io/tr7cd472386695f4a8

TODOs:
1. Change title to "GET IN TOUCH"
2. Remove the text "Sign up here to receive festival news and updates by email."
3. Add addresses to MozFest House, and MozFest Weekend under a "Contact Info" section
4. Add emergency info text under a "Raising Issues at the Festival" section. This should be hidden for now. Closer to the festival date, we will update this information (https://github.com/mozilla/mozillafestival.org/issues/1094).
5. Replace "Make it Better" with "Email Us" and update copy under it.
6. Add section above footer about how attendees can provide feedback for Mozfest. 
7. Remove the `/location` page

**Comment by gideonthomas** [comment]
@mmmavis this should be ready to work on.

**Comment by sabrinang** [comment]
@mmmavis Here is the banner on google drive: https://drive.google.com/open?id=1ptJ44xGiNyIuLmc5hpbSMsGP_4eKAFyN

For grey, I referred to "Join Us" on the homepage:
`.light-grey-bg  background-color: #F5F5F5`

**Comment by mmmavis** [comment]
Live https://mozillafestival.org/contact
