### ISSUE TITLE
Generic comment to leave on unsuccessful proposal GitHub ticket

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1076]
When curation processes ends we will have a script that
- goes through all proposal GitHub tickets * without * milestone (unsuccessful proposals),
- leaves a generic comment,
- and closes that ticket. 

This is the copy we used last year. 

```
Thank you for taking the time to submit a session to MozFest. Due to the high level of submissions, we’re unable to accept all proposals and unfortunately, your session was not part of the final group.

Thank you for taking the time to submit and we will follow up on email very soon.
```

Screencap from last year:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/2896608/44493001-48c50780-a61b-11e8-883b-ef8045619f8b.png">

**By August 30 - Please provide copy to use for this year or let me know if we can just reuse last year's.**

**Comment by marcwalsh** [comment]
I think lets remove the second 'Thank you' - @Saallen can you review please?

```
Thank you for taking the time to submit a session to MozFest. 
Due to the high level of submissions, we’re unable to accept all 
proposals and unfortunately, your session was not part of the final group.

You'll receive a follow up email from us in the next few days.
```

**Comment by Saallen** [comment]
Approved

**Comment by mmmavis** [comment]
Thanks!
