### ISSUE TITLE
[Due Aug. 30] Accepted proposals spreadsheet - finalize columns to include

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1078]
By August 30, please provide finalized list of columns to include on the to-be-created spreadsheet of accepted proposals.

Please reference to lists below and decide what should be included in the new spreadsheet.

## Columns in the master spreadsheet of ALL proposals

- uuid
- timestamp
- githubissuenumber
- firstname
- surname
- email
- organisation
- twitterhandle
- githubhandle
- otherfacilitator1firstname
- otherfacilitator1surname
- otherfacilitator1email
- otherfacilitator1githubhandle
- otherfacilitator2firstname
- otherfacilitator2surname
- otherfacilitator2email
- otherfacilitator2githubhandle
- otherfacilitator3firstname
- otherfacilitator3surname
- otherfacilitator3email
- otherfacilitator3githubhandle
- space
- secondaryspace
- l10nwish
- l10nlanguage
- l10nsupport
- sessionname
- description
- outcome
- afterfestival
- numsofparticipants
- format
- timeneeded
- needs
- travelstipend
- proposallanguage
- residence
- privacypolicy
- receiveemailupates

## Meta on GitHub

- any special labels we should pull and create individual spreadsheet columns?
- what else?

## Scheduling related meta

- date of session
- start time of session
- end time of session
- all day session (T/F checkbox)
- location of session
- anything else?
 
## Anything else?

?

**Comment by marcwalsh** [comment]
## Columns To Transfer from Master Spreadsheet

_Strikethrough means do not include, bold means I have repositioned in the table_

- uuid
- ~~timestamp~~
- **sessionname**
- **description**
- githubissuenumber
- firstname
- surname
- email
- organisation
- twitterhandle
- githubhandle
- otherfacilitator1firstname
- otherfacilitator1surname
- otherfacilitator1email
- ~~otherfacilitator1githubhandle~~
- otherfacilitator2firstname
- otherfacilitator2surname
- otherfacilitator2email
- ~~otherfacilitator2githubhandle~~
- otherfacilitator3firstname
- otherfacilitator3surname
- otherfacilitator3email
- ~~otherfacilitator3githubhandle~~
- ~~space~~
- ~~secondaryspace~~
- ~~l10nwish~~
- l10nlanguage
- ~~l10nsupport~~
- ~~outcome~~
- ~~afterfestival~~
- ~~numsofparticipants~~
- format
- timeneeded
- needs
- travelstipend
- ~~proposallanguage~~
- residence
- privacypolicy
- receiveemailupates


## Meta from GitHub

- [Production] Flagged (Label)
- [Production] Edited (Label)
- Attached Milestone (This should be one of the first columns on the new spreadsheet)

## Scheduling Related Data

- Date
- Time Start
- Time End
- Room/Location
- All Day (Checkbox)

**Comment by gideonthomas** [comment]
@mmmavis can this ticket be closed?

**Comment by mmmavis** [comment]
Yup yup.

Just a note that I'm gonna merge the `Date`, `Time Start`, and `Time End` into one column since the timeblocks on Saturday and Sunday have different start/end times. Having 3 columns might confuse wranglers.
