### ISSUE TITLE
[Due Aug. 30] Unsuccessful proposals spreadsheet - finalize columns to include

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1079]
By August 30, please provide finalized list of columns to include on the to-be-created spreadsheet of unsuccessful proposals.

Please reference to lists below and decide what should be included in the new spreadsheet.

## Columns in the master spreadsheet of ALL proposals

- uuid
- timestamp
- githubissuenumber
- firstname
- surname
- email
- organisation
- twitterhandle
- githubhandle
- otherfacilitator1firstname
- otherfacilitator1surname
- otherfacilitator1email
- otherfacilitator1githubhandle
- otherfacilitator2firstname
- otherfacilitator2surname
- otherfacilitator2email
- otherfacilitator2githubhandle
- otherfacilitator3firstname
- otherfacilitator3surname
- otherfacilitator3email
- otherfacilitator3githubhandle
- space
- secondaryspace
- l10nwish
- l10nlanguage
- l10nsupport
- sessionname
- description
- outcome
- afterfestival
- numsofparticipants
- format
- timeneeded
- needs
- travelstipend
- proposallanguage
- residence
- privacypolicy
- receiveemailupates

## Meta on GitHub

- any special labels we should pull and create individual spreadsheet columns?
- what else?

## Anything else?

?

**Comment by marcwalsh** [comment]
## Columns required from Master Spreadsheet

- githubissuenumber
- firstname
- surname
- email
- otherfacilitator1firstname
- otherfacilitator1surname
- otherfacilitator1email
- otherfacilitator2firstname
- otherfacilitator2surname
- otherfacilitator2email
- otherfacilitator3firstname
- otherfacilitator3surname
- otherfacilitator3email
- sessionname
- privacypolicy
- receiveemailupates

## Required GitHub Meta

- [Production] Flagged (Label)

**Comment by mmmavis** [comment]
Thanks @marcwalsh 🍻
