### ISSUE TITLE
Sponsors 2018

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1081]
We have started to recieve new sponsors for 2018.

Please add new logos and links to be added to the sponsorship page here as new issues.
Note that logo should be high res.

**Comment by gideonthomas** [comment]
Sorry @Saallen, I made a mistake, we're tracking all the logos in https://github.com/mozilla/mozillafestival.org/issues/1027 and I'll file dev tickets every two weeks.
