### ISSUE TITLE
[Due Sept. 6] Provide finalized list of session block start time & end time

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1083]
**By September 6** - Please provide finalized list of session block start time & end time.

**Comment by mmmavis** [comment]
@marcwalsh thanks for the note. Um I'll have to investigate and see what we can do. I really wanna avoid having a fancy/"smart" spreadsheet like what we had 2-3 years ago as that led to numerous human errors when people edited the sheet. The scripts I had prepared became not useful in end and MozFest production team and I had to do a ton of manual fixes afterwards... I'd like to avoid that from happening again. 😬

**Comment by gideonthomas** [comment]
@mmmavis, can this ticket be closed or is there work left to do here?

**Comment by mmmavis** [comment]
I'm just going to add 1 column to the spreadsheet

Dropdown options would be in this format

- Saturday (10:00 - 11:00)
- Saturday (11:15 - 12:15)
- Saturday (11:15 - 12:45)
- (... etc)

**Comment by mmmavis** [comment]
Note that Sunday 11:30 - 12:30 block should start from **11:00** instead
