### ISSUE TITLE
Homepage 2018 speakers

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1084]
Now that we have the speakers list from https://github.com/mozilla/mozillafestival.org/issues/1024, we should feature them on the homepage as well like last year.

What we need input on:
1. What layout would you like for the speakers? Does this work (with the new speakers): https://redpen.io/cs6aa0082d55d20d65

**Comment by KevZawacki** [comment]
Hi @gideonthomas 

Yep, a layout similar to the current one 👍 

We have 18 speakers this year, so perhaps we arrange them 4x4, with a row of 2 at the bottom? And, under their headshots we can put their title and Twitter handle. Should I put together a copy doc with that info?

**Comment by gideonthomas** [comment]
Thanks @KevZawacki! We can use content from the speakers page doc you've already created, so don't worry about it.

@sabrinang, does 4x4 work or will it look too crowded?

**Comment by gideonthomas** [comment]
Hey @KevZawacki, what "title" do we use for each of the speakers? I might be wrong about what we're taking out from the content from the speakers page haha (sorry). Would you mind creating a copy doc for this?

**Comment by KevZawacki** [comment]
Hi @gideonthomas, certainly. Copy [here](https://docs.google.com/document/d/1vc8pLMbPS1raShBGh-rcPrglrNGjWenZHjfkzBF5rcs/edit); let me know if you have any questions.

**Comment by gideonthomas** [comment]
Thank you so much! @sabrinang, can we do this in a 4x4 grid?

**Comment by sabrinang** [comment]
I made some design mockups for the speakers on the homepage:

4x4 mockups: https://redpen.io/sy7a213d99ce724452
- with the margins and type sizes currently, this may only fit on a wide desktop screen (line width is too narrow for long twitter handles)

3x3 mockup: https://redpen.io/wj86294c0b5763fba0
- this is more likely to appear on smaller viewports and I would recommend this so the line lengths are not truncated or be too narrow
- also divides evenly 3x6

**Comment by gideonthomas** [comment]
@Saallen, which mockup would you prefer?

**Comment by Saallen** [comment]
I like 4x4 better- especially if we are adding another section about Data Done Right

**Comment by gideonthomas** [comment]
@sabrinang, would we be able to reduce the font size of the twitter handle slightly so that it fits?

**Comment by sabrinang** [comment]
@gideonthomas Yes we can and I checked in with Mavis that we can as well.

**Comment by gideonthomas** [comment]
Awesome! Thanks!
