### ISSUE TITLE
QA: Unclear Location 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1086]
A mozillian on slack pointed out "... but can't see recommendation for hotel or where the conference will be held on the mozfest website?" and I realized we do not have **Ravensbourne University** on the homepage anymore when the copy updated.

I think we can add it near where North Greenwich is:

![image](https://user-images.githubusercontent.com/2492510/44885645-dc7b8100-ac76-11e8-9262-d1c30457a57a.png)

**Comment by Saallen** [comment]
Hey
Please amend to 
MozFest House, October 22-26, [Royal Society of Arts (RSA)](https://www.google.com/maps/place/RSA+House/@51.5093702,-0.1248943,17z/data=!3m1!4b1!4m5!3m4!1s0x487604c9572d71f1:0xc61aaa0727953544!8m2!3d51.5093669!4d-0.1227056), Central London
MozFest weekend, Octoerb 26-28, [Ravensbourne University,](https://www.google.com/maps/place/Ravensbourne+University+London/@51.5016761,0.0035609,17z/data=!3m1!4b1!4m5!3m4!1s0x47d8a81c7b6dfe23:0xc31e4c0ca6a4ace2!8m2!3d51.5016728!4d0.0057496) Greenwich

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/
