### ISSUE TITLE
[Due End of Sept. 10] Organize MozFest Proposal Repo

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1090]
Hi @marcwalsh (pinging you here since I'm not sure who on MozFest production team should be responsible for this)

I'll be running my scripts on September 11 (Tuesday) so please make sure by the end of September 10 (Monday) Pacific Time, [GitHub issues in the proposal repo](https://github.com/MozillaFestival/mozfest-program-2018/issues) are organized in the way that

1. all open issues without milestone that were initially posted by @mozfest-bot are the **unsuccessful proposals**
2. all open issues with milestone that were initially posted by @mozfest-bot are the **accepted proposals**
3. close the remaining issues

Thanks!

**Comment by marcwalsh** [comment]
Hey @mmmavis this will be myself and @Saallen checking through on the 10th Sept.

:)

**Comment by gideonthomas** [comment]
Hi @marcwalsh just wanted to check in and see if this is done? If so can you close this ticket?

**Comment by marcwalsh** [comment]
Hi @gideonthomas @mmmavis 

@Saallen and I reviewed GitHub and we're made any nessessary changes.

You're good to go! :)

Thanks!!
