### ISSUE TITLE
Add wranglers to Gaming experience 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1091]
In relation to Space page: Update New Experiences #1055
Gaming mozfest wranglers have been added to the wrangler list and should be added in two place

*  [to this page](https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0)
*  to [wrangler page](https://mozillafestival.org/team/wranglers)

- [ ] Rebecca Khan
- [ ] Ashlyn Sparrow
- [ ] Hang Do Thi Duc

@gidon can you organise this?

**Comment by gideonthomas** [comment]
@KevZawacki, would you be able to review the three bios for the Gaming MozFest wranglers in this spreadsheet: https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0

**Comment by KevZawacki** [comment]
Hi @gideonthomas, I just reviewed and made some small tweaks. All set 👍

**Comment by gideonthomas** [comment]
Perfect! Thanks, Kevin!
