### ISSUE TITLE
Homepage: Add featured theme

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1092]
Content ticket: https://github.com/mozilla/mozillafestival.org/issues/1025

Content: https://docs.google.com/document/d/1O1fn5JGI09COZnK8HDLm8sorHYpGkhcErVIsGYqsOro/edit

Needs design on the homepage to incorporate this content.

**Comment by sabrinang** [comment]
I mocked up the content and included the tagline lockup on the homepage here: 

version 1 - full text: https://redpen.io/ph038f96153d825c59
version 2 - last paragraph only: https://redpen.io/vscf67cb1fa98c5781

I can also exclude the tagline graphic to be text only if preferred.

**Comment by gideonthomas** [comment]
@Saallen would you be able to provide feedback on the designs / review and pick one mockup? Deadline - Tuesday, EOD.

**Comment by zee-moz** [comment]
@Saallen right now we don't have a blog post on the theme. If we're restricting to option 2 (which is about 55 words) I am hesitant to make people click out to the full description (which is only about 100 words more) I think it's and probably not worth it the jump from the website out to medium or pulse-- I would try to keep users on this site as much as possible.

**Comment by gideonthomas** [comment]
We will be going with version 2 and adding a page on the foundation site about MozFest which will have more descriptive text about the theme. This page on the foundation site will also link back to the MozFest site so that users can go back to the MozFest site after leading about the theme.

**Comment by sabrinang** [comment]
data done right lockup can be found here (home page asset folder): https://drive.google.com/open?id=1DNUbeRLQwYjyF69-44ET4EMoa3B72I_d
