### ISSUE TITLE
Homepage: Update speakers

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1093]
Design ticket: https://github.com/mozilla/mozillafestival.org/issues/1084

Design comp: https://redpen.io/sy7a213d99ce724452

Speaker List: https://docs.google.com/document/d/1vc8pLMbPS1raShBGh-rcPrglrNGjWenZHjfkzBF5rcs/edit

One note from the design ticket: Lower the font-size of the twitter handle slightly so that it fits in one line.

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/
