### ISSUE TITLE
[DEV] Update emergency info on contact page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1094]
On `/contact`, we will show a section for "Raising Issues at the Festival" according to https://redpen.io/tr7cd472386695f4a8. We need to update the emergency contact number and email to the copy once we have this information.

**Comment by Saallen** [comment]
Updated with safety email

Please remove phone number and in an event of an emergency...

**Comment by gideonthomas** [comment]
@mmmavis there are comments in the redpen for minor copy changes along with this ticket. Would you be able to do it? The changes are:
1. Remove the "in case of emergency call 911" line.
2. Add the safety email - festivalsafety@mozilla.com
3. Remove the "or contact us at 08954b432rew" part.

**Comment by mmmavis** [comment]
Done!
