### ISSUE TITLE
[DEV] Update wrangler bios and photos part 2

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1095]
This is the second part (and hopefully final) of updates that need to happen to the team page.

Along with the wrangler bio updates, can you also update the spelling of "Decentralization" on the wrangler page? It should be spelt "Decentralisation" to be consistent with the rest of the website.

## Wranglers

| Update Type | Name | Twitter | Photo | Bio |
| --- | --- | --- | --- | --- |
| UPDATE | Kade Morton | [same] | [Link](https://drive.google.com/file/d/1c9IbCS4fjbuTN9G7Lf_jWArof1AU807p/view?usp=sharing) | [same] |
| ADD to Gaming Mozfest | Ashlyn Sparrow | [empty] | [Link](https://drive.google.com/file/d/1dFV9fi7QJyNehyXDGh5fPIw2_YOEp9la/view?usp=sharing) | Ashlyn Sparrow is the learning technology director and lead game designer at the University of Chicago’s Game Changer Chicago Design Lab. She is also creative director at Resilient Games Studio. Ashlyn has worked on serious board, card, and digital games, and also public health apps. |
| ADD to Gaming Mozfest | Rebecca Ricks | [empty] | [Link](https://drive.google.com/file/d/1dMjwke13VAc9N9YglGDcUA6C72Hm_1Ql/view?usp=sharing) | Becca Ricks is a researcher and creative technologist thinking about online privacy and computational systems within a human rights framework. Her work investigates how social platforms collect, monetize, and disclose data about people using automated or opaque processes. Most recently, Becca was a Mozilla Fellow researching encryption and privacy at Human Rights Watch. |
| ADD to Gaming Mozfest | Hang Do Thi Duc | [empty] | [Link](https://drive.google.com/file/d/1dSDwmlQTdQUOrpx59IhaY3_lam1lk2JJ/view?usp=sharing) | Hang is a design technologist whose work explores the social web and the effect of data-driven technologies on privacy, identity, and society. She is the creator of the browser extension Data Selfie and the privacy research and data storytelling project about Venmo’s public feed Public By Default. |
| DELETE from Privacy and Security | Vojtech Sedlak | - | - | - |

**Comment by Saallen** [comment]
Further Updates

- [ ] Remove Vojtech from p&s space

- [ ] Add Kristine Grivcova to Digital Inclusion - requested further details

**Comment by gideonthomas** [comment]
Thanks @Saallen, filed https://github.com/mozilla/mozillafestival.org/issues/1096 for Kristine and updated this ticket for the removal of Vojtech.

**Comment by mmmavis** [comment]
Done! 

https://mozillafestival.org/spaces
https://mozillafestival.org/team/wranglers
