### ISSUE TITLE
Bio and photo for Kristine Grivcova

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1096]
Tracking issue for the Bio and Photo for the Digital Inclusion wrangler - Kristine Grivcova

**Comment by gideonthomas** [comment]
@marcwalsh any updates on this?

**Comment by marcwalsh** [comment]
@gideonthomas I’ve requested this for Friday. Will update on the wrangler bio spreadsheet and ping you on there as soon as I have it!

**Comment by Saallen** [comment]
@marcwalsh any update?
If not lets update w no photo

**Comment by gideonthomas** [comment]
@Saallen I only have a photo, no bio, so we should update with just the photo?

**Comment by marcwalsh** [comment]
@gideonthomas @saallen sorry for the delay - bio below:

I’m a research engineer from London. I work at the BBC R&D where we think about the future of technology and media. More specifically I’ve been working with Machine Learning and how it can be used in Radio applications in a unique and transparent way.

@KevZawacki would you be able to have a look at this and suggest any edits please?

**Comment by KevZawacki** [comment]
@marcwalsh Edits:

Kristine Grivcova is a research engineer from London. She works at the BBC R&D, where she thinks about the future of technology and media. More specifically, Kristine explores machine learning and how it can be used in radio applications in a unique and transparent way.

**Comment by gideonthomas** [comment]
Thanks for being so quick @KevZawacki! Moving to the dev ticket: https://github.com/mozilla/mozillafestival.org/issues/1116
