### ISSUE TITLE
[DEV] Speakers page: Add 2018 speakers

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1097]
Migrated from https://github.com/mozilla/mozillafestival.org/issues/1048

Design Comp: https://redpen.io/cu4c572de30b3a4681

Content: https://docs.google.com/document/d/1RelFJevDXLSdam_a8yqwhFRYyM3juPDlJ4w74jlYizs/edit#

Headshots: https://drive.google.com/drive/folders/1uz7gEXQOSy8JaQc-BUQjuNJ1p_FlHWza

**Comment by mmmavis** [comment]
@gideonthomas just to confirm we are adding "speakers" to the nav bar as well, right?

**Comment by gideonthomas** [comment]
Yep

**Comment by mmmavis** [comment]
@sabrinang do you have cropped version of headshots? If not I will process photos on my end.

**Comment by sabrinang** [comment]
No cropped versions I used photos from Kevin's headshot folder above. I can crop them on Monday if you need @mmmavis

**Comment by mmmavis** [comment]
@sabrinang 

No worries. I can crop them on my end to avoid blocker. I just wasn't sure if we need to use the same photos for website and printed guide for consistency.

**Comment by mmmavis** [comment]
Live! https://mozillafestival.org/speakers
