### ISSUE TITLE
Festival Guide insert: MozFest house

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1100]
MozFest House
Content in development [here](https://docs.google.com/document/d/1_U-psv7RO6BaRpu3s58L1iDivh3pH5lgzVKZAUw7Fbc/edit#)

- [x] Guide
- [x]  list of events and partners
- [x] venue, dates

**Comment by gideonthomas** [comment]
@Saallen I know this isn't crucial to launch, but do you have a status update on this?

**Comment by gideonthomas** [comment]
@Saallen to have this done by Friday, Sep 28

**Comment by Saallen** [comment]
@gideonthomas I updated the document. This is document is to be inserted to the MozFest house festival guides- 
so only need 300 copies need to be printed
I gave a brief blurb to situate the booklet and listed the events, with timings and brief outline

**Comment by gideonthomas** [comment]
Thanks @Saallen!

**Comment by gideonthomas** [comment]
Added to the festival guide ticket https://github.com/MozillaFoundation/mozfest-design-2018/issues/73
