### ISSUE TITLE
QA- MozFest House- amend location

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1101]
Please amend the linked location from on [MozFest house page](https://mozillafestival.org/house)
MozFest House is located just off Trafalgar Square at the Royal Society of Arts (RSA), 8 John Adam St, London WC2N 6EZ. 

Link currents sends people here- https://www.thersa.org/contact

Please amend to :
https://www.google.com/maps/place/RSA+House/@51.5093702,-0.1248943,17z/data=!3m1!4b1!4m5!3m4!1s0x487604c9572d71f1:0xc61aaa0727953544!8m2!3d51.5093669!4d-0.1227056),

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/house
