### ISSUE TITLE
Contact Us Page: Sign Up Link Issue

### ISSUE THREAD

**Issue by KGorr** [mozilla/mozillafestival.org#1107]
The "sign up here" link on the contact page (https://mozillafestival.org/contact) directs to a MozFest 2017 Ti.To sign up page: https://ti.to/Mozilla/mozfest-2017

The contact us page is linked via the "get in touch" icon the footer of every page on the website.

cc: @Saallen

**Comment by KGorr** [comment]
@Saallen (or anyone who knows) - can you please let me know what the correct link is for directing people to sign up for updates on the festival? I need to put it in an email draft. Thanks!

**Comment by Saallen** [comment]
assigning @marcwalsh to help with this one

**Comment by gideonthomas** [comment]
@KGorr, the new website page for Contact Info is live - https://mozillafestival.org/contact and is linked to by the "Get In Touch" link at the bottom.

**Comment by KGorr** [comment]
Great - thanks!
