### ISSUE TITLE
Small update to speaker bio

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/mozillafestival.org#1115]
Hi @sabrinang & @mmmavis,

I'm hoping we can make a small update to a speaker's bio. We should identify Camille Francois as a Mozilla Fellow. 

So, her blurb at https://mozillafestival.org/speakers should read:

"Camille Francois is **a Mozilla Fellow,** research director at Graphika and affiliate at Harvard’s Berkman Klein Center for Internet & Society."

Would it be possible to make that update sometime this week? Thank you!

**Comment by mmmavis** [comment]
https://mozillafestival.org/speakers has been updated!

@sabrinang I'm gonna assign this ticket to you now in case the changes need to be reflected on printed guide as well.

**Comment by sabrinang** [comment]
Thanks for looping me in! I'll make sure the speaker copy doc that Makiko is referring to reflects this change as well.

**Comment by KevZawacki** [comment]
Thanks, both!
