### ISSUE TITLE
[DEV] Update production team and wrangler bios part 3

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1116]
@mmmavis would you be able to crop the images as well?

## Production Team

| Update Type | Name | Title | Photo | Bio |
| --- | --- | --- | --- | --- |
| ADD after Kevin | Kristina Gorr | Communications Lead | [Link](https://drive.google.com/file/d/1cvzn5RG0aq7_aoVMYdC4eB1tWH_6tRqx/view?usp=sharing) | Kristina is Mozilla’s Open Leadership Community Coordinator. Communication is the name of her game and writing is her passion. She enjoys helping connect people, passions, and events using engaging language. This year marks Kristina’s third year supporting MozFest’s communication efforts. |
| ADD after Mavis | Amanda Lee Gaffar | Executive Assistant | [Link](https://drive.google.com/file/d/1iUOce8wtoAxlaDQByuO16HIpzu2Y4jlz/view?usp=sharing) | Amanda joined Mozilla in 2017, bringing her Executive Assistant expertise of over 20 years to the Foundation. During MozFest season, Amanda wears her travel hero hat and manages logistics for everyone traveling to London. If you see Amanda at MozFest be sure to give her a high five! |
| ADD after Marc | Stephanie Rowe | Production Coordinator | [Link](https://drive.google.com/file/d/1eN9bpQmopT8_DuQI9ym9WXCFVIH0NuZC/view?usp=sharing) | Stephanie is MozFest’s Production Coordinator. She has contributed to several large-scale international events over the years, from data analysis to ideation and planning. Stephanie brings both an analytical mind and deep creativity to her work, and is dedicated to creating a seamless and engaging MozFest experience. |

## Wranglers

| Update Type | Name | Twitter | Photo | Bio |
| --- | --- | --- | --- | --- |
| ADD to Digital Inclusion | Kristine Grivcova | empty | [Link](https://drive.google.com/file/d/1bkvsVnoepVrBB549e3obgMFsu-dfj3EA/view?usp=sharing) | Kristine Grivcova is a research engineer from London. She works at the BBC R&D, where she thinks about the future of technology and media. More specifically, Kristine explores machine learning and how it can be used in radio applications in a unique and transparent way. |

**Comment by mmmavis** [comment]
@gideonthomas yea I can crop images on my end for the website. For production team additions, could you specify where and in what order should I add those people in?

**Comment by Saallen** [comment]
@gideonthomas - can I have an update on this?

**Comment by gideonthomas** [comment]
It will be done this week -- we were waiting on Kristine's bio.

**Comment by mmmavis** [comment]
Done!
