### ISSUE TITLE
[DEV] Add featured theme to homepage

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1117]
Design comp: https://redpen.io/vscf67cb1fa98c5781

Assets: https://drive.google.com/drive/folders/1DNUbeRLQwYjyF69-44ET4EMoa3B72I_d

Content:

This year at Mozilla Festival, dive into our theme “Your Data and You,” through interactive sessions, art, games, dialogues, debates, and the latest tech. We’ll explore the risks and benefits, the implications for the health of the Internet, and how we can take control of our data, our online lives, and our collective future.

**Comment by mmmavis** [comment]
Done1
