### ISSUE TITLE
[DEV] Add 2018 sponsors to website

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1118]
Content ticket: https://github.com/mozilla/mozillafestival.org/issues/1027

### Sponsor List
Name | Image | Partnership Type | Link |
--- | --- | --- | --- |
Sticker Mule | [Image](https://www.stickermule.com/assets/images/stores/sticker_mule/press/downloads/logo-colored/Sticker-Mule-logo-SVG-e614db0061.zip) | Closing Party Partner | [Link](https://mule.to/mozfest-2018) |
Private Internet Access | [Image](https://drive.google.com/open?id=1-qpa-oANqW6xFgtitQc2VZyUlSTpRihe) | Presenting Festival Partner | [Link](https://www.privateinternetaccess.com/) |
Internet Society | [Image](https://assets.internetsociety.org/Styleguide/#page/029105C2-BD06-4184-9C413CD5BAB15B76) | Science Fair Partner | [Link](https://www.internetsociety.org/) |
Samsung | [Image](https://drive.google.com/open?id=1SDf1_ndD_cH42uBU39QZJ6iYvhyqHZ9s) | Youth Zone Partner | [Link](https://www.samsung.com/uk/apps/samsung-internet/) |

TODO:
1. Update /team/sponsors page. Presenting partner will replace Supporting Partner. The other three will replace the three below the supporting partner.

**Comment by mmmavis** [comment]
@gideonthomas are we keeping the existing "Our 2017 Sponsors" section AND add a new section "Our 2018 Sponsors" to the page? Or replace 2017 section entirely with 2018?

**Comment by gideonthomas** [comment]
replace it

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team/sponsors
