### ISSUE TITLE
[Oct 2] Port sessions and facilitators info to Guidebook

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1120]
According to [our original timeline](https://docs.google.com/document/d/1ahAMhq_GKBKR1velvE6iQgrZBC07OA6xoXpdaU3w8I4/edit#heading=h.eav1696hnq7e) - on ~~Oct. 1 Monday~~ postponed to Oct. 2 Tuesday, port sessions and facilitators info from the "accepted proposals spreadsheet" to Guidebook.

@marcwalsh let me know if we want to postpone this by a few days.

**Comment by marcwalsh** [comment]
Hey @mmmavis - we talked on the wrangler call today. 

We need to push this back until Tuesday 2nd please.

**Comment by mmmavis** [comment]
kk I'll update this ticket and the Google Doc!

**Comment by mmmavis** [comment]
Done!

Accepted proposals and their facilitators info have been ported to Guidebook!
