### ISSUE TITLE
Remove Ramy Raoof as MozFest speaker

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/mozillafestival.org#1124]
Hi @sabrinang & @mmmavis,

One of our speakers -- Ramy Raoof -- has had to drop out. Can we remove him from the https://mozillafestival.org/ homepage and also https://mozillafestival.org/speakers?

On a related note -- is there a ticket for the print program, so we remove him from there, too?

**Comment by sabrinang** [comment]
@KevZawacki I mentioned it to Makiko to remove it from the printed guide design issue as well https://github.com/MozillaFoundation/mozfest-design-2018/issues/73#issuecomment-426361029

**Comment by KevZawacki** [comment]
@sabrinang 🙏

**Comment by mmmavis** [comment]
Done!
