### ISSUE TITLE
Add curated sessions and general events info to Guidebook

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1128]
Accepted proposals and their associated facilitators info have been ported to Guidebook. This ticket is just a reminder so that we don't forget to add curated sessions and general events info to Guidebook (e.g, lunch time, opening talk, science fair, D&D talks etc)

**Comment by gideonthomas** [comment]
@marcwalsh this is done right? If so, can we close?

**Comment by gideonthomas** [comment]
I think this is done
