### ISSUE TITLE
[Post-MozFest] Remove wranglers' access to Guidebook

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#1129]
This is a reminder for us to remember removing wranglers' access to Guidebook after MozFest (not sure what the best time is, though).

**Comment by gideonthomas** [comment]
@mmmavis  we did this right?

**Comment by mmmavis** [comment]
@gideonthomas nope, roughly 50 people still have editor/admin access to MozFest 2018 Guidebook. Should we remove their access (all? non-staff?)?

**Comment by gideonthomas** [comment]
eeek for now let's remove non-staff access

**Comment by mmmavis** [comment]
Done!
