### ISSUE TITLE
Add Tim Berners-Lee to homepage + speaker page

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/mozillafestival.org#1130]
Hi @mmmavis, apologies for the late add. But, it's a good one!

Tim Berners-Lee has confirmed he will be speaking at MozFest. Sometime next week, could you add him to https://mozillafestival.org/ + https://mozillafestival.org/speakers?

[Here's his headshot](https://drive.google.com/open?id=1n4kOR5pk8aAsCo2x561PfiwEB2lkm4Nl).

Here's his bio:
"Sir Tim Berners-Lee invented the web in 1989. He is the founder and director of the World Wide Web Foundation and a professor at Massachusetts Institute of Technology and at Oxford University. He is co-founder and CTO of the newly launched company inrupt, that’s helping to fuel the success of Solid, the technically potent open-source platform built to decentralize the web."

On the homepage, the text under his headshot should read:
Tim Berners-Lee
[@timberners_lee](https://twitter.com/timberners_lee)
Talk

And on the /speaker page, he should go between Renee and Julie. His entry should read:

**Tim Berners-Lee on his latest work (Talk)**
_Saturday, Oct. 27, 12:45–13:45_
Then name, Twitter, bio

Note: Can you also update the timestamp for Renee's talk to "Saturday, Oct. 27, 12:45–13:45"?

Thank you! :-) Let me know if you need anything further!

**Comment by KevZawacki** [comment]
Hi @sabrinang 👋 

Sharing a heads up about a new speaker addition. 

I believe it's too late to add to the print program. But, is it possible to include Tim on design materials still in the works, like screen slides and posters?

**Comment by mmmavis** [comment]
Hi @KevZawacki where on the homepage D&D section do you want Tim to show up? Also in between Renee & Julie?

**Comment by KevZawacki** [comment]
Hi @mmmavis, between Renee and Julie would be perfect 👍 Thanks!

**Comment by mmmavis** [comment]
Done!
