### ISSUE TITLE
Old schedule page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1131]
This link is still live- can we archive 
https://app.mozillafestival.org/#_spaces

**Comment by gideonthomas** [comment]
@mmmavis not sure if this is something you can do or not, feel free to re-assign otherwise

**Comment by mmmavis** [comment]
@gideonthomas it's probably a @cadecairos thing.

@Saallen do you wanna make https://app.mozillafestival.org and all the pages under this domain `404` or ?

**Comment by marcwalsh** [comment]
@gideonthomas @cadecairos can we redirect this to - `https://guidebook.com/guide/147793/`

**Comment by gideonthomas** [comment]
assigning to me to file a devops ticket.

**Comment by gideonthomas** [comment]
Filed https://github.com/MozillaFoundation/mofo-devops/issues/630
