### ISSUE TITLE
2 small edits to https://mozillafestival.org/speakers

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/mozillafestival.org#1132]
Hi @mmmavis,

When you have a chance (not urgent), would you be able to make two small edits to  https://mozillafestival.org/speakers?

[1] Add a time under "Who Controls the Internet? (Panel)." The time is Sunday, Oct. 28, 12:45–13:45.

[2] Update the times for Soudeh Rad and Mitchell to 15:15 - 16:15. (They currently read 15:15 - 15:55.)

Apologies for the extra work as I finalize the schedule!

**Comment by gideonthomas** [comment]
@KevZawacki does this need to be reflected in the festival guide as well? This might have to be the final edit to the guide since we're going to print soon.

**Comment by KevZawacki** [comment]
Hi @gideonthomas, I reviewed the festival guide yesterday and flagged issues directly in that document, so no worries.

**Comment by mmmavis** [comment]
Done!
