### ISSUE TITLE
Update page for festival weekend- guidelines

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1136]
During the festival week, we will have many alternative ways to raise issues, online and in person. If you have issues, please direct them to festival@mozilla.org (Recipients of this email are Sarah Allen [Guidelines pag](https://mozillafestival.org/guidelines)e update request

paragraph labeled Raising Issues at MozFest
Please amend the last sentence....

During the festival week, we will have many alternative ways to raise issues, online and in person

Call +44 (0) 22 8553030
Email festivalsafety@mozilla.com
These channels reach Sarah Allen, Allen Gunn and Marc Walsh
#Mozhelp on Twitter
Go to Mozhelp desk on level 4 in Ravensbourne University

**Comment by gideonthomas** [comment]
@Saallen is this ok:
<img width="1439" alt="screen shot 2018-10-12 at 4 47 47 pm" src="https://user-images.githubusercontent.com/5816130/46893418-cf89aa00-ce3e-11e8-9b90-b84a373126a7.png">

**Comment by Saallen** [comment]
amend the first paragraph please

...and if you feel you are being harassed in any way please immediately contact the Festival Executive Director, Sarah Allen

[remove the next sentence  At the festival venue sent]
Immediately go into During the festival week,....

Amend last bullet point 
* Got to the #Mozhelp desk on level 4 over MozFest weekend at Ravensbourne University, or the registration desk at MozFest House in the RSA

**Comment by gideonthomas** [comment]
@Saallen how does this look? Had to change the copy a bit to accommodate the layout.

<img width="1440" alt="screen shot 2018-10-15 at 9 41 04 pm" src="https://user-images.githubusercontent.com/5816130/46987672-34553680-d0c3-11e8-8647-2248836d50ec.png">

**Comment by Saallen** [comment]
Thank you looks great

**Comment by gideonthomas** [comment]
@mmmavis would you be able to make the change as in the screenshot above?

The copy is:
If you believe you‘re experiencing practices at MozFest which don‘t meet the above policies, or if you feel you are being harassed in any way, please immediately contact the Festival Executive Director, Sarah Allen.

During the festival week, we will have many alternative ways to raise issues online and in person.

Call us at +44 (0) 22 8553030 or email us at festivalsafety@mozilla.com. These channels reach Sarah Allen, Allen Gunn, and Marc Walsh.

You can also tweet with #mozhelp on Twitter or visit the #MozHelp desk on level 4 over MozFest weekend at Ravensbourne University, or the registration desk at MozFest House in the RSA.

**Comment by gideonthomas** [comment]
Done
