### ISSUE TITLE
QA- website- weekend schedule

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1137]
As we have on all printed assets 12:00 start for lunch on Sat and Sun

Can we change it on Sunday to 12:00?
https://mozillafestival.org/why-come-to-mozfest

**Comment by gideonthomas** [comment]
Wait name tags say that lunch starts at 12...can you confirm?

**Comment by Saallen** [comment]
Wrong edits- updated above @gideonthomas

**Comment by gideonthomas** [comment]
@Saallen don't see the update :P mind posting it in a new comment?

**Comment by Saallen** [comment]
As we have on all printed assets 12:00 start for lunch on Sat and Sun

Can we change it on Sunday to 12:00?
https://mozillafestival.org/why-come-to-mozfest

**Comment by gideonthomas** [comment]
Awesome, thanks @Saallen! @mmmavis would you be able to do this?

**Comment by mmmavis** [comment]
Done!
