### ISSUE TITLE
New addition to sponsors page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1144]
New sponsor for website page only @gideonthomas 
Jessie to confirm the following info

- [x] confirmation of title of partner type
- [x] Confirmation of layout on page hierarchy
- [x] Logo - [in this folder](https://drive.google.com/drive/folders/1zWZdMp3xCjaisMM7ZDJP5_3syLUmTmEt?usp=sharing)
- [x] Link - https://www.shareable.net/

**Comment by gideonthomas** [comment]
will ask Jessie on Monday.

**Comment by Saallen** [comment]
Update from Jessie @gideonthomas 
Call them Media Partner

 Also, if possible, I would change the order of sponsors on the web page to 1. Private Internet Access  2. ISOC   3. Shareable   4. StickerMule   5. Samsung.

**Comment by gideonthomas** [comment]
Thanks @Saallen!

@mmmavis would you be able to make this change?

Sponsor: Shareable
Image: https://drive.google.com/file/d/1drOOkrKXf9PlAMFdiipuitRv2qJ4MBZ0/view?usp=sharing
Title: Media Partner
Link: https://www.shareable.net/

Order of Sponsors should be:
1. private internet access
2. Internet Society
3. Shareable
4. Stickermule
5. Samsung

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team/sponsors

**Comment by Saallen** [comment]
Thanks!!!
