### ISSUE TITLE
Remove offline schedule info on /schedule

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/mozillafestival.org#1145]
@mmmavis @sabrinang mentioned that we probably shouldn't say that "you can find the schedule on info booths" because that isn't necessarily true.

Can you remove that last line "If you don't wish to use Guidebook, please note that we will be displaying the schedule at info booths on each floor over the festival weekend." from the `/schedule` page?

@Saallen are you ok with this?

**Comment by Saallen** [comment]
But the schedule will be shared on screens at the Info booths- which are a table with a screen laptop and two volunteers- and the large info totems

**Comment by gideonthomas** [comment]
Oh ok if this is confirmed, that's perfect, sorry, we weren't aware of this! Thanks!

cc @sabrinang
