### ISSUE TITLE
QA- landing page and schedule banner

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1151]
@mmmavis - As the landing page is often the about page on mozfest.org
can we get the schedule banner here too- mirroring the top banner from the home page?
![screen shot 2018-10-24 at 19 30 57](https://user-images.githubusercontent.com/10194015/47452951-5d608000-d7c3-11e8-918d-312686db9b3b.png)

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/about

**Comment by Saallen** [comment]
Thanks Mavis. Super speedy
