### ISSUE TITLE
Ticket page- 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1152]
cc @gideonthomas 
We have sold out of all tickets apart from Sunday and Youth- is there a way to signify this on the ticket page? You cannot tell in its current format and top line of options gives rego not available options. People wont click through all options until Sunday..
https://mozillafestival.org/tickets

**Comment by mmmavis** [comment]
@Saallen Would simply replacing the ticket button with "Sold Out" work?

![screenshot_2018-10-25 mozilla festival mozfest](https://user-images.githubusercontent.com/2896608/47492183-5037a580-d844-11e8-9a73-80bb0b76d121.png)

**Comment by Saallen** [comment]
Yes please

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/tickets
