### ISSUE TITLE
Add YouTube Links for Individual Speakers

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#1161]
@gideonthomas @mmmavis - can you add the individual talk links to each of the speakers on the website. There is one or two still processing, which should be complete in the next couple of hours.

cc/ @Saallen 

Thanks!

## Add Video Links To:
- [x] Amba Kak - `https://youtu.be/jrZD6eK-fRw`
- [x] Zara Rahman - `https://youtu.be/FsIXHQifkXw`
- [x] Malavika Jayaram - `https://youtu.be/FsIXHQifkXw`
- [x] Renee DiResta - `https://youtu.be/baPF-sOXP24`
- [x] Tim Berners-Lee - `https://youtu.be/elfSzMATcB4`
- [x] Julie Owono - `https://youtu.be/sOieG7xvBNA`
- [ ] ~~Esra’a Al-Shafei~~ - `Not Available`
- [ ] ~~Mahsa Alimardani~~ - `Not Available`
- [x] Camille Francois - `https://youtu.be/503Yup0wpIk`
- [x] Guillaume Chaslot - `https://youtu.be/503Yup0wpIk`
- [x] Alondra Nelson - `https://youtu.be/503Yup0wpIk`
- [x] Clinton Watts - `https://youtu.be/503Yup0wpIk`
- [ ] Roya Mahboob (@KevZawacki should we remove Roya?)
- [x] Nathalie Richards - `https://youtu.be/EwT9Mpzft4I`
- [x] Maryant Fernandez - `https://youtu.be/R8crgz1Wb1I`
- [x] Chris Riley - `https://youtu.be/R8crgz1Wb1I`
- [x] Soudeh Rad - `https://youtu.be/cyEwbmYn7fA`
- [x] Mitchell Baker - `https://youtu.be/gmcU-uMWNj0`

**Comment by marcwalsh** [comment]
@gideonthomas @mmmavis - all video links are updated in the initial ticket info :)

**Comment by gideonthomas** [comment]
@jessevondoom @alanmoo cc'ing you here in case you want these links for the foundation site as well.

**Comment by KevZawacki** [comment]
🎆 

Hi @mmmavis, we can indeed remove Roya. That section can be updated like so:

Nathalie Richards on Tech and Inclusion (Talk)
_Sunday, Oct. 28, 11:00–12:10_
[Video](https://www.youtube.com/watch?v=EwT9Mpzft4I&feature=youtu.be) 

**Nathalie Richards**
[nathrich](https://twitter.com/@nathrich)
Nathalie Richards is co-founder of EduKit, a free online resource for teachers.

**Comment by gideonthomas** [comment]
Done
