### ISSUE TITLE
Write post-festival wrap-up blog

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#317]
@HPaulJohnson to draft the skeleton. We'll fill in the content over the weekend and finalize on Monday, Nov 9.

cc @KevZawacki

**Comment by edrushka** [comment]
Draft here: https://docs.google.com/document/d/1-Uu_UKiRZOUFIzHKRWTyD47WnVVwcEP7Qhs_VWWxZt4/edit

**Comment by mmmavis** [comment]
@edrushka I believe we can close this ticket? 🐹

**Comment by edrushka** [comment]
ha! 2015! DONE!

**Comment by mmmavis** [comment]
🌻
