### ISSUE TITLE
Prepare for 2016 site updates

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#353]
From https://github.com/MozillaFoundation/mofo-devops/issues/309#issuecomment-207022922 

Tackle the following tasks in order

1. [x] move the current codebase (2015 site) to `2015.mozillafestival.org` branch (copy `master`)
2. [x] temporarily remove `.travis.yml`
3. [x] rename this repo to `mozillafestival.org`
4. [x] check in 2016 site updates to `develop` and `master`
5. [x] link `develop` to `master` to Heroku instances for staging and production respectively
6. [x] update `.travis.yml` and add it back to repo

**Comment by ioana-chiorean** [comment]
hey @mmmavis - let me know if you need some QA on these last few changes made.

**Comment by Saallen** [comment]
@ioana-chiorean It would be great to have you on QA after you spotted some hidden issues last year. Feel free to check out the new site and the call for Proposals and let us know what you think

**Comment by mmmavis** [comment]
Oops. forgot to close this ticket. This is totally DONE!

thanks @ioana-chiorean 😄 let us know if you spot anything that needs improvement!
