### ISSUE TITLE
Upgrade React  to v15

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#357]
Upgrade `React` to `v15`

**Comment by Pomax** [comment]
0.14, or 15.0?

**Comment by mmmavis** [comment]
Was thinking v0.14 first since it might be a big jump. We can do 0.14 -> v15 in a follow-up PR. 

If this sounds redundant let's just upgrade to v15 straight. :grin:

**Comment by Pomax** [comment]
Not sure we'd get a lot out of first doing 14 if we then have to still move up to 15, so it might be worth just going for 15 on a smaller project like this, to get a sense of how much work it'll be for the larger React projects (like teach)?

**Comment by mmmavis** [comment]
cool that makes sense. let me edit this ticket a bit :wink:
