### ISSUE TITLE
Improve the look of ti.to

### ISSUE THREAD

**Issue by vazquez** [mozilla/mozillafestival.org#364]
I want to find out how much flexibility ti.to gives us to modify the look of the registration page: https://ti.to/Mozilla/mozfest-2016.

@mmmavis, do you know how I can access the admin section of ti.to to see/make changes?

**Comment by vazquez** [comment]
Changes made! [https://ti.to/Mozilla/mozfest-2016](https://ti.to/Mozilla/mozfest-2016)

This is what was changed:

- Added apple wallet icon
- Adjusted map so that it's more awesome
- Added a homepage banner
- Changed theme

I feel this is good to close. I've extended pretty much all of tito's customization features.

**Comment by mmmavis** [comment]
:sparkles:  :eyes:
