### ISSUE TITLE
Mozfest proposals github integration

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/mozillafestival.org#383]
@mmmavis there is where I got.

Right now the pull request for the form I have been working on is here: https://github.com/mozilla/mozillafestival.org/pull/365

The form itself is finished. It's a pretty quick and dirty job mostly from running with last year's form and not getting fancy.

I'm setting up the integration to a google sheet now.

I'm slipping on the github integration.

We also wanted to setup an email if the github integration happens inviting people to come edit their session. We could still do this a few days after we open proposals, that just means we'll need to do a single migration when we start github integration, and let real time github ticket creation happen from there on out, and send out the emails when we do the migration once we open up github integration.

I also need to setup the form for the other languages too. It's not a huge l10n integration, MVP just need a copy of the form in a new URL with the copy changed.

- [x] update form based on recent changes to google form (scott)
- [x] integrate with sheets (scott)
- [ ] email setup (cade)
- [ ] integrate with github
- [x] setup multiple langs (scott)

**Comment by ScottDowne** [comment]
cc @edrushka @simonwex @mmmavis

**Comment by ScottDowne** [comment]
Adding this: https://docs.google.com/a/mozillafoundation.org/forms/d/19eD51TFUfklPS57XccwP_YPkDZ4DVl_aB4olaJmvgNU/edit

That's the example for what the form needs to look like.

**Comment by ScottDowne** [comment]
Here is the sheet I setup that's a backend for the data to live. https://docs.google.com/spreadsheets/d/1b7QggNDiPd4cpml4fgGeQJ_DsS90p54np34l4GLjMN0/edit#gid=1419268412

This is the form fields, which should not be used, instead use this for editing the fields: https://docs.google.com/a/mozillafoundation.org/forms/d/1E0-DnkmwsXLJNwe5l5S56-cGuKxjkpgYJhI5iXvuEZg/edit

**Comment by ScottDowne** [comment]
@mmmavis I think I need help with the github integration, and maybe the other langs.

**Comment by mmmavis** [comment]
Thanks for the explanation/summary @ScottDowne 😄 

> We also wanted to setup an email if the github integration happens inviting people to come edit their session.

If I remember correctly, we don't wanna let people edit their session proposal once submitted. They can comment on the Github ticket but not modify the original proposal. Otherwise it can make the proposal reviewing process really hard for the program team since the proposals may or may not be final (no easy way for the team to tell). Another thing is that even if proposal submitters wanna make changes, they will *not* be able to edit the ticket due to the lack of privilege on the repo.

**Comment by mmmavis** [comment]
> I also need to setup the form for the other languages too. It's not a huge l10n integration, MVP just need a copy of the form in a new URL with the copy changed.

Ummm... since the Google form is used as data storage backend(Google form should never be shared out directly otherwise the real time Github integration will be skipped) and the MozFest site is only available in English. I wonder if having ONE English form is enough? @ScottDowne @edrushka

**Comment by ScottDowne** [comment]
I figured it would multiple pages with different copy (translations) and
form fields which all submits to the same Google form back end. It wold say
which lang as a form field.

**Comment by mmmavis** [comment]
> I figured it would multiple pages with different copy (translations) and form fields which all submits to the same Google form back end. It wold say which lang as a form field.

Still feel a little incomplete since only the form will be localized - the rest including comments on Github and response from the program team will be in English. Maybe we can leave this as P2?

**Comment by ScottDowne** [comment]
I'm pretty sure we have people who know those Lang's that can manage those
tickets.

**Comment by ScottDowne** [comment]
So, I'm ending my day today with a working English submission to google forms, seems like the P1. The rest we can figure out tomorrow, as P2s.

**Comment by ScottDowne** [comment]
@mmmavis @edrushka @Saallen

Dev link is here: https://arcane-peak-71038.herokuapp.com/proposals

It works and the data should end up here: https://docs.google.com/spreadsheets/d/1b7QggNDiPd4cpml4fgGeQJ_DsS90p54np34l4GLjMN0/edit#gid=1419268412

You should all have access to that sheet.

Feedback is welcome in this ticket for now.

**Comment by Saallen** [comment]
Feedback on copy- 
This year we are accepting proposals in Hindi, French and Arabic
this should be Spanish, French and Arabic

**Comment by Saallen** [comment]
There is American spelling here- the 👊 between the Z and S
Organization- @edrushka are we sticking to European spelling here?

**Comment by Saallen** [comment]
There should be a subnote by organisation and Twitter handle- 
Organisation should have- please leave blank if you don't want it publised
Same for twitter

**Comment by ScottDowne** [comment]
The Organization vs Organisation thing was my bad. I agree it should be Organisation for this.

Updated Organization and the langs.

Doing the twitter/org public note now.

**Comment by ScottDowne** [comment]
@Saallen I updated the copy on twitter and org privacy, but, the copy was kinda guessed. If you want me to change it to something explicit I'm happy to :)

**Comment by ScottDowne** [comment]
Could we also go with "Please leave blank if you want it private." maybe?

**Comment by Saallen** [comment]
Feedback- Other faciliators should have additional comment below which says:
One per line, (e.g. John Doe @j.doe <j.doe@example.com>)

**Comment by Saallen** [comment]
Freedback- there should be no other option on the botton of the first section- my bad

**Comment by Saallen** [comment]
Feedback- 
the text on the top of the section two should read
Call for artists, designers, creative technologists, makers, coders, scientists, visual journalists -- from techies to newbies! We are inviting submissions of original artwork that relates to our lives online.

Submissions can be mixed-media, photography, video, games, animation or moving images, visual art, graphic design, or sculpture. Although the work may be performative or 3D in origin, please consider that it will be exhibited on screens and must be submitted digitally. 

On this call we are only accepting digital work. The set-up and curation of the exhibit will be done through an exploration of DIY solutions, mainly working with a variety of screens, open-source technology and experimenting with layouts. 

Please ensure images are 300 dpi. Videos should have a 4:3 or 16:9 ratio, and be 5 minutes max.

**Comment by Saallen** [comment]
Feedback-
section two Method on its own feels confusing...are we missing text here?

**Comment by ScottDowne** [comment]
@Saallen if other doesn't make sense in section 1 space radio buttons, does it also not make sense in section 3 another space radio option, same goes for the other space input in "Is there another space you believe this exhibit could be shown within?" in section 2.

**Comment by Saallen** [comment]
Yes, that is correct- there should be no other option of other

**Comment by ScottDowne** [comment]
@Saallen you lost me on that last comment :P 

You mean, no other option for the three space related radios, one for each page. So other option only applies to the format bit? "MozFest accepts many different session formats. What do you think would work best for your session? (multi select option) *"

**Comment by Saallen** [comment]
Yes @ScottDowne 😵

**Comment by Saallen** [comment]
Feedback:
Is there another space you believe this exhibit could be shown within?
Missing Open Badges from the list

**Comment by Saallen** [comment]
Feedback: on the terms and conditions section on section two-
Please remove " 
The agreement is not that this is origional work but that you agree to all the terms, so the tick box should be " yes I agree to these terms above"

**Comment by Saallen** [comment]
Feedback:
If I dont agree the popup red text reads- Must be your own original work.
This will need to be changed. 
I might ask @edrushka for her advice on what to have here instead

**Comment by Saallen** [comment]
Feedback:
on section three question 4 can you change this Tell us what you'll do with 3 participants. 15? 25? 
to this- Tell us what you'll do with 3 participants? 15? 25?

**Comment by Saallen** [comment]
Feedback:
after session format we should have a question  follow imediately
If you chose "other" above, please outline why below

**Comment by ScottDowne** [comment]
@edrushka @Saallen for the terms and conditions error message, what about something like "You must agree to the above terms and conditions."?

**Comment by ScottDowne** [comment]
I think I have done everything for feedback so far cept https://github.com/mozilla/mozillafestival.org/issues/383#issuecomment-222734443 which needs a decision made before I can do anything.

**Comment by edrushka** [comment]
Agree it's slightly confusing, but let's leave for now and if people answer the question in a way that isn't helpful to Luca, we can change the wording or add a text hint explaining what kind of answer we want. @ScottDowne ship it as-is.

**Comment by edrushka** [comment]
Here's my 👀 on the form:

**Page 1**
- [ ] reword deadline line in banner to fix typo:  Deadline for submissions is August 1, 2016 at 21:00 UTC
- [ ] link the words Spanish, French and Arabic to their respective forms
- [ ] change Organisation field subtext to fix typo: Please leave blank if you don't want it published.
- [ ] change Other facilitators field for clarity: One per line, format is Name[single space]Twitter handle [single space]email (e.g. John Doe @j.doe j.doe@example.com)
- [ ] change Twitter handle question for consistency and typo: 

Twitter handle
Please leave blank if you don't want it published.
- [ ] add link to What Space are you submitting your proposal to? so it reads
What Space are you submitting your proposal to? Read details on each Space here [link to Spaces and Sessions page]

**Page 2** (if you selected MozEx as your space)
- No changes! 🐬 

**Page 3** (if you selected any other space)
- [ ] For the first question, MozFest accepts many...  change the bracket text from (multi select option) to (you may select multiple formats)
- [ ] For the second question, remove the word 'below' so it simply reads: If you chose "other" above, please outline why.

**Comment by ScottDowne** [comment]
This is done enough that this ticket is no longer useful. Closing.
