### ISSUE TITLE
Get Fringe page up

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#386]
For reference, 2015 Fringe Events:
- Google Form: https://docs.google.com/a/mozillafoundation.org/forms/d/1XCjIF3ptc4XAl7ql-pkhhIDc7dERYshrLHOFZgjdIUY/viewform
- Response: https://docs.google.com/spreadsheets/d/1nzxWVgjB92R4-VdZF4RRqa2Rl7i5hkbsRYSUEddcOGE/edit#gid=677270378

We should set up the same flow for this year. @edrushka do you know who will be approving the fringe events before we show them on the MozFest site? Last year it was @Saallen (I think).

**Comment by edrushka** [comment]
Ah, sorry @mmmavis - there's a ticket here https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/12

The 2016 from has been created: https://docs.google.com/a/mozillafoundation.org/forms/d/10l8_PtMgHvhxh4qZcGqTzWm3a0QhuTQOIVnn4Bx8qKc/edit# 

Yes, either Sarah and/or I can approve the events before we show them on the site. And yes, we can use exactly the same flow as last year.

**Comment by Saallen** [comment]
Yahhooooo 🎉
