### ISSUE TITLE
Update og:image

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#407]
original ticket filed here: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/64

**Comment by mmmavis** [comment]
current: https://github.com/mozilla/mozillafestival.org/blob/develop/public/assets/images/site-thumbnail.png (old pic from 2015)

![current](https://raw.githubusercontent.com/mozilla/mozillafestival.org/develop/public/assets/images/site-thumbnail.png)

can we create a version for 2016 plz? https://github.com/mozilla/mozillafestival.org/blob/develop/public/assets/images/mozfest_2016.jpg
![2016](https://raw.githubusercontent.com/mozilla/mozillafestival.org/develop/public/assets/images/mozfest_2016.jpg)
- size: 1200px * 630px
- with MozFest wordmark on it

@kristinashu can I get some help from you? 😄

**Comment by kristinashu** [comment]
Yup! Here you go:
![site-thumbnail2016](https://cloud.githubusercontent.com/assets/1068783/16205827/820cf186-36da-11e6-9842-5f6397271ce0.jpg)
Let me know if you need anything else!

**Comment by mmmavis** [comment]
@kristinashu lovely thanks! 🌹
