### ISSUE TITLE
Update Tabzilla to the latest version

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/mozillafestival.org#413]
The Mozilla Tab is lately used just to redirect to mozilla.org from what I am seeing right now on other websites. 
Either way - it shows the gear store which is closed at the moment so there is no point  ( beside the other links ) to open  it up. 

https://www.mozilla.org/en-US/firefox/products/
https://www.mozilla.org/
https://www.mozilla.org/en-US/contribute/

![unspecified1](https://cloud.githubusercontent.com/assets/1391451/16647087/2eec8f0c-4436-11e6-87f2-5315dc9711f5.png)

**Comment by mmmavis** [comment]
Good discovery. Thanks @ioana-chiorean ! 😉  Yeah I think that's cuz we are still using the old Tabzilla - we should update it to the latest version.
