### ISSUE TITLE
link spaces on /proposals to their descriptions on /spaces-and-sessions

### ISSUE THREAD

**Issue by autonome** [mozilla/mozillafestival.org#423]
Had some feedback from people trying to submit proposals that they don't know what the spaces mean. There's a small bit of text at the top of the list that links the word "here" to the spaces page, but each time I pointed that out, the user said "totally didn't see that at all".

Instead we should have each space listed in the form linked to their description, or have a "(learn more)" link after the space title, and have those links open in a new window.

Looks like no anchors in the spaces-and-sessions page, so would need to add those, eg:

https://mozillafestival.org/spaces-and-sessions#digital-arts-and-culture

**Comment by mmmavis** [comment]
Hi @autonome I made the anchor links more discoverable - clicking on any space name on https://mozillafestival.org/spaces-and-sessions will give you the anchor link to that particular space description. Was just a quick fix... I'm open for design suggestion! 😉

**Comment by autonome** [comment]
Great, thanks Mavis! That makes it easier for wranglers to link directly to
their space descriptions.

If we can link the space names on /proposals to those anchors, we can close
this issue out!

**Comment by ioana-chiorean** [comment]
🎉

**Comment by autonome** [comment]
@ioana-chiorean this isn't closed yet! the space names in /proposals are not yet linked to the anchors Mavis created in /spaces-and-sessions.

**Comment by ioana-chiorean** [comment]
@autonome Sorry I misunderstood then ( i thought the patch fixed it)

**Comment by mmmavis** [comment]
@autonome @ioana-chiorean thanks! you two are more active than I'm on this repo (shame on me)! 

Deadline for this year's call for proposal has passed.  We'll make sure we make the space descriptions more discoverable next year. 🍻
