### ISSUE TITLE
some improvement to /proposals text

### ISSUE THREAD

**Issue by autonome** [mozilla/mozillafestival.org#424]
Been getting feedback that this page is confusing.

> "Share your idea"

This is a bit confusing, since it's unclear whether you're actually submitting something *you* will be doing, or that you think the conference should do. Would be clearer as something like "Submit your proposal". Not as nice sounding, but much clearer - suggestions welcome :)

> "MozFest is a diverse, interactive and highly inclusive event with sessions, activities and experiences suited for a range of interaction styles."

This sentence sounds awesome! But then the next sentence is...

> "You should expect anywhere between 3 and 25 participants at your session. Be prepared for all abilities and ages in the audience. As a facilitator, you will frame the session goals, team up small groups and ensure participants work productively and purposefully together."

Which only makes sense for a traditional conference session, not "sessions, activities and experiences suited for a range of interaction styles" as we stated moments before. Maybe could take this whole section out, since the form itself guides some of this.

**Comment by mmmavis** [comment]
Hey @autonome , thanks for providing your valuable feedback! 👍 Just so you know that @Saallen and @edrushka might be unavailable to reply at the moment due to travel/PTO.

**Comment by edrushka** [comment]
@autonome Thanks Dietrich! These are all great points/observations. Unfortunately I was largely offline with PTO and various team events and didn't catch this until now....and the call for proposals closes in 3 days. 

There's a lot we can do to improve the entire submission process in 2017, starting with more streamlined copy. I will flag this as a reminder, and see if there's any way to include you suggestions in future 2016 comms.

**Comment by Saallen** [comment]
Hey @autonome thanks for the feedback- we have captured this already for our lessoned learned 2016. Good shout out

**Comment by mmmavis** [comment]
thanks again @autonome 🍸 🍰 🍷
