### ISSUE TITLE
Make Participation Guidelines more CoC explicit

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/mozillafestival.org#425]
I am subscribed to a newsletter about Call for Papers (http://papercall.io/cfps) and in the last one ("The Weekly CFP Issue #44") I was happy to see they mentioned MozFest for the next week. But.. at Code of Conduct they said none. While I already contacted them and shared the Participation Guidelines I was thinking if there is anything we can do on our side to have this  more explicit? ( maybe add under participation guideline in small letters Code of Conduct?)

My worry is that some might not even apply if they consider we do not have a CoC - even if we do have it under a nice name: https://mozillafestival.org/guidelines

![screenshot from 2016-07-19 08 36 17](https://cloud.githubusercontent.com/assets/1391451/16940227/0cb06c60-4d91-11e6-8481-34a2984d4f1c.png)

cc @autonome as he is also experienced with this. 
cc @Saallen - as for travel expenses we might want to tell them we do cover some? In some cases they mentioned, yes,some or a mail to get more details.

**Comment by SpikeUK** [comment]
In general I would agree with making it more obvious our 'Participation Guideline' are effectively a CoC.
We added the Guidelines either 2014 or 2013 - I cannot remember now.
When the Local Volunteers sign-up they are directed to the Guidelines and tick a box to indicate that they have read them and agree to abide by them. Additionally, I go through them at at least one of the training sessions. We also had a copy of them printed out and stuck up on the wall in the Volunteers room last year and will do the same this.

**Comment by ioana-chiorean** [comment]
I know it is present @SpikeUK - my proposal is just for the Call for papers specifically. 
Maybe we should consider linking it to the page directly, int he text somewhere. 

Their reply on twitter: https://twitter.com/scottefein/status/755349764997341184

**Comment by SpikeUK** [comment]
Ah, apologies @ioana-chiorean - I did not realise that you were specifically referring to the CFP shout out and submission process. I agree we should give it more prominence some how.

**Comment by Saallen** [comment]
Hi guys,
this is interesting-  @ioana-chiorean thanks for sharing this and contacting them.
 Its funny, we do have a code and we do offer stipends....
We made our participation guidelines in accordance to Mozillas specific guidelines and spent a long time on them,with many voices. While they are not on the top info line, we couldnt fit everything on that navigation bar- we do a lot of work with our facilitators pre festival sharing and explaining these guidelines, and use the main stage to  voice them. I can email the Call for Papers and get the proper links on there- thanks 👍

**Comment by ioana-chiorean** [comment]
@Saallen -so did we took a decision here? Will we add a line in the Call for proposals? Or by reaching them we are ok? ( just to know if we keep this issue open or not.)

**Comment by Saallen** [comment]
Hi @ioana-chiorean - we are not adding it into the call as its on the main page of the website and call is closing.
We can close this issue if everyone else is happy?

**Comment by ioana-chiorean** [comment]
Good for me! 
_Maybe a note for 2017 as many people care a lot about this before submitting._

**Comment by Saallen** [comment]
@ioana-chiorean Sure- we have added this to our list already for 2017 :)
