### ISSUE TITLE
Feedback sent to Festival Email

### ISSUE THREAD

**Issue by marcwalsh-zz** [mozilla/mozillafestival.org#428]
Dear MozFest,

The https://mozillafestival.org/ site is nice and easy to read - for me.
But the only way to read it is if JavaScript is enabled in a browser,
which is not very friendly towards a significant amount of people.

Also: all the header tags lack anchors, therefore when I wanted to link
the localization topic to other, I can't directly do it.

Please reconsider doing progressive enhancement sites instead of a
Javascript-only version and to make use of the semantic ideas that help
a lot of people with disabilities.

All the best,

**Comment by mmmavis** [comment]
Thanks for forwarding the email @marcwalsh !

I just made the anchor links more discoverable - clicking on any space name on https://mozillafestival.org/spaces-and-sessions will give you the anchor link to that particular space description. Was just a quick fix... I'm open for design suggestion! (maybe I should just get some help from the designers 😉 )
