### ISSUE TITLE
Change messaging now all volunteers places are filled

### ISSUE THREAD

**Issue by SpikeUK** [mozilla/mozillafestival.org#467]
On volunteer please change the text on the button from "Sign Up to be a MozFest Volunteer" to "Sorry, All Volunteer roles Have Now Been Filled" (capitalise to suit). Button should be changed to a dummy with no function.

**Comment by SpikeUK** [comment]
Not sure how I should draw attention to this request - can anyone advise please

**Comment by marcwalsh** [comment]
@edrushka  - I'm not admin on this repo so can't change anything. Are you alright to oversee this please?

**Comment by edrushka** [comment]
Hey @SpikeUK you're in a repo we don't monitor. I've filed the ticket here: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/112

**Comment by SpikeUK** [comment]
Thank you @edrushka - I am a numpty with Github :)
