### ISSUE TITLE
Update production site

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#478]
`master` branch has [code for livestream version of homepage](https://github.com/mozilla/mozillafestival.org/commit/945a3cc13cbeef7518a908cac0652590b51803da). We don't want to push it live just yet. @edrushka can you ping me or any dev when we are ready to "press the button"?

To push this to production:

Go to the `mozillafestival-org` pipeline on Heroku and press "Promote to production..." button on the staging section.

**Comment by alanmoo** [comment]
✅
