### ISSUE TITLE
Add Pulse Projects to Festival site

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mozillafestival.org#482]
@kristinashu @edrushka – @alanmoo and I spoke briefly about putting MozFest related things from Pulse directly on the site. He whipped up a page that I think is just about good to go. 

_Why not link to Pulse?_ Pulse isn't ready for prime time. It's got some rough edges that be exposed by a huge amount of traffic. Integration will also make way more sense for visitors to the site. 

I think the page just needs a sentence or two at the top for context. 
https://mozillafestival-org-sta-pr-481.herokuapp.com/projects

Thoughts?

**Comment by xmatthewx** [comment]
@kristinashu – please do a quick design review of the page linked above this week. Or, assign back to me. 

@alanmoo – I spoke with Sarah and Erika, and we will run with this approach rather than an external link.

**Comment by xmatthewx** [comment]
@Saallen – see link above. It doesn't mention or link to Pulse itself, but that could be added when v2 is built.

**Comment by kristinashu** [comment]
@xmatthewx this page should have a banner image like the other pages and then the "Mozfest Projects" title can go over top of it. 

Do you have some intro text to give it context?

**Comment by xmatthewx** [comment]
@edrushka how about: "MozFest attracts and generates dozens of projects that thrive long after the festival weekend. We've gathered examples here that provide a catalyst for enduring collaboration across our vibrant network."

A banner image would be good if we can find a moment to make it. If not, can we survive without? I don't think it's a blocker.

**Comment by kristinashu** [comment]
Here's a banner image: ![project-banner](https://cloud.githubusercontent.com/assets/1068783/20023182/9d4ed0b8-a29b-11e6-8350-b893f40bd39c.jpg)

**Comment by xmatthewx** [comment]
Thanks @kristinashu 

@alanmoo - let's update with banner and below it, this intro text.

> MozFest attracts and generates dozens of projects that thrive long after the festival weekend. See the examples below and find a catalyst for collaboration with our vibrant network.

Below the projects, let's add:

> See more projects & assets from our network on [Pulse](https://mzl.la/pulse).

**Comment by alanmoo** [comment]
I've updated the PR- [take a look](https://mozillafestival-org-sta-pr-481.herokuapp.com/projects) at this and let me know if it needs anything else.

**Comment by kristinashu** [comment]
Looks good @alanmoo, just the h2 title should be blue #362fc1 instead of the old red #E14164 color.

**Comment by xmatthewx** [comment]
I added two comments in the PR. Left align visit buttons. Add and reorder projects. Should have posted that here.

**Comment by alanmoo** [comment]
I've addressed these issues. One more look?
