### ISSUE TITLE
Order of menu items

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mozillafestival.org#483]
Order of the main nav seem quite random at the moment ([temp link](https://mozillafestival-org-sta-pr-481.herokuapp.com/projects)): 
Projects
Schedule
Blog
What to Expect
Spaces & Sessions

I recommend we update it to: 
What to Expect
Spaces & Sessions
Projects
Schedule
Blog

What do you think @xmatthewx @alanmoo?

**Comment by xmatthewx** [comment]
Agreed. I didn't notice before, but the label "What to Expect" is a bit weird post festival. `About` would make sense, but we use that in the footer. `About MozFest`??

**Comment by alanmoo** [comment]
The only issue I see with that is the page URL is "expect". Do we change the title on the page itself, but not the URL? Or leave the page alone and just change the header link title?

**Comment by xmatthewx** [comment]
Oye. Um. I don't think it matters too much either way. I can't imagine there are many direct bookmarks. I also can't imagine many people will notice the URL. Not ideal, but not critical.

I'd vote to change the label only. But let's see what @kristinashu says about the label itself.

**Comment by kristinashu** [comment]
"What to Expect" doesn't seem like an issue so I think we could keep it the way it is.
