### ISSUE TITLE
What To Expect page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#489]
https://mozillafestival.org/expect
    
**What is MozFest like?**
- [x] Change "Read our Festival Guide" to "Read the 2016 Festival Guide"

**Video**
- [x] Update to 2017 video (link will be ready by Feb 24)

**Weekend Outline**
- [x] Change dates on table to Friday Oct 27, Saturday Oct 27, Sunday Oct 29

**Participating at MozFest**
- [x] Link "Participation Guidelines" in the last para to https://www.mozilla.org/en-US/about/governance/policies/participation/

**Comment by hannahkane** [comment]
@edrushka - will the video be ready today?

**Comment by edrushka** [comment]
🔥 Hot off the press, here it! 🔥 

https://vimeo.com/205552025/37560e3619

cc @alanmoo

**Comment by hannahkane** [comment]
@alanmoo - mind doing the video link replacement? I'm getting on a plane shortly.

**Comment by alanmoo** [comment]
This is merged and on staging
