### ISSUE TITLE
Fringe page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#494]
https://mozillafestival.org/fringe
- [x] Replace the 3 paragraphs of text with:

MozFest is about working in the open and sharing ideas with the greater community. There are several innovative events taking place around the world with this same philosophy, and we would love to align them with MozFest.

How do you know if your event is a Fringe Event? It can be held anywhere in the world, but must include collaborative workshops or discussions focused on building tools and resources to keep the Web free and innovative.

**We are expanding the festival in 2017 to feature an entire week of Fringe Events.** Contact us to learn more.

- [x] Update CTA button. Text: Contact Us Links to: festival@mozilla.org
- [x] Remove (hide) events and form from page

**Comment by hannahkane** [comment]
@alanmoo - didn't know the best way to hide the form. Can you let me know the best way?

**Comment by alanmoo** [comment]
@hannahkane commenting out these lines: https://github.com/mozilla/mozillafestival.org/blob/master/pages/fringe-events.jsx#L241-L251 and the horizontal rule line, separately should do it. Don't want to remove them entirely since there's a good chance they'll be back.

Comments in JSX are done by wrapping with `{/*`. So, `{/* <div>Foo</div> */}`

**Comment by hannahkane** [comment]
thanks, @alanmoo. just added this. (to the same branch. was that not the right workflow?)

**Comment by alanmoo** [comment]
That's fine. Usually if you make change to a PR you request a review again, but letting me know here works.

**Comment by edrushka** [comment]
Just clarifying that the events and form will indeed return later in the year. I think you're both aware, but just so there's no confusion due to my wording above.

**Comment by hannahkane** [comment]
Thanks, @edrushka. We just hid it, but will be easy to un-hide when we need to.
