### ISSUE TITLE
Terms page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#497]
https://beta.webmaker.org/#/legal?_k=unyb1o

- [x] update this link to point to https://www.mozilla.org/en-US/about/legal/terms/mozilla/

**Comment by alanmoo** [comment]
Was this from the footer or was it elsewhere on the teams page?

**Comment by hannahkane** [comment]
@alanmoo - are you asking what @edrushka was intending with this ticket, or what I implemented? I updated the link to Terms in the footer, which is, I believe, the only place it appears. But @edrushka to confirm.

**Comment by alanmoo** [comment]
Both, kind of. I just did a search on `master` for  that link and nothing came up, so I'm going to call this closed.

**Comment by edrushka** [comment]
Confirming it was only on the footer.
