### ISSUE TITLE
Update wordmark

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#499]
The MozFest wordmark (Mozilla Festival and gear icon) is featured in the nav bar of every page on the [website](https://mozillafestival.org/). It does not align with the new branding guidelines.

Please update the design to align with the new brand.  

Note 1: we need to continue using the name Mozilla Festival and should not shorten it to MozFest at this time.

Note 2: this wordmark will also be used in the promo video

**Comment by sabrinang** [comment]
The new brand doesn’t have clear guideline on extensions of the mozilla brand logo placement yet but there was a clip of mozilla festival brand previewed on the from the [unveiling video](https://www.youtube.com/watch?v=MuLWXHgyEVw&feature=youtu.be) but in general the colour used for “mozilla” will also be the highlight colour for following highlight box.

I'll be referencing this clip from the video:
![mozilla-festival_example-animation](https://cloud.githubusercontent.com/assets/2492510/22970249/4d3d495c-f326-11e6-9149-92133fe4e2ef.gif)

From this example, I did some iterations on the lockup:
![mozilla_festival-wordmark-interim_iterations-03](https://cloud.githubusercontent.com/assets/2492510/22970300/7bc38ee4-f326-11e6-85b1-8efac1af4f57.png)

This lockup is the most similar to the previous and here is an example of colours from the one web palette last year to match the feel of the site and to provide enough contrast:
<img width="689" alt="screen shot 2017-02-15 at 2 30 29 am" src="https://cloud.githubusercontent.com/assets/2492510/22970412/e70d3858-f326-11e6-8141-e33164da8bde.png">

If we want to align to the new brand colours we can choose one from the new mozilla palette (yellow or neon blue would work with the site's existing palette): 
<img width="763" alt="screen shot 2017-02-15 at 2 37 37 am" src="https://cloud.githubusercontent.com/assets/2492510/22970693/d4e26d78-f327-11e6-8e64-ea6252edbb4e.png">

Note: In future updates, "festival" should be set using Zilla typeface when it is released and available.

**Comment by edrushka** [comment]
Nice! I like the stacked versions, either with the cog to left, as in the current lockup, or to the right with partial highlight, as in your last iterations. 

I'm open to both yellow and neon blue.

**Comment by hannahkane** [comment]
Really nice, @sabrinang.

@xmatthewx - do you want to offer final approval?

**Comment by xmatthewx** [comment]
Stacked, without the gear icon looks great. Yellow looks good, but could changed for different applications. Done!

In the future, we could explore gear as overlay like clip in video, but let's definitely not play with that now.

**Comment by sabrinang** [comment]
Here is the stacked wordmark without the logo exported in:
1 - black/white
2 - black/(new mozilla brand) yellow

<img width="1073" alt="screen shot 2017-02-15 at 11 43 53 am" src="https://cloud.githubusercontent.com/assets/2492510/22992291/19e70572-f374-11e6-8ca6-001f7ec360b5.png">


Exported in .svg and .png on gdrive: https://drive.google.com/open?id=0B4Q8pzCpDS_eb1BXUnpWLXZ2RVU 

The .ai file of the explorations can be found there too for future reference or updates.

**Comment by sabrinang** [comment]
![mozilla-festival_wordmark-interim_video](https://cloud.githubusercontent.com/assets/2492510/22999039/661ff434-f38e-11e6-8f0c-c09846bf377e.png)
@edrushka is there a preference for wordmark for video context? I was thinking that the horizontal wordmark (2nd right) would look the most balanced

**Comment by xmatthewx** [comment]
The black box really disappears. Would be good to share with Yuliya. Guidelines say "The logo highlight is always black, except for very rare cases when a white one-color logo can be used." I'm curious if that means that festival should also be white. 

 - I suggest we proceed without the gear paired with the logo. We can examine that later after we get through network site stuff. 
 - I think the horizontal lockup works better in this setting. stacked & left aligned feels odd when it is centered on the screen.

**Comment by sabrinang** [comment]
horizontal lockup is also exported in the folder: https://drive.google.com/open?id=0B4Q8pzCpDS_eb1BXUnpWLXZ2RVU
