### ISSUE TITLE
Remove Tabzilla

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#501]
@xmatthewx am I correct in assuming we no longer use Tabzilla? Is there a replacement? If we remove from the MozFest site, there is nothing that links back to mozilla.org

**Comment by xmatthewx** [comment]
We can drop the tab. We can look at adding the footer used across most of our sites for links back to Mozilla. It should be easy to drop in.

**Comment by edrushka** [comment]
@xmatthewx in our meeting today we discussed keeping the footer as-is for now and simply adding a mozilla.org link to the very bottom set of links (About / Festival Team / Participation Guidelines / Terms / Privacy ) as a way for people to get back to the mothership, since we're taking out Tabzilla.

There will be other MozFest site updates throughout the year (when we open the call for proposals in June and when we update the visual design for 2017 later in the summer). We can harmonize the footer on one of those occasions.

Are you ok with that? 

cc @hannahkane

**Comment by sabrinang** [comment]
Example of tabzilla-free header with mozilla wordmark link in footer incorporating existing links to look more like the format we have on other sites:
<img width="1039" alt="remove-tabzilla_add-footer" src="https://cloud.githubusercontent.com/assets/2492510/22971184/c15ba97a-f329-11e6-9ffe-7c43eab069c8.png">
We can probably make another exception here and do without the small icons if you want so we don't need to make new ones for *festival team* and *participation guidelines*.

**Comment by edrushka** [comment]
Fine with me to drop the small icons. The highlighter on the new Moz logo already makes that section look quite busy.

**Comment by hannahkane** [comment]
Nice synthesis of footer styles!

@sabrinang - can you do a version without the small icons, and then create an implementation ticket, please?
