### ISSUE TITLE
Implement news section

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozillafestival.org#505]
This is part of #503, but pulling this into a separate ticket so we can discuss implementation, including questions about how we'll curate content.

- Final mockup is here: https://github.com/mozilla/mozillafestival.org/issues/502#issuecomment-280093698
- It uses all existing colours and typography of the site, the only additional asset is using Medium's logo icon above the titles which can be downloaded here: https://github.com/Medium/medium-logos/archive/master.zip

In terms of pulling in content, we could do this dynamically, or perhaps, since @edrushka says the content isn't likely to change very often, we could do this in a simpler, static way. 

@gvn says it will not be possible to take the comparable section from the MLN site, so we'll have to build it here.

@edrushka - maybe to get us going, can you tell us what the content would be to start?

**Comment by edrushka** [comment]
**Left column**
[Surveillance and Race Online](https://medium.com/mozilla-festival/surveillance-and-race-online-c03dda350fb9#.inkvhivm2)

**Right column**
1) [Journalism at MozFest 2016: Great Stories, Strong Communities, New Tools](https://medium.com/mozilla-festival/journalism-at-mozfest-2016-great-stories-strong-communities-new-tools-dd99e9829167#.g3mk196yp)
2) [Wie steht es um die Gesundheit des Internets? Auf Spurensuche beim Mozilla-Festival](http://t3n.de/news/mozilla-festival-internet-gesundheit-761360/3/)
3) [Learning In The Youth Zone](https://medium.com/mozilla-festival/learning-in-the-youth-zone-5d649fdfceea#.5twnwprz2)

cc @Saallen

**Comment by Saallen** [comment]
Do we want the Internet health report anywhere here? As once these changes go live it will probably be the greatest moment for hits and length of time on the page so would be good to capture this curiosity and encourage reading of the report. What do others think?

**Comment by edrushka** [comment]
Good call. I've replaced the third one with that.

**Comment by alanmoo** [comment]
Since this is a mix of stuff, pulling from multiple sources, I'm just going to make this static for now.

**Comment by edrushka** [comment]
Perfect. We don't envision updating this super frequently.

**Comment by alanmoo** [comment]
For the left column we're linking to a Medium article which simply has a video and a description below it? I'm not going to argue against it I just want to point it out and make sure that's desired.

**Comment by edrushka** [comment]
@alanmoo correct. Just like in the mockup here https://github.com/mozilla/mozillafestival.org/issues/502#issuecomment-280093698
