### ISSUE TITLE
Select new photo for landing page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#508]
@Saallen Here are some suggestions to replace the main banner image on the landing page (Reagan speaking)

~https://www.flickr.com/photos/mozfest/30575310851/in/album-72157675892449415/~
~https://www.flickr.com/photos/mozfest/30032747144/in/album-72157675892449415/~
https://www.flickr.com/photos/mozfest/30556946742/in/album-72157675892449415/ - edit out alcohol
https://www.flickr.com/photos/mozfest/30004702073/in/album-72157672259755823/ - ok but quite similar to last year
https://www.flickr.com/photos/mozfest/30580887676/in/album-72157674377310602/ - really love
https://www.flickr.com/photos/mozfest/30622955755/in/album-72157674377310602/ - like content, needs a colour wash
https://www.flickr.com/photos/mozfest/30535185001/in/album-72157674377310602/ - love but not homepage. Use elsewhere in a later site update.
https://www.flickr.com/photos/mozfest/30598758376/in/album-72157674377310602/ - like but no kids on homepage

cc @sabrinang if you want to rule any of these out immediately, feel free to delete or strikethrough.

**Comment by Saallen** [comment]
Hi @edrushka these links are not working for me....
Can you screen share later in our 1:1?

**Comment by sabrinang** [comment]
Note: For the 4th photo, it has the 2016 branding pretty large which may clash as a main banner if it is next to new branding stuff (but can be photoshopped out if you like the photo itself)

**Comment by edrushka** [comment]
ooohhh good catch! :eyes: Thanks!

**Comment by edrushka** [comment]
@Saallen can you try these links again? They should work. If not, can you book some time on the cal for me to screenshare?

**Comment by edrushka** [comment]
@sabrinang could you kindly mock up these 2 photos to see which looks best for the landing page? If we could use a different colour other than purple for the colour wash, that would be ideal since we want people to realize we've updated the site. Thank you! 🌷 

https://www.flickr.com/photos/mozfest/30580887676/in/album-72157674377310602/ 
https://www.flickr.com/photos/mozfest/30622955755/in/album-72157674377310602/

**Comment by sabrinang** [comment]
![mozilla-festival_update-0217-01](https://cloud.githubusercontent.com/assets/2492510/23323002/680b8704-fa9b-11e6-93e1-1b8f9a286bb4.jpg)
![mozilla-festival_update-0217-05](https://cloud.githubusercontent.com/assets/2492510/23322840/abc190c0-fa9a-11e6-8567-1ff364d1dd77.jpg)

**Comment by edrushka** [comment]
Thank you @sabrinang!!

We both liked the first one better, even before you mocked it up, and I think it's clearly the winner.

**Comment by sabrinang** [comment]
hero image exported here: https://drive.google.com/open?id=0B4Q8pzCpDS_eRjBUSXhSalp0YXM
