### ISSUE TITLE
Bug- Tab says MozFest 2016

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#524]
Eagle eyed @chadsansing spotted the browser tab says MozFest 2016 even on our fancy new 2017 site

@alanmoo do you have a fix for this? 

cc @edrushka

**Comment by alanmoo** [comment]
I just merged a PR that Mavis opened last night to fix this. Should be live on staging. I'll push to master when I properly start my day

**Comment by alanmoo** [comment]
Closed by #523. It might be a little while before you see it kick in, as I believe this site is behind a CDN.

**Comment by Saallen** [comment]
:champagne:
