### ISSUE TITLE
Add "cookies" link to footer

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#525]
It is an EU legal requirement that the site have a "Cookies" link in the bottom footer. See https://www.mozilla.org/en-US/ as an example.

It should link to the 'cookie' section of the privacy page:  https://www.mozilla.org/en-US/privacy/websites/#cookies

cc @hannahkane for assigning

**Comment by alanmoo** [comment]
A few things:

* That page is already linked to via the `Privacy` link (the link you use just scrolls down the very short page.)
* The cookie section of the privacy page you link to is about Firefox, not the specific site.
* Are we actually storing anything on the user's computer for this site that would require this disclaimer? For the schedule app I can understand it, but I'm not positive about this site.

**Comment by alanmoo** [comment]
That being said, I've opened #527, I'm just not convinced it's the right solution to an issue we may or may not have.

**Comment by edrushka** [comment]
cc @abigailphillips

**Comment by abigailphillips** [comment]
"That page is already linked to via the Privacy link (the link you use just scrolls down the very short page.)"

The separate link for 'Cookies' to call out this info is an internal compromise -- the EU E-Privacy Directive actually requires more, but for various reasons the decision was made to not present a more intrusive warning or request.

"The cookie section of the privacy page you link to is about Firefox, not the specific site."

I agree this should link to an earlier para; I'll look into getting the anchor placement fixed.

"Are we actually storing anything on the user's computer for this site that would require this disclaimer? For the schedule app I can understand it, but I'm not positive about this site."

Is your question: Do we have to include this disclaimer if we don't use cookies? -- i.e., are you storing something on the user's computer that you believe does not require this disclaimer? Or are you saying that you don't store anything on the user's computer at all?

**Comment by alanmoo** [comment]
For the last item, good clarification: I don't believe we store anything on the user's computer at all for this site, so do we still need the disclaimer? 
(@mmmavis can you confirm that we don't store anything? A quick search of the repo shows no results for `localstorage` or `cookies`.)

If we use [the schedule app](https://app.mozillafestival.org/) again this year (which we currently link to from the festival site, although it's a different domain), that would definitely need the disclaimer.

**Comment by alanmoo** [comment]
I just looked at the debugger, it looks like Google Analytics and Tito drop a cookie, so I guess that triggers the need for this?

**Comment by mmmavis** [comment]
@alanmoo we can remove Tito related code since we are not using it now (and may or may not use it again for this year's MozFest. Decision depends on what comes out from the MozFest tooling research) For Google Analytics I can't really tell if we are making use of it - I can't access it on GA dashboard.

**Comment by abigailphillips** [comment]
If you know for certain there will not be cookies at any point, let me know. Otherwise please include the link. Thanks.
