### ISSUE TITLE
Request via ti.to page and 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#530]
Pinging @alanmoo  in the hope he can help but know @mmmavis set up the tito page late in 2016

Received feedback on twitter today on the new site:
is it possible to carry the header from the ti.to homepage so you can navigate to other pages in the site?

[Ti.to home page ](https://ti.to/Mozilla/mozfest-2017)

CC @edrushka

**Comment by alanmoo** [comment]
It's on a different domain, so not likely. We could change whatever link is being used to get there to open the site in a new tab. What link was used?

**Comment by mmmavis** [comment]
> It's on a different domain, so not likely.

Yup yup.

Both the ti.to page and http://mozillafestival.org/tickets are up. I think we are good to close this ticket! 🍻
