### ISSUE TITLE
Evaluate Sched

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#534]
@ScottDowne @cadecairos I started to evaluate existing software for MozFest proposal curation / schedule app again. I can't recall what the reason was that we couldn't use Sched 2 years ago. Was it because it didn't pass the security review? I wonder if things have been improved on that front... @cadecairos if we'd like to ask for a security review on Sched again how should I start?

---

https://sched.com

Features: https://sched.com/features
Step-by-step guide: https://sched.com/support/section/setup/

## Admin Dashboard

<img width="916" alt="screen shot 2017-03-10 at 11 27 44 am" src="https://cloud.githubusercontent.com/assets/2896608/23809998/a6bac62e-0584-11e7-9e70-920d0b9dddf7.png">

## Schedule builder

<img width="1411" alt="screen shot 2017-03-10 at 11 54 51 am" src="https://cloud.githubusercontent.com/assets/2896608/23810917/79ef8770-0588-11e7-8b3f-3514a4910a9a.png">

![page-shot-2017-3-10 sched admin_ edit session](https://cloud.githubusercontent.com/assets/2896608/23811267/1f50d844-058a-11e7-83f7-1b0ba6cf160c.png)

**Comment by ScottDowne** [comment]
It was because there wasn't sufficient time to get it through sec review.
We never did see if it would fail or pass. Worth looking into.

**Comment by mmmavis** [comment]
@ScottDowne good to know! I'll give Sched a try myself first then.

**Comment by mmmavis** [comment]
Closing as Sched isn't one of our shortlisted candidates.
