### ISSUE TITLE
DUE JUNE 1: Social Media Graphic: Call for Proposal 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#541]
Create a simple graphic that will accompany social media posts for proposals.

Possible Copy: "Call for Proposal 2017" (TBD)
Platforms: Twitter and Facebook (any others?)
Date: Sent out on June 1

**Comment by sabrinang** [comment]
Idea for twitter graphic that includes "Call for Proposals" some of the new brand colours and pixelated stuff with mozfest cubes:
![twitter 1760x800 copy](https://cloud.githubusercontent.com/assets/2492510/25925172/dbe25be0-359b-11e7-9f10-44f65af7c07a.png)

**Comment by hannahkane** [comment]
cc @edrushka

**Comment by edrushka** [comment]
Very pretty!! For text, perhaps:
- Submit a MozFest session   OR  Submit a session for MozFest
- MozFest Call for Proposals is open  OR  Now open: MozFest Call for Proposals

I think we need the word MozFest prominently featured - the updated wordmark will be new to people (plus not everyone knows MozFest = Mozilla Festival).

**Comment by edrushka** [comment]
cc @Saallen

**Comment by Saallen** [comment]
Ooh looks great @sabrinang 
Another place for the banner is  on our emails to promote the open call via our ti.to - we have the ability to attach a banner.

**Comment by sabrinang** [comment]
Here are some versions with new copy and alternative colours:
![twitter 1760x800 purple](https://cloud.githubusercontent.com/assets/2492510/26419055/4580339c-4073-11e7-93d7-b646ee113673.jpg)
![twitter 1760x800 yellow](https://cloud.githubusercontent.com/assets/2492510/26419157/97d8a7dc-4073-11e7-9f92-e3445190026f.jpg)

**Comment by sabrinang** [comment]
![preview](https://cloud.githubusercontent.com/assets/2492510/26475223/274e8ed4-416b-11e7-8e86-7c4628b40cb3.jpg)
- 2 dimensions: 1760x800px and 800x800px
- various colours from [mozilla palette](https://mozilla.ninja/color-palette) with overlay effects
- using 4 various copy options: 'Submit a MozFest session', 'Submit a session for MozFest', 'MozFest Call for Proposals is open' & 'Now open: MozFest Call for Proposals'

Exported social shares on gdrive here: https://drive.google.com/open?id=0B4Q8pzCpDS_eLURVNVEtNVhGQ3M

If the emails banner have a specific dimension I can make those as well if 1760x800px doesn't work.

Design review? @edrushka @Saallen

**Comment by edrushka** [comment]
R+ these are great! 
@stephaniemcv does 1760x800px work for emails? I think ti.to is fairly flexible, but if we send any emails via another platform, let me know if they should be a specific size.

**Comment by stephaniemcv** [comment]
Oooh, pretty! Our templates in Salesforce Marketing Cloud have width maximum around 640px for rectangle and 250px width for square images. Higher than that and you run the risk of blowing out the template and getting weird gaps in some email clients. 

These also look like they will scale down well on mobile and the text will still be readable!

**Comment by sabrinang** [comment]
social graphics complete + emails have been sent out ✉️✨
