### ISSUE TITLE
Master List of May 2017 Updates

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#543]
## Top Nav Bar  
Ticket #546
- [x] add Propose (links to google form)
- [x] reorder items
- [x] remove Schedule 
 
## Landing Page
Ticket #548
- [x] Update main banner CTA
- [x] Highlight video
- [x] Refresh news section with new stories

## What to Expect Page
Ticket #549
- [x] Slight copy tweak of 'What is MozFest like' section
- [x] Add a11y section

## Spaces & Sessions Page
Ticket #550
- [x] This page should be called Spaces
- [x] Edit copy
- [x] Change 'View the MozFest 2016 schedule' to 'Submit a session'
- [x] Update space descriptions and space wranglers

## Projects Page
Ticket #551
- [x] Tweak copy

## Tweet MozFest
Ticket #552
- [x] Update autofilled tweet text 

## About
Ticket #553
- [x] Update Mark's section
- [x] Update numbers
- [x] Fix minor copy error

## Festival Team
Ticket #554
- [x] Hide wranglers & partners tabs

## Call for Proposals form
Ticket #556
- [x] Create main en-GB version
- [x] Link to additional localizd versions Ticket #557 (TBD)

## Guidelines 
Ticket #581 
- [x] Update 2 links

**Comment by Saallen** [comment]
Right before we publish we need legal to review and update privacy and terms @edrushka
