### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#548]
https://mozillafestival.org/

- [x] Update main banner CTA
Change 'watch video' to 'propose a session'

- [x] Highlight video
Create new section for this, under the hero banner and above the speakers section. Video should be visible with a play button.   Design ticket: #559

- [x] Refresh news section with new stories

- [x] Bottom footer, replace 'About' with 'Blog'

**Comment by edrushka** [comment]
News stories:

**Left column:**
[Bringing Back the Decentralized Web](https://medium.com/mozilla-festival/bringing-back-the-decentralized-web-5598408037c7) 

**Right column:**
[Internet health as a social issue](http://www.cbc.ca/radio/spark/internet-health-as-a-social-issue-1.4053202)
[Mozilla planta cara a los ‘trolls’](http://tecnologia.elpais.com/tecnologia/2016/10/31/actualidad/1477905484_625075.html)
[Peering Behind the MozEx Installation](https://medium.com/mozilla-festival/mozfest-2016-behind-the-mozex-installation-146a2b45f3f0)


**Alternates**
[How Do We Connect First-Time Internet Users to a Healthy Web?](https://blog.mozilla.org/blog/2017/03/20/connect-first-time-internet-users-healthy-web/)

cc @Saallen let me know if you want something else included instead

**Comment by Saallen** [comment]
How about putting the IH report there as there will be high traffic when the call just opens so would be good to share with everyone?
S

**Comment by edrushka** [comment]
We are currently featuring https://blog.mozilla.org/blog/2017/01/19/digital-citizens-lets-talk-about-internet-health/ I've asked Kev if there's something more recent, but there might not be. If not, do you want to keep that one persistent?

**Comment by Saallen** [comment]
Is there no direct way link to the report?
If not this blog is perfect
Thanks

**Comment by edrushka** [comment]
We can certainly link directly to the report: https://internethealthreport.org/v01/
I'll use this instead of "Peering Behind the MozEx Installation".

This ticket is no longer blocked. Final stories are in the 2nd comment.

**Comment by mmmavis** [comment]
Done! http://temp-mozfest-cfp-2017.herokuapp.com/
