### ISSUE TITLE
What to Expect 

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#549]
https://mozillafestival.org/expect

- [x] Slight copy tweak of 'What is MozFest like' section. Copy [here](https://docs.google.com/document/d/1tM5i3QnPwtxCmblC5hfKZq7vYG3xQwpW_AYDWiKFshM/edit#heading=h.aaaz5dixnj00)

- [x] Add Accessibility section Copy [here](https://docs.google.com/document/d/1tM5i3QnPwtxCmblC5hfKZq7vYG3xQwpW_AYDWiKFshM/edit#heading=h.aaaz5dixnj00)
- put this underneath Participation Guidelines

**Comment by edrushka** [comment]
@Saallen three things on this ticket:
1) suggest changing "Demo party" to "closing celebration" on weekend schedule
2) review What to Expect edits [here](https://docs.google.com/document/d/1tM5i3QnPwtxCmblC5hfKZq7vYG3xQwpW_AYDWiKFshM/edit#)
3) review new a11y section [also here](https://docs.google.com/document/d/1tM5i3QnPwtxCmblC5hfKZq7vYG3xQwpW_AYDWiKFshM/edit#)

**Comment by Saallen** [comment]
@edrushka I agree demo party is over so happy with this text change- however there is a need for more than " celebratory drinks". no need to rush this piece here until festival updates in September

**Comment by edrushka** [comment]
No longer blocked. I've edited first comment with copy links.

**Comment by mmmavis** [comment]
@edrushka did you mean

![screen shot 2017-05-30 at 14 31 10-fullpage](https://cloud.githubusercontent.com/assets/2896608/26605904/b384e1c8-4544-11e7-81f4-5f859b272141.png)

**Comment by edrushka** [comment]
Yah, where it says Demo Party on the Sunday schedule, please change to Closing Celebration.

**Comment by edrushka** [comment]
Oh - did you mean the A11Y section? That looks good too! 👍 😀

**Comment by mmmavis** [comment]
Done! http://temp-mozfest-cfp-2017.herokuapp.com/expect
