### ISSUE TITLE
Spaces and Sessions page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#550]
- [x] Title on hero banner should just be Spaces

- [x] Edit introductory paragraph. Change to:
Spaces are physical and thematic learning hubs based around a broad topic, like web literacy or digital inclusion. A Space is made up of sessions, which are hands-on, educational gatherings based around a specific topic, like “Using Crafts to Teach Localization Processes.” Sessions generally run 30-90 minutes.

- [x] Change 'View the MozFest 2016 schedule' to 'Submit a session'

- [x] Update space descriptions. Copy is being finalized in #560. Mavis, make sure to confirm we're done editing before making these updates.

- [x] Change 'See the sessions in this space' links under each description to 'Propose a session in this space' (links to form)

- [x] Update Wrangler names (no links, just plain text)

**Comment by edrushka** [comment]
Wrangler Teams:

**Online Privacy & Security**

Stéphanie Ouillon
Brett Gaylor
Mavis Ou
Phillipa Bailey
David Ross
Jonathan Kingston

**Open Innovation**

Aurelia Moser
Christos Bacharakis
Raegan MacDonald
Phillip Smith


**Decentralization**

Vigneshwer ‘Viki’ Dhinakaran
Ian Forrester
Tim Cowlishaw 
Jon Tutcher

**Web Literacy**

Luke Pacholski
Fredrick Sigalla
Phillipa Bailey
Julie Neville
Mariana Delgado
Edoardo Viola

**Digital Inclusion**

Kenyatta Forbes
Hannah Kane
Michael Saunby
Heather Bailey
Martha Segwick

**Youth Zone**

Dorine Flies
Shwetal Shah
Andrew Mulholland
Connor Ballard-Pateman

**Comment by mmmavis** [comment]
Done! http://temp-mozfest-cfp-2017.herokuapp.com/spaces
