### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#551]
@xmatthewx we're updating the MozFest website for the opening of the Call for Proposals on June 1. Are you still happy with what's featured here? https://mozillafestival.org/projects 

I can't remember what algorithm generates the featured projects, but it'd be good if these updated fairly regularly as there will be more traffic to the site from June - Nov.

**Comment by xmatthewx** [comment]
Those were added directly to the site. We didn't yet have the real API setup. When we dig in this summer, we can automate to pull things that mention mozfest or are tagged mozfest.

For now, a simple addition would be to add a link at the top of page. Something like:  "Browse projects below and more on [Pulse](https://www.mozillapulse.org)."

What do you think?

**Comment by xmatthewx** [comment]
We should meet at some point in the next few weeks to talk about how Mozfest shows up on network site and how the site itself should evolve this summer. Make some longterm plans.

**Comment by edrushka** [comment]
That works. 

Mavis, please change the text under the hero banner to "MozFest attracts and generates dozens of projects that thrive long after the festival weekend. See the examples below and find a catalyst for collaboration with our vibrant network. [Browse more projects on Pulse.](https://www.mozillapulse.org/featured)

**Comment by mmmavis** [comment]
Done! http://temp-mozfest-cfp-2017.herokuapp.com/projects
