### ISSUE TITLE
Localize Call for Proposals form

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#557]
- Localize en-GB form into other languages:

- [x] German
- [x] French
- [x] Spanish

**Comment by edrushka** [comment]
This work is underway! Re-assigning to @TheoChevalier

**Comment by TheoChevalier** [comment]
L10N tracking dashboard: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_form.lang

Translations: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_form.lang&action=translate&show

German form is ready!
Spanish is done but still under review (early next week)
French should be done early next week too

**Comment by TheoChevalier** [comment]
French is now ready too! Waiting for last strings + review for Spanish.

**Comment by mmmavis** [comment]
Notes for Mavis:

- Space names should be localized **on the form**
- Space names **on the spreadsheet** should be in English
- Space names **on GitHub** should be in English

**Comment by TheoChevalier** [comment]
@mmmavis Got confirmation this morning that current Spanish translations are final: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_form.lang&action=translate&show
Note that some strings from yesterday are missing, but that should not block us

**Comment by TheoChevalier** [comment]
French and German error messages + success page are available for you

**Comment by TheoChevalier** [comment]
And Spanish is fully ready too, now

**Comment by mmmavis** [comment]
Woooohoooo
