### ISSUE TITLE
Design section to highlight video on landing page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#559]
See ticket #548 for context

Design a new section, below the hero banner, to highlight the video. It can look similar to the video treatment on https://mozillafestival.org/expect but with a different background colour than the D&Ds to differentiate it.

**Comment by sabrinang** [comment]
Here are some ideas for the video section on the landing page:
<img width="1361" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26080806/023bcf44-397d-11e7-9921-62a7df1b74f1.png">
1 - moving video below and would be more informative to pair this with a CTA (perhaps what to expect since it relates to showing a video of last year).

2 - changing the hierarchy of the subheading typography on the hero to make way for a featured video which moves it higher on the view port with no specific text with it.

3 - using zilla on heading and shortened hero section so video section beneath is higher. 

*copy on design mockups are just placeholder

**Comment by edrushka** [comment]
Ohhh nice options!! I think I prefer Option 1, since I like the opportunity to highlight a line or two about 'What is MozFest'? I also like Option 2 as it's nice and clean (although I worry that the video competes with the CTA button). I like that Option 3 is shorter, but am not sure how I feel about the white highlighting on the title text.

@Saallen @hannahkane what are your thoughts?

**Comment by hannahkane** [comment]
These are great. I actually prefer option 3 because I like that it's tied to the CTA, and I like the highlighted text and the shorter hero.

My second choice would be option 1, again, for the connection to the CTA.

**Comment by Saallen** [comment]
I am 😍 option 3.
Love the welcome to MozFest! Its fresh, its announces the festival and its different.
Love the video placement- and "what is MozFest like"- really shares what I worried the audience finds hard to understand.....this is what to expect.


What do ppl feel about separating the speakers more from the top section? As it does like feel they could be linked to the video.....what is mozfest like and here are the speakers... but if no one else gets this then happy as is.

**Comment by sabrinang** [comment]
@Saallen I think you bring up a good point about the speakers section but I think a concern I have is that it seems like those speakers are for 2017 (but they are actually from 2016) so it could feel more separate with some copy/context that it was from last year.

@erikad Can you also write some final copy for the "What is MozFest like" section

**Comment by edrushka** [comment]
@Saallen pls review blurb copy [here](https://docs.google.com/document/d/1tM5i3QnPwtxCmblC5hfKZq7vYG3xQwpW_AYDWiKFshM/edit#heading=h.aaaz5dixnj00)

**Comment by Saallen** [comment]
Looks good @edrushka  I added some comments

**Comment by edrushka** [comment]
This is no longer blocked. Blurb copy is here.

**Comment by sabrinang** [comment]
![video section revised](https://cloud.githubusercontent.com/assets/2492510/26419708/73144ee0-4075-11e7-8c37-35db77599c87.jpg)
- heading uses https://github.com/mozilla/zilla-slab
- copy blurb used
- a divider beneath this video section is included to separate the speakers more from the top section

**Comment by Saallen** [comment]
😍 
Looks great-  Love the separation of video content . As long as Mozfest in the banner will become MozFest I am very happy

**Comment by sabrinang** [comment]
Thanks @Saallen I updated that mockup to "MozFest".

There are no new assets for this section so @edrushka if you give the R+ for the design I believe it is ready for build.

**Comment by edrushka** [comment]
Design looks good. R+ 
Tiny copy tweaks for implementation:
The world's leading festival for the open Internet movement.  (capitalize Internet)
October 27-29, 2017 Ravensbourne College, London (no period after London)

**Comment by sabrinang** [comment]
Thanks team! Closing and filed implementation ticket here https://github.com/mozilla/mozillafestival.org/issues/578
