### ISSUE TITLE
Copy edit space descriptions for consistency

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#560]
All the spaces have submitted their descriptions [here](https://docs.google.com/document/d/1CUFkpdNuiUqgrdfqosz83GL0pub0VfEdKjc3qbgWWbg/edit#heading=h.ao7i8wb2xwva). Need to copy edit as lightly as possible so they read with a consistent voice. These edited descriptions will go on the [Spaces page](https://mozillafestival.org/spaces-and-sessions), and on the call for proposals form.

@KevZawacki do you have time to take a first pass?

**Comment by KevZawacki** [comment]
@edrushka Sure -- what's the deadline?

**Comment by edrushka** [comment]
End of day Thursday May 18, ideally, so we can run any changes by the teams before we publish. Let me know if that's not workable, or if you'd like me to take the first pass.

**Comment by KevZawacki** [comment]
@edrushka no prob!

**Comment by KevZawacki** [comment]
@edrushka OK, edits in! Once you've accepted / rejected, can you let me know? I'd like to do a final copyedit to ensure nothing became garbled in the track changes process.

**Comment by edrushka** [comment]
Marking this as closed as I believe all the changes are in. THANK YOU KEVIN!!!! 🌻
