### ISSUE TITLE
Decide what gets ported to Github

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#564]
Decide what information gets ported from the Call for Proposals google form to the Github ticket for each session.

cc @Saallen

**Comment by hannahkane** [comment]
Dependent on finalizing the form. :)

**Comment by mmmavis** [comment]
Form is finalized. Let's figure out what to include on Github. We should also create a new repo for 2017 proposals. Last year we had https://github.com/MozillaFoundation/mozfest-program-2016.

**Comment by mmmavis** [comment]
I like @Saallen 's idea of using GitHub's milestone for a proposal's primary Space choice. I'm thinking

- `milestone`: proposal's primary space. There will be 6 milestones:
  - Web Literacy
  - Decentralisation
  - Open Innovation
  - Digital Inclusion
  - Privacy and Security
  - Youth Zone

- labels:
  - 6 Space labels, used as a proposal's secondary Space choice. Label format: `[Space] Name of Space`
  - `Stipend requested`
  

Anything else? @Saallen @edrushka @hannahkane

**Comment by edrushka** [comment]
Also, a label for if they will facilitate in another language, please! I did these manually last year, because we used an open text field on the CFP form. This year we have buttons on the form, so automating French, Spanish and German labels should be easy. We've created a 4th "open text" option to choose, but maybe we should remove that.

**Comment by edrushka** [comment]
For Github porting, I propose:

**1) Github ticket title** 

- session name

**2) First comment** in the ticket contains:

- ID (this autogenerates)
- Submitter's Name  
- Submitter's Affiliated Organisation  
- Submitter's Twitter 
- Submitter's Github
- Additional facilitators
- What will happen in your session? 
- What is the goal or outcome of your session? 
- After the festival, how will you and your participants take the learning and activities forward?
- How will you deal with varying numbers of participants in your session? 
- If your session requires additional materials or electronic equipment, please outline your needs.

**3) Labels:**
- Secondary space (if applicable)
- Additional language (if applicable)
- Stipend requested (if applicable)
- Time needed (<60; 60; 90; all weekend)

**4) Milestone:**
- First choice space

**Comment by Saallen** [comment]
Looking good ladies! 

**Labels**
* Time needed (<60; 60; 90; all weekend)
I am a little worried about this label as this is the most prone to being inaccurate information at time of curation.
* Experiences
We need experiences here as labels too- the artist in residence experience will be manually adding sessions as will advocacy (name tbc)  Example of label-  [Experience] Artist in residency
* Format labels
We will need labels for formats but not required for June 1st


**first comment**
This is a great example from last year - [Issue 860 ](https://github.com/MozillaFoundation/mozfest-program-2016/issues/860)
* We are proposing to add 5 blocks of text to the first issue- when in 2016 we added only 4.
My worry is massive long dense first comments- and this year we have changed our questions slightly so worry about responses being HUGE

**Comment by edrushka** [comment]
My thinking is to include the info necessary to accept or reject a ticket. We don't want wranglers having to refer to the master spreadsheet to curate. So we could potentially remove these 2 questions, since they are more prompts for the session hosts:
- After the festival, how will you and your participants take the learning and activities forward?
- How will you deal with varying numbers of participants in your session?
Similarly, we can port "Time needed (<60; 60; 90; all weekend)" to the first comment, rather than making it a label. This way, wranglers can use to label to note how much time will _actually_ be given.

And yes, +1 to creating manual labels for for formats and experiences. I'll make a new comment with all these changes.

**Comment by edrushka** [comment]
**1) Github ticket title** 

- session name

**2) First comment** in the ticket contains:

- ID (this autogenerates)
- Submitter's Name  
- Submitter's Affiliated Organisation  
- Submitter's Twitter 
- Submitter's Github
- Additional facilitators
- What will happen in your session? 
- What is the goal or outcome of your session? 
- If your session requires additional materials or electronic equipment, please outline your needs.
- Time needed 

**3) Labels:**

- Secondary space (if applicable)
- Additional language (if applicable)
- Stipend requested (if applicable)

**4) Milestone:**

- First choice space

**5) Additional labels for manual curation:**

- note: please remove all the autogenerated Github labels like "bug", "duplicate" etc.
- Experience: Artist in residency
- Theme: Advocacy
- Theme: Youth
- Format: Classroom
- Format: Shed
- Format: Gallery

**Comment by Saallen** [comment]
Looks good-
Thinking about privacy should we removed the twitter handle? or on the Call for Proposals page highlight this goes on github as public data? Twitter is pretty personal and in the past we have viewed it as personal as email addresses.

**Comment by mmmavis** [comment]
@Saallen these are [the sample Github tickets](https://github.com/mmmavis/test-mozfest-2017-proposals), you can test the form http://temp-mozfest-cfp-2017.herokuapp.com/proposals and let me now if anything needs changes.

+1 on removing Twitter handle from GitHub tickets.

**Comment by mmmavis** [comment]
Done!
