### ISSUE TITLE
Upgrade webpack and tidy up npm scripts

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#566]
Build task takes way too long to finish! 😱 On average it takes 70secs for the `build` task to complete (the initial build AND all the rebuilds triggered by `watch` task)... This seems too long for a relatively small brochure site like this. @alanmoo have you experienced this when you worked on this site few months ago?

**Comment by mmmavis** [comment]
Um I think it's worth upgrading webpack to v2 and tidying up all the npm scripts a bit.

**Comment by alanmoo** [comment]
I haven't looked into webpack 2 but yeah there's probably opportunity to at least improve the dev build time via some tidying. Maybe no compression for dev, but make sure it's there for production?

**Comment by mmmavis** [comment]
@alanmoo oh yea, I cleaned things a bit and now build time (on development) is around 8 secs!
