### ISSUE TITLE
Create Call for Proposals Google Form

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#568]
This is the 🔑 key ticket 🔑 to unlock all the CFP work!

@Saallen please port the etherpad work into an actual Google Form. I can review it there if needed, and then we'll hand to Mavis.

**Comment by Saallen** [comment]
I got the key I got the secret.....


(Example)[https://docs.google.com/a/mozillafoundation.org/forms/d/10Pwt_tVkqvxqnz6KTV3Wf2HDz5WQCq78toQKB5E8pXM/edit} would love feedback on especially on the last section from @hannahkane @mavis to the flow and the questions

**Comment by edrushka** [comment]
HEre is it! https://docs.google.com/a/mozillafoundation.org/forms/d/10Pwt_tVkqvxqnz6KTV3Wf2HDz5WQCq78toQKB5E8pXM/edit?ts=59258a06

**Comment by hannahkane** [comment]
Form looks great! Some minor notes:
 - Don't forget to change the title (currently includes "[draft 1]")
 - Do we need to collect an email address or some other way to contact them?
 - Don't forget to link to the Spaces page!
 - Maybe put the "After the festival, how will you and your participants..." question immediately following the "What is the goal or outcome of your session?" They seem somewhat related in my mind.
- Consider small rewrite of "We offer these stipends to encourage diversity in facilitators." Perhaps "We offer these stipends to ensure that cost is not a barrier to participation" or something similar?
- Suggest this tiny rewrite: "Please note we may not be able to support all of your needs but will work with you to provide the best solution possible."

**Comment by edrushka** [comment]
Thank you! Kevin is going to do a quick review tomorrow and then I'll make all the changes.

**Comment by edrushka** [comment]
Kev's changes:

-- "This year we are accepting proposals in English, Spanish, French and German."

-- At MozFest, sessions are thematically organized into spaces. Please read the brief descriptions of each space here [link // needs hyperlink] before answering the following questions.

**Comment by edrushka** [comment]
@hannahkane I made your edits - thanks! And just to clarify, people don't submit via this form directly. Mavis will build a page #569 based off this form. Therefore, I kept "draft" in the title and added a line at the very top directing people to the website (last year, someone found our draft form online and tried to use it). This is also why the links are missing (but Mavis will add them in #569).

A further point of clarification, the localized forms *will* be on Google docs. We won't build pages for those.

**Comment by edrushka** [comment]
@Saallen Two things:

1) Why do we have first and last name separated? Is there any reason not to have one field for Name (this will make porting to the Github ticket more straightforward)
2) Propose adding this line to the top of the form, as a separate lin after "This year we are accepting proposals in English, Spanish, French and German.":

Accessibility: If you would like to submit a session and have difficulty using this text-based form, please email us to discuss other options.

**Comment by edrushka** [comment]
Marking this as closed since the form is now on staging: https://mavis-mozfest.herokuapp.com/proposals
