### ISSUE TITLE
Set up automated confirmation email

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#574]
Text written in #563 
Last year's set up ticket: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/47

**Comment by mmmavis** [comment]
DevOps ticket filed to verify our configs from last year are still valid: https://github.com/MozillaFoundation/mofo-devops/issues/501

**Comment by edrushka** [comment]
@mmmavis the text is ready [here](https://docs.google.com/document/d/1tM5i3QnPwtxCmblC5hfKZq7vYG3xQwpW_AYDWiKFshM/edit#heading=h.gubel5wujtd5). Removing the 'needs help' as this is now ready for implementation. ✋

**Comment by mmmavis** [comment]
@cadecairos can you point me to the repo where the email template is located so I can file a PR to update the content?

**Comment by cadecairos** [comment]
@mmmavis The template is kept here: https://github.com/mozilla/webmaker-mailroom/tree/master/templates

**Comment by mmmavis** [comment]
Thanks @cadecairos ! PR submitted: https://github.com/mozilla/webmaker-mailroom/pull/59 Hopefully this is a quick review for you.

Another question - if I wanna test this on MozFest staging, can I copy and use the same sawmill/hatchet creds that we have for MozFest production?

**Comment by cadecairos** [comment]
@mmmavis staging mozfest is hooked up to staging sawmill, so once we land the update to sawmill, it will work. remember that the sawmill event name is now "mozfest_session_proposal_2017"

**Comment by mmmavis** [comment]
@cadecairos awesome! Can you help land the updates to sawmill please?

**Comment by cadecairos** [comment]
yup, wating on a review: https://github.com/mozilla/sawmill/pull/80

**Comment by cadecairos** [comment]
@mmmavis It's on staging now, can you test and confirm it's working?

**Comment by mmmavis** [comment]
@cadecairos I get this `IncompleteSignature:` error. It says blah blah blah `not a valid key=value pair (missing equal-sign)`. You can check the error log at `2017-05-31T22:29:38.686695+00:00 app[web.1]` to see the detail. Is it something I can fix on my end/MozFest site?

**Comment by cadecairos** [comment]
@mmmavis I think that may have been caused by some leading whitespace on the env var, can you try again?

**Comment by mmmavis** [comment]
Duh whitespacessss! Yea I got the confirmation email! Yay! (It was in my spam box though)

<img width="950" alt="screen shot 2017-05-31 at 5 51 53 pm" src="https://cloud.githubusercontent.com/assets/2896608/26660073/596db3cc-462a-11e7-9fa4-e421b5785d6a.png">

**Comment by mmmavis** [comment]
Thanks @cadecairos !!! Confirmed this is working great!!! ✨  @Saallen and @edrushka both got their emails in the inbox (not spam!) I think it's probably I had done too much testing before so Google decided to mark that sender as spammer.
