### ISSUE TITLE
Build section to highlight video on landing page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#578]
### Mockup
![video section revised](https://cloud.githubusercontent.com/assets/2492510/26513652/7f8ac67e-4221-11e7-819b-f8fef356b3a0.jpg)
### Design Notes
- Using existing styles except the heading uses Zilla Slab Regular Highlight https://github.com/mozilla/zilla-slab
- A divider beneath this video section is included to separate the speakers from the top section

Design issue: https://github.com/mozilla/mozillafestival.org/issues/559
____

### Copy
**Welcome to MozFest**

The world's leading festival for the open Internet movement.
October 27-29, 2017 Ravensbourne College, London

[Propose a Session]
 
**What is MozFest like?**
MozFest is for advocates of a healthy Internet. Explore the intersection of the web with civil society, journalism, public policy, and art through interactive sessions.

[What to Expect]

**Comment by mmmavis** [comment]
Done! http://temp-mozfest-cfp-2017.herokuapp.com/
