### ISSUE TITLE
Localize Social Media Graphic: Call for Proposal

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#580]
For the social shares, we will be having them in other languages as well:
- [x] German
- [x] French
- [x] Spanish

These most likely will be posted after June 1 but we can get them out quickly after we get the translated copy.

### Copy to Translate
Submit a session for MozFest

### Reference
English design issue: https://github.com/mozilla/mozillafestival.org/issues/541

cc/ @edrushka @Saallen

**Comment by hannahkane** [comment]
Adding @TheoChevalier to coordinate translations

**Comment by edrushka** [comment]
This work is underway.

**Comment by TheoChevalier** [comment]
German and French are ready https://l10n.mozilla-community.org/langchecker/?website=6&file=social/2017/mozfest.lang&action=translate&show
(First two strings, the next ones are tweets)

French: 
`Proposez une session pour le MozFest`
`L’appel à propositions est ouvert pour le MozFest`

German:
`Schlagen Sie eine Sitzung für das MozFest vor`
`Ab sofort können Vorschläge zum MozFest abgegeben werden`

**Comment by Saallen** [comment]
🇩🇪 🇫🇷

**Comment by TheoChevalier** [comment]
Spanish is now ready too, we’re complete 🎉
Let me know if some strings are too long, we may be able to shorten them a little bit

**Comment by edrushka** [comment]
@TheoChevalier yay! Can you throw the ES string in this ticket?

@sabrinang can you pop these strings into the CFP graphics and let us know if they are too long?

**Comment by TheoChevalier** [comment]
Sure, here’s Spanish:
`Enviar una sesión para MozFest`
`Abierta la convocatoria de propuestas para el MozFest`

(Also available from the link above if needed)

**Comment by sabrinang** [comment]
Thanks @TheoChevalier for the translated strings! I have a question about a FR string, on https://l10n.mozilla-community.org/langchecker/?website=6&file=social/2017/mozfest.lang&action=translate&show there is one on that site that is different than the one you pasted in this ticket (see below). 

### Strings on this ticket:
German (de):
`Schlagen Sie eine Sitzung für das MozFest vor`
`Ab sofort können Vorschläge zum MozFest abgegeben werden`

Spanish (es):
`Enviar una sesión para MozFest`
`Abierta la convocatoria de propuestas para el MozFest`

French: 
`Proposez une session pour le MozFest`
**`L’appel à propositions est ouvert pour le MozFest`**

### Strings on this website:
<img width="1006" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26803398/e5f9052c-49f8-11e7-80af-05164e20de18.png">

I have used the one on the site so far for the designs (2 variations for each), can you confirm which FR string should be used or is more accurate?

<img width="935" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/26803378/d03f42b4-49f8-11e7-8980-cd0a3cbb4a13.png">

**Comment by TheoChevalier** [comment]
Ah, good catch @sabrinang, the version you used (from the website) is the correct one

**Comment by sabrinang** [comment]
All localized social shares are exported here in gdrive: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eQk1YYkt2WVhSQVk?usp=sharing

**Comment by sabrinang** [comment]
@edrushka or @Saallen R? Can you review these social shares? 
Redpen: https://redpen.io/p/pxf744fb02d396a081 
or 
Google Drive: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eQk1YYkt2WVhSQVk?usp=sharing

**Comment by edrushka** [comment]
Beautiful! R+

Thank you Sabrina 🌷
