### ISSUE TITLE
Guidelines page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#581]
https://mozillafestival.org/guidelines

Working in the Open section
- [x] update repo link to point to 2017 repo: https://github.com/MozillaFoundation/mozfest-program-2017
- [x] update 'how we work open at Mozilla' link to point to: https://mozilla.teachable.com/p/open-leadership-101

**Comment by mmmavis** [comment]
Done! http://temp-mozfest-cfp-2017.herokuapp.com/guidelines
