### ISSUE TITLE
Changes to Call for Proposals form

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#583]
https://temp-mozfest-cfp-2017.herokuapp.com/proposals

**INTRO SECTION**
- [x] Change formatting of first paragraphs:

**Welcome to the MozFest 2017 Call for Proposals.**

MozFest sessions cover a wide range of topics, but share two important qualities: they are _interactive_ and _inclusive_.

Sessions may have anywhere from 3 to 25 participants, with a vast range of abilities and ages. Everyone at the festival is welcome to attend your session.

- [x] Since the localized versions of the form likely won't be ready for the first, amend that line to read:
In addition to English, this year we are accepting proposals in Spanish, French and German. Please check back in by June 15 to find localized versions of this form.

- [x] Tweak the A11Y line to read:
If you would like to submit a session and have difficulty using this text-based form, please email us to discuss accessibility options.

- [ ] Add the "remove" functionality to the 'Additional facilitators for your session' question

**HINT TEXT**
- [x] Only need hint text for:
- Email address
- Twitter handle
- Github handle
- Additional facilitators

**DESCRIBE YOUR SESSION SECTION**

- [x] Add question, after "What is the goal or outcome of your session? (120 words max)": After the festival, how will you and your participants take the learning and activities forward?

- [x] Add question, after "How much time you will need?":  How will you deal with varying numbers of participants in your session? What if 30 participants attend? What if there are 3?

**ADDITIONAL SUPPORT SECTION**
- [x] No section description needed (the one that's there is from the intro)
- [ ] Try this for formatting:

MozFest offers limited places for travel sponsorship covering flights and accommodation over the festival weekend. These stipends are offered to those who need support traveling to the event and would have no other means to attend through work or personal covering of costs. We offer these stipends to encourage diversity in facilitators. **Do you require a travel stipend?** (required)

Many attendees bring a personal device (smartphone, laptop or tablet) to the festival. We can provide you with a projector and office supplies (paper, pens, post-it notes). Please note we may not be capable of supporting all your needs but will work with you to provide the best solution possible. **If your session requires additional materials or electronic equipment, please outline your needs.** (max 120 words)

**Comment by edrushka** [comment]
Marking this as P1 as @TheoChevalier is ready to send form to localizers.

**Comment by mmmavis** [comment]
Addressed most of the changes: http://temp-mozfest-cfp-2017.herokuapp.com/proposals

### Undone

- `Add the "remove" functionality to the 'Additional facilitators for your session' question` 
  - making the "remove" button visible is easy but making both the add button and remove button look good takes time. Especially we are using an external library to build the form, there are some customization limitation.

- formatting change in `ADDITIONAL SUPPORT SECTION`
  - Same reason. There are limitations on how much we can customize the form. In this case currently it's not possible to do the suggested formatting. i.e., we can pass "text" as the question for the library to build the form (e.g., `aabbcc 12345 zzz`) but not "jsx/html" (e.g., `aabbcc <strong>bold me</strong>`)

It's possible to make the above changes. But it takes time as it'll need to involve designer's help and more dev work on the form library we are using. Let's leave these as todos after the first big CFP push. @edrushka does this sound okay?

**Comment by edrushka** [comment]
It's fine to not add the remove functionality. If people make a mistake, they can contact us via email or Github and we can make the change

The Additional support section is not great. How breaking up the last part into 2 sections and making use of the section description text area. 

**Rename Additional Support to Travel Support**
- Use the session description to write: 
MozFest offers limited places for travel sponsorship covering flights and accommodation over the festival weekend. These stipends are offered to those who need support traveling to the event and would have no other means to attend through work or personal covering of costs. We offer these stipends to encourage diversity in facilitators.
- That section has one question: Do you require a travel stipend? (required)

**Create a new section called Session materials**
- similarly, use the session description to write:
Many attendees bring a personal device (smartphone, laptop or tablet) to the festival. We can provide you with a projector and office supplies (paper, pens, post-it notes). Please note we may not be capable of supporting all your needs but will work with you to provide the best solution possible. 
- This section has one question: If your session requires additional materials or electronic equipment, please outline your needs. (max 120 words)

**Comment by mmmavis** [comment]
Changes made! http://temp-mozfest-cfp-2017.herokuapp.com/proposals
