### ISSUE TITLE
Guidebook security review

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#589]
Conduct rapid assessment on Guidebook.

Mavis, assigning you for now, but feel free to re-assign.

cc @cadecairos @mmmavis

**Comment by edrushka** [comment]
heya -- any updates? I just want to make sure this gets started.

**Comment by cadecairos** [comment]
@edrushka can you provide more info about what Guidebook is, and where to find it?

**Comment by mmmavis** [comment]
Hey @alanmoo @jessevondoom so Guidebook was the 2nd on my shortlist when I did the schedule app research. Since our decision about using Attendify is still up in the air should we start a RRA for Guidebook during the meantime?

@edrushka also mentioned https://eventory.cc/ but I haven't had a chance to check it out yet.

**Comment by jessevondoom** [comment]
@mmmavis I think it's smart to start the review so we know what we're dealing with. I've got the email from Attendify so I'll write them and see if I can get any wiggle room / clarity on the fees they're asking for.

**Comment by alanmoo** [comment]
@mmmavis you mentioned the RRA scheduling takes a few weeks to actually happen, right?

**Comment by mmmavis** [comment]
@cadecairos let's file a RRA ticket. [Guidebook](https://guidebook.com/) is just another schedule app candidate that we are hoping to use for MozFest. Do you mind filing the ticket and cc'ing me on the bug? I would appreciate if you could join the call so if I got asked a question I couldn't answer I would someone to help me 😃 

DevOps ticket filed: https://github.com/MozillaFoundation/mofo-devops-private/issues/79

**Comment by edrushka** [comment]
@cadecairos any updates on this?

**Comment by cadecairos** [comment]
@edrushka @mmmavis and I attended the RRA yesterday. Things look alright so far. They're putting together a Risk record bug for us, and are sending Mavis a security questionnaire to send over to GuideBook.

**Comment by edrushka** [comment]
Thanks! Do you have an estimation of how much more time it will take to know if this is a viable option. Days? Weeks? Months?

**Comment by cadecairos** [comment]
It depends on the responsiveness and openness that Guidebook has when filling out the security questionnaire. Worst case scenario I'd estimate as two weeks.

**Comment by edrushka** [comment]
Hey @cadecairos - we need to make our final decision on the app by July 27. Can you and @mmmavis please do what you can to ensure Guidebook has the questionnaire in time to fill it out before then? Thanks very much.

**Comment by mmmavis** [comment]
Hey @cadecairos - just wondering what happens after we receive the filled questionnaire from Guidebook. Are there more stages to go through for this vendor security review?

/cc @edrushka

**Comment by cadecairos** [comment]
We'll add the responses to the Risk Record bug on bugzilla, and have the security team review it for any red flags.
