### ISSUE TITLE
Write Call for Proposals tweets

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#590]
Draft tweets here: https://docs.google.com/document/d/1zlSNYv-noARdo8Rm-ZalE2pxkmmvB_V9CyfTanJd8sw/edit#

@Saallen and @Lottarao please review before I hand (some of these) to @TheoChevalier for L10N. Thanks!

**Comment by Saallen** [comment]
@erikad these look great- could some of them link to the spaces page where folks can find out more about the space narratives?

**Comment by edrushka** [comment]
Good idea. I'll also add 1 or 2 directly linking Global Sprint to MozFest.

**Comment by edrushka** [comment]
This is done. Will create a Call for Proposals Cheat Sheet to share this more widely with staff, wranglers and network.
