### ISSUE TITLE
QA: Proposal form 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#600]
Feedback from @Saallen 

* Final closing date is confusing- Deadline for submissions is 12:00am BST August 1, 2017-
Can it be changed to closing date August 1st 2017?

* When I click on any link it loads directly in page I am using- this should link to a new tab as would be more helpful. Currently when I then click back to return to the form all the fields I have filled in are now empty

* organized should be organised
* Decentralisation should be spelt with a Z here under choose a space- this is the only US spelling as this word is part of the IH report- all other spelling should be UK

* Having this statement above the question seems out of order- Please note we may not be capable of supporting all your needs but will work with you to provide the best solution possible.- If your session requires additional materials or electronic equipment, please outline your needs. Can we change the order- Question first then statement?

* I am not able to submit- this is the second time this has happened. also my submission from last night is not on the tes response sheet....using firefox browser :)

/cc @edrushka

**Comment by hannahkane** [comment]
Just noting functionality test passed for me in desktop Chrome and mobile Safari. Have some follow-up UX tickets to file, but basic submission flow passed.

**Comment by mmmavis** [comment]
Thanks for the feedback @Saallen ! All the issues you found have been fixed except the `Having this statement above the question seems out of order` one as there are some tech limitations (tldr, we are using an external library to build the form and the library only allow us to customize certain things).

I've asked more people to QA the form. So far no one has encountered any issue. I'm guessing maybe there were some fields you forgot to fill? I'll keep an eye on the QA response I get.
