### ISSUE TITLE
Localize the automated reponse email

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#602]
Localize the confirmation email detailed in #574.

- [x] German
- [x] French
- [x] Spanish

**Comment by edrushka** [comment]
This work is underway.

**Comment by TheoChevalier** [comment]
Tracking dashboard: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=emails/2017/mozfest_call.lang

Translations: https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2017/mozfest_call.lang&action=translate&show

So far, German is ready

**Comment by TheoChevalier** [comment]
French is now ready too! Waiting for last strings + review for Spanish.

**Comment by mmmavis** [comment]
@cadecairos just a headsup - once things have been localized I will submit a PR on `sawmill` and tag you for review. 😉

**Comment by mmmavis** [comment]
@TheoChevalier I know nothing about German but the capitalization in the following 2 strings look a bit odd to me:

- `Hi [First Name],` --> `Guten Tag [First Name],`  
   - lowercase `t` instead?
- `Thank you for submitting a session proposal for MozFest!` --> `danke für Ihren Vorschlag für eine Veranstaltung beim MozFest!`
   - uppercase `D` instead?

Could you help verify?

**Comment by TheoChevalier** [comment]
@mmmavis Guten Tag is correct, I can find several occurrences in past emails:
https://pontoon.mozilla.org/de/engagement/emails/2017/copyright.lang/?string=163193
https://pontoon.mozilla.org/de/engagement/emails/2017/data_privacy_day.lang/?string=161961

As for the lack of capitalization for the first sentence, it’s also wanted because there is no period before (that’s the rule they are following). I know some things can seem odd from an external point of view in several languages, but most of the time it’s just weird rules we don’t know about :)

**Comment by mmmavis** [comment]
@TheoChevalier Gotcha! Thanks! Sounds like it's a simple copying and pasting job for me then!

**Comment by mmmavis** [comment]
hey @TheoChevalier , can you help me proofread and see if I hyperlinked the right text in the test email below? I can't tell if I wrapped `<a>` around the right word(s) or not 👀 

<img width="1171" alt="screen shot 2017-06-08 at 7 05 01 pm" src="https://user-images.githubusercontent.com/2896608/26958066-78fae56c-4c7d-11e7-9302-d5f23ffe1a16.png">


<img width="1177" alt="screen shot 2017-06-08 at 7 02 30 pm" src="https://user-images.githubusercontent.com/2896608/26958094-9ca609ba-4c7d-11e7-83ee-9d5d49bc74c6.png">

**Comment by TheoChevalier** [comment]
I think you nailed it pretty well, the only one I would change is the link to the video for both locales:

`Wenn Sie bei GitHub neu sind, zeigt Ihnen <a>dieses 45-sekündige Video</a>, wie Sie sich für ein kostenloses Benutzerkonto registrieren.`
`Si vous n’avez pas l’habitude d’utiliser GitHub, <a>cette vidéo de 45 secondes</a> vous montrera comment créer un compte gratuit.`

(Adding this to the l10n check list for next year)

**Comment by mmmavis** [comment]
@TheoChevalier thanks! That's very helpful. I will update my [PR](https://github.com/mozilla/webmaker-mailroom/pull/61)!

**Comment by mmmavis** [comment]
@TheoChevalier and /cc @Melechuga : do you mind QAing this Spanish email template for me? Copy is based on the [finalized translations](https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2017/mozfest_call.lang&action=translate&show) but I just don't know if I included the right words for hyperlinks.

<img width="1168" alt="screen shot 2017-06-13 at 11 07 53 am" src="https://user-images.githubusercontent.com/2896608/27097305-a66817aa-5028-11e7-97c2-96163ebde40f.png">

For reference, this is the verified English version:
<img width="1170" alt="screen shot 2017-06-13 at 11 11 03 am" src="https://user-images.githubusercontent.com/2896608/27097424-0e263390-5029-11e7-9ed4-b699137a2707.png">

**Comment by TheoChevalier** [comment]
Thanks @mmmavis! It looks good, I would just tweak the video link like French and German:

`Si es tu primera vez en GitHub, <a>este vídeo de 45 segundos</a> te mostrará cómo crear una cuenta gratuita.`

**Comment by mmmavis** [comment]
Woooohoooo done! Thanks team!
