### ISSUE TITLE
Localize call for proposals tweets

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#603]
Localize the EN call for proposals tweets from #590

- [x] German
- [x] French
- [x] Spanish

**Comment by edrushka** [comment]
This work is underway.

**Comment by TheoChevalier** [comment]
Tracking dashboard: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=social/2017/mozfest.lang

Translations: https://l10n.mozilla-community.org/langchecker/?website=6&file=social/2017/mozfest.lang&action=translate&show

 So far, German is ready

**Comment by TheoChevalier** [comment]
French is now ready too! Waiting for final review for Spanish, and a couple strings have to be shortened

**Comment by TheoChevalier** [comment]
Forgot to close this ticket, but the latest translation were added to the GDocs
