### ISSUE TITLE
AND WE ARE LIVE!!

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#611]
Whoop- first big hurdle cleared 🎆 the Call for Proposals is OPEN
So exciting to come into work and see the website looking all swish and new at 9am 

Well done, high fives, virtual hugs and rounds of appreciation @mmmavis @edrushka @hannahkane  @sabrinang and everyone else who tested, spell checked and worked hard behind the code ❤️

**Comment by edrushka** [comment]
![giphy](https://cloud.githubusercontent.com/assets/4515662/26685582/67983ca4-469f-11e7-8c7f-18be71214f1f.gif)

Thanks everyone. Technically we got this live on the 31st - I think this is a new record 😄

**Comment by mmmavis** [comment]
＼＼\\٩( 'ω' )و //／／
