### ISSUE TITLE
Localized proposals curation flow

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#612]
@edrushka 

We know we will have the non-English forms live on different pages on the site (i.e., different URLs than just `/proposals`). How about the spreadsheet and GitHub repo? Do we plan to have these non-English proposals go to the same spreadsheet and repo as what the English proposals use?

**Comment by edrushka** [comment]
The localized pages should live here:
https://mozillafestival.org/proposals-francais   ---->  mzl.la/francais
https://mozillafestival.org/proposals-espanol  ----> mzl.la/espanol
https://mozillafestival.org/proposals-deutsch ----> mzl.la/deutsch

They should live on the same spreadsheet and enter into the same repo as the EN proposals. 

The only part of the process that's different is the form and the autogenerated thank you/confirmation email, which will be localized as well.

**Comment by edrushka** [comment]
If you have the time, I suggest you prep as much of that process as you can now. When the strings come in, we'll be on fire to get them up and public 🔥 🔥 🔥 🚒

**Comment by mmmavis** [comment]
@edrushka 

Say someone submitted a proposal in French, but he didn't choose to conduct the session in a non-English language, how should the response show up on spreadsheet? Do we want the "additionallanguage" field on spreadsheet to be blank? or "French"? Same question applies to GitHub ticket. What label do we wanna use to indicate that the **proposal itself** is in non-English?

**Comment by edrushka** [comment]
Let's use the same label. The proposal itself will clearly be in French (we'll and the translated version in the second comment) so we don't need any further identification on Github. I am going to make the blanket assumption that if someone submits a proposal in another language, they are willing to host a bilingual session!

**Comment by mmmavis** [comment]
These are definitely edge cases but I still need more clarification so I can handle things correctly in code.

### Case 1 
1. someone submits a French proposal
2. he didn't choose to conduct the session in any non-English language (he didn't answer that "bilingual" question)

Expected spreadsheet result: `additionallanguage` set to `French`
Expected Github issue result: `French` label applied

### Case 2 (a super edge case but I still need to handle this case in code)
Question for you @edrushka :
1. someone submits a French proposal
2. he chose to conduct the session in Japanese

Expected spreadsheet result: `additionallanguage` set to `French` OR `Other: Japanese`? or both?
Expected Github issue result: `French` label? `Other: Japanese` label? or both?

**Comment by edrushka** [comment]
Haha! I ❤️ Case 2. This might be more common expected, since many people can speak both French and Spanish (we saw this in the proposals from last year).

I'd do:
Spreadsheet set to French.
Both Github labels:  French and Other: Japanese

**Comment by mmmavis** [comment]
@edrushka now I think about it, I think the meta on Spreadsheet and Github should **not** differ to avoid future confusion. 

- I'll add a new column in Spreadsheet called `proposallanguage` that records the language the proposal was written in (e.g., `French` in this case).
- On Github both the `proposallanguage` and `additionallanguage` will appear as language labels. (e.g., `French` and `Other: Japanese`)

**Comment by mmmavis** [comment]
@TheoChevalier @hannahkane I will add those last minute translations in in ~an hour. Other than that, everything is ready for testing.

MozFest staging site links:
- https://mozillafestival.org/proposals/francais
- https://mozillafestival.org/proposals/espanol
- https://mozillafestival.org/proposals/deutsch

Please try submitting a non-Eng proposal and see if your entry ends up showing on
- https://docs.google.com/spreadsheets/d/16QMKfetQbW7N0a21URIYoV16ZtFPj8bqOCujVUV-oIc/edit#gid=0
- https://github.com/mmmavis/test-mozfest-2017-proposals/issues (only a few selected meta is exposed here)
- and verify that you do get a non-Eng confirmation email

**Comment by mmmavis** [comment]
@xmatthewx can you help update the moz shortlinks? We made adjustments to the urls. Here's the updated list:

- https://mozillafestival.org/proposals/francais ----> mzl.la/francais
- https://mozillafestival.org/proposals/espanol ----> mzl.la/espanol
- https://mozillafestival.org/proposals/deutsch ----> mzl.la/deutsch

**Comment by hannahkane** [comment]
@mmmavis and @TheoChevalier - tests passed for me.

I will note a few things, none of which feels like a blocker to me:
 - The "Submitting" button state is in EN for all forms. It's also misspelled in EN; should be "Submitting" not "Submiting".
 - The success message is in EN for all forms
 - Wondering if the question about delivering the session bilingually is confusing in the context of non-EN forms. Is the assumption that all sessions will be delivered in EN, though some will also be delivered in another language? I think if I were filling out a form in a non-EN language, I would assume I'd be delivering the session in that language. (Apologies if this has already been discussed)

**Comment by mmmavis** [comment]
thanks for the QA @hannahkane 

- To your first 2 points - I just fixed the typo and added the last bits of translations in!
- To your last point - @edrushka and I discussed about it [earlier in this ticket](https://github.com/mozilla/mozillafestival.org/issues/612#issuecomment-305870369) but the discussion was more around how these meta should show up on spreadsheet & GitHub. I would assume if I were filling out a French proposal I would be delivering the session in French as well. Maybe we should open up a followup ticket and get @edrushka 's thoughts when she's back from PTO?

**Comment by xmatthewx** [comment]
> update the moz shortlinks

@mmmavis – I updated the links. I believe I did it right. Please check 'em.

**Comment by hannahkane** [comment]
Thanks, @mmmavis. Sorry I missed the earlier conversation about multilingual sessions. I'll open a follow-up ticket.

I think we're good to go, though we should get an OK from @TheoChevalier during his morning before we push this to production.

@TheoChevalier - can you please let us know once you've had a chance to review staging? (See @mmmavis's instructions [above](https://github.com/mozilla/mozillafestival.org/issues/612#issuecomment-308509749)).

**Comment by TheoChevalier** [comment]
@mmmavis looks like we’re missing `We welcome workshops and exhibits, and strongly favor these over sessions that are exclusively lectures and slide presentations.` in all languages. Other than that, it looks good to me :)

**Comment by mmmavis** [comment]
@TheoChevalier nice catch! I'll add the strings in now!

**Comment by mmmavis** [comment]
I just added in the missing text!

**Comment by mmmavis** [comment]
Done done done! 

My test entry went through ✨ https://github.com/MozillaFoundation/mozfest-program-2017/issues/50

**Comment by hannahkane** [comment]
@mmmavis - nice work! Can we close this?
