### ISSUE TITLE
QA: Change name

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#615]
https://mozillafestival.org/spaces

Please change Viki's name  in the Decentralization space to:
D. Vigneshwer 'Viki'

**Comment by Saallen** [comment]
please add Mark Boas here as a wrangler too :bowing_woman:

**Comment by mmmavis** [comment]
> please add Mark Boas here as a wrangler too :bowing_woman: 

@Saallen to "Decentralization" ? or another Space?

**Comment by Saallen** [comment]
to Decentralization please @mmmavis

**Comment by Saallen** [comment]
Hey @edrushka  We are also missing in this space Solana Larsen here- is that correct?

**Comment by edrushka** [comment]
@mmmavis please add Mark and change Viki for now, we'll get back to you soon about Solana (will file a new ticket). Thanks!

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/spaces
