### ISSUE TITLE
Bug: Proposal GitHub tickets should not have "none" label

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#616]
**Problem:**
If a proposal has its "Secondary Space" set to "None",  when it get posed on GitHub it gets a "None" label.

**Solution:**
We should clear that value before sending the proposal to spreadsheet and to GitHub so the entry doesn't have a "None" field value and GitHub label.

---

Another issue:
If user chose "Other" as the additional language without specifying the language, we should simply ignore that value.

**Comment by edrushka** [comment]
@mmmavis is it ok if I manually remove those labels in Github now? I'm doing a demo on Thurs and don't want people to be confused.

**Comment by mmmavis** [comment]
@edrushka yup plz go ahead.
