### ISSUE TITLE
Update secondary space labels on proposal repo

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#619]
I was making some edits to label names today. I wanted the label with space name to be more overt as a secondary request so edited the labels to read [secondary Space] Web literacy....
I just noticed that someone add a new session and the label automatically added was not one I edited. Is there a bug or did I break the system @mmmavis @edrushka 
![screen shot 2017-06-06 at 18 20 48](https://user-images.githubusercontent.com/10194015/26842684-966ace58-4ae5-11e7-839c-0c308025c2ed.png)

**Comment by mmmavis** [comment]
> Is there a bug or did I break the system

@Saallen Neither 😉  The automated proposal pipeline won't know any changes made directly in GitHub. Currently we configure the script to apply a `[Space Name]` label if a secondary Space was selected in the proposal. If we would like to change the label to be prefixed with `Secondary Space` (e.g., `[Secondary Space] Space Name`) I can update the script. Let me know! 👀

**Comment by Saallen** [comment]
Ah I see @mmmavis phew!
Can we change the script to make the secondary label clearer for all submissions?

**Comment by mmmavis** [comment]
Okay I will make this change after my calls this morning. Once I'm done, @Saallen can I go ahead and move these that are currently in `[Space Name]` to `[Secondary Space] Space Name`. That way we can remove those `[Space Name]` labels and avoid confusion.

**Comment by mmmavis** [comment]
Done!
