### ISSUE TITLE
Launch localized CFPs

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#622]
1) Mavis makes the localized forms live at
- https://mozillafestival.org/proposals/francais
- https://mozillafestival.org/proposals/espanol
- https://mozillafestival.org/proposals/deutsch 

2) Mavis adds a link to each language on the English form (and removes line 'Please check back in by June 15 to find localized versions of this form.')

3) Hannah, ask Willse to remake the shortlinks as follows (and confirm they work!)
- https://mozillafestival.org/proposals/francais   ---->  mzl.la/francais
- https://mozillafestival.org/proposals/espanol  ----> mzl.la/espanol
- https://mozillafestival.org/proposals/deutsch ----> mzl.la/deutsch
If they don't work the individual language G-Docs will need updating 😱 

4) Hannah adds to full resources for each language to the [cheat sheet]( https://docs.google.com/document/d/1vBmHO7KGRub9DUV2XynQTAHOnURbh4Ijs9z-iDsK-uo/edit#heading=h.e4nm4wtgicqb). Remove all the links currently there and just link to each page:
[French](https://docs.google.com/document/d/1ncidPMbhZrHAGtt-EfMVaozmJpaujoTmOh5YIkUizHA/edit)
[German](https://docs.google.com/document/d/10qqj2S0ShSZRjmByQdUDFg-UXOWZDuEkOr7AuU2BxMU/edit)
[Spanish](https://docs.google.com/document/d/1yD01hrCHGknbGaqgO-erEP_L4qpMWs7066hAGEl7eh4/edit)

5) Sarah sends [email to wranglers](https://docs.google.com/document/d/1nrELRduyvX4UKYuFVfFW1dHcpYUaQOhI8K_GboQxBYI/edit#heading=h.73q269jgq40q) 

6) Also for Sarah, If [MoFo staff email](https://docs.google.com/document/d/1nrELRduyvX4UKYuFVfFW1dHcpYUaQOhI8K_GboQxBYI/edit#heading=h.t3xzbdl17sq9) hasn't gone out yet, include the mention of localized resources in the email (already drafted).

**Comment by edrushka** [comment]
cc @mmmavis @hannahkane @Saallen @TheoChevalier

**Comment by hannahkane** [comment]
Localized forms are on staging, and have been QA'd for functionality, though not for localization.

Link to each language on the EN form is working as expected on staging.

Shortlinks exist.

Cheatsheet updated.

I think we just need an OK from @TheoChevalier to push to production, and then @Saallen can send the Wrangler and Mofo staff emails.

**Comment by mmmavis** [comment]
Seems like @TheoChevalier has okayed on the localization piece. (see [this comment](https://github.com/mozilla/mozillafestival.org/issues/612#issuecomment-308578015))

**Comment by TheoChevalier** [comment]
Yup, 🚢 it!

**Comment by mmmavis** [comment]
My test entry went through ✨ https://github.com/MozillaFoundation/mozfest-program-2017/issues/50

THANKS TEAM!

🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻

**Comment by Saallen** [comment]
Sweeet 🍬 - apart from the text issue at the top of the page we are golden.
Nice work team and congrats- let the multi-lingual sessions roll in
🇫🇷 🇪🇸 🇩🇪 

I will email and tweet now

**Comment by hannahkane** [comment]
@Saallen - ok if we close this issue?

**Comment by Saallen** [comment]
For shizzellllll- Thanks everyone
