### ISSUE TITLE
Additional copy for top of call for proposals page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#626]
During yesterdays call it was highlighted that we need a bit more context about the type of sessions we are looking for. I want to de-emphasizes slide presentations and lecture but ensure people understand they can submit a wide variety of sessions such as art pieces and hacks.
What do people think about this as a copy edit @mmmavis @KevZawacki @hannahkane to the top of this page, first line: https://mozillafestival.org/proposals

MozFest sessions cover a wide range of topics, but share two important qualities: they are interactive and inclusive. We welcome workshops, exhibits and often shy away from lectures and slide presentations.

**Comment by hannahkane** [comment]
I like the idea of clarifying. Some of the best Mozfest sessions I've attended have *included* slide presentations and a bit of lecture, they just *also* included an interactive/hands-on component. Not sure if the intent is to avoid that style altogether.

Perhaps something like, "MozFest sessions cover a wide range of topics, but share two important qualities: they are interactive and inclusive. We particularly love workshops, hack sessions, and exhibits and often shy away from sessions that are exclusively lectures."

Perhaps this overcomplicates the paragraph? I think your original suggestion, Sarah, is really good.

**Comment by KevZawacki** [comment]
Either update works for me! Good idea to clarify.

**Comment by Saallen** [comment]
How about 
MozFest sessions cover a wide range of topics, but share two important qualities: they are interactive and inclusive. We welcome workshops, exhibits and often shy away from sessions that are exclusively lectures and slide presentations.

**Comment by hannahkane** [comment]
WFM!

**Comment by KevZawacki** [comment]
Sure! Two tiny copy edits (in bold):

MozFest sessions cover a wide range of topics, but share two important qualities: they are interactive and inclusive. We welcome workshops **and** exhibits**,** and often shy away from sessions that are exclusively lectures and slide presentations.

**Comment by Saallen** [comment]
Helllo @mmmavis 
Can you please make the following text amendment to the top of the introduction of the call for proposals page.

Existing line: MozFest sessions cover a wide range of topics, but share two important qualities: they are interactive and inclusive. 
Please add to end of existing line -We welcome workshops and exhibits,  and often shy away from sessions that are exclusively lectures and slide presentations.

**Comment by mmmavis** [comment]
@Saallen yup yup I'll make that change today.

/cc @TheoChevalier as this might affect the content we are showing on the localized proposal pages.

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/proposals

**Comment by TheoChevalier** [comment]
Thanks, including the new string in the batch of last minute strings, will be exposed in a few

**Comment by Saallen** [comment]
Thanks all!!!

**Comment by TheoChevalier** [comment]
If I followed correctly the discussions in https://github.com/mozilla/mozillafestival.org/pull/618 are we good with `We welcome workshops and exhibits, and strongly favor these over sessions that are exclusively lectures and slide presentations.`? Let me know if I can push the button 🚢

**Comment by TheoChevalier** [comment]
Couldn’t wait more, so I just pushed the version above ↑
Thanks!

**Comment by Saallen** [comment]
@mmmavis, @hannahkane @TheoChevalier 
Sorry I mis-interpreted theo's comment above- I thought the language he used above was the translated version of localised copy edits.
the copy request to the top of the Call for Proposals was:
_We welcome workshops and exhibits,  and often shy away from sessions that are exclusively lectures and slide presentations._

What we currently now at the top of the form is:
_We welcome workshops and exhibits, and strongly favor these over sessions that are exclusively lectures and slide presentations._

I would prefer not to use _strongly favour_ here- I feel it changes the intention. Looping in @KevZawacki as if you dont want to use often shy away we need something else other than strongly favour.

**Comment by KevZawacki** [comment]
@Saallen 

How about: "We prefer interactive workshops and exhibits over lectures and slide presentations."

**Comment by Saallen** [comment]
@KevZawacki its feels a small bit like we are repeating here with the sentence above. 


Another option is :
MozFest sessions cover a wide range of topics, but share two important qualities: they are interactive and inclusive. Successful sessions are not lectures or presentations with slides, but sessions designed to challenge and encourage audience participation.

**Comment by KevZawacki** [comment]
@Saallen Ooh — perfect!

**Comment by Saallen** [comment]
Great- thanks Kevin
 @mmmavis can you make this change to the main MozFest EN site?
@TheoChevalier can you make this change to the FR, ES and DE pages?

**Comment by edrushka** [comment]
Might I suggest the smallest tweak (removing the repetition of 'sessions' in the same sentence)? 

MozFest sessions cover a wide range of topics, but share two important qualities: they are interactive and inclusive. Successful sessions are not lectures or presentations with slides, but are designed to challenge and encourage audience participation.

**Comment by TheoChevalier** [comment]
String exposed (without the repetition), will post updates here once translations are ready

**Comment by Saallen** [comment]
@edrushka  great spot
@TheoChevalier thanks !!

**Comment by TheoChevalier** [comment]
@mmmavis translations are done, over to you :) https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_form.lang&action=translate&show

**Comment by Saallen** [comment]
Hello @mmmavis, @edrushka and @TheoChevalier -
Legal would like the following amendment as indicated by Italics below

"Once you have submitted your session, it will enter an open curation process on GitHub. _All information you submit here, except your email address and Twitter handle, will be publicly available on GitHub. Mozilla may contact you via email in regard to your submission."_

Please ping me when we at least have the english page updated so I can update them- thanks and sorry @TheoChevalier for the late request when you already made adjustments

**Comment by TheoChevalier** [comment]
No problem, string added to the l10n queue, French is ready https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_form.lang (at the bottom of the page)

**Comment by TheoChevalier** [comment]
Spanish and German now done as well: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_form.lang&action=translate&show#string8

**Comment by mmmavis** [comment]
@Saallen @edrushka @TheoChevalier changes are live! https://mozillafestival.org/proposals
