### ISSUE TITLE
Add icons to footer links

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#630]
... since icons are required!

For context see https://github.com/mozilla/mofo-ui/issues/63

**Comment by mmmavis** [comment]
@sabrinang @taisdesouzalessa @kristinashu I'm not sure what icons to use for the first 3 links. Please see what's available in `mofo-bootstrap` currently: https://mozilla.github.io/mofo-bootstrap/demo/ (scroll to page bottom)

<img width="694" alt="screen shot 2017-06-12 at 6 11 59 pm" src="https://user-images.githubusercontent.com/2896608/27061679-c151a6fa-4f9a-11e7-98a0-2296a08b6e0b.png">

**Comment by kristinashu** [comment]
I'd say:
- speak bubble from "IRC" for "Blog"
- "i" from "info" for "Festival Team"
- happy face from "Code of Conduct" for "Participation Guidelines"

Thanks @mmmavis!
