### ISSUE TITLE
New Sponsor page on MozFest.org

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#631]
We need a new page to be added to the MozFest website for sponsorship opportunities.
I am currently working on content for this page and will add this content to the issue once it has been approved.

In the meantime 
* @sabrinang  can you find a new picture for the top of this page?
* @mmmavis once I get approval on content can you please create this new page- with link to be added to the top navigation bar?
 
Looping in @KevZawacki @hannahkane @TheoChevalier @edrushka

**Comment by Saallen** [comment]
Copy for the new Sponsorship page


MozFest is the world’s leading event for and by the open Internet movement, and one of Mozilla’s largest annual networking opportunities. This three-day festival of interactive sessions, hands-on activities, and engaging talks brings together 1,800 passionate advocates of the open web from around the world for the flagship event in  Mozilla’s leadership network.
 
For 2017, Mozilla is offering new sponsorship opportunities for supporters to help us deliver MozFest in London. The festival is growing at a phenomenal rate, as are the opportunities to collaborate, build, and convene with this dynamic network. 

If you would like to sponsor MozFest 2017, please reach out to us at festival@mozilla.org. A festival team member will share with you the various options for support and next steps.
 We look forward to to hearing from you.

**Comment by sabrinang** [comment]
@Saallen Here are some image picks:
https://www.flickr.com/photos/mozfest/30603219796/
https://www.flickr.com/photos/mozfest/30572444401/
https://www.flickr.com/photos/mozfest/30535184381/in/album-72157674377310602/

new image treatment can be similar to home
<img width="740" alt="image" src="https://user-images.githubusercontent.com/2492510/27160923-a8f36b64-512c-11e7-9e3e-307146ebf7fd.png">

**Comment by Saallen** [comment]
hello @sabrinang I like the two images you have treated. Anyone else with preferences? @hannahkane @mmmavis ??

**Comment by Saallen** [comment]
@mmmavis can you tell me the expected timeline you think you can go live with this page?
Its important that it happens asap as its a  request from the exec team.

**Comment by mmmavis** [comment]
@Saallen 

This can be pushed live on Monday. 

![screen shot 2017-06-16 at 15 13 30-fullpage](https://user-images.githubusercontent.com/2896608/27246426-60bcd936-52a6-11e7-91e3-146357309e72.png)

- "Production" tab goes to https://mozillafestival.org/team
- "Sponsors" tab goes to https://mozillafestival.org/team/sponsors
- `We look forward to to hearing from you.`  -> the double `to` looks like typo to me so I removed one from the sentence. Just wanna confirm it was indeed a typo 😉 
- Question: @Saallen do we also wanna add a "Sponsors" link to the top nav bar? If so where should we put it? After "Propose" or?

**Comment by Saallen** [comment]
Hello @mmmavis 
Great spot on the typo- 4 other ppl missed it!!!
* Production goes to team 👌 
* Sponsors goes to sponsors 🆗 
* Yes, we want a sponsors link on top nav- add it to the end of this current list please
* I think that is fine with hero image

Thanks!!

**Comment by mmmavis** [comment]
@sabrinang can you attach the new hero image here?

**Comment by sabrinang** [comment]
![banner-sponsorship](https://user-images.githubusercontent.com/2492510/27306568-f249acfc-54fa-11e7-9902-1262750905a6.png)
@mmmavis

**Comment by sabrinang** [comment]
![banner-sponsorship 2x](https://user-images.githubusercontent.com/2492510/27311535-68f10c7c-5516-11e7-88e9-5e36e916942e.jpg)

**Comment by mmmavis** [comment]
Just push the changes live. Should be on https://mozillafestival.org/team/sponsors soon.

**Comment by Saallen** [comment]
Hellloooo looking good 👀 
Thanks!

**Comment by edrushka** [comment]
Very nice! Really love the image you selected - perfect for this page.
