### ISSUE TITLE
Address potentially confusing question on form about bilingual sessions

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozillafestival.org#636]
Following up on #612 - perhaps we can close this without changing anything, but I just wanted to follow up to make sure we've addressed all of the edge cases.

Below is what's already been discussed. My remaining question is: the field doesn't specifically include English as an additional language, though the submitter could include it in the "Other" field. Given that most of the site is in English, but the form has been localized, I wonder if some people will    include English but others won't, even if they are planning to conduct the session partially in English. Is that a use case we need to address?

------

### Case 1 
1. someone submits a French proposal
2. he didn't choose to conduct the session in any non-English language (he didn't answer that "bilingual" question)

Expected spreadsheet result: `additionallanguage` set to `French`
Expected Github issue result: `French` label applied

### Case 2 (a super edge case but I still need to handle this case in code)
Question for you @edrushka :
1. someone submits a French proposal
2. he chose to conduct the session in Japanese

Expected spreadsheet result: `additionallanguage` set to `French` OR `Other: Japanese`? or both?
Expected Github issue result: `French` label? `Other: Japanese` label? or both? 

## Current implementation
Column in Spreadsheet called proposallanguage that records the language the proposal was written in (e.g., French in this case).
On Github both the proposallanguage and additionallanguage will appear as language labels. (e.g., French and Other: Japanese)

**Comment by edrushka** [comment]
Yah, I can see this already happening. People are choosing English as the 'other' language, which is not required and only creates confusion for anyone exploring the repo. I suggest adjusting the CFP form question to read: 
Would you like to deliver this session bilingually in English and one of the following languages?
(for the localized CFPs, we'd say the same thing - English and one of the following languages).

If you think that would help clarify, I can write a ticket for this change.

**Comment by hannahkane** [comment]
I think that clarifies it.

**Comment by edrushka** [comment]
@mmmavis can you adjust the additional language question on the CFP form to read

Would you like to deliver this session bilingually in English and one of the following languages?

**Comment by mmmavis** [comment]
@TheoChevalier can you help get `Would you like to deliver this session bilingually in English and one of the following languages` translated please?

**Comment by TheoChevalier** [comment]
Sure thing, string exposed. Will post update here as usual when translations are ready :)

**Comment by TheoChevalier** [comment]
@mmmavis all set! Please find the translations here https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_form.lang&action=translate&show#string43

**Comment by mmmavis** [comment]
@TheoChevalier um I can't see that page... it's a broken link for me. Is the site down for the moment?

**Comment by TheoChevalier** [comment]
@mmmavis Sorry about that, we are indeed experiencing issues :/ https://bugzilla.mozilla.org/show_bug.cgi?id=1383642

Let’s go old school:

de `Möchten Sie die Veranstaltung auf Englisch und in einer der folgenden Sprachen zweisprachig abhalten?`
es `¿Te gustaría impartir esta sesión en inglés y en otro de los siguientes idiomas?`
fr `Souhaitez-vous présenter cette session en anglais et également dans l’une des langues suivantes ?`
