### ISSUE TITLE
Fix gendered DE translation

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#640]
Received a [flag on twitter](https://twitter.com/kkvie/status/881204444528091136) indicating the German Call for Proposals form uses a gendered form of people. 

@TheoChevalier Can you please request a review this translation to ensure it doesn't contained gendered terms.

**Comment by TheoChevalier** [comment]
Thanks for filing, @edrushka, asked Michael to have a look when he has a chance

**Comment by TheoChevalier** [comment]
@edrushka @mmmavis Michael updated the translations, full list of changes here https://github.com/mozilla-l10n/engagement-l10n/commit/1afd52c33707e12cdaae05c492782635ed5b2439

**Comment by edrushka** [comment]
Thanks (and thanks to Michael as well) for the quick turnaround on this.

@mmmavis is it possible to update the German form with these changes in the next few days?

**Comment by mmmavis** [comment]
Changes are live: https://mozillafestival.org/proposals/deutsch

**Comment by edrushka** [comment]
Thanks, everyone!
