### ISSUE TITLE
Update Mark's speech bubble

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#642]
@mmmavis I just noticed this never got updated!! 😱 

Please update Mark's speech bubble on the [About](https://mozillafestival.org/about) page with [this text](https://docs.google.com/document/d/1aIup5OqSMpZriTVBImKhfh4Ldlo-wHsYjicszez0Cz4/edit).

**Comment by mmmavis** [comment]
Live: https://mozillafestival.org/about
