### ISSUE TITLE
Write tagline for MozFest 2017

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#643]
Please help us brainstorm the MozFest 2017 tagline (2-5 words used heavily in festival design). Kindly add your ideas, +1s and comments to this [**brainstorming document**](https://docs.google.com/document/d/1sU8moda1784OI_762r8oYMmZh2jIpDW-rMGPjLjNdPY/edit#) by EOD Friday July 14.

cc @KevZawacki @Lottarao @chrislarry33 @Saallen @hannahkane @brettgaylor

**Comment by hannahkane** [comment]
Added some suggestions

**Comment by sabrinang** [comment]
https://github.com/MozillaFoundation/mozfest-design-2017/issues/4#issuecomment-321631916
"The tagline "Web For All" has been approved by Chris to move forward. Erika received explicit approval that we can proceed with the Web For All tagline."
