### ISSUE TITLE
Add more data to autogenerated comment

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#644]
Hey @mmmavis. Can we add 3 things to the top of the autogenerated MozFest ticket comments:

- Session name
- Primary Space 
- Secondary Space 

These can come at the top, right after the session ID. This doesn't have to be retroactive, but it would be helpful going forward. Please let me know - thanks!
cc @phillipadsmith

**Comment by edrushka** [comment]
Hey @mmmavis any chance you can get to this in the next week or so?

**Comment by phillipadsmith** [comment]
Howdy @mmmavis!

If it’s helpful, I can send a pull request against issue-template.md and, if needed, lib/proposal-handler.js 

Just shout if you’ve got your hands full, :)

Phillip.

**Comment by mmmavis** [comment]
I just did a prod push. It should be available on the production site soon.

**Comment by mmmavis** [comment]
Hey @edrushka @phillipadsmith forgot to mention - just a note that primary and secondary spaces info can change during the curation process as wranglers are free to reassign GitHub milestone (primary space) & label (secondary space) to a ticket... these changes will not show in the top comment of a proposal ticket.
