### ISSUE TITLE
Volunteer page on Website

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#645]
Hello @edrushka and @mmmavis -

The hero @tomfarrow has prepared the [volunteer sign up page](https://ti.to/mozfestvolunteers/mozfest-volunteer-program-2017) for 2017on tito- we are going to start promoting later this week through our own channels- We would love for this to be live on the website whenever you are next updating.

Tom was also looking for graphics for emails - @sabrinang can you give Tom access to the drive with graphics for this year please- I will ping you his email

**Comment by mmmavis** [comment]
Hi Sarah, by going live on the website did you mean updating this page https://mozillafestival.org/volunteer with new content?

**Comment by sabrinang** [comment]
For the logo, you can use svg or png here:
[mozilla-festival_vertical-black.zip](https://github.com/mozilla/mozillafestival.org/files/1143036/mozilla-festival_vertical-black.zip)

Which follows the brand taxonomy seen here: https://mozilla.ninja/logosystem

We only have graphics for call for proposals so far which can be found here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eLURVNVEtNVhGQ3M?usp=sharing

@TomFarrow Let me know if there is some specific email graphics you are looking for

**Comment by edrushka** [comment]
Hey @Saallen that link goes to a Ti.to ticket page. Where is the link to sign up to become a volunteer?

**Comment by Saallen** [comment]
hey @edrushka that is the link- mirrors the process from last year .
You fill out all the questions within the ticket- we have a wiki page, with further information which @tomfarrrow is linking within the ticket somewhere....
@mmmavis yes that is the page- I had forgotten it was on the website already :duck:

**Comment by edrushka** [comment]
@Saallen @TomFarrow  What do you think about these minor text amendments to clarify the process for people landing on the page without context?

#### The [Volunteer page](https://mozillafestival.org/volunteer) on the website

Volunteers are integral to what we do at Mozilla, and MozFest is no different. The annual festival could not take place without the time, dedication and love of our local volunteers.

Drawn from the local community, volunteers at MozFest do so much, from running the welcome desk and arranging swag bags to assisting press and helping with programming. We try to place people in roles they’re most interested in, and rotation of roles is encouraged. We provide training before the event, and we host several volunteer socials. Read more on our [volunteer wiki](https://wiki.mozilla.org/Mozfest/2017/Volunteers).

Volunteers are asked to share four hours of their time. As a thank you, we’ll cover the festival’s ticket cost. Volunteers also receive meals and a MozFest t-shirt. Unfortunately, we cannot cover travel to and from the event or provide accommodation.

To apply, register for a (free) volunteer ticket [here](https://ti.to/mozfestvolunteers/mozfest-volunteer-program-2017). During the registration process, you'll have the opportunity to fill out a brief survey that will help us place you in role suited to your needs and interests.


#### The [Ti.to process](https://ti.to/mozfestvolunteers/mozfest-volunteer-program-2017) 

On the landing page, alter grey text to read: 
To volunteer with MozFest, register for a (free) volunteer ticket. During this registration process, you'll have the opportunity to fill out a brief survey that will help us place you in role suited to your needs and interests.

On the survey, add a question where people can indicate what they are interested in helping with. Example "Is there a particular element of the festival you'd like to work on?"

**Comment by hannahkane** [comment]
Hey @Saallen - I can update the Volunteer page on the website whenever you give the go-ahead. Cheers!

**Comment by Saallen** [comment]
Sweet @hannahkane - lets make it LIVEEEEE 🎆

**Comment by edrushka** [comment]
Thanks all. Closing this ticket - implementation can be tracked in #654.
