### ISSUE TITLE
Master list of August 2 updates

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#648]
## Top Nav Bar  
Ticket #649
- [ ] replace Propose with Tickets

## Landing Page
Ticket #650
- [ ] Update main banner CTA
- [ ] Update news stories

## Spaces Page
Ticket #651
- [ ] Remove 'Propose a session in this space' 
- [ ] Add blurb for Art experience
- [ ] Add wrangler bios

## Tweet MozFest 
Ticket #652
- [ ] Update autofilled tweet text 

## Festival Team
Ticket #653 &  #682
- [ ] Add Marc's bio
- [ ] Add Chris' bio
- [ ] Add Esme
- [ ] Add Volunteer coordinators

## Volunteer Page
Ticket #654
- [ ] Add link to signup form

## Partners tab on team page
Ticket #655
- [ ] Bring this tab back to life
- [ ] Add new partners

## Fringe page
Ticket #656
- [ ] Link to fringe from

## Call for proposals form
The form can stay live. We just shouldn't link to it from the website.

**Comment by edrushka** [comment]
cc @hannahkane

**Comment by hannahkane** [comment]
Nice! I wonder if I can do many of these myself, perhaps with an assist from @mmmavis or @alanmoo.

**Comment by alanmoo** [comment]
The few I clicked into definitely look like you should be able to.

**Comment by hannahkane** [comment]
@edrushka - is it just the things related to removing the CfP and opening ticket sales that need to wait until August 2nd? Can the other things be done earlier?

**Comment by edrushka** [comment]
That's right, @hannahkane. The following pages can be done earlier (although most are waiting for content, which will take a bit to wrangle):

- Spaces
- Festival team
- Volunteer
- Partners
- Fringe
- Landing (update news stories can be done now)
