### ISSUE TITLE
Spaces page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#651]
- [ ] Change white text on hero banner to Spaces & Experiences

- [ ] Remove "Submit a session" from Spaces description text

- [ ] Remove the line 'Propose a session in this space' from each of the 6 space descriptions

- [ ] Add a new section for Experiences after Youth Zone
Description text:
Experiences are artworks, exhibits, activities and interactions that bridge Spaces by weaving together  many of the themes present at the festival.

- [ ] Under Experiences, add: 
    **Artist Open Studio**
 Wranglers: Luca M Damiani, Irini Papadimitriou, Angela Plohman - 

    **Wayfinding and Recognition** 
Wranglers: Tim Riches
Desciption: Recognise your participation at Mozfest and understand how your contribution makes a difference to the future of the open web. You’ll have the chance to use an augmented reality app to explore and expose different pathways throughout the festival, unlock hidden experiences and swag! We want to recognise your participation at Mozfest, your contribution to the future of the open web and provide you with a record of your experience and the skills you’ve learned along the way that you can share online. After the festival we’ll also direct you to organisations where you can continue your adventure.

    **Dialogue and Debates**
Wrangler: Kevin Zawacki (no link needed, he already has bio on team page)
Description: On MozFest's Dialogues & Debates stage, luminaries at the intersection of technology and society discuss bright spots and threats to Internet health. Each speaker delivers a captivating 20-minute, TED-style talk. Our 2017 speakers are activists, journalists, ethical hackers and comedians hailing from eight countries on four continents.

    **Theme Wrangling**
MozFest 2017 will feature a set of thematic sessions distributed across each of the Spaces. These sessions will explore Policy & Advocacy, Journalism, and Youth Leadership.
Wranglers: Emrys Green, Erika Owens, Melissa Romaine

- [ ] Add wrangler bios 
Bios are being collected [here](https://docs.google.com/spreadsheets/d/1RyDQ1BF3gYLMj9Koy9gqEbB_LQoQQa0opVLfOgNzt_I/edit#gid=0) - spreadsheet is organized by space/experience.

- [ ] Remove Phillipa and Heather from web lit and digital inclusion.

**Comment by edrushka** [comment]
@mmmavis can you please remind me what we did with the wrangler bios last year. Were they revealed on hover?

**Comment by edrushka** [comment]
This page can be updated as soon as the copy is ready.

**Comment by edrushka** [comment]
@Saallen please see how I've arranged the content on this page (in the first comment). If we add the Experiences section as I've proposed, we can also put the D&Ds here once they are announced.

**Comment by Saallen** [comment]
heY @edrushka 
looks great-  Tim will be under experiences as Wayfinding and Recognition.
Let me press that team for a description. Artist in res is now called artist open studio. 
Shoud we call Emrys theme wrangling piece- Youth Led ?

So to clarify Experiences will have its own section with 4 elements
* Artist Open Studio
* Wayfinding and Recognition
* Dialogue and Debates
* Theme Wrangling

Each of these experiences will have wranglers too. Most are under the bios file already

**Comment by mmmavis** [comment]
@edrushka last year wrangler bios were actually on another page `/team/wranglers`.

<img width="880" alt="screen shot 2017-07-31 at 10 35 07 am" src="https://user-images.githubusercontent.com/2896608/28789959-25a0d3a8-75dc-11e7-83b8-1e89a1c72074.png">

Note that the name (hot pink heading) was an anchor link. Wrangler's name on the "Space" page was a hyperlink that linked the anchored section on the `/team/wranglers` page.

Are we okay with ^ this year? @edrushka

**Comment by edrushka** [comment]
Yes, that works Mavis, and will help keep the Spaces page a little cleaner.

**Comment by edrushka** [comment]
Unblocking this, @mmmavis - I've gotten all the copy I can. Everything still missing will have to come later in separate tickets. Both the top comment in this ticket and the wrangler bios spreadsheet are updated and ready for implementation.
