### ISSUE TITLE
Partners tab

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#655]
https://mozillafestival.org/team/partners

- [ ] Bring this tab back to life!
- [ ] Add 2017 partners

**Comment by edrushka** [comment]
@mmmavis can you please let us know what partners are already there? We'll be keeping many of them.

**Comment by edrushka** [comment]
This page can be updated as soon as the logos are ready.

**Comment by mmmavis** [comment]
<img width="867" alt="screen shot 2017-07-17 at 5 47 11 pm" src="https://user-images.githubusercontent.com/2896608/28295758-02660e68-6b18-11e7-86f2-101d6861b4d9.png">

**Comment by Saallen** [comment]
Hey--
 to be removed-
 UCANTOO, tech girls, Met office and Open leadership institute

**Comment by edrushka** [comment]
Unblocked! This can go live any time - doesn't have to wait until Aug 2.
