### ISSUE TITLE
Rename issue-template.md 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#658]
**[ UUID ]** <%= id %>

**[ Submitter's Name ]** <%= submitterName %>
<% if (typeof(submitterOrg) !== "undefined") { %>**[ Submitter's Affiliated Organisation ]** <%= submitterOrg %><% } %>
<% if (typeof(submitterGithub) !== "undefined") { %>**[ Submitter's Github ]** <%= submitterGithub %><% } %>

<% if (typeof(additionalFacilitators) !== "undefined") { %>**[ Additional facilitators ]** <%= additionalFacilitators %><% } %>

### What will happen in your session?
<%= description %>

### What is the goal or outcome of your session?
<%= outcome %>

<% if (typeof(needs) !== "undefined") { %>
### If your session requires additional materials or electronic equipment, please outline your needs.
<%= needs %>
<% } %>

### Time needed
<%= timeNeeded %>

**Comment by Saallen** [comment]
cc @mmmavis ....weird. The titles from the open call are pre filled when I open a new issue.....

**Comment by mmmavis** [comment]
@Saallen I'm confused about what we are trying to do here. We shouldn't be submitting proposals directly via GitHub. Is there anything on the [program repo](https://github.com/MozillaFoundation/mozfest-program-2017/) that needs fixing?

**Comment by Saallen** [comment]
Hey @mmmavis everytime I open a new issue on this repo- the website- the first comment is automatically filled in with the above text. Yes this should happen in the program repo but not on the website one.....so I take it this is not happening to you? It is happening to @marcwalsh

**Comment by mmmavis** [comment]
@Saallen ahhh gotcha. I didn't realize that. Fixing it now. Thanks for reporting! 😉
