### ISSUE TITLE
Design ideas from Raves Graduate show

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#659]
Hey @sabrinang  I attended the grad show at Ravensbourne and they have some super simple but very effective design ideas for way-finding.  Thought they might be interesting as your start your research. Sorry some of the photos are pretty badly taken ...

**Comment by Saallen** [comment]
These photos are from the entrance foyer to the festival- lots of colour and chaos- looked exciting as you arrived


![imag0439](https://user-images.githubusercontent.com/10194015/28285999-a9f6d4bc-6b2e-11e7-8ab8-482774a78afd.jpg)
![imag0437](https://user-images.githubusercontent.com/10194015/28286001-a9ff1870-6b2e-11e7-99bf-32828b12e1de.jpg)
![imag0438](https://user-images.githubusercontent.com/10194015/28286000-a9f6a0e6-6b2e-11e7-9353-bbc56c7e88e1.jpg)
![imag0441](https://user-images.githubusercontent.com/10194015/28285998-a9f69b00-6b2e-11e7-9e1b-ece175888efe.jpg)

**Comment by Saallen** [comment]
The main stage on the 4th floor and surround balconies
![imag0441](https://user-images.githubusercontent.com/10194015/28286078-e724c556-6b2e-11e7-85ab-180a86d3f987.jpg)

**Comment by Saallen** [comment]
On the floors - colour coded

**Comment by Saallen** [comment]
Nice little other touches

![imag0443](https://user-images.githubusercontent.com/10194015/28286246-724096d8-6b2f-11e7-870d-182d8f8c121d.jpg)
![imag0456](https://user-images.githubusercontent.com/10194015/28286245-723ccd78-6b2f-11e7-9add-4a4ab4eab5f7.jpg)

**Comment by sabrinang** [comment]
Thanks for sharing these photos @Saallen! Wow those streamers have a lot of visual impact :)

**Comment by Saallen** [comment]
@sabrinang they are actually tape
