### ISSUE TITLE
Comma used in Session Proposal 'Other' Language Causing Errors

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#661]
Hello!

Someone who tried to submit a session was given an error whenever they entered "Language 1, Language 2" as the other option on the bilingual question. 

I recreated this myself, it seems to be if there's a comma in that answer the form throws back an error saying "Sorry! We are unable to submit your proposal at the moment. Please try again or contact us."

**Comment by marcwalsh** [comment]
Another person just emailed festival@ with this issue as they were trying to add various languages using commas.

**Comment by mmmavis** [comment]
Thanks for debugging it, @marcwalsh . 😉  I will get to this ticket today!

**Comment by mmmavis** [comment]
This should be fixed by now.
