### ISSUE TITLE
Tickets page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#664]
Staging link: https://mozillafestival-org-sta-pr-665.herokuapp.com/tickets

- [x] Add text to reflect options on ti.to page text below

**Comment by edrushka** [comment]
### MozFest is the world's leading festival for the open internet movement.
#### Join influential thinkers from around the world to build, debate, and explore the future of a healthy internet.

**MozFest Weekend Ticket £45**
Join us for the entire MozFest program of interactive sessions, talks and exhibits. This ticket gains you entry to the full weekend, including the opening Science Fair, evening social events, a networking breakfast, and hundreds of sessions. Lunches and hot drinks are included on Saturday and Sunday. Buy a MozFest Weekend Ticket.

**Friday Night Science Fair Ticket  £10**
Join us for the MozFest opening Science Fair on Friday 27th October from 18:00 - 21:00 for a night of exciting demos, prototypes, networking and drinks. This ticket is valid for entry on Friday evening only.
Buy a Friday Night Science Fair Ticket.

**Youth Ticket £3**
Join us for two days of hacking, building, and crafting at MozFest. This ticket covers entry for Saturday 28th and Sunday 29th October and includes lunch. (Youth tickets must be accompanied by one adult ticket or be part of a school group.) Buy a Youth Ticket.

**Comment by edrushka** [comment]
@mmmavis I tweaked the MozFest Weekend ticket and Youth ticket description in the comment above. These changes have been mirrored on ti.to as well.

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/
