### ISSUE TITLE
Confirmation Emails Not Being Received

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#671]
Hi @mmmavis 

We've had someone email through to the festival@ address saying their issue has been submitted however they haven't received a confirmation email about it. 

The email was releated to this: https://github.com/MozillaFoundation/mozfest-program-2017/issues/308

I tried submitting a couple of tests and didn't receive an email for either also. Would you be able to take a look at this, please?

**Comment by mmmavis** [comment]
@marcwalsh Thanks for reporting! Those emails might have landed in a spam folder. I'm gonna check the error log and see if anything was recorded.

**Comment by mmmavis** [comment]
@marcwalsh the system we are using ([Heroku](https://heroku.com/)) only keeps up to a maximum of 1,500 log lines so unfortunately I'm not able to see what happened to the confirmation email for https://github.com/MozillaFoundation/mozfest-program-2017/issues/308 . However from all the logs I have access to I see no failing message about the confirmation emails so I'm guessing those emails landed in a spam folder. Could you check yours?

**Comment by marcwalsh** [comment]
@mmmavis I've checked but can't see it for either, I also emailed the person who reported it, and it hasn't appeared in theirs either.

**Comment by mmmavis** [comment]
@marcwalsh ah okay. @cadecairos is on PTO today but I've asked him to help us dig into the error logs when he's back.

**Comment by cadecairos** [comment]
The system that was sending these emails experienced a bug where the email address validation check stopped working. As a result of this, all outgoing emails processed by the system were dropped . It appears this happened as early as July 19th.

I've corrected the problem by rotating the API credentials used to validate emails. You should see confirmations now.

**Comment by mmmavis** [comment]
@cadecairos we would like to reach out to people who **did** successfully submit proposals but **did not** get a confirmation email. Is there a way to find out the list of emails from the log?

**Comment by cadecairos** [comment]
Yeah I think I can pull logs for those which failed to send

**Comment by cadecairos** [comment]
(I've shared the list of emails that had confirmations dropped with @mmmavis via MoFo Google Drive)

**Comment by mmmavis** [comment]
@cadecairos thanks!

@marcwalsh there are 287 emails that we need to reach out 😨 Unfortunately there isn't already a script that can help us with batch sending personalized emails. Is it okay if we write a more generic email that points people to the GitHub proposal repo (instead to their individual proposal ticket)? That way we can easily send out that email to 287 people all at once.

/cc @edrushka

**Comment by marcwalsh** [comment]
@mmmavis - How about a good old fashioned mail merge on Thunderbird? If we're able to confirm that almost all of the sessions from the 19th July we could just use the Master Proposal Google Sheet as the data for the merge and only send to those who submitted on the 19th July until the problem was resolved?

**Comment by mmmavis** [comment]
@marcwalsh wow I didn't know about mail merge magic until now! ✨  What kind of meta do you need from the master spreadsheet? I already have the list of emails we should be contacting and I can try writing a script that cross references and extracts meta from the spreadsheet.

- submitter's name
- submitter's email
- link to their GitHub ticket
- title of proposal 

anything else?

**Comment by marcwalsh** [comment]
That sounds like a plan! 👍 

I'll have to do a bit of reading about neatening up links but I think this should be a fairly easy workaround... :)

**Comment by mmmavis** [comment]
@cadecairos do you remember around when you fixed [this](https://github.com/mozilla/mozillafestival.org/issues/671#issuecomment-319397301)? I'd like to know it so I can filter the right set of proposals 😉

**Comment by cadecairos** [comment]
I updated the environment variable that was creating the issue on 2017-08-01  at 14:20:26 UTC

**Comment by cadecairos** [comment]
also, the logs indicate the first email from "festival@mozilla.org" failed to send at 2017-07-27 20:56:15 UTC

**Comment by marcwalsh** [comment]
Emails have all been sent out! 👍 

Thanks for your help @mmmavis and @cadecairos

**Comment by mmmavis** [comment]
🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰
