### ISSUE TITLE
Youth Ticket description edit request

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#674]
On the website we have the following text
MozFest Weekend (Youth)
Join us for two days of hacking, building, and crafting at MozFest. This ticket covers entry for Saturday 28th and Sunday 29th October for youth aged 18 and under. It includes lunch for both days. (Youth tickets must be accompanied by one adult ticket or be part of a school group.)

Can you change the last sentence to be ( Under 16's must be accompanied by one adult ticket or part of a school group) @edrushka

**Comment by edrushka** [comment]
On https://mozillafestival.org/tickets Please change (Youth tickets must be accompanied by one adult ticket or be part of a school group.) to: 

Under 16's must be accompanied by one adult ticket or be part of a school group.

 [^ I intentionally removed brackets).

cc @hannahkane @mmmavis
