### ISSUE TITLE
Update Fringe Form

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#681]
Update fringe form with the following fields:

Name of Event (required)
Date and Time (required)
Event Location (required)
Contact email (required - this will not be published)
Description of your Event (required)
How your event demonstrate one or more of the following characteristics (required) (short answer text box)
- Event is co-designed with partners/allies and community
- Includes creative, hands-on activities
- Facilitation promotes collaboration, innovation and respect
- Designed in the open (e.g. you publish process blogs or have an open curation process) 
- Presents leadership opportunities for all (attendees, mentors, event staff)
- Promotes protects or advances the health of the Internet 
- Includes a code of conduct, ensuring all are welcome to share and be heard

Link to register for the event if available
Privacy Policy checkbox (required)

**Comment by mmmavis** [comment]
@edrushka can you 👀 content & form fields? 

https://mozillafestival-org-sta-pr-666.herokuapp.com/fringe
https://mozillafestival-org-sta-pr-666.herokuapp.com/fringe/success

The form library doesn't allow me to include a hyperlink in the label of the field. I had to change things a bit for the privacy policy checkbox.

One question - Do we wanna add a timezone dropdown?

**Comment by edrushka** [comment]
https://mozillafestival-org-sta-pr-666.herokuapp.com/fringe

- Facilitation promotes collaboration, innovation and respect. should be its own bullet point (currently merged with 2nd bullet)
- 6th bullet should read "Protects or advances the health of the Internet."
- 2-column layout looks great! R+ on that!
- On form field contact email, it should say Contact email (required - will not be made public)
- Final question should read "How does your event demonstrate one or more of the following characteristics?"
- 6th bullet on form question should read "Protects or advances the health of the Internet."

https://mozillafestival-org-sta-pr-666.herokuapp.com/fringe/success
Message should read: Your event will show up on the MozFest Fringe Page after it has been reviewed by our team.


I don't think it needs a timezone box unless we start seeing a lot of remote/virtual events.

**Comment by mmmavis** [comment]
@edrushka what event information do we wanna display on "event card"? Currently I have the following meta displayed

- name of event
- date and time
- location
- link
- description

<img width="409" alt="screen shot 2017-08-08 at 11 27 58 am" src="https://user-images.githubusercontent.com/2896608/29088001-aba9878c-7c2c-11e7-97d5-405849b9483f.png">

**Comment by edrushka** [comment]
Looks good.

**Comment by mmmavis** [comment]
Done: https://mozillafestival.org/fringe Backend spreadsheet has been shared with @Saallen and @edrushka 🍰 🍰 🍰
