### ISSUE TITLE
Further bios to the team page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#682]
Bios to be added to the team page

- Esme Simcox as Production assistant
- Volunteer coordinators x 3 
- Sarah to update her bio

@esmeSimcox will get the bios from the vol coordinators for you @edrushka

**Comment by EsmeSimcox** [comment]
@edrushka Here is my bio, feel free to change it if you would like. 

Esme is the Production Assistant for MozFest 2017. She is still in university studying Digital Television Production at Ravensbourne and has recently produced their Graduate Show. This will be her first MozFest.

I will get a photo to you this evening.

**Comment by EsmeSimcox** [comment]
@edrushka here is Ziggy's Bio for the website and his photo.

“Ziggy is one of the volunteer coordinators for MozFest 2017 and has been involved with the Festival since 2011. As a Mozilla Rep, he focuses on developing the Belgian Mozilla community back home and organizes Mozilla’s yearly presence at Fosdem as well. You’ll most definitely see him running through the venue during the event!”
![ziggy](https://user-images.githubusercontent.com/30292263/29265651-c3ee3782-80d9-11e7-9df4-830ad80af2fa.jpg)

**Comment by EsmeSimcox** [comment]
@edrushka here is Tom's Bio for the website and his photo.

"Tom co-ordinates process, governance and logistics for a number of community teams across Mozilla. With experience in technology and process management, Tom is joining this year's volunteer co-ordinator team. He aims to empower volunteers to feel effective and welcomed over the weekend by bringing in a process and people mindset."
![tom](https://user-images.githubusercontent.com/30292263/29270837-74055a36-80f0-11e7-8c0e-caecf33f3c11.jpg)

**Comment by EsmeSimcox** [comment]
@edrushka Here is @rtsayles Bio for the website and his photo.

"Robby is a Mozilla Rep Mentor based out of Dallas, Texas. He loves volunteering and a big web and aviation feel."
![robby](https://user-images.githubusercontent.com/30292263/29272814-8d3094cc-80f9-11e7-9bbb-2326c604047e.jpg)

**Comment by edrushka** [comment]
Thanks @EsmeSimcox - still waiting on your photo. I'll also need festival job titles for you and these other lovely people.

**Comment by EsmeSimcox** [comment]
@edrushka  I've just uploaded mine onto my comment, sorry for the delay! I am a Production Assistant and Robby, Ziggy and Tom are our Volunteer Coordinators.

**Comment by rtsayles** [comment]
Hi @edrushka , see you soon (smiles)

**Comment by edrushka** [comment]
@hannahkane all the bios and photos are here, so this is ready to implement.

**Comment by mmmavis** [comment]
Hannah is on PTO this week. I'll take this on!

**Comment by mmmavis** [comment]
https://mozillafestival.org/team ✨

**Comment by EsmeSimcox** [comment]
Hi @mmmavis, sorry to keep sending these over to you! We have just had a new member join the MozFest team, Dan Rad, a logistical assistant. Could you please add him to the website? 

Dan Rad is a Logistical Assistant, his 2nd year back with MozFest. Dan has graduated from Ravensbourne with a degree in Digital Television Production and has worked on a variety of short films and TV shows.

<img width="622" alt="screen shot 2017-09-25 at 12 03 52" src="https://user-images.githubusercontent.com/30292263/30805523-aac293ee-a1e9-11e7-8714-e606f76e2c45.png">

**Comment by Saallen** [comment]
swoon DanRad 😍

**Comment by Saallen** [comment]
Wait- why am I only seeing all these great photos now!!!!
@edrushka we need to up our own photo game

**Comment by edrushka** [comment]
@Saallen is "Logistical Assistant" a UK job title? I'd call this a "Logistics Assistant"

**Comment by edrushka** [comment]
@mmmavis please add this to the staff page: Photo is in the comment above.

Dan Rad
Dan Rad is a Logistics Assistant. This is his second year with MozFest. Dan graduated from Ravensbourne with a degree in Digital Television Production and has worked on a variety of short films and TV shows.

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team
