### ISSUE TITLE
Add Artist Open studio to Spaces

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#683]
Here is the approved content for the experience- Artist Open studio @edrushka 
Submitted by Angela -with request for Kevin to copy edit @KevZawacki

Artist Open Stuio
 Decription text  -Ensuring the health of the internet requires a diversity of approaches and voices. Art and design play key roles in engaging new audiences around these social issues and in shaping critical thinking around an open and healthy web. To highlight these artistic perspectives, MozFest, in collaboration with Digital Learning at V&A and Tate, has invited 5 artists to address each of the 5 thematic issue areas of the festival through an installation and on-site lab:

An Xiao Mina (Web Literacy)
Paolo Cirio (Privacy and Security)
Archana Prasad (Decentralization)
Gretta Louw (Open Innovation)
Brooklyn Pakathi (Digital Inclusion)

Participants will be able to engage with the artists in an open lab setting where they will be sharing their artistic practices and developing collaborative work with the public

**Comment by KevZawacki** [comment]
@Saallen Below, a (lightly) edited version:

**Artist Open Studio**
Upholding a healthy internet requires diverse voices and approaches—like art and design.

Art and design play key roles in engaging new audiences around issues like privacy and inclusion, and in shaping critical thinking around a healthy web. To highlight these artistic perspectives, MozFest—in collaboration with Digital Learning at V&A and Tate—has invited artists to address each of the five thematic issue areas of the festival through an installation and on-site lab:

An Xiao Mina (Web Literacy)
Paolo Cirio (Privacy and Security)
Archana Prasad (Decentralization)
Gretta Louw (Open Innovation)
Brooklyn Pakathi (Digital Inclusion)

Participants will engage with the artists in an open lab setting. Artists will share their practices, and also develop collaborative work with the public.

**Comment by edrushka** [comment]
@mmmavis or @hannahkane pls add Kevin's blurb as the description for the Artist Open Studio on https://mozillafestival.org/spaces.

**Comment by hannahkane** [comment]
@mmmavis - I can do this one.

@edrushka - do we have links for the artists?

**Comment by edrushka** [comment]
no, not at this time
