### ISSUE TITLE
Create Speakers page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#685]
We need a place on the site to highlight 2017 speakers and 2016 archived talks. 

Wondering if it makes sense to use the [Team Page](https://mozillafestival.org/team) as a template, and have tabs for each year (let's design this assuming speaker series will continue in 2018 and beyond).

Content for 2017 is already written in the [blog](https://medium.com/mozilla-festival/journalists-activists-hackers-meet-this-years-mozfest-speakers-89018c7d2c97). Content for 2016, including links to talks, could be easily compiled. 

Note that if we built a dedicated page, 2016 speakers should come off the landing page.

What do you think @mmmavis @hannahkane @KevZawacki @Saallen

**Comment by KevZawacki** [comment]
@edrushka Using the Team Page as a template is a great idea!

**Comment by mmmavis** [comment]
This sounds good! But we'll need to tweak how we display the tab selections as the current design doesn't work well on mobile. I had to use very tiny font size for the tab text on [team page](https://mozillafestival.org/team) to fit. @sabrinang any suggestion?

<img width="308" alt="screen shot 2017-08-11 at 11 34 53 am" src="https://user-images.githubusercontent.com/2896608/29227063-34f4bd50-7e89-11e7-9b87-d643a5a875e3.png">

**Comment by edrushka** [comment]
Thanks Mavis and Kevin. @hannahkane flagging this so you can think about assigning a dev. No urgent deadline at this time, but this would be great to have now that we've announced our speakers.

**Comment by mmmavis** [comment]
@hannahkane I can take this on next heartbeat. This will involve some code cleanup + design changes. It shouldn't take more than half a day to implement it.

**Comment by mmmavis** [comment]
Hey @edrushka , (Hannah is on PTO this week) I have bandwidth to work on this this heartbeat. Please give me a ping when copy for 2016 tab is ready. 😉

**Comment by edrushka** [comment]
Text is here: https://docs.google.com/document/d/13BRS4ni2tQmJDF3nHoyrUpZc1-DwqM7L0xx_q5yaKUE/edit

Photos are here: https://medium.com/mozilla-festival/everything-you-need-to-know-about-mozfests-speaker-series-af8eb8f186bf

Note that not all talks have transcripts - only the ones w/links.

**Comment by edrushka** [comment]
Photos are also currently on landing page.

**Comment by mmmavis** [comment]
Live https://mozillafestival.org/speakers

**Comment by KevZawacki** [comment]
🎆

**Comment by edrushka** [comment]
Woooooo! 🎷
