### ISSUE TITLE
Close CFP

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#688]
Friday end-of-day (end of working day, not midnight) we need to close the late proposal form. If we need the URL to point somewhere, it can go here: https://mozillafestival.org/proposals 

@mmmavis anything else we need to do to close the CFP for good?

**Comment by edrushka** [comment]
Clarifying this is Friday August 18.

**Comment by mmmavis** [comment]
@edrushka I think redirecting the late proposal page and other form related pages (e.g., localized forms etc) to /proposals should do.

**Comment by edrushka** [comment]
Perfect! Thank you.

**Comment by mmmavis** [comment]
Done!
