### ISSUE TITLE
Localize 'web for all'

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#690]
Hi @TheoChevalier 

We've confirmed that our visual tagline will be 'Web For All'. You can see some of Sabrina's initial designs [here](https://docs.google.com/presentation/d/1AJuG0G-rOwGLrlT0T2P2VnWBnkT_uSEW6kR9aK7ZqLQ/present#slide=id.g1fad573a30_1_94) (note that these are not final - design work is still very much in progress).

Can you please get started on localizing these in our 3 main languages (French, Spanish, German). I'll have more info on Friday about additional languages.

Thanks!

**Comment by edrushka** [comment]
A note for localizing for design is that if there are multiple options, it would be ideal to go with a translation that is short (i.e. few characters) and/or visually balanced (i.e. each word has similar number of characters). I realize this may not be possible in all languages.

**Comment by edrushka** [comment]
cc @sabrinang

**Comment by TheoChevalier** [comment]
> A note for localizing for design is that if there are  multiple options, it would be ideal to go with a translation that is  short (i.e. few characters) and/or visually balanced (i.e. each word has  similar number of characters). I realize this may not be possible in  all languages.

It is quite unlikely indeed, we may not even have the same number of words. Providing more context around what meaning/message the tagline must carry could help to take a different approach while limiting the risks of carrying a wrong/different message.

**Comment by edrushka** [comment]
This is the simple text that we integrate into several of our design elements (e.g. posters, stickers, stage backdrops and the cover of the printed guide). There's a bit more context, and some examples from previous years, on the first page of [this brainstorm document](https://docs.google.com/document/d/1sU8moda1784OI_762r8oYMmZh2jIpDW-rMGPjLjNdPY/edit#).

**Comment by edrushka** [comment]
@TheoChevalier here's an example of how the localized versions of "web for all" will be used. They'll be combined in a kind of honeycomb pattern, with some blank squares for other people to fill in their languages.

![screenshot 2017-09-06 15 14 25](https://user-images.githubusercontent.com/4515662/30137079-8cdc0a2c-9316-11e7-91bf-b65c6465ef08.png)

**Comment by edrushka** [comment]
L10N tracking dashboard: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_design_assets.lang

**Comment by TheoChevalier** [comment]
@sabrinang Heads up that we will have a design challenge for Chinese as we can’t use italic for this language

Notes from our zh-TW localizer regarding the font:

Font: The glyphs and punctuation marks are different in countries using Han characters, for zh-TW please use fonts with TC suffix (eg. PingFang TC/Heiti TC if the designer is using Mac, or Noto Sans CJK TC/Microsoft Jhenghei on Windows & Linux).

Web for all: 眾人之 Web - Literally "Everyone's Web", can be broken into 眾人<br>之<br>Web. We can keep that in English if it doesn't look good at all

**Comment by edrushka** [comment]
@TheoChevalier this poster is ready for QA: https://redpen.io/ufbe29f9afa00df975

**Comment by TheoChevalier** [comment]
Hindi looks good (French as well)

**Comment by TheoChevalier** [comment]
Peter confirmed Chinese looked good, even with italic
