### ISSUE TITLE
Content: Welcome message

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#693]
- [ ] copy tbd

**Comment by edrushka** [comment]
Draft 1. cc @KevZawacki this is a modified version of Marc's speech bubble. If anything, this is still too long.

-----

Welcome to MozFest!

This year marks our eighth MozFest. It’s also our most ambitious one yet — more than ever, the movement for a healthy Internet needs a place to convene, organize and act.

Today, the concept of Internet health reaches far beyond the realm of open source code: it’s linked to civil liberties and public policy, free expression and inclusion. Discussions about the state of the web include engineers, but now also teachers, lawmakers, community organizers and artists.

The Internet is layered into our lives like we never could have imagined. Access is no longer a luxury — it’s a fundamental part of 21st century life. A virus is no longer a nuisance consigned to a single terminal — it’s an existential threat that can disrupt hospitals, governments and entire cities.

The movement for a healthy Internet is primed to address these problems. But we need a hub to trade ideas, find inspiration, swap code and build solutions.

MozFest is that hub.

Our sessions, speakers and workshops are built to foster collaboration across disciplines, borders and continents. We’re ready to face the biggest issues of the day — from fake news and online harassment to global cyberattacks — together, with an eye toward practical, open source solutions.

The challenges we’re facing are sizeable. But we’re here together to roll up our sleeves and address them head on — then return to our communities, classrooms and computers, better equipped to defend the Internet as a global public resource.

Thank you for joining us.

**Comment by KevZawacki** [comment]
@edrushka This works for me. One small change: "fake news" --> "misinformation."

We're trying to avoid "fake news" because it's become such a loaded, political phrase.

**Comment by edrushka** [comment]
@KevZawacki tweak to include pre-week???

**Comment by KevZawacki** [comment]
@edrushka We should. How about (new copy is bolded):

Welcome to MozFest!

This year marks our eighth MozFest. It’s also our most ambitious one yet — more than ever, the movement for a healthy Internet needs a place to convene, organize and act.

Today, the concept of Internet health reaches far beyond the realm of open source code: it’s linked to civil liberties and public policy, free expression and inclusion. Discussions about the state of the web include engineers, but now also teachers, lawmakers, community organizers and artists.

The Internet is layered into our lives like we never could have imagined. Access is no longer a luxury — it’s a fundamental part of 21st century life. A virus is no longer a nuisance consigned to a single terminal — it’s an existential threat that can disrupt hospitals, governments and entire cities.

The movement for a healthy Internet is primed to address these problems. But we need a hub to trade ideas, find inspiration, swap code and build solutions.

MozFest is that hub.

Our sessions, speakers and workshops are built to foster collaboration across disciplines, borders and continents. **And this year, we're expanding the festival to include pre-week workshops and conferences, an initiative titled MozFest House. It will enable deeper dives and even more collaboration.** 

We’re ready to face the biggest issues of the day — from fake news and online harassment to global cyberattacks — together, with an eye toward practical, open source solutions.

The challenges we’re facing are sizeable. But we’re here together to roll up our sleeves and address them head on — then return to our communities, classrooms and computers, better equipped to defend the Internet as a global public resource.

Thank you for joining us.

**Comment by edrushka** [comment]
That works for me, @KevZawacki 

Do you think we should cut this down at all? I'm suddenly worried this is a lot of text, and will feel like a huge wall of words opening the guide.

**Comment by KevZawacki** [comment]
@edrushka 

Yeah, we could trim. Perhaps:

Welcome to MozFest!

This year marks our eighth MozFest. More than ever, the movement for a healthy Internet needs a place to convene, organize and act.

Today, the concept of Internet health reaches far beyond the realm of open source code: it’s linked to civil liberties and public policy, free expression and inclusion. Access is no longer a luxury — it’s a fundamental part of 21st century life. A virus is no longer a nuisance consigned to a single terminal — it’s an existential threat that can disrupt hospitals, governments and entire cities.

The movement for a healthy Internet is primed to address these problems. But we need a hub to trade ideas, find inspiration, swap code and build solutions.

MozFest is that hub.

Our sessions, speakers and workshops are built to foster collaboration across disciplines, borders and continents. And this year, we're expanding the festival to include pre-week talks and gatherings, an initiative titled MozFest House.

We’re ready to face the biggest issues of the day — from fake news and online harassment to global cyberattacks — together, with an eye toward practical, open source solutions.

Thank you for joining us.

**Comment by edrushka** [comment]
![nice](https://user-images.githubusercontent.com/4515662/30175747-b5b419c8-93b4-11e7-9330-7fd88b2660db.gif)

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----

Welcome to MozFest!

This year marks our eighth MozFest. More than ever, the movement for a healthy Internet needs a place to convene, organize and act.

Today, the concept of Internet health reaches far beyond the realm of open source code: it’s linked to civil liberties and public policy, free expression and inclusion. Access is no longer a luxury — it’s a fundamental part of 21st century life. A virus is no longer a nuisance consigned to a single terminal — it’s an existential threat that can disrupt hospitals, governments and entire cities.

The movement for a healthy Internet is primed to address these problems. But we need a hub to trade ideas, find inspiration, swap code and build solutions.

MozFest is that hub.

Our sessions, speakers and workshops are built to foster collaboration across disciplines, borders and continents. And this year, we're expanding the festival to include pre-week talks and gatherings, an initiative titled MozFest House.

We’re ready to face the biggest issues of the day — from fake news and online harassment to global cyberattacks — together, with an eye toward practical, open source solutions.

Thank you for joining us.
