### ISSUE TITLE
Content: Schedule overview

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#694]
**Friday**
18:00 Science Fair begins 

**Saturday**
9:00-9:30 Welcome and opening
10:00 -11:00 Session block 1
11:15- 12:15 Session block 2 and D&D 1 *note for cassie, some of these sessions are 90 minutes and run to 12:45 - not sure if we can explain this w/out being confusing.
12:00- 14:00 Lunch
12:45- 13:45 D&D 2
13:00 - 13:45 Session block 3
14:00-15:00 Session block 4
15:15- 16:15 Session block 5 and D&D 3
16:30- 17:30 Sessions 6
18:00 Evening activities begin

**Sunday**
09:30 - 10:45 MozFest Breakfast
11:00 - 12:00 Session 7 and D&D 4
12:15 - 13:15 Session 8 *note for cassie, some of these sessions are 90 minutes and run to 12:45 - not sure if we can explain this w/out being confusing.
12:00 - 14:00 Lunch 
12:45- 13:45 D&D 5
14:00 - 15:00 Session 9 
15:15 - 16:15 Session 10 and D&D 6
16:30 - 17:30 Sessions 11
18:00 - Closing Celebration

**Comment by edrushka** [comment]
@KevZawacki can you please edit the above comment to reflect the updated D&D timings? Thanks! :bowtie:

**Comment by KevZawacki** [comment]
@edrushka Sure — updated.

**Comment by edrushka** [comment]
@marcwalsh note we made lunch start at 12:00 on Sunday.

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----

**Friday**
18:00 Science Fair 

**Saturday**
9:00 - 9:30 Welcome and opening
10:00 -11:00 Sessions
11:15- 12:15 Sessions and Dialogues & Debates 
12:00- 14:00 Lunch
12:45- 13:45 Dialogues & Debates 
13:00 - 13:45 Sessions 
14:00 - 15:00 Sessions 
15:15- 16:15 Sessions and Dialogues & Debates 
16:30- 17:30 Sessions
18:00 Evening activities begin

**Sunday**
09:30 - 10:45 MozFest Breakfast
11:00 - 12:00 Sessions and Dialogues & Debates 
12:15 - 13:15 Sessions 
12:00 - 14:00 Lunch
12:45- 13:45 Dialogues & Debates 
14:00 - 15:00 Sessions
15:15 - 16:15 Sessions and Dialogues & Debates 
16:30 - 17:30 Sessions 
18:00 - Closing Celebration
