### ISSUE TITLE
Content: Spaces

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#695]
- [x] Intro blurb about spaces
- [x] Overview of each of the 6 spaces is [here](https://mozillafestival.org/spaces)

**Comment by edrushka** [comment]
@KevZawacki can you put together 1-sentence bios for each

**Comment by KevZawacki** [comment]
These are one-sentence descriptions of Spaces, for use in print materials? 

 Assuming yes... thoughts on the below?

Decentralization | A space for unpacking concepts like mesh networking and blockchain — and conversely, internet shutdowns and closed systems

Digital Inclusion | A space exploring equity, access and participation for _everyone_, all across the web 

Open Innovation | A space for learning about open source, open projects, open code and all other things open

Privacy and Security | A space exploring encryption, VPNs, mass surveillance and safety online

Web Literacy | A space devoted to the skills required to read, write and participate on the web

Youth Zone | A space for youth leaders and their mentors who are creating art, technology and positive social change

**Comment by edrushka** [comment]
I like these short versions. @Saallen are you good to go w/short versions rather than longer copy from the Spaces page?

**Comment by edrushka** [comment]
Confirming short versions are ok 🙆

**Comment by Saallen** [comment]
Hey @KevZawacki I am loving them all, but wonder if Open Innovation could be changed slightly.
I am not sure it fully encapsulates their narrative. 
Could we lose "open source" and add open production??
Just feeling that all things open and open source are too similar and we should show the lenght of the narrative

**Comment by KevZawacki** [comment]
@Saallen Yeah, certainly!

**Comment by edrushka** [comment]
Opening blurb:

Sessions at MozFest are organized into spaces — physical and thematic learning hubs based around a topic of broad relevance to a healthy Internet.

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----
Spaces

Sessions at MozFest are organized under spaces — physical and thematic learning hubs based around a topic of broad relevance to a healthy Internet.

**Decentralization** - A space for unpacking concepts like mesh networking and blockchain — and conversely, internet shutdowns and monopolies

**Digital Inclusion** - A space exploring equity, access and participation for everyone, all across the web

**Open Innovation** - A space for learning about open production, open projects, open code and all other things open

**Privacy and Security** - A space exploring encryption, VPNs, mass surveillance and safety online

**Web Literacy** - A space devoted to the skills required to read, write and participate on the web

**Youth Zone** - A space for youth leaders and their mentors who are creating art, technology and positive social change
