### ISSUE TITLE
Content: Dialogues and Debates

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#696]
- [x] Name, twitter handles, job titles and photos are [here](https://medium.com/mozilla-festival/journalists-activists-hackers-meet-this-years-mozfest-speakers-89018c7d2c97)
- [x] Intro blurb (~1-200 words or less) @KevZawacki 
- [x] Title of talks 
- [x] Timings

**Comment by edrushka** [comment]
@KevZawacki possible to have the rest of this content (intro blurb, titles and timings) by EOD Wednesday?

**Comment by KevZawacki** [comment]
@edrushka 

Sure. We won't have the talk titles anytime soon, but everything else is ready to go.

**BLURB**

Trolls. Misinformation. Efforts to undermine encryption.

These are just a few of the topics this year’s MozFest speakers will explore. Join us as 20 luminaries at the intersection of technology and society discuss bright spots and threats to Internet health. Our speakers hail from eight countries on four continents. They’re activists, journalists, ethical hackers and comediennes.

Speakers deliver 20-minute, TED-style talks throughout the festival weekend. Below, meet each speaker.

**TIMES**

Are all in [our updated Medium blog](https://medium.com/mozilla-festival/journalists-activists-hackers-meet-this-years-mozfest-speakers-89018c7d2c97).

**Comment by KevZawacki** [comment]
@edrushka Do you need anything further to update https://mozillafestival.org/speakers with the times?

**Comment by cassiemc** [comment]
@edrushka @KevZawacki Do you know if there are hi-res versions of the speakers photos available (and we have permissions to use in print?) I collected all the low-res ones here for reference: https://www.dropbox.com/sh/55ojz4y11ehs44o/AADGJXP_G4uz77xSAWh7NuPQa?dl=0

**Comment by KevZawacki** [comment]
Hi @cassiemc @edrushka 

Hi-res speaker headshots can be found [here](https://drive.google.com/file/d/0B-BKZVAww2KHVW51a0d6U2MtMHc/view?usp=sharing
). We can use in print.

**Comment by cassiemc** [comment]
Fantastic, thanks @KevZawacki! Should any of these speakers be emphasized over others, e.g. keynotes? Last year I guess it was all wrangler bios so they were treated uniformly but different treatments might help people know the don't-miss time slots. @edrushka

**Comment by KevZawacki** [comment]
I think we should treat them all equally. We're not planning on billing any as bigger or better than others. @cassiemc

**Comment by edrushka** [comment]
Agree. We do not have any keynotes during the Saturday morning plenary, so all D&D speakers should get equal treatment.

**Comment by edrushka** [comment]
@KevZawacki as I was finalizing this text I noticed it doesn't reference the Q&A. How do you feel about altering the last line of the intro to read:

Speakers deliver 20-minute, TED-style talks, followed by a moderated Q&A.

**Comment by KevZawacki** [comment]
@edrushka Yes, let's. So, here's the updated text:

**Dialogues and Debates**
Trolls. Misinformation. Efforts to undermine encryption.

These are just a few of the topics this year’s MozFest speakers will explore. Join us as 20 luminaries at the intersection of technology and society discuss bright spots and threats to Internet health. Our speakers hail from eight countries on four continents. They’re activists, journalists, ethical hackers and comediennes.

Throughout the festival weekend, speakers deliver 20-minute TED-style talks, followed by a moderated Q&A. Below, meet each speaker and learn when they're presenting.

**TIMES**

(Are all in our [updated Medium blog](https://medium.com/mozilla-festival/journalists-activists-hackers-meet-this-years-mozfest-speakers-89018c7d2c97).)

**Comment by edrushka** [comment]
Great - I'm going to omit the line "Below, meet each speaker and learn when they're presenting." because that might not make sense with the design .

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----
Dialogues and Debates

Trolls. Misinformation. Efforts to undermine encryption.

These are just a few of the topics this year’s MozFest speakers will explore. Join us as 20 luminaries at the intersection of technology and society discuss bright spots and threats to Internet health. Our speakers hail from eight countries on four continents. They’re activists, journalists, ethical hackers and comediennes.

Throughout the festival weekend, speakers deliver 20-minute TED-style talks, followed by a moderated Q&A.

**Comment by edrushka** [comment]
Hi @cassiemc - since you haven't closed this I'll comment here. Please note that Morgan Marquis-Boire will no longer be speaking. The blog w/speaker timings has been updated and I've changed the text in the comment above to read "19 speakers" instead of 20.
