### ISSUE TITLE
Content: Accessible MozFest

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#698]
- [ ] Content TBD

**Comment by edrushka** [comment]
Draft 1 cc @KevZawacki @sedgwickkm (this is for the printed festival guide)

---

Accessible MozFest

At MozFest, accessibility is a vital part of how our network creates an inclusive community. From providing childcare to emphasizing language inclusion to supporting attendees’ diverse physical and cognitive needs, we are increasing our efforts to ensure every that MozFest participant can engage with the people, spaces and themes of the festival.

Visit us at the registration area to learn more.

**Comment by KevZawacki** [comment]
Works for me!

One small edit: "...our efforts to ensure **every that** MozFest participant..." --> "... our efforts to ensure **that every** MozFest participant..."

**Comment by sedgwickkm** [comment]
This looks good to me too.

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----

Accessible MozFest

At MozFest, accessibility is a vital part of how our network creates an inclusive community. From providing childcare to emphasizing language inclusion to supporting attendees’ diverse physical and cognitive needs, we are increasing our efforts to ensure that every MozFest participant can engage with the people, spaces and themes of the festival.

Visit us at the registration area to learn more.
