### ISSUE TITLE
Content: Network for Internet Health

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#699]
Note: This page is currently TBD. Requires concise language.

- [x] short blurb on network

**Comment by edrushka** [comment]
@KevZawacki Do we have a ~150 description of the network suitable for MozFest audiences?

**Comment by KevZawacki** [comment]
@edrushka How about:

The Mozilla Network* fights to keep the web decentralized, open and free. In short: We protect the health of the Internet.

The “we” behind this network isn't just Mozilla — it’s a far larger group. There are technologists, yes. But also educators, artists and activists, hailing from Cape Town, Chicago, Shenzhen, Berlin and beyond.

Members of the Network understand that three-and-a-half billion people — and counting — now live their lives on the Internet. We understand the opportunity the Internet unlocks — and, conversely, the dangers of mass surveillance, insecurity and centralization. We understand that a positive future depends on a healthy Internet.

These fights will be fought across borders, in legislatures, at protests, online and in person. And they will influence everything from public policy to free expression and consumer technology. Now more than ever, we need a Network.

_*No official name yet, so not sure what we'd want to say. CLaw can advise._

**Comment by hannahkane** [comment]
cc @jessevondoom @Sydette

**Comment by edrushka** [comment]
Jesse and Sydette: for context, this is copy for a page in the MozFest printed festival guide. We don't _need_ to include this page, but I thought it might be useful and relevant to the MozFest audience. The firm deadline for finalizing this content is Sept. 15.

**Comment by KevZawacki** [comment]
@edrushka @jessevondoom @Sydette

Alternative: We can simply use the Mozilla Foundation boilerplate, [here](https://www.mozilla.org/en-US/foundation/). Might be easier.

**Comment by edrushka** [comment]
@jessevondoom @Sydette I need to move your deadline on this ahead to Sept 13, since Sarah and I need a day to review everything that's going in the guide before the 15th. Thanks.

**Comment by jessevondoom** [comment]
I'll have this tomorrow!

**Comment by jessevondoom** [comment]
This probably needs a clean-up from @KevZawacki but here's a blurb I stole from a few places and tried to get more of the Internet Health / network framing into things:

> The Internet is a vital global resource, connecting billions of us to the people, places, and ideas that matter to us. We come together to learn, share, and collaborate online. There is a movement for a Internet health that is larger than Mozilla and we fuel it by supporting individuals and communities who lead in that space. 

The nonprofit Mozilla Foundation believes the Internet must always remain a global public resource that is open and accessible to all. Our work is focused on helping that movement for a healthy Internet grow and thrive. Our communities connect to form a rich network filled with technologists, teachers, artists, and so many more — all focused on an Internet that is decentralized, inclusive, secure, open, and understandable for all.

**Comment by KevZawacki** [comment]
Thanks, @jessevondoom & @edrushka. I trimmed a bit:

> The Internet is a vital global resource, connecting billions of us to the people, places, and ideas that matter most. Online, we come together to learn, share, and collaborate. 
> 
> Today, there is a growing movement for a Internet health — a movement to keep the web decentralized, inclusive, secure, open, and understandable. Mozilla fuels this movement by supporting its leading individuals and communities. We connect and empower these leaders to form a rich network of technologists, teachers, artists, activists, and many more.

**Comment by edrushka** [comment]
Do we want any kind of link? e.g. "Join us at _____"?

**Comment by cassiemc** [comment]
@edrushka +1 I think a call to action would really help here. It's kind hard to know why this blurb is nestled in with the rest of the content, otherwise? Unless we're thinking of it as some kind of endorsement? An ethos or principle?

**Comment by jessevondoom** [comment]
@cassiemc @edrushka Makes sense to me. Maybe just "Join us and learn more at https://network.mozilla.org/"

**Comment by cassiemc** [comment]
wfm, thanks!

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----

A Network for Internet Health

The Internet is a vital global resource, connecting billions of us to the people, places, and ideas that matter most. Online, we come together to learn, share, and collaborate.

Today, there is a growing movement for Internet health — a movement to keep the web decentralized, inclusive, secure, open, and understandable. Mozilla fuels this movement by supporting its leading individuals and communities. We connect and empower these leaders to form a rich network of technologists, teachers, artists, activists, and others.

Join us and learn more at network.mozilla.org
