### ISSUE TITLE
Content: Working open

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#700]
Note: This page needs better title

- [ ] blurb on working open and how to carry work forward after MozFest

**Comment by edrushka** [comment]
Draft 1  cc @acabunoc @zee-moz - this is copy for the printed MozFest guide. I modified content from the OL101. Let me know if you have feedback!

--------------

**How to work open**

The Internet— a dynamic, complex, interconnected ecosystem of people, ideas, information— thrives when we collaborate and share information and skills widely and freely.

If you’re new to working open, here are three principles to get you started:

**Share decision-making.** Encourage contributors to participate meaningfully in the decision-making process and help shape the direction of the project.

**Share resources.** Distribute code and content widely and freely, allowing others to build on your project and maximizing its usefulness for all.

**Invite participation.** Welcome as many diverse perspectives into the community as possible, and find ways to let anyone who’s interested pitch in— your project will be better, more powerful and more useful for it.

Interested in diving deeper? mzl.la/open-leadership

**Comment by zee-moz** [comment]
@edrushka looks good. I might just switch around the order-- I think we ended up ordering the principles that way because that's how they appeared in the flow of Mark's story, but it makes much more sense to say:

1. Invite participation
2. Share decision-making
3. Share resources. 

Because it's harder to share decision-making if you don't have participants! @acabunoc what do you  think?

**Comment by acabunoc** [comment]
+1 changing the order

After some our convos w/ the MIT folks, should we change 'Invite participation' to 'Design for participation'?

**Comment by edrushka** [comment]
cc @chadsansing

**Comment by edrushka** [comment]
Draft 2: [changed order of items]

**How to work open**

The Internet— a dynamic, complex, interconnected ecosystem of people, ideas, information— thrives when we collaborate and share information and skills widely and freely.

If you’re new to working open, here are three principles to get you started:

1) Invite participation. Welcome as many diverse perspectives into the community as possible, and find ways to let anyone who’s interested pitch in— your project will be better, more powerful and more useful for it.

2) Share decision-making. Encourage contributors to participate meaningfully in the decision-making process and help shape the direction of the project.

3) Share resources. Distribute code and content widely and freely, allowing others to build on your project and maximizing its usefulness for all.

Interested in diving deeper? mzl.la/open-leadership

**Comment by chadsansing** [comment]
@edrushka - I don't think we'll have settled on map language ahead of the milestone for this, so if it works for others, no blockers from me.

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----

How to Work Open

The Internet— a dynamic, complex, interconnected ecosystem of people, ideas, information— thrives when we collaborate and share information and skills widely and freely.

If you’re new to working open, here are three principles to get you started:
1. Invite participation. Welcome as many diverse perspectives into the community as possible, and find ways to let anyone who’s interested pitch in— your project will be better, more powerful and more useful for it.
2. Share decision-making. Encourage contributors to participate meaningfully in the decision-making process and help shape the direction of the project.
3. Share resources. Distribute code and content widely and freely, allowing others to build on your project and maximizing its usefulness for all.

Interested in diving deeper? Visit mzl.la/open-leadership
