### ISSUE TITLE
Content: MozFest House

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#701]
Content for this page still TBD

- [ ] blurb on pre-week 
- [ ] rough schedule of events, or link to full schedule
- [ ] some of the participating orgs

**Comment by edrushka** [comment]
cc @Saallen @KevZawacki

**Comment by edrushka** [comment]
Kevin, please add pre-week copy for guide to this ticket

**Comment by KevZawacki** [comment]
Hi @edrushka, suggested pre-week copy [here](https://docs.google.com/document/d/18Wuzj1zLx5o1gvEIWcnf4xw0BfNYPjKqjS6jYaOyqxY/edit?ts=59aee05e).  

Do we need a shorter version for print materials?

**Comment by edrushka** [comment]
Yes, we def. need a shorter version. The first four paragraphs could work, and we could either have a single sentence listing the events, or a very simple schedule in a table like the [Weekend Outline.](https://mozillafestival.org/expect)

**Comment by KevZawacki** [comment]
@edrushka I like the first 4 paragraphs + a Weekend Outline-type table.

**Comment by edrushka** [comment]
@Saallen how do you feel about a table for Mon-Fri with each *public* event listed (not the times and details, just the name of the event) and one link underneath the table pointing to website for time/details/ticketing.

**Comment by edrushka** [comment]
This is obviously completely undesigned, but here's the amount of text we're looking at if we include a description of each event in the Guide.




![screenshot 2017-09-08 14 32 34](https://user-images.githubusercontent.com/4515662/30232142-1f380a5a-94a3-11e7-8c2c-cd193bab6bf3.png)

@Saallen I feel this is too much text for the guide (we're getting really tight on space), plus I am nervous about the event info or schedule changing after we go to print. What are your thoughts on listing some of the events in sentence form instead, e.g.

Join us for MisinfoCon London, an event exploring solutions to misinformation online; Detox & Defend for Women, an online privacy workshop for women; a Journalism Tech Unconference; and much more. See a full schedule of MozFest House events at mozfest.org/house

**Comment by edrushka** [comment]
So to clarify, the MozFest House entry in the festival guide would read:

MOZFEST HOUSE
 
Sometimes, the MozFest weekend just isn’t enough.
 
Introducing MozFest House: our central London venue that extends MozFest into a week-long festival.
 
From Monday 23rd - Friday 27th October, MozFest participants are invited to dig deeper into their work, trade ideas, swap code, and build solutions.
 
MozFest House features films, workshops, conferences, and talks, all focusing on Internet health and showcasing the diversity of the Mozilla network. 
 
Join us for MisinfoCon London, an event exploring solutions to misinformation online; Detox & Defend for Women, an online privacy workshop for women; a Journalism Tech Unconference; and much more. See a full schedule of MozFest House events at mozfest.org/house.

**Comment by Saallen** [comment]
In agreement @edrushka that a table is too much information
I dont think we event need information on the events. I wouldnt be against removing "Join us for MisinfoCon London, an event exploring solutions to misinformation online; Detox & Defend for Women, an online privacy workshop for women; a Journalism Tech Unconference; and much more."

I think it could read


MOZFEST HOUSE

Sometimes, the MozFest weekend just isn’t enough.

Introducing MozFest House: our central London venue that extends MozFest into a week-long festival.

From Monday 23rd - Friday 27th October, MozFest participants are invited to dig deeper into their work, trade ideas, swap code, and build solutions.

MozFest House features films, workshops, conferences, and talks, all focusing on Internet health and showcasing the diversity of the Mozilla network.
See a full schedule of MozFest House events at mozfest.org/house.

**Comment by edrushka** [comment]
Perfect. I think this is good for the guide :1st_place_medal:

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----

MozFest House 

Sometimes, the MozFest weekend just isn’t enough.

Introducing MozFest House: our central London venue that extends MozFest into a week-long festival.

From Monday 23rd - Friday 27th October, MozFest participants are invited to dig deeper into their work, trade ideas, swap code, and build solutions.

MozFest House features films, workshops, conferences, and talks, all focusing on Internet health and showcasing the diversity of the Mozilla network.

See a full schedule of MozFest House events at mozillafestival.org/house
