### ISSUE TITLE
Content: Sponsors

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#702]
- [ ] blurb thanking our sponsors
- [ ] sponsor logos

**Comment by cassiemc** [comment]
Don't forget, vector logos (svg, eps, ai) or hi-res where possible :)

**Comment by cassiemc** [comment]
@edrushka I don't see any sponsor pages in last year's guide. Any idea of how many there will be? Will they need to be tiered?

**Comment by edrushka** [comment]
Yes, this is a new page. We didn't have an official sponsorship program last year.

Let's work on the tiering in [this private google doc](https://docs.google.com/document/d/1unimp4LxiOa2tLOEUAFmWlLFktuNzoRYwUc9Sh_-Y_g/edit), since not all the contracts have been finalized so I don't want share prematurely on Github. @jcbarajas is our awesome new director of fundraising. Juan, can you please help tier these organizations? The don't fit very neatly into categories ;)

**Comment by cassiemc** [comment]
Just a note that there is no blurb here saying thanks, that I can see, just the listed names. So I'll go with what we have! @edrushka
