### ISSUE TITLE
Content: Participation guidelines

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#703]
- [x] short version of participation guidelines:

#### OLD VERSION
The Mozilla Festival respects Mozilla's community participation guidelines. These guidelines cover our behaviour as participants, facilitators, wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

**How to treat each other:**
Be respectful and welcoming
Try to understand different perspectives
Do not threaten violence
Empower others
Strive for excellence
Don‘t expect to agree with every decision

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org

#### UPDATED VERSION FOR 2017

The Mozilla Festival respects Mozilla's community participation guidelines. These guidelines cover our behaviour as participants, facilitators, wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

How to treat each other:
Be respectful and value each other’s ideas, styles and viewpoints.
Be direct but professional; we cannot withhold hard truths.
Be inclusive and help new perspectives be heard.
Appreciate and accommodate our many cultural practices, attitudes and beliefs.
Be open to learning from others.
Lead by example and match your actions with your words.

The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org or call xxxxxxxxx

**Comment by edrushka** [comment]
@marcwalsh please add emergency phone number when we get it

**Comment by edrushka** [comment]
@Saallen @marcwalsh @KevZawacki do we want to use the same short version of the participation guidelines that we used last year (see the first comment) or should we revise them to reflect Mozilla's [updated participation guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/)? I've taken a first crack here at what this might look like:

-------

Be respectful and value each other’s ideas, styles and viewpoints. 
Be direct but professional; we cannot withhold hard truths.
Be inclusive and help new perspectives be heard.
Appreciate and accommodate our many cultural practices, attitudes and beliefs.
Be open to learning from others.
Lead by Example and match your actions with your words.

The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org or call xxxxxxxxx

**Comment by KevZawacki** [comment]
@edrushka Hm. If there's been an update, perhaps we should go with the new ones you've penned.

**Comment by Saallen** [comment]
Hey @edrushka Looking good and agree with Kevs comment.

**Comment by Saallen** [comment]
What do folks think about changing this line, (or creating a second version) so we can share these guidelines with all Mozilla festival events, MozFest house and fringe?
The following will not be tolerated at MozFest *TO* The following will not be tolerated at Mozilla festival or affiliated events xxxx please contact the information desk or [insert email ] - sorry know this is complicated here but  trying thinking more broadly

**Comment by edrushka** [comment]
Sure, we can do all of those things:
- a sharable version that people can use for their Fringe event 
- a MozFest version for the festival guide and posters
- a MozFest House version for posters that says "The following will not be tolerated at MozFest House"

**Comment by edrushka** [comment]
This short version has been approved by Larissa from the D&I team so let's call it locked! ✋ 😁

**Comment by marcwalsh** [comment]
@edrushka I've updated this with the correct telephone number which is ready for use! 💃

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----

The Mozilla Festival respects Mozilla's community participation guidelines. These guidelines cover our behaviour as participants, facilitators, wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

How to treat each other:
Be respectful and value each other’s ideas, styles and viewpoints.
Be direct but professional; we cannot withhold hard truths.
Be inclusive and help new perspectives be heard.
Appreciate and accommodate our many cultural practices, attitudes and beliefs.
Be open to learning from others.
Lead by example and match your actions with your words.

The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org or call +44 (0) 207 855 3030.
