### ISSUE TITLE
Closing Issues and Rejecting Sessions

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#705]
Hi @mmmavis - So this is what we're thinking on how to reject sessions on GitHub.

- [x] **Export Standard Rejection Spreadsheet - Open Issues with No Milestone & No Gold Star Label**
   (7th September)
   * Session Name
   * Email
   * Personal Name
- [x] **Export 'Gold Star' Rejection Spreadsheet - Open Issues with No Milestone & Gold Star Label**
   (7th September)
   * Session Name
   * Email 
   * Personal Name
- [x] **Create a script to auto comment and close unsuccessful submissions (proposals with no milestone).**
   (8th September)

Let me know if this makes sense. :)

**Comment by marcwalsh** [comment]
@mmmavis - Am I also able to get access to the repo to add labels etc please?

**Comment by edrushka** [comment]
I think I just gave you access Marc. Let me know if that didn't work.

**Comment by marcwalsh** [comment]
Thanks @edrushka 

I've updated the order for the tasks. As we've closed some issues for being duplicates if we can export only open issues and then go ahead with the bulk close after this.

**Comment by mmmavis** [comment]
@marcwalsh could you put down the date that each action item needs to be completed by/on? I don't wanna accidentally bulk close tickets 😂 .

**Comment by marcwalsh** [comment]
@mmmavis Sure! All updated in the ticket :)

**Comment by mmmavis** [comment]
@marcwalsh thanks! I will start working on the script this week. Do we already know what we want the mozfest-bot (the same GitHub account that created tickets on the proposal repo) to comment on those unsuccessful submissions? Not a blocker for me to start working on the script atm but I'll need to have the final copy by end of September 5 to get everything going 🚗 .

**Comment by marcwalsh** [comment]
Thanks @mmmavis 

Just tagging @Saallen and @edrushka about the copy, here's what I suggest below based on last year's.

```
Thank you for taking the time to submit a session to MozFest. Unfortunately, we’re unable to accept your session proposal into this year’s program.  We’ve also sent you more information to the email address you used when submitting.
```

**Comment by Saallen** [comment]
Thank you for taking the time to submit a session to MozFest. Due to the high level of submissions, we’re unable to accept all proposals and unfortunately, your session was not part of the final group.
Thank you for taking the time to submit and we will follow up on email very soon

**Comment by marcwalsh** [comment]
@mmmavis - this is the confirmed copy by Sarah:

_Thank you for taking the time to submit a session to MozFest. Due to the high level of submissions, we’re unable to accept all proposals and unfortunately, your session was not part of the final group.
Thank you for taking the time to submit and we will follow up on email very soon._

We'll send out the mail merge using Thunderbird for standard responses and by Ti.To's RSVP feature for the highlighted sessions. Copy is being confirmed in #729. 

Thanks! :)

**Comment by mmmavis** [comment]
Awesome! @marcwalsh scripts are almost ready! 🎉  Just to confirm again I should run the script to handle action item 1 & 2 on September 7th PDT and run script for action item 3 on September 8?

**Comment by Saallen** [comment]
Hey @mmmavis please dont run until we confirm on the day- We have some last minute issues that should be cleared but end of day 7th but let me update here on the day

**Comment by mmmavis** [comment]
@Saallen alright I'll wait for the ping!

**Comment by mmmavis** [comment]
My script was flagged by GitHub as spammer not long after it started commenting/closing tickets.  😭 I should've scheduled each posting action with some delay next time. Oh well lesson learnt! Had to manually comment on tickets the script didn't get to but at least this work is ALL DONE NOWWWWWWWWWW 🎉 🎉 🎉 

@marcwalsh I've shared a Google Spreadsheet with you. It should have all the contact info you need.

**Comment by Saallen** [comment]
Oh no! How many did you end up commenting on? Next time for fiddly manual
actions wait for us, we can definitely jump in and help
But totally appreciate that you saw it through!b thanks!!

S
