### ISSUE TITLE
Dyslexia-friendly version of festival guide

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#709]
Festival guide content is [here](https://github.com/mozilla/mozillafestival.org/issues/691). When copy is finalized (after Sept 15) we can create a dyslexia-friendly version using [these guidelines ](http://www.bdadyslexia.org.uk/common/ckeditor/filemanager/userfiles/About_Us/policies/Dyslexia_Style_Guide.pdf)published by the British Dyslexia Association.

These will be printed on a regular office printer before the festival, and made available at the accessibility table at registration.

cc @sedgwickkm

**Comment by sedgwickkm** [comment]
Draft here: https://docs.google.com/document/d/1MRHH3g01wMpof2TS1sS3txiiPbFFdLP6zOiFBhJSNos/edit?usp=sharing

**Comment by edrushka** [comment]
We are done drafting the dyslexia-friendly version of the guide: https://docs.google.com/document/d/1MRHH3g01wMpof2TS1sS3txiiPbFFdLP6zOiFBhJSNos/edit?usp=sharing

**Comment by edrushka** [comment]
WIP here: https://www.dropbox.com/s/p8bb4ul7xb2w2mf/Dyslexia%20friendly%20guide.indd?dl=0
