### ISSUE TITLE
create Media Center page on mozfest.org

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/mozillafestival.org#716]
We'd like to create a Media Center webpage on mozfest.org — a place where journalists planning to cover/attend can get their bearings.

Just simple text, nothing more. It would have a unique URL and, ideally, be linked to from the site footer.

[Here is the copy](https://docs.google.com/document/d/1cg9HdKeG_KOjffS4EZiLdyNMxIoA1gtVq9mmWXHOL84/edit#).

@edrushka What else can I do to help?

**Comment by edrushka** [comment]
@KevZawacki do we have any press-related pics we could use for the hero banner?

**Comment by KevZawacki** [comment]
@edrushka How about either

(1) A screenshot of a press story. I like [this one](https://elpais.com/tecnologia/2016/10/31/actualidad/1477905484_625075.html) (and not just because we're in it):

![screen shot 2017-08-25 at 8 47 14 am](https://user-images.githubusercontent.com/11045250/29714622-02a2f8e6-8972-11e7-9f4d-65d64668a3b8.png)

or a boilerplate MozFest photo, like [this one](https://www.flickr.com/photos/mozfest/30548994561/in/album-72157672259755823/).

**Comment by edrushka** [comment]
Kev, you totally just want us featured more on the website 😆 I think the screenshot might be a little busy for a hero banner but let's get @sabrinang's advice. Can you help us find a hero banner image for the new media page?

**Comment by sabrinang** [comment]
I like Kevin's 2nd choice: https://www.flickr.com/photos/mozfest/30548994561/in/album-72157672259755823/ over the screenshot (which has lots of legible text for a cover photo)

We might also try some more behind-the-scene media photos such as:
https://www.flickr.com/photos/mozfest/30601424636/in/album-72157672259755823/
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2492510/29726914-985f9cae-8986-11e7-83d9-b27e3cd565e8.png">

https://www.flickr.com/photos/mozfest/30639984325/in/album-72157672259755823/
<img width="777" alt="image" src="https://user-images.githubusercontent.com/2492510/29726897-88553620-8986-11e7-9fe2-18858c266104.png">

**Comment by KevZawacki** [comment]
@sabrinang Oh! I love the second photo you recommended!

**Comment by edrushka** [comment]
Me too!!!

**Comment by edrushka** [comment]
@mmmavis can you please build this page when you are able?

Content [here](https://docs.google.com/document/d/1cg9HdKeG_KOjffS4EZiLdyNMxIoA1gtVq9mmWXHOL84/edit#)
Hero banner image being worked on [here](https://github.com/MozillaFoundation/mozfest-design-2017/issues/22)
Link can go on bottom footer between Participation Guidelines and Terms. Link text = Media.

**Comment by mmmavis** [comment]
@edrushka @KevZawacki what's the url we want this page to be on? `mozillafestival.org/media`?

**Comment by edrushka** [comment]
Yes, that works.

**Comment by mmmavis** [comment]
@sabrinang can you suggest what icon we can use for the "Media" link on footer?
<img width="838" alt="screen shot 2017-08-28 at 4 49 53 pm" src="https://user-images.githubusercontent.com/2896608/29798291-0df4ef5a-8c11-11e7-819c-cb49c91b6097.png">

Icon should come from `mofo-boostrap` as we are aiming to have consistent footer style across MoFo sites. See the icon selection [here](https://mozilla.github.io/mofo-bootstrap/demo/). If none of the existing icons works we can easily add new icons to mofo-bootstrap but I'd suggest looping in other MoFo designers before we do so.

**Comment by KevZawacki** [comment]
@mmmavis I'm OK using the 'info' icon — unless having two of the same icons in a footer is bad practice?

**Comment by mmmavis** [comment]
@KevZawacki sounds good to me! 👍 

@sabrinang can you give me a ping when the hero image has been processed? Thanks!

**Comment by mmmavis** [comment]
https://mozillafestival.org/media 🎤 🖊 📷 🎥

**Comment by edrushka** [comment]
ohhhh the hero image looks great!

Mavis, are we moving away from pink text on white background? I forget where we landed on that after our a11y research.

**Comment by mmmavis** [comment]
@edrushka https://github.com/mozilla/mozillafestival.org/issues/706#issuecomment-325508041 we tried using blue text instead pink but that colour looked too dull as a highlighting colour. Looks like we are still finding a better highlighting colour to switch to.

**Comment by edrushka** [comment]
Ok great - not a blocker for this page. Thanks for the update!

**Comment by edrushka** [comment]
@KevZawacki does this page meet your needs?

**Comment by KevZawacki** [comment]
@edrushka @mmmavis 

This is fantastic! Thank you for the very quick work.

One minor tweak (that's not at all urgent). Can we update the first sentence of the second paragraph to:

To receive press credentials to attend and cover MozFest; to request information and photos; or to arrange an interview with Mozilla executive director Mark Surman, contact Corey Nord at corey(at)pkpr.com.

**Comment by mmmavis** [comment]
@KevZawacki sorry didn't see your comment until now. I can make this adjustment today. 👍

**Comment by mmmavis** [comment]
updated!
