### ISSUE TITLE
Add Kirstie as wrangler

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#717]
Please add Kirstie Whitaker to the Open Innovation team on both the [Spaces](https://mozillafestival.org/spaces) and [Team](https://mozillafestival.org/team/wranglers) pages. You can put her in alphabetical order after Phillip.

Bio, handle and photo are [here](https://docs.google.com/spreadsheets/d/1RyDQ1BF3gYLMj9Koy9gqEbB_LQoQQa0opVLfOgNzt_I/edit#gid=0) on the spreadsheet.

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team/wranglers#Kirstie-Whitaker

**Comment by edrushka** [comment]
Whoa! That was lightening fast! ⚡️ Thanks Mavis!

cc @auremoser

**Comment by auremoser** [comment]
Awesome, thank you @mmmavis !
