### ISSUE TITLE
Localize "welcome"

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#720]
@TheoChevalier is there an existing resource that has the word "welcome" localized in many different languages? If so, @sabrinang can refer to this for the design of the big welcome sign.

**Comment by TheoChevalier** [comment]
Yes, I actually have two options: “Welcome” and “Hello!”, but we have more languages with the former.

Welcome: https://transvision.mozfr.org/string/?entity=mobile/android/base/android_strings.dtd:firstrun_panel_title_welcome&repo=central

Hello: https://transvision.mozfr.org/string/?entity=mozilla_org/mozorg/contribute/index.lang:ba74ea1a&repo=mozilla_org (With some html to strip in French)

For obvious reasons, the choice of font will be important and probably limited. Let me know if you have questions.

Note that there’s also a JSON format at the bottom of the page if needed: https://transvision.mozfr.org/api/v1/entity/central/?id=mobile/android/base/android_strings.dtd:firstrun_panel_title_welcome

**Comment by edrushka** [comment]
This is PERFECT! Thank you!! 🌻

**Comment by edrushka** [comment]
@sabrinang when you have this design ready, Theo will share it with the L10N mailing list to QA the fonts. Please tag him when you post the design.
