### ISSUE TITLE
Content: Curated Programming

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#725]
- [ ] Blurb on each of the themes (Policy/Advocacy, Journalism, and Youth Led) and wranglers

- may be possible to combine with Artist Open Studios page or Spaces page

**Comment by edrushka** [comment]
@Saallen do we have 1-2 line descriptions written down anywhere?

**Comment by edrushka** [comment]
@Melechuga @emrysgreen @erikao is it possible for you to write a 1-2 sentence description about what theme(s) your curated sessions will explore that I can include in the printed festival guide? Thanks!

**Comment by Saallen** [comment]
Follow a topic of interest across the program and the floors such as Advocacy and Policy, Journalism or Youth Led sessions

**Comment by edrushka** [comment]
Draft 2

**Curated Programming**
MozFest 2017 features three curated topics that allow you to explore each of the festival's spaces through a particular lens.

Policy and Advocacy: What does copyright have to do with the internet? Is the internet a public utility? Why is my biometric data needed so I can buy a bag of rice? And what can I do about this? These big questions - an more - will be explored in the Policy and Advocacy sessions.

Journalism: [tbd]

Youth-led: [tbd]

**Comment by Melechuga** [comment]
@edrushka @Saallen Thanks for kicking this off; I've added my blurb below. Can we call it "Open Policy + Advocacy"?
Open Policy + Advocacy: How is the internet being shaped by governments and corporations? What can we do to ensure it stays open? Come share ideas with leaders in the movement, and let's explore big questions together.

**Comment by emrysgreen** [comment]
Sorry for the delay guys.  How's this as a starter?

Youth Led: Young People aged 8-25 teach, discuss and explore the internet health topics using Robots, VR, Dance, Coding, Social Media, Gaming and more.  Supported by Arts Award, join the demonstrations, exhibitions and learning opportunities.

**Comment by edrushka** [comment]
Simplified version: In these sessions, young people aged 8-25 teach, discuss and explore robots, VR, dance, coding, social media, gaming and more.

**Comment by edrushka** [comment]
Journalism: These sessions explore innovation on the open web, from infrastructure like Django to engaging data visualisations and insightful data analysis. Join us in exploring strategies and tools for multimedia, accessibility, security, and more.

**Comment by edrushka** [comment]
To discover these sessions, search the schedule app using the labels Open Policy & Advocacy, Journalism and Youth-Led.

**Comment by emrysgreen** [comment]
Thanks @edrushka .  Is there a way of adding "Supported by Arts Award" in there somehow just as a nod to the time & travel costs that they're funding under this strand?

**Comment by edrushka** [comment]
Hey @emrysgreen - I don't think this spot is the best way to highlight Arts Award's generous contributions. This page of the guide is dedicated to highlighting program elements, and is not the right place for individual or organizational plugs.

**Comment by emrysgreen** [comment]
Ok cool, sure thing.


Emrys Green MInstLM LCGI FRSA BA(Hons)
www.cloudartisans.co.uk
07905 253099

Please consider the environment when printing this email.  Please refer to the sending domain's terms and conditions for Email usage & data protection.  The views expressed are that of the sender and not of the organisation represented.

On 14 Sep 2017, at 21:33, Erika Drushka <notifications@github.com> wrote:

Hey @emrysgreen - I don't think this spot is the best way to highlight Arts Award's generous contributions. This page of the guide is dedicated to highlighting program elements, and is not the right place for individual or organizational plugs.

**Comment by edrushka** [comment]
@cassiemc - confirming this is final text. Please close this ticket when you've copied this to your working doc.

-----

Curated Programming

MozFest 2017 features three curated topics that allow you to explore each of the festival's spaces through a particular lens. To discover these sessions, search the schedule app using the labels Open Policy & Advocacy, Journalism and Youth-Led.

Journalism: These sessions explore innovation on the open web, from infrastructure like Django to engaging data visualisations and insightful data analysis. Join us in exploring strategies and tools for multimedia, accessibility, security, and more.

Open Policy + Advocacy: How is the internet being shaped by governments and corporations? What can we do to ensure it stays open? Come share ideas with leaders in the movement, and let's explore big questions together.

Youth-Led: In these sessions, young people aged 8-25 teach, discuss and explore robots, VR, dance, coding, social media, gaming and more.
