### ISSUE TITLE
Photography: Shot List for Photographer

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#727]
### Description:
MozFest photo albums have been a useful resource year round. We can use it as an opportunity to let the photographer know if we want them to capture any specific shot we can use for other things or to document anything specific (like swag last year).

**Comment by sabrinang** [comment]
Oops I meant to file this in the design repo but I'll just leave it here

**Comment by Saallen** [comment]
* Artist open studio
* Sponsor logo positioning
* different types of sessions

**Comment by sabrinang** [comment]
We are brainstorming a shot list here: https://docs.google.com/a/mozilla.com/document/d/1WCZnh6XHFUA1NhXqvZ6XkbKzduXWS2QSJ9z4wPt3kpA/edit?usp=sharing

@taisdesouzalessa @natalieworth are also contributing ideas they would like to use for network and fundraising projects etc.

**Comment by sabrinang** [comment]
We shared the doc with Erik W 👍

**Comment by sabrinang** [comment]
## Post-MosFest Documentation
Photos by Erik Westra: https://westraco.pixieset.com/mozfest2017/
I have taken some photos as well: https://drive.google.com/open?id=1yPdvbAbR6g7tvle9rA2hiaLTLeOgsMuY

I sat down with Erik W to go over the shot list Friday afternoon of MozFest weekend and after MozFest was complete we discussed what swag shots we wanted on the lightbox. He separated the albums (promo, signage + swag) which was helpful!
