### ISSUE TITLE
Rejection Email for Submissions

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#729]
We need two rejection emails for after the close of curation, which we will send to all that have had their milestone removed. Full process listed in #705 

- [x] Standard Copy for Rejecting Submissions
- [x] Copy for Highlighted Sessions

--

Last year's copy is below, last year we offered all submissions a ticket, however this year we are only offering to sessions that have been flagged.

Update on your Mozfest proposal

Hi there, 

Thanks so much for submitting a session for MozFest. This year we had an unprecedented number of submissions, and sadly not enough space on the program to accept them all.

Regrettably, we're not able to incorporate your session proposal xxxxxxxxxxxxxx.

However, we would love you to still be a part of the weekend. If you are in London from Oct 28-30 we hope you will join us as a participant at the festival. Please accept a free, non-transferrable ticket to the event: 

[insert new link]

If you're unable to join us in London, there are plenty of ways to enjoy the festival. [Sign up here] for news on remote participation options, live-streaming links to our Speaker Series, and more. 

All the best, 
The festival team

**Comment by edrushka** [comment]
### Standard Copy

Subject: Your MozFest proposal

Hello,

Thank you for submitting your proposal, XXXXXXXXXXXX, to MozFest 2017. Regrettably, we are not able to include it in our festival programming this year. 

We received an incredible number of proposals and the festival team was impressed by the high standard of the submissions. Our space wranglers carefully considered every idea, and were struck by the quality and creativity of the proposals. We regret that MozFest cannot accommodate more sessions.

We would like to wish you the best of luck with your idea. If you are in London in October, we hope you will [join us at the festival](https://mozillafestival.org/tickets). If you are in search of collaborators for your project, please consider listing it on [Mozilla Pulse](https://www.mozillapulse.org/featured).

If you're unable to join us in London, there are plenty of ways to enjoy the festival. [Sign up here] for news on remote participation options, live-streaming links to our Speaker Series, and more.

Again, thank you for taking the time to submit your idea to MozFest.

Sincerely,
The MozFest Team




### Highlighted Sessions

Subject: Your MozFest proposal

Hello,

Thank you for submitting your proposal, XXXXXXXXXXXX, to MozFest 2017. Regrettably, we are not able to include it in our festival programming this year. We received an incredible number of proposals and we wish it were possible to accommodate more sessions. 

During the curation process, our Space Wranglers identified your proposal as especially strong, and we would love to invite you to the Festival as a participant — we think you have a lot of great ideas to contribute. If you are in London from Oct 27-29, please accept this free, non-transferable ticket to MozFest.

If you're unable to join us in London, there are plenty of ways to enjoy the festival. [Sign up here] for news on remote participation options, live-streaming links to our Speaker Series, and more. If you are in search of collaborators for your project, please consider listing it on [Mozilla Pulse](https://www.mozillapulse.org/featured).

Again, thank you for taking the time to submit your idea to MozFest and we hope to see you at the Festival.

Sincerely,
The MozFest Team

**Comment by marcwalsh** [comment]
Perfect! Thank you @edrushka
