### ISSUE TITLE
Localize participation guidelines

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#731]
@TheoChevalier Here is the short version of the participation guidelines we'll be using for the posters. Please localize into our supported festival languages.

-------

**Participation Guidelines**

The Mozilla Festival respects Mozilla's community participation guidelines. These guidelines cover our behaviour as participants, facilitators, wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

How to treat each other:

- Be respectful and value each other’s ideas, styles and viewpoints.
- Be direct but professional; we cannot withhold hard truths.
- Be inclusive and help new perspectives be heard.
- Appreciate and accommodate our many cultural practices, attitudes and beliefs.
- Be open to learning from others.
- Lead by example and match your actions with your words.

The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org or call +44 20 7855 3030

**Comment by edrushka** [comment]
This copy is finalized (I added in the phone number) and ready to be translated into:
- de
- es
- fr
- it
- hi-IN
- pt-BR
- zh-TW

**Comment by edrushka** [comment]
L10N tracking dashboard: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_design_assets.lang

**Comment by edrushka** [comment]
Posters are designed here, ready for QA: https://redpen.io/p/st123a285766334577

**Comment by TheoChevalier** [comment]
Besides Peter’s comments in Redpen for zh-TW, there are two typos in Spanish:

1) In the first line, "respecta" should be "respeta"

2) Near​ the end, "violencia" should be Violencia"

**Comment by edrushka** [comment]
Thanks @TheoChevalier - are the rest ok?

**Comment by TheoChevalier** [comment]
Not sure if each team had a look so far, but that’s the only feedback I got

**Comment by TheoChevalier** [comment]
The Hindi translator left a comment in RedPen, but mentioning it here too — everything is fine for Hindi
