### ISSUE TITLE
Localize "I speak" stickers

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#735]
Last year, we only localized the language (the words I speak remained in English). 
![screenshot 2017-09-06 14 59 58](https://user-images.githubusercontent.com/4515662/30136497-19571080-9314-11e7-85b4-952dc617214e.png)

This makes sense, especially if we want the language in the bottom line to be the full English word, rather than the localization code.

If we do that again this year, we can re-use (see the [2016 ticket](https://github.com/MozillaFoundation/Mozfest2016_production/issues/149).)
- French
- Spanish
- Italian
- German
- Hindi

And only need translations for:
- pt-BR
- zh-TW

**Comment by edrushka** [comment]
L10N tracking dashboard: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_design_assets.lang

**Comment by sabrinang** [comment]
I'm currently designing these stickers https://github.com/MozillaFoundation/mozfest-design-2017/issues/24#issuecomment-328907191 and I specifically have a localization question for Hindi.

When I copy and paste the localized Hindi word in Illustrator it appears different. This is also how it appeared last year when the designer made these but unsure if they were correct last year.
<img width="934" alt="image" src="https://user-images.githubusercontent.com/2492510/30338144-6a0e9680-979f-11e7-989f-b0c7d291c70a.png">

@TheoChevalier Is this incorrect? Let me know if you have any tips of inputting Hindi into Adobe Illustrator (I tried looking for tutorials but couldn't reproduce the same looking word so far)

**Comment by edrushka** [comment]
Nice to see these designs coming along, @sabrinang :)

Instead of having the localization codes (HI) we'd like to have the full word (Hindi) this year. We realized that many people don't know the codes, so it won't be useful information. Especially for languages like zh-TW.

**Comment by edrushka** [comment]
cc @vigneshwerd to confirm this Hindi text is correctly applied.

**Comment by vigneshwerd** [comment]
The translation of "hi" in Hindi is "नमस्ते" and the localized text of Hindi word is "हिन्दी". The localized text in the current design does not sound right to me.

**Comment by TheoChevalier** [comment]
@sabrinang Unfortunately I’m not a font guru, but it looks like a font issue indeed :/ 

It seems to work here on GitHub, and on Transvision. For Hindi it seems to fall back to the system font Devanagari MT on macOS, does this one work? What font are you trying with?

https://transvision.mozfr.org/string/?entity=toolkit/chrome/global/languageNames.properties:hi&repo=central
