### ISSUE TITLE
Create MozFest House page 

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#737]
Need:
- [ ] image for Hero Banner https://github.com/MozillaFoundation/mozfest-design-2017/issues/50
- [ ] descriptive text - being finalized [here](https://docs.google.com/document/d/18Wuzj1zLx5o1gvEIWcnf4xw0BfNYPjKqjS6jYaOyqxY/edit?ts=59b123ba)
- [ ] schedule in table form
- [ ] sign up for co-working: https://ti.to/Mozilla/mozfest-house-co-working-space

any other content required here @Saallen @marcwalsh?

---

(Mavis) I added some notes for implementation
- after chatting with @marcwalsh we've decided to set up this page like the Fringe page (i.e., hooking it up with the spreadsheet) so program team can easily make schedule changes live
- this is the spreadsheet to pull content from: https://docs.google.com/spreadsheets/d/1YNHtYe_9lowzTAx0mj5XD2DaX3UZX785rVvTt7Vjpps/edit#gid=0

**Comment by mmmavis** [comment]
@edrushka is this gonna be a page on the MozFest site? If so and if we are thinking about adding it to the nav bar, we will need some design help as the current nav bar design will not accommodate that many links nicely.

**Comment by edrushka** [comment]
Yes. I think we may have to remove Projects to accommodate this new page in the top nav. We'll need to discuss.

**Comment by edrushka** [comment]
@mmmavis here's a[ schedule of events](https://docs.google.com/spreadsheets/d/14zKmZX0vFujBHkovkEmcLsDm_5gzIILoJiBV4caBvPE/edit#gid=0) in VERY rough form. Can you take a look and tell me if I should file a separate ticket for design love?

**Comment by Saallen** [comment]
Looping @lucieclick in here
Is there anyway we can make it a bit more easy to read?
lIke the old fringe page- one event per line?
with 2/3 sentences per event and link to ticket page??

**Comment by Saallen** [comment]
@lucieclick and myself think there should be a way to sign up to come and co work in the space
We are going to  create a sign page expecially to capture these names. We would like a sentence on the page for this. cc @marcwalsh on creating tito page

**Comment by mmmavis** [comment]
@edrushka yes some design love would be great! I'm not sure table would be the best layout to show all the events since we have so many cells to show.

**Comment by edrushka** [comment]
@mmmavis agree. Especially because the events all have different start times and durations. What do you think about the fringe-style layout like Sarah suggested above?

**Comment by mmmavis** [comment]
@edrushka fringe-style layout sounds great!

**Comment by edrushka** [comment]
Hurray! I think we have all the required info for this page!

**URL:** mozillafestival.org/house
**Nav bar:** House (replaces Projects)
[Hero banner image](https://user-images.githubusercontent.com/2492510/30399776-a81a3782-9889-11e7-9364-d0ebc453f407.jpg)
**Hero banner text:** MozFest House
**Header text:** Sometimes, the MozFest weekend just isn’t enough.
**Main text:**

Introducing MozFest House: our central London venue that extends MozFest into a week-long festival.

From Monday 23rd - Friday 27th October, MozFest participants are invited to dig deeper into their work, trade ideas, swap code, and build solutions.
 
MozFest House features films, workshops, conferences, and talks, all focusing on Internet health and showcasing the diversity of the Mozilla network. 
  
- Where: MozFest House is located just off Trafalgar Square at the [Royal Society of Arts](https://www.thersa.org/contact) (RSA), 8 John Adam St, London WC2N 6EZ. RSA is a contemporary venue equipped with co-working areas, meeting rooms, and a speakers forum. 
 
- When: MozFest House will be open Monday 23rd - Friday 27th October between 9:00 and 23:00. 
 
- Who: Coders, journalists, teachers, hackers — anyone and everyone working toward a healthier Internet. All ages and skill levels are welcome. Please note you must register for MozHouse events separately from the weekend festival.

MozFest House features a free co-working space. To use the space, sign up [here](https://ti.to/Mozilla/mozfest-house-co-working-space).
_*Note: With the exception of ViewSource, MozFest House events are hosted but not produced by Mozilla._

**Listing of public events** in fringe-style layout #742

**Comment by Saallen** [comment]
looks great @edrushka

**Comment by edrushka** [comment]
Alright @mmmavis - there's some events in the spreadsheet, so this is ready to go! 🏇

**Comment by mmmavis** [comment]
I updated the top comment with some notes for implementation.

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/house
