### ISSUE TITLE
Further bios to add to the Wranglers Page

### ISSUE THREAD

**Issue by EsmeSimcox** [mozilla/mozillafestival.org#738]
Mehan Jayasuriya - Open Innovation

~~Mehan Jayasuriya is a technologist and writer based in Portland, Oregon, U.S.A. He is currently a Program Manager at Mozilla, where he oversees the WINS wireless innovation challenges, which focus on connecting the unconnected in some of the most difficult scenarios. He has previously worked for a variety of technology companies, academic institutions and non-profits, including Tumblr, NYU, General Assembly and Public Knowledge; his writing on culture, technology and policy has been published by The Guardian, Pitchfork and Gizmodo.~~

I had to edit this to get it under the 50 word limit:

Mehan is a technologist and writer based in Portland. At Mozilla, he oversees the WINS wireless innovation challenges, which connect the unconnected in some of the most difficult scenarios. He has worked for a variety of technology companies, academic institutions and non-profits, and he writes about culture, technology and policy.

Twitter: @mehan_j

![me_garrett_miller_large](https://user-images.githubusercontent.com/30292263/30320414-6effac64-97aa-11e7-82f2-286d51604ea7.jpg)

**Comment by EsmeSimcox** [comment]
@edrushka

**Comment by edrushka** [comment]
Brett Gaylor is a documentary filmmaker and the Commissioning Editor for Advocacy Media at the Mozilla Foundation.  His privacy documentary Do Not Track is the recipient of the International Documentary Association award for best nonfiction series, the 2016 Peabody Award, and the Prix Gemaux for Best Interactive Series.
[
Photo](https://www.flickr.com/photos/etherworks/10681077404/in/album-72157624027265512/)

**Comment by edrushka** [comment]
Angela's [photo](https://assets.mozilla.net/leadership/mozilla_portrait_Angela-Plohman.jpg) (her bio text is already up).

**Comment by mmmavis** [comment]
Just give me a ping when this is ready for implementation. I'd like to update everything in one shot/PR 😉 .

**Comment by edrushka** [comment]
Will do. I'm trying to collect everything in one place for you! :)

**Comment by EsmeSimcox** [comment]
Chrystian Rodriguez (Digital Inclusion)

Chrystian works as the Network Manager for Mozilla, Hive NYC - he works with the network to strengthen the network as a space for learning, innovation, and leadership by co-designing digital peer professional development opportunities. He facilitates spaces to aim to explore, create, and share tools, ideas, and practices that can transform learning in NYC. In his spare time, Chrystian teaches film at Third World Newsreel and is a collector of film soundtracks on vinyl.

![xtian crop](https://user-images.githubusercontent.com/30292263/30386258-4a854d1a-98a1-11e7-8676-39a0caca4569.jpg)

**Comment by edrushka** [comment]
Natalia Mileszyk (Open Innovation wrangler)
@nmileszyk
Natalia is a lawyer and public policy expert dealing with digital rights, copyright reform and open policies at Centrum Cyfrowe, a leading Polish think-and-do-tank exploring society’s response to the robust development of technology She’s also a member of Communia Association for Public Domain and legal expert for Creative Commons.
![photonm](https://user-images.githubusercontent.com/4515662/30407920-5bee39d6-98b0-11e7-8540-38c1349707a2.jpg)

**Comment by edrushka** [comment]
Add Raegan's Twitter handle to [her bio](https://mozillafestival.org/team/wranglers#Raegan-MacDonald):  twitter.com/ShmaeganM

**Comment by edrushka** [comment]
Add Stéphanie's bio (Privacy and Security)

Stéphanie is a Security Engineer at Mozilla working on Firefox. She is
passionate about privacy, security and their implications for people in
their online and offline lives. Among other activities, she focuses on
sharing technical knowledge beyond the Free and Open Source Software
communities.

**Comment by edrushka** [comment]
Add Jenn Beard (Open Innovation)

Jenn is a naturally curious person who collects new experiences through continuous learning and travel. Currently, she works for Mozilla on a grant-making program that supports the creation of high-speed internet technologies for education. Jenn’s favorite area of innovation at the present time is craft cocktails.
![jenn beard headshot](https://user-images.githubusercontent.com/4515662/30460885-d0676a26-996e-11e7-9afa-4735fa28b1c0.jpg)

**Comment by edrushka** [comment]
Add Tim Riches' photo: 
![5b_tfeewyx5iqwarh3xlg0xpr6zub-uktdmqehiohepzy8q8gmknhm5civmmyid97sqlnicugpb-z7qeo7tushgwjdpc60bbkdne w1280-h641](https://user-images.githubusercontent.com/4515662/30461037-bbbe5b92-996f-11e7-854d-d0a7723be1e6.jpg)

**Comment by edrushka** [comment]
Add Angela's photo: 
![mozilla_portrait_angela-plohman](https://user-images.githubusercontent.com/4515662/30461059-ebca4d32-996f-11e7-9f28-bc1dbe2b119f.jpg)

**Comment by EsmeSimcox** [comment]
Grace Owolade-Coombes - Youth Zone

Co-founder of South London Raspberry Jam - delivering autism and Tourette's Syndrome friendly digital making workshops.  Certified Raspberry PI educator and specialist in specific learning difficulties, diversity and Inclusion. Proud parent to 2 young coding ninjas, exploring transformative experience of learning in informal shared space   and advocating peer learning


<img width="746" alt="screen shot 2017-09-18 at 11 56 39" src="https://user-images.githubusercontent.com/30292263/30539019-752bde74-9c68-11e7-8ab4-c01b16e96cb8.png">

**Comment by edrushka** [comment]
Steph's photo (privacy and security):

![stepho](https://user-images.githubusercontent.com/4515662/30571309-dcd41e00-9cb4-11e7-93da-3153ee08eeab.jpg)

**Comment by edrushka** [comment]
@mmmavis I believe this is all the updates. Over to you for implementation! 👯

**Comment by mmmavis** [comment]
Everything has been added to the site! :tada:
