### ISSUE TITLE
Info for back of House name card

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#739]
@Saallen @marcwalsh @lucieclick what information do we need on the back of the House name card? For reference, here's what's on the main [weekend name card](https://github.com/MozillaFoundation/mozfest-design-2017/issues/21#issuecomment-328984425).

**House info**
- Wifi network & password
- Connect (not sure if it's appropriate to ask people to tweet MozFest at MisInfocon, Open News etc.)
- Help (do we want to have our safety # here or is it each individual event's responsibility)

**Comment by Saallen** [comment]
Suggested content for back of the name tag

* participation guidelines
* Enjoyed  MozFest HOUSE, join us for the weekend at Ravensbourne

**Comment by edrushka** [comment]
Updated:
- wifi
- participation guidelines

**Comment by edrushka** [comment]
Participation Guidelines:
Be respectful and value each other’s ideas, styles and viewpoints.
Be direct but professional; we cannot withhold hard truths.
Be inclusive and help new perspectives be heard.
Appreciate and accommodate our many cultural practices, attitudes and beliefs.
Be open to learning from others.
Lead by example and match your actions with your words.

The following will not be tolerated at MozFest House: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org

**Comment by edrushka** [comment]
@Saallen @lucieclick please review this redpen to see what the back of the house namecard will feature: https://redpen.io/pc3767d55910f95a95
