### ISSUE TITLE
Update a11y section with blog

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#740]
Please adjust the second paragraph of the a11y section on [this page](https://mozillafestival.org/expect) to include the blog:

During the open call for proposals, if you would like to submit a session and have difficulty using the text-based form, please email us to discuss other options. Read details about accessibility support at the festival venue in [this blog](https://medium.com/mozilla-festival/accessibility-at-mozfest-606c3ad20c04).

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/expect
