### ISSUE TITLE
House event details for website

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#742]
@marcwalsh @Saallen @lucieclick please add details of each public House event to [this spreadsheet](https://docs.google.com/spreadsheets/d/1YNHtYe_9lowzTAx0mj5XD2DaX3UZX785rVvTt7Vjpps/edit?ts=59bb2a65#gid=0) to populate the website.

Marking this P1 as everything else for the House page is ready.

**Comment by marcwalsh** [comment]
@edrushka - I haven't got access to the doc.
