### ISSUE TITLE
Content: Guidebook App Listing

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#744]
There are various pieces of content that we need for the App Store listings of the Guidebook app. 

- [x] App Full Name
   - 30 characters max. (including spaces)
   - This will be the title of your app as displayed in each of the App Stores.

- [x] App Short Name
   - 20 characters max. (including spaces)
   - This is the name of your app that shows up underneath the icon on the device’s
home screen.

- [x] Preview Description
   - 50 characters max. (including spaces)
   - A short preview of the app, shown on Amazon, Google Play and Blackberry.

- [x] Full Description
   - 4000 characters max (including spaces)
   - The main description for the app should include keywords needed for search in Google Play.

- [x] Product Feature Bullets
   - 500 characters max
   - 4 bullet points of the main features of the app

- [x] Keywords
   - 100 characters max
   - Keywords that can be used to find your App on the App store. Separate
keywords with commas

**Comment by edrushka** [comment]
**App Full Name:** MozFest 2017
**App Short Name:** MozFest
**Preview Description:** 
MozFest is the world's leading festival for the open Internet movement. October 23-29, 201. Ravensbourne College, London.
**Full description:** 
Welcome to MozFest!

This year marks our eighth MozFest. More than ever, the movement for a healthy Internet needs a place to convene, organize and act.

Today, the concept of Internet health reaches far beyond the realm of open source code: it’s linked to civil liberties and public policy, free expression and inclusion. Access is no longer a luxury — it’s a fundamental part of 21st century life. A virus is no longer a nuisance consigned to a single terminal — it’s an existential threat that can disrupt hospitals, governments and entire cities.

The movement for a healthy Internet is primed to address these problems. But we need a hub to trade ideas, find inspiration, swap code and build solutions.

MozFest is that hub.

Our sessions, speakers and workshops are built to foster collaboration across disciplines, borders and continents. And this year, we're expanding the festival to include pre-week talks and gatherings, an initiative titled MozFest House.

We’re ready to face the biggest issues of the day — from fake news and online harassment to global cyberattacks — together, with an eye toward practical, open source solutions.

Thank you for joining us.

**Product Features Bullets:**
(I'm not sure what to put here.) Sessions. Experiences. Dialogues and Debates. Artists. ???? 

**Keywords:**
- Mozilla
- Festival
- MozFest
- Internet
- Web
- Digital
- Open Source
- Technology
- Collaborative
- Privacy
- Security
- Innovation
- Literacy
- Decentralization
- Inclusion
- Youth
- Leadership
- Art
- Journalism
- Policy
- Advocacy
- Science
- House
- Workshops
- Film
- Hackjam
- Code

(add more.....)



@marcwalsh can you confirm w/ Guidebook these make sense? If they have best practices for this text I'm happy to modify any of this. Is it confusing to have the app  long name and short name so similar? Should we reference the year given that we will likely have a new guide next year?

**Comment by mmmavis** [comment]
<img width="514" alt="screen shot 2017-09-19 at 11 00 48 am" src="https://user-images.githubusercontent.com/2896608/30607433-db7adab0-9d29-11e7-854b-66fbaf7effee.png">

Looks right? I'm a ssuming MozFest House events won't go on here.

**Comment by edrushka** [comment]
I think we *do* want MozFest House events on there. Correct @Saallen?

**Comment by Saallen** [comment]
Yes, lets get them on here too- we can give the link to the sign up pages for tickets or attendance

**Comment by Saallen** [comment]
Can @marcwalsh confirm that these keywords for searching should include the "tracks" you talked of in a message- so our space names and experiences?

**Comment by marcwalsh** [comment]
@edrushka - the short description is too long. I've tried editing it down however it has to be 50 characters or less. Even "MozFest is the leading festival for the open Internet movement." is too long.

@Saallen - The keywords are not for the internal search it's for visibility​ on the app stores. So apart from MozFest and Mozilla Festival. If we're aiming to reach people who find the app by chance instead of those who are attending. 

On the keyword section, it's 100 characters max so currently we can have the following from the top of the list:

mozilla, festival, mozfest, internet, open web, digital, open source, technology, collaborative, privacy

**Comment by edrushka** [comment]
How about this for the short description: 
A festival for the open Internet movement.

For keywords:
Mozilla festival Internet open source web digital technology advocacy art journalism youth global community code

**Comment by Saallen** [comment]
Suggested content for guidebook main page- 

Welcome to MozFest!

This year marks our eighth MozFest. More than ever, the movement for a healthy Internet needs a place to convene, organize and act.

This schedule shares spaces, session descriptions and timings, and different ways to navigate across the program such as different experiences and session formats.

Experiences are artworks, exhibits, activities and interactions that bridge Spaces by weaving together many of the themes present at the festival.
This include:
Artist open studio - 5 artists onsite producing art work exploring the narratives of the 5 spaces
Theme wrangling- discover sessions under the themes of Journalism, Advocacy and Policy and youth led
Emergent sessions- continue the conversation and book a table for sessions what build upon or extend from other sessions over the weekend

Session formats help participants understand the level of interaction within each session
We have 3 distinct formats
**Learning Forum, for listening, learning and discussing individual topics. Sessions here develop and implement ideas for improvement, exchange or review.
**Gallery, contains interactive exhibits, installations, games, stalls designed for 1:1 self driven experience and emergent activities. 
** Shed, for hands-on making, hacking and prototyping. Sessions in the Shed require attendees to create and build code, objects or crafts

**Comment by edrushka** [comment]
Thanks @Saallen - I made a few tweaks and got it a bit shorter.

-----

Welcome to MozFest, a festival for advocates of a healthy Internet.

This schedule shares session descriptions and timings, and different ways to navigate across the program. 

You can explore sessions individually, by session facilitator, or grouped under spaces or experiences.

Session formats help participants understand the level of interaction within each session:
* Learning Forum session are for listening, learning and discussing individual topics. Sessions here develop and implement ideas for improvement, exchange or review.
* Gallery sessions contain interactive exhibits, installations, games, stalls designed for 1:1 self driven experience and emergent activities.
* Shed sessions feature hands-on making, hacking and prototyping. Expect to create and build code, objects or crafts.

MozFest features a range of experiences, which span the different spaces of the festival, including:
* Artist Open Studios - Five artists are embedded in the festival, producing art work exploring the narratives the space.
* Curated Programming - Three curated topics allow you to explore each of the festival's spaces through a particular lens: Open Policy & Advocacy, Journalism and Youth-Led.
* Dialogues and Debates: 19 luminaries at the intersection of technology and society will deliver compelling talks in the Walker Space on the ground floor.

Emergent sessions:
MozFest provides space for emergent sessions. To book a table and have your session added to the schedule, visit the library on the 5th floor.

**Comment by marcwalsh** [comment]
@edrushka  - The app features is what the user can do with the app so for example:

- Browse the MozFest House and Weekend Schedule
- Link up with wranglers, facilitators and other attendees.
- Share your photos of the festival with everyone

(Obviously not the best, but hopefully, that gives you an idea.

**Comment by edrushka** [comment]
@marcwalsh how about this for the app features:

- Browse the MozFest schedule
- Find session locations on a map
- Connect with wranglers, facilitators and other attendees
- Share your photos of the festival

**Comment by marcwalsh** [comment]
That is perfect! Thanks @edrushka
