### ISSUE TITLE
Remove Morgan Marquis-Boire as speaker

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/mozillafestival.org#746]
Hi @mmmavis @edrushka 

Morgan Marquis-Boire has had to cancel his speaking engagement at MozFest. We'll want to update https://mozillafestival.org/speakers to reflect that. 

@edrushka Can you let Cassie know, in case she's begun designing the print materials?

**Comment by edrushka** [comment]
Will do.

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/speakers @edrushka I'm gonna keep this ticket open in case you need it as a reminder for pinging Cassie.

**Comment by edrushka** [comment]
Thanks @mmmavis - I will close this as I pinged Cassie in #696
