### ISSUE TITLE
Amend Sarahs Bio

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#750]
Hello can you change my bio to 

Sarah Allen is MozFest's Executive Director. When she is not focused on MozFest, she works with the network to deliver Mozilla aligned convenings around the globe. Sarah draws her experience from a diverse events background working in theatrical experiences, global sporting events and community festivals. MozFest 2017 will be Sarah’s fifth festival.

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team
