### ISSUE TITLE
Custom CSS for ti.to/Mozilla

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#751]
Hey @mmmavis @sabrinang @edrushka 

With all the various tickets we're using on ti.to this year we're linking to: [ti.to/Mozilla](http://ti.to/Mozilla) more than we have done in previous years.

They've enabled our account to have the ability to use custom CSS so it can incorporate a little more branding etc and our fonts etc.

I'm not sure if this is totally out of scope or how difficult this might be but thought it was worth a discussion. 

Let me know your thoughts! An [example](https://ti.to/tcdalumni) they sent over to me is this which looks a lot neater. 

M :)

**Comment by mmmavis** [comment]
That sounds exciting! @marcwalsh in order for @sabrinang and I to investigate the work needed, can you attach a list of ti.to links/pages we currently have?

**Comment by marcwalsh** [comment]
I think the main one to focus on (as it just adds to an inline stylesheet, so it's per page) is ti.to/Mozilla as this is what we'll be what we're linking with guidebook.

**Comment by mmmavis** [comment]
Cool. @sabrinang let me know what needs to be updated. Just a note that the timeline (arrows and axis) can't be easily changed as they are actually in image files like [this](https://titoproduction.global.ssl.fastly.net/assets/public-timeline-upcoming-157a0318734f6951520cbcb4eff4a20cb4354ab5a93a31e9086fe14e45fef8f5.png).

**Comment by sabrinang** [comment]
Closing - https://ti.to/Mozilla has white mozilla wordmark and we can open up issue later in design repo if it needs to be refreshed for 2018.
