### ISSUE TITLE
Content for mini-net

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#752]
Let's gather content here:

**Comment by KevZawacki** [comment]
1) Sam B.'s forthcoming Attitudes About Internet Health report.

cc @Lottarao

**Comment by edrushka** [comment]
cc @marcwalsh

**Comment by Saallen** [comment]
* lunch times and locations
* wifi password
* MozHELP

The mini nets are on rotation and cannot be timed.  We need to be sure not to over load with text when its visible for limited period of time

**Comment by edrushka** [comment]
Closing this ticket. Add additional requests to https://github.com/MozillaFoundation/mozfest-design-2017/issues/13
