### ISSUE TITLE
Localize “[Language] speakers welcome”

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/mozillafestival.org#753]
Tracking: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_design_assets.lang
Completed translations: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_design_assets.lang&action=translate&show
Locales: All MozFest locales
Deadline: 2017-10-04

CC @edrushka

**Comment by TheoChevalier** [comment]
Once Italian is done, we’re good to go

**Comment by edrushka** [comment]
I can reach out to Edoardo if we're stuck on Italian. @mmmavis just let me know when you need these lines to amend the session descriptions on Guidebook.

**Comment by mmmavis** [comment]
@edrushka The script needs to know these lines before it starts exporting things from GitHub and spreadsheet. I'm still unsure when we are ready to port things over, for that I'm waiting for the ping from @marcwalsh .

**Comment by marcwalsh** [comment]
@mmmavis If we can aim for tomorrow your time. I can email the wranglers and let them know. If they then mark any updates and one of the production team can copy them over.

@edrushka - Does that time frame seem realistic?

**Comment by edrushka** [comment]
Yup! Here are the strings. The only one missing is Italian, and I can add those 2 manually later on.


de:  Deutschsprachige willkommen
es: Bienvenidos todos los que habláis español
fr: Les personnes parlant français sont les bienvenues.
hi-IN: इस सत्र में हिंदी भाषियों का स्वागत हैं
pt-BR: Falantes de Português são bem vindos
zh-TW: 歡迎會說華語的伙伴參加
