### ISSUE TITLE
Update participation guidelines on website

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#754]
Update "How to treat each other" with:

How to treat each other:

- Be respectful and value each other’s ideas, styles and viewpoints.
- Be direct but professional; we cannot withhold hard truths.
- Be inclusive and help new perspectives be heard.
- Appreciate and accommodate our many cultural practices, attitudes and beliefs.
- Be open to learning from others.
- Lead by example and match your actions with your words.

The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

**Comment by edrushka** [comment]
Thanks @mmmavis  - is it possible to make this not all caps and bolded? The bolding is fine, but combined with all caps feels a little aggressive ;)

**Comment by mmmavis** [comment]
updated!

**Comment by edrushka** [comment]
Thank you!!!! 🌻
