### ISSUE TITLE
Project page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mozillafestival.org#763]
Last year, at the end of MozFest, we add a Projects page to the MozFest site and main nav. This year, it might be good to queue that up in advance, so it can display during the festival ...  so attendees and onlookers can find opportunities for collaboration. 

The simplest solution, might be a page with intro text and a big button to Pulse [mozfest tag](https://www.mozillapulse.org/tags/mozfest) (instead of building a feed).  

@edrushka - has there been any discussion on this yet this year?

@alanmoo – maybe this is something an engineer who isn't traveling to the fest might handle?

**Comment by edrushka** [comment]
We only took it off the top nav because we ran out of room. @Saallen do you think we could replace House with Projects on Friday afternoon? After the festival we could remove What to Expect and bring House back in to the top nav (keeping Projects as well).

**Comment by Saallen** [comment]
Hello- I would like to keep House- but let's chat to discuss

**Comment by xmatthewx** [comment]
We could put a link on the Spaces page, below the intro paragraph. Or, call it out wherever you'll link to the schedule. Doesn't need to be in the main nav.

**Comment by alanmoo** [comment]
Any definitive direction on this?

**Comment by edrushka** [comment]
@mmmavis is there room in the top nav for one more item or  do we need to cut something?

**Comment by alanmoo** [comment]
I think part of the question is how soon you want to remove "tickets" and put up "projects"

**Comment by edrushka** [comment]
Take Spaces off and replace it with pulse. This can happen any time. All the space info is currently on guidebook.

**Comment by xmatthewx** [comment]
@alanmoo - tickets are sold out. @edrushka says you can remove that from the nav.

**Comment by alanmoo** [comment]
What about the bottom section of the homepage?

**Comment by edrushka** [comment]
Sure you can take that bottom ticket banner out and/or replace with Pulse.

**Comment by edrushka** [comment]
Scratch that!!! We just set up a mailing list for 2018 to point people to. Tickets have sold out so we want a way for interested people to engage.

Please update banner text to 2018, and point to this url: https://ti.to/mozilla/mozilla-festival-2018
