### ISSUE TITLE
After MozFest: Link to speaker series on AirMo

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/mozillafestival.org#768]
Last year, in the days after MozFest 2016, we linked speakers' headshots on MozFest.org to recordings of their talks on AirMo.

Let's aim to do so again this year. I'll update this ticket when the links become available.

@alanmoo, let me know how else I can help. Here's the workflow from last year: https://github.com/mozilla/mozillafestival.org/commit/87a8c25a154c75c88f2def23a15e356fbfc64cf4

**Comment by KevZawacki** [comment]
@edrushka, what do you think? ^

**Comment by edrushka** [comment]
We could replace the What is MozFest like section currently on the homepage with a "view the talks" section, and link to them individually.

**Comment by alanmoo** [comment]
@KevZawacki When you have the links, someone needs to update [this file](https://github.com/mozilla/mozillafestival.org/edit/speakers/talks/2017.js) keeping the URLs for each talk inside the backticks 
```
videoLink: `https://air.mozilla.org/`,
````

If you can do that yourself, go ahead and post here after, @mmmavis or I can review. Or just post the links with people here and one of us can drop it in the code.

**Comment by KevZawacki** [comment]
Great! Thanks for your help, @alanmoo

**Comment by KevZawacki** [comment]
Hi @alanmoo & @mmmavis, our talk footage is ready for the website:

Mishi Choudhary | https://air.mozilla.org/mozfest-2017-saturday-dialogues-and-debates/ | 0:00 - 30:15

Alan Knott-Craig | https://air.mozilla.org/mozfest-2017-saturday-dialogues-and-debates/ | 30:15 - 50:18

Ashley Black | https://air.mozilla.org/mozfest-2017-saturday-dialogues-and-debates/ | 51:35 - 1:14:05

Anasuya Sengupta & Siko Bouterse | https://air.mozilla.org/mozfest-2017-saturday-dialogues-and-debates/ | 1:14:13 - 1:31:10

Matt Mitchell | https://air.mozilla.org/mozfest-2017-saturday-dialogues-and-debates/ | 1:31:16 - 1:48:00

Ugo Vallauri | https://air.mozilla.org/mozfest-2017-saturday-dialogues-and-debates/ | 1:49:00 - 2:08:25

Mark Surman, Katherine Maher and Ryan Merkley | https://air.mozilla.org/mozfest-2017-saturday-dialogues-and-debates/ | 2:10:15 - 2:49:10

Audrey Tang | https://air.mozilla.org/mozfest-2017-sunday-dialogues-and-debates/ | 00:52 - 19:32

Emily May | https://air.mozilla.org/mozfest-2017-sunday-dialogues-and-debates/ | 21:19 - 44:22

Nighat Dad | https://air.mozilla.org/mozfest-2017-sunday-dialogues-and-debates/ | 45:55 - 56:43

Gisela Perez de Acha | https://air.mozilla.org/mozfest-2017-sunday-dialogues-and-debates/ | 1:41:31 - 2:03:17

Nanjira Sambuli | https://air.mozilla.org/mozfest-2017-sunday-dialogues-and-debates/ | 2:03:30 - 2:18:20

Julia Angwin | https://air.mozilla.org/mozfest-2017-sunday-dialogues-and-debates/ | 2:18:25 - 2:39:10

Gillian Crampton Smith | https://air.mozilla.org/mozfest-2017-sunday-dialogues-and-debates/ | 4:12:45 - 4:40:00

Sarah Jeong and Emily Gorcenski | https://air.mozilla.org/mozfest-2017-sunday-dialogues-and-debates/ | 4:41:36 - 5:22:10

cc @edrushka

**Comment by alanmoo** [comment]
Added, awaiting code review
