### ISSUE TITLE
Update festival guide link on mozillafestival.org/expect

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/mozillafestival.org#769]
Hi @edrushka,

On the What To Expect page, there is still a link to our 2016 schedule. Possible to remove or update? A reporter emailed us today confused.

On a related note: In addition to the schedule app, is there a PDF of our print guide I can share?

**Comment by edrushka** [comment]
Perfect timing! We're about to upload the 2017 guide to Issu. Hope to have that ready in the next few days. Assigning @marcwalsh  (can you also create a PDF for Kevin when you do this?)

**Comment by edrushka** [comment]
The 2017 Festival Guide has been uploaded to Issuu. Link is here: https://issuu.com/mozfest/docs/mozfest_2017_festival_guide

@mmmavis can you please update the link on https://mozillafestival.org/expect and the text above it to "Read the 2017 Festival Guide"? Let me know if you need a screenshot for the image. 

Thanks!

**Comment by edrushka** [comment]
Not an P1, because the links are correct, but at some point we should update the image to a spread from the 2017 guide.
