### ISSUE TITLE
Update outdated dependencies

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#788]
😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 

# dependencies 

https://david-dm.org/mozilla/mozillafestival.org

![screenshot-2018-1-3 dependency status for mozilla - mozillafestival org v1 0 0 - david](https://user-images.githubusercontent.com/2896608/34540997-7625abd0-f08b-11e7-98a8-9cbfc38c03bf.png)

😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 

# dev dependencies

https://david-dm.org/mozilla/mozillafestival.org?type=dev

![screenshot-2018-1-3 dependency status for mozilla - mozillafestival org v1 0 0 - david 1](https://user-images.githubusercontent.com/2896608/34541001-77e3783a-f08b-11e7-8e4e-539ff022bcd3.png)

**Comment by mmmavis** [comment]
I'm closing this one as most of the outdated dependencies have been updated. The ones that are left require more work and changes in the codebase (e.g., update `react-router` etc) - I'll tackle those in separate tickets.

**Comment by alanmoo** [comment]
Great. Add them to this project when you make them so we have an overview of it?
