### ISSUE TITLE
Better design for the 404 page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#805]
Please help make this 404 page better 😉 

Some context: 

MozFest wasn't serving real 404 page before (by "real" I mean http status `404`). When users hit a random route all they got was a blank page with nothing on it (http status `200`). This is because the site didn't have server side rendering working and routes were handled client-side. I got server side rendering working yesterday and got a slightly better 404 page up. Design is obvious not good but at least it is better than a blank white page. 😂 Let's give it some design love.

![screenshot-2018-1-9 mozilla festival](https://user-images.githubusercontent.com/2896608/34736455-d772268e-f527-11e7-8c11-64201de7792f.jpg)

/cc @sabrinang

**Comment by edrushka** [comment]
I'll add this to the [site update project brief.](https://docs.google.com/document/d/1Uk7qz4b-dhlTRQh6l5fYrLmzCFeYUfO3gonXjDzxNLM/edit?ts=5a60983f#)

**Comment by sabrinang** [comment]
Note: I'll be referencing the foundation site 404 page that we updated last year: https://github.com/mozilla/foundation.mozilla.org/issues/143#issuecomment-300642641

**Comment by sabrinang** [comment]
I have some mockup options for this 404 page.

We can either make the banner text more obvious with a heading and 404 graphic in the body:

![mozilla-festival_website-update-404 2x](https://user-images.githubusercontent.com/2492510/35885500-d27c5c0e-0b42-11e8-98e9-a8ab9adb4578.jpg)

or make it similar to the foundation site with a narrow nav with text on the left and image on the right (keeping the styling of the existing mozilla festival site):
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/2492510/35885479-c2516310-0b42-11e8-8424-3c10e7985788.png">

@edrushka @mmmavis any feedback or preferences?

**Comment by mmmavis** [comment]
@sabrinang I prefer the one that shares the same style as Foundation site's 404 page.

**Comment by sabrinang** [comment]
The 404 graphic is exported as an .svg here: https://drive.google.com/open?id=1OpfN3isH6eV7oGAhip-QCiRpeKP10d8v

@mmmavis Good to hear you prefer the version that aligns with the foundation site as well. The image and content would be higher up on the page as well 👍

**Comment by sabrinang** [comment]
@edrushka Does this design look good to you as well? If so we can close this and file a separate implementation ticket (I don't know if there is one already)

**Comment by edrushka** [comment]
Go ahead and close - I'll link to the dev ticket. Thanks!
