### ISSUE TITLE
Change main site CTA

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#810]
Since there may not be capacity to update the MozFest site until the second half of February, requesting this small change text and link change to the main banner to tide us over.

Please change main banner text to: 
The world's leading festival for the open Internet movement.
2018 dates coming soon

Change the CTA box text to:
Get updates

and link the CTA box to:
https://ti.to/mozilla/mozilla-festival-2018 ~~(link currently points to an error message but will fix in ti.to in the next day or two)~~

**Comment by edrushka** [comment]
@alanmoo to assign. cc @Saallen and @mmmavis

**Comment by mmmavis** [comment]
I will take this one on since I'm already doing some MozFest site work.

**Comment by mmmavis** [comment]
@edrushka is the ti.to page ready to be linked to? If so, I'll get our site CTA changes live today.

**Comment by edrushka** [comment]
Yup! It's ready to go! (sorry, thought I edited the comment)

**Comment by mmmavis** [comment]
Changes are live!

**Comment by edrushka** [comment]
Awesome - thank you Mavis! 💐
