### ISSUE TITLE
Design Updates to MozFest Home Page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#813]
### Description 
We will refresh the MozFest home landing page so it is up to date for 2018. Create a mockup with these design updates:
- [x] Remove "Latest News" section because it is stagnant and not the latest
- [x] Add Katherine, Ryan & Mark images to Dialogues & Debates section
- [x] Change banner text in bottom banner to Join Us at MozFest
- [x] Update hero area with text to be about the opening of the call for proposals 
- [x] Update hero area with promotional video
- [x] Update hero banner background
- [x] Update logo lockup 
- [x] _(Consider nav structure as well but that can be a separate ticket)_

### Reference
Design Brief Doc: https://docs.google.com/document/d/1Uk7qz4b-dhlTRQh6l5fYrLmzCFeYUfO3gonXjDzxNLM/edit?usp=sharing

**Comment by sabrinang** [comment]
@edrushka Here is a mockup of the landing page with updates (excluding copy updates). You can leave feedback on directly on [redpen](https://redpen.io/xzbf932cbb04b7adb7) or on the ticket.

Original banner photo: https://westraco.pixieset.com/mozfest2017/fullset/?pid=1477513298&id=5&h=Mjk5MzE3Mzc3OA
![mozilla-festival_website-update-2018](https://user-images.githubusercontent.com/2492510/35837151-0b8f9920-0a99-11e8-9250-68946ded68e3.jpg)

**Comment by edrushka** [comment]
Thanks, Sabrina! 
- new lockup looks good!
- top nav is definitely cleaner. 'About' and 'House' should definitely stay. It's important that 'Sponsors' is easily visible so I'd advocate to keep it up top. I'm torn on 'Spaces & Experiences' (it should be experiences, not sessions) and 'What to Expect' - both are valuable to potential new wranglers and sponsors so I'm leaning towards keep. What do you think?
- Hero banner - I'm concerned that the text blocks out all the women so all you see is men. I know the banner is responsive but is it possible to crop the image or find another with a more diverse audience?
- Video banner looks good 
- D&Ds section looks good
- The art banner is good as a placeholder until we know more. Would be cool if the image could rotate (I'll ask Mavis).
- Join Us banner looks good 
- Bottom banner - we can remove the "fringe events" icon. (Mavis can do this.)

**Comment by sabrinang** [comment]
Yeah I understand about the hero banner and I'm looking through the album for group shots as other contenders:
- https://westraco.pixieset.com/mozfest2017/p/MTQ3NzUxMjY1NQ==-MTE4Nzg5OTE4MQ/ (this might have the same issue)
- https://westraco.pixieset.com/mozfest2017/p/MTQ3NzQ3MjI2Mw==-Mzk2NDc2NjgyNQ/
- https://westraco.pixieset.com/mozfest2017/p/MTQ3NzQ2NTE1Nw==-NzY1ODYzMjgw/
https://westraco.pixieset.com/mozfest2017/fullset/?pid=1477514009&id=0&h=NzM5ODY1Njkx

@edrushka Do you prefer any of these?

Redpen updated (excluding photo as commented above and included spaces & experiences and sponsors in nav): https://redpen.io/xzbf932cbb04b7adb7

**Comment by edrushka** [comment]
https://westraco.pixieset.com/mozfest2017/p/MTQ3NzUxMjY1NQ==-MTE4Nzg5OTE4MQ/ and https://westraco.pixieset.com/mozfest2017/fullset/?pid=1477514009&id=0&h=NzM5ODY1Njkx are my favs. Also, you don't need to use a photo from 2017 if one from 2016 will work!

**Comment by sabrinang** [comment]
@edrushka Comparing these banners on https://redpen.io/jv72b3f02c5fc46d2d I prefer this image:
![mozilla-festival_banner-home-2018_2 2x](https://user-images.githubusercontent.com/2492510/35939459-0d4a5976-0c01-11e8-9d49-394ab02099da.jpg)

In context:
<img width="993" alt="screen shot 2018-02-07 at 12 16 51 pm" src="https://user-images.githubusercontent.com/2492510/35939392-dd30c93c-0c00-11e8-88fa-3b3678dfb7c6.png">

Image on gdrive: https://drive.google.com/file/d/1BuDzt7lzGVoIdJQrkyEaho3Z4D3coCFP/view?usp=sharing

**Comment by edrushka** [comment]
Agree - that's the best of the bunch.

**Comment by edrushka** [comment]
Yes, go ahead. I'll link to the relevant dev tickets. Thanks for this, Sabrina! 💐
