### ISSUE TITLE
Master list of February 2018 updates

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#814]
[Project brief](https://docs.google.com/document/d/1Uk7qz4b-dhlTRQh6l5fYrLmzCFeYUfO3gonXjDzxNLM/edit?ts=5a60983f#)
[Feb 2017 updates](https://github.com/mozilla/mozillafestival.org/issues/488) (for reference)

----
## Top nav
Ticket #815 
- [ ] Update logo lockup
- [ ] Simplify and reorder items

## Landing page 
Ticket #816 
- [ ] Refresh hero banner 
- [ ] Add video banner - BLOCKED
- [ ] Add Katherine, Ryan & Mark to D&Ds section
- [ ] Update D&D links - BLOCKED
- [ ] Remove news banner
- [ ] Change banner text in bottom banner to Join Us at MozFest

## About page
Ticket #817
- [ ] Tweak copy for 2018 
- [ ] Update timeline with entry for 2017

## Speakers page
Ticket #818
- [ ] Update speakers with links to polished videos - BLOCKED
- [ ] Add Mark, Katherine and Ryan

## House page
Ticket #819 
- [ ] Update banner image
- [ ] Tweak copy for 2018 NEED SARAH'S SIGNOFF
- [ ] Archive 2017 House events as reference 

## What to Expect page
Ticket #821
- [ ] Replace festival guide image 
- [ ] Replace video with latest version BLOCKED
- [ ] Text tweaks

## Spaces page
Ticket #822
- [ ] add '2017' to Spaces and Experiences section titles

## Media page
Ticket #823
- [ ] Add stories from 2017

## Tweet MozFest
Ticket #824
- [ ] Change tweet auto-text 

## Bottom nav/banner
Ticket #825
- [ ] Remove Fringe

## Volunteer
Ticket #826 
- [ ] Tweak text

## 404 Page
Ticket #805 
- [ ] Improve 404 page

## Sponsor page
Ticket #827 
- [ ] Update intro copy

**Comment by ScottDowne** [comment]
I started to go through some of the tickets and do the obvious things that were easy, didn't require assets, and I didn't hit any blockers on questions I had.

https://mozillafestival-org-sta-pr-830.herokuapp.com/

Nothing fancy or exciting there.

**Comment by edrushka** [comment]
So far so good! Thanks, @ScottDowne!

**Comment by edrushka** [comment]
Update on blocked tickets, @ScottDowne 
- Youtube links for the Dialogue and Debates (D&D) videos for ticket #816 and #818 should be ready early-mid next week cc @KevZawacki 
- Promo video for #816 and #821 should *hopefully* be mid next week
- I don't think the arts page  that we wanted to link in the banner on #816 will be ready by next week, so we'll likely have to add it later on

**Comment by edrushka** [comment]
Update: The D&D videos are now ready! Still waiting on the promo video.

**Comment by ScottDowne** [comment]
@edrushka I wonder how much of this can be marked complete? I bet most if not all, if all of these had tickets too.

**Comment by edrushka** [comment]
Since you've closed all the tickets with the Feb 2018 label, all of these should be complete! :)
