### ISSUE TITLE
Speakers page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#818]
Updates to speakers page

- [ ] Add Mark
Mark Surman @ msurman
Mark is Executive Director of the Mozilla Foundation, a global community that does everything from making Firefox to taking stands on issues like privacy and net neutrality. Mark’s main job is to build the movement side of Mozilla, rallying the citizens of the web, building alliances with likeminded organizations and leaders, and growing the open internet movement. Mark’s goal is nothing short of making the health and accessibility of the internet a mainstream issue around the world.

- [ ] Add Katherine 
Katherine Maher @ krmaher
Katherine Maher is the executive director of the Wikimedia Foundation, the nonprofit behind Wikipedia. Maher has deep experience in the non-profit and international sectors, with a particular focus on the intersection of technology and human rights, development, transparency and community building.

- [ ] Add Ryan
Ryan Merkley @ ryanmerkley
Ryan Merkley is the CEO of Creative Commons, where he is building a vibrant, usable commons powered by collaboration and gratitude.
Prior to Creative Commons, Ryan was Chief Operating Officer of Mozilla. He is an experienced campaigner and advocate for social causes, and has advised political campaigns on the local and national levels.

- [x] Add updated links for each video 
links tdb

**Comment by ScottDowne** [comment]
The speakers sections are a tab switcher with previous years (2016, 2017), do we want to keep adding new tabs (it'll not be great adding more than two) or can we remove 2016, and only keep this year and last year, or remove the tab switcher completely, and do something simpler? Or only show this year without any historic years. (removing 2016 and 2017) How much value is there in showing previous years?
![tabs](https://user-images.githubusercontent.com/197334/36279804-50761e22-1266-11e8-8a35-148d462efaa5.png)

**Comment by edrushka** [comment]
We definitely want to keep a historical record of these talks. We may need to redesign this page at some point to avoid too many tabs, but I don't think that's in scope for now, unless you have time, @ScottDowne. Assuming not, let's keep the 2016 and 2017 tabs. The 2018 tab won't need to be added until the fall.

**Comment by ScottDowne** [comment]
If someone clicks on the 2017 or 2016 how do I get back to 2018? I think we'll need a tab for 2018 for this year. Which is probably fine for now.

**Comment by ScottDowne** [comment]
Added 2018 with a new tab to the link here https://mozillafestival-org-sta-pr-830.herokuapp.com/

**Comment by edrushka** [comment]
Wait...but...we don't have any 2018 speakers yet. Mark, Katherine and Ryan were part of the 2017 speakers (we just accidentally omitted them).

**Comment by ScottDowne** [comment]
Oh, haha, for some reason I thought this was related to 2018. (hence all my blabbering about 2018 in the tab thingy)

If it's just adding it to 2017, that's much easier.

**Comment by edrushka** [comment]
Unblocked! 

Here is a title and description for all the 2017 videos: https://docs.google.com/document/d/1iCatrYXOkPJYjMxyeIDDA2yiFyvbQmcf3CFBbjlmLrk/edit

Videos are here: https://www.youtube.com/playlist?list=PLYiaJo7rYNXInD71OAShY4xfl6fhskoUV

**Comment by edrushka** [comment]
![ryan](https://user-images.githubusercontent.com/4515662/36996178-fc281af6-206a-11e8-8cdf-de76e7a0820b.jpeg)
![katherine](https://user-images.githubusercontent.com/4515662/36996185-feb4620c-206a-11e8-9a2e-74837db7d2a3.jpeg)
![mark](https://user-images.githubusercontent.com/4515662/36996189-01445c66-206b-11e8-8f43-c13fc62451bd.jpeg)
