### ISSUE TITLE
House page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#819]
Updates to House page

- [x] Update hero banner with new image (see ticket #820)

- [x] Tweak the first three sentences of paragraph text to read:

MozFest House is a central London venue that extends MozFest into a week-long festival.

From Monday 22rd - Friday 26th October, MozFest participants are invited to dig deeper into their work, trade ideas, swap code, and build solutions.

MozFest House features films, workshops, conferences, and talks, all focusing on Internet health and showcasing the diversity of the Mozilla network. The venue also features a free co-working space. 

- [x] Tweak 'When' to read:
MozFest House will be open Monday 22rd - Friday 26th October between 9:00 and 23:00.

- [x] Remove the following two lines:

MozFest House features a free co-working space. To use the space, sign up here.

Note: With the exception of ViewSource, MozFest House events are hosted but not produced by Mozilla.

- [x] and replace them with

**Are you interested in hosting an event as part of MozFest House? Contact us at festival@mozilla.org**

- [x] Add a title above the event listings that reads: MozFest House 2017 

- [x] Remove the registration links from all the 2017 events

**Comment by edrushka** [comment]
@Saallen please confirm these changes to the House page. I've removed the "Introducing" language, updated the dates and removed sign-up links. I think we should continue displaying the 2017 listings for a while longer so people have an idea of what kind of events can take place here.

**Comment by Saallen** [comment]
Good idea- thanks all looks great

**Comment by ScottDowne** [comment]
@edrushka What are event listings? I don't see anything about that on the house page. (been a while since I've been thinking about mozfest so maybe it should be obvious what event listings are?)

**Comment by edrushka** [comment]
Event listings are the individual events that were featured in MozFest House 2017 (example image below). We'd like to keep 2017 events as a reference for now, as we are beginning conversations with potential new event hosts for 2018 and we'd like them to see what sort of events take place at MozFest House (since it's still quite new, not everyone is aware what can take place there). However, we don't need to display registration links. 

Later in the year (summertime) we'll delete the 2017 events and start adding 2018 events (with reg links) as they are confirmed.

![screenshot 2018-02-20 14 28 14](https://user-images.githubusercontent.com/4515662/36453095-b6829dc4-164b-11e8-8640-f15f4e8f0354.png)

**Comment by ScottDowne** [comment]
This one should be done now.
