### ISSUE TITLE
What to Expect page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#821]
Updates for What to Expect:

- [x] Update image for festival guide
- [x] Update video link to new video - LINK TBD
- [x] In Weekend Outline update dates to Fri Oct 26, Sat Oct 27, Sun Oct 28
- [x] change the Saturday party entry to just read '19:30 MozFest Party'

**Comment by edrushka** [comment]
New image for festival guide 
![screenshot 2018-02-09 16 52 04](https://user-images.githubusercontent.com/4515662/36056599-89c47ef4-0dba-11e8-9e88-02062d08e5fd.png)

**Comment by sabrinang** [comment]
@ScottDowne Updated spread thumbnail for 2017 guide is exported here: https://drive.google.com/open?id=1Ek3DKwBDW74vfQGC8gH1TKty7idvn8pv
![mozfest-2017_festival-guide-preview 2x](https://user-images.githubusercontent.com/2492510/37114608-acf94e52-21fd-11e8-8406-120ab3b7835c.png)

**Comment by edrushka** [comment]
ohhhh very nice Sabrina! 🎨
