### ISSUE TITLE
Media page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#823]
Updates to Media page

The following stories should be featured:
- [new addition] **The Culture Trip** [Artists, Activists and Open Web Advocates Are Gathering at This London Festival for Internet Health](https://theculturetrip.com/europe/united-kingdom/england/london/articles/artists-activists-and-open-web-advocates-are-gathering-at-this-london-festival-for-internet-health/) October 2017

- [new addition] **Marketplace** [Why is the internet so sick?](https://www.marketplace.org/2017/10/30/world/why-internet-so-sick) October 2017

- [new addition] **Heise** [MozFest 2017: Festival für ein besseres Internet](https://www.heise.de/ix/meldung/MozFest-2017-Festival-fuer-ein-besseres-Internet-3863398.html) October 2017 

- [new addition] **IFEX** [Anything but neutral: A digital rights Q&A](https://www.ifex.org/international/2017/09/29/digital-rights-defenders/) September 2017
- [already there] El País / Mozilla planta cara a los ‘trolls’ / November 2016 
- [already there] t3n / Wie steht es um die Gesundheit des Internets? Auf Spurensuche beim Mozilla-Festival / November 2016
- [already there] 3D Printing Industry / Exploring the Open Web at MozFest 2016 / October 2016
- [already there] American Libraries Magazine / MozFest 2016: Dispatch from a Librarian / November 2016
- [already there] The Independent / Baroness Kidron interview: ‘Children’s online safety is too vital to leave to Government’ / October 2014
- [already there] The Guardian / MozFest 2014: Creative Chaos - in the Best Way Possible / October 2014

**Comment by edrushka** [comment]
@KevZawacki can you please curate the list of stories you want on the Media page, ensuring there are a few highlights from 2017?

**Comment by KevZawacki** [comment]
Sure, @edrushka. To https://mozillafestival.org/media, let's add:

Marketplace

**The Culture Trip**
[Artists, Activists and Open Web Advocates Are Gathering at This London Festival for Internet Health](https://theculturetrip.com/europe/united-kingdom/england/london/articles/artists-activists-and-open-web-advocates-are-gathering-at-this-london-festival-for-internet-health/) October 2017

**Marketplace**
[Why is the internet so sick?](Why is the internet so sick?) October 2017

**Heise**
[MozFest 2017: Festival für ein besseres Internet](https://www.heise.de/ix/meldung/MozFest-2017-Festival-fuer-ein-besseres-Internet-3863398.html) October 2017 

**IFEX**
[Anything but neutral: A digital rights Q&A](https://www.ifex.org/international/2017/09/29/digital-rights-defenders/) September 2017

**Comment by edrushka** [comment]
@KevZawacki anything you want to delete?

**Comment by KevZawacki** [comment]
@edrushka Good question. Let's remove the 2011 & 2013 press hits. They're ancient!

**Comment by edrushka** [comment]
👍 I've updated the top comment. Thanks, Kev!
