### ISSUE TITLE
Tweet text

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#824]
- [ ] Update auto-filled tweet text to: "#MozFest 2018 will take place October 26-28 at Ravensbourne College. See you in London! www.mozfest.org"

**Comment by edrushka** [comment]
cc @KevZawacki @Saallen if either of you have more creative suggestions

**Comment by KevZawacki** [comment]
👍

**Comment by Saallen** [comment]
it's always good if it's a boast with a question
How about
" I just got my ticket for MozFest in London, from the 26-28 Oct. Will I see you there?

**Comment by edrushka** [comment]
We aren't putting tickets up for sale in this round of updates. Normally we do that later in the year. That tweet is perfect for when ticket sales open.
