### ISSUE TITLE
Bottom nav

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#825]
- [x] Remove 'Fringe Events' from bottom nav/banner

**Comment by ScottDowne** [comment]
@edrushka Question, if we are removing the link to the fringe events page from the footer like the description says. What does that mean for the page itself, should we delete it or do we have future plans for it?

**Comment by edrushka** [comment]
We'll keep the page. It's just not relevant now, and won't be populated with fresh data until September or so. Maybe 'hide' is a more accurate term than 'remove'.

**Comment by ScottDowne** [comment]
That works, and I think remove is technically the correct term, so you're fine there, I was just double checking.

**Comment by ScottDowne** [comment]
It is removed in that link I shared in the main 2018 ticket.

**Comment by ScottDowne** [comment]
On staging https://mozillafestival-org-staging.herokuapp.com/
