### ISSUE TITLE
Draft blog for 2018 dates announcement

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#829]
We'll be updating the website at the end of the month with the 2018 festival dates. We should have a corresponding medium blog to announce the big news. 

Here's what we did last year: https://medium.com/mozilla-festival/mozfest-2017-dates-announced-3ffdea8e55c2  I think this format works. 

@KevZawacki If we use last year's blog as a template, suggestions for any other details we should include?

cc @Saallen

**Comment by KevZawacki** [comment]
@edrushka No major changes. Let's be sure to plug a few of the 2017 talks, MozFest House, & press coverage.

**Comment by Saallen** [comment]
Could we add something about the theme? 
Would be good to start to seed the conversation around Data, and other areas that come from the Weds call

**Comment by KevZawacki** [comment]
Hi @edrushka, [here's our brief blog](https://docs.google.com/document/d/15EjbRpVxGWiqnZm0z4k7PkokfRcfakBZCtGY-o5HFOg/edit#) announcing the MozFest 2018 dates. Feel free to revise.

**Comment by edrushka** [comment]
Closing as we made this announcement. Thanks, Kevin!
