### ISSUE TITLE
Master List of May 2018 Updates

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#846]
# Website

### https://github.com/mozilla/mozillafestival.org/issues/851 Spaces & Experience page
- #850 Update Space Narratives/Descriptions from 
- #853 Update Space Wranglers names (no links, just plain text until we have bios)

### https://github.com/mozilla/mozillafestival.org/issues/853 Festival Team Page 
- https://github.com/mozilla/mozillafestival.org/issues/852 Update wrangler profiles (bio, photo, twitter, pulse)

### https://github.com/mozilla/mozillafestival.org/issues/854 Guideline Page
- https://github.com/mozilla/mozillafestival.org/issues/855 Update repo link to point to 2018 repo

### https://github.com/mozilla/mozillafestival.org/issues/872 Sponsors Page
_______________
# Call for Proposal Content

### CFP Confirmation Email
- https://github.com/mozilla/mozillafestival.org/issues/857 Write confirmation email
- https://github.com/mozilla/mozillafestival.org/issues/858 Set up automated confirmation email

### CFP Form
- https://github.com/mozilla/mozillafestival.org/issues/863 Write form
- https://github.com/mozilla/mozillafestival.org/issues/864 Legal review for form

### CFP Social
- https://github.com/mozilla/mozillafestival.org/issues/859 Write tweets 
- [mozfest-design-2018/issues/4](https://github.com/MozillaFoundation/mozfest-design-2018/issues/4) Social Graphics

### CFP Cheat Sheet
- https://github.com/mozilla/mozillafestival.org/issues/860 Write cheat sheet
______________
# Other
### https://github.com/mozilla/mozillafestival.org/issues/855 Program (Curation) Repo
- https://github.com/mozilla/mozillafestival.org/issues/877 Write readme for repo
- https://github.com/mozilla/mozillafestival.org/issues/878 Set up repo

### https://github.com/mozilla/mozillafestival.org/issues/862 Theme: Festival Tagline

______________________
### Follow up chats to determine scope 
- https://github.com/mozilla/mozillafestival.org/issues/867 l10n with Theo
- [ ] a11y with Emma
- [x] artist open web tech with Alan/Mw
- [ ] sponsorships with Stephanie
- [ ] volunteer feedback with Tom
- [x] design (tech) contractor with Mw / reach out to Cassie
- [x] guidebook confirmation (Jack?)

**Comment by sabrinang** [comment]
@Saallen Meta ticket for May 2018 updates. I referenced [last years ticket](https://github.com/mozilla/mozillafestival.org/issues/543) and notes from our call today. Please add anything that is missing and I'll be filing individual tickets for each page and linking back to the comment above for reference.

/cc @mmmavis

**Comment by Saallen** [comment]
Thanks 😁 - added some new updates above and made a new issue for https://github.com/mozilla/mozillafestival.org/issues/849
