### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#848]
Website updates for https://mozillafestival.org/

- [x] Update main banner heading, copy + button link with propose a session CTA 
- [ ] Update autofilled tweet text with proposal copy (from tweet #mozfest link on footer)
Last year's copy: _I just proposed a session for #MozFest 2017. Check out mine, and others, at [link to github repo with all sessions]._

**Comment by KevZawacki** [comment]
@Saallen How about: "Talks from activists, journalists and hackers on the front lines of internet health."

**Comment by sabrinang** [comment]
@caltrider Here is a mockup with the text and updated logo:
![landing-1_iteration](https://user-images.githubusercontent.com/2492510/40687053-3dbe53c4-634e-11e8-83ec-4652b200ee0e.jpg)

I made another iteration after seeing this in context too and would like to hear your thoughts. 

I changed the order of the top banner text so the submission cta text is closer to the deadline text. I also experimented with a gradient colour so it stands out. I simplified the body text and made the location more descriptive.
![landing-2_iteration](https://user-images.githubusercontent.com/2492510/40687054-3ddcc5d4-634e-11e8-8c34-d428306068ed.jpg)

**Comment by caltrider** [comment]
I really like your second iteration @sabrinang. The one with the gradient on the top bar and changed language. Looks great.

And the header without the second “come with an idea…” line, I like that best too

I think this works for the June 1st deadline. And then maybe next week we can dig into some design ideas to make that header bolder (and lose the background images too?)

**Comment by sabrinang** [comment]
@caltrider Great, thanks for the review! I also made both the banner and body copy to be "London, England" to be consistent.

@mmmavis  Here is the final copy for the June 1st deadline:

Top header:
> October 26-28, 2018 in London, England   |   Submit your session now for MozFest 2018!  Submission deadline is August 1.

Hero banner:
>  Where Web Meets World
October 26-28, 2018
Ravensbourne College in London, England
[button: Submit Your Session Now]

![landing-2_final](https://user-images.githubusercontent.com/2492510/40688181-02487762-6352-11e8-92e8-5e7514875fcb.jpg)

**Comment by sabrinang** [comment]
@mmmavis For the June 1st deadline, you do not need to revise content below this hero banner area. Can we also make the top header appear on all the other pages too?

**Comment by mmmavis** [comment]
@sabrinang 

> Can we also make the top header appear on all the other pages too?

Yup yup. Do we want the banner to show on mobile as well? I'm afraid it might take up a huge space on mobile and push everything down below the fold.

**Comment by sabrinang** [comment]
@mmmavis Yes it'd be preferable to have it on mobile as well but not too large that it takes up a lot of vertical space. Oh good point, if we don't want it to push everything down do you think we can have it below the hero area then?
![mobile-landing_iteration](https://user-images.githubusercontent.com/2492510/40689474-1edf8d66-6357-11e8-894b-43a1a66c323e.jpg)

**Comment by mmmavis** [comment]
@sabrinang changes are up: https://mozillafestival-org-sta-pr-894.herokuapp.com/ I'll let you decide whether or not we can close this ticket 😉

**Comment by Saallen** [comment]
Hey @caltrider @sabrinang - Loving the new banner, and using the space for more digestable info but I worry that our tag does not relate to the theme. Web meets world doesnt give any clue or make any connection with the data theme- which is super important to call out as it underpins Marks letter, and the space descriptions. Can we make a decision today on what [the tag](https://docs.google.com/document/d/1X2_EAyU6J2LuapT9SqAM3KPTstAIkjN22dMhDWLiW-0/edit) should be? 

I added my top two suggestions- please add you suggestions from list on the page or +1 already suggested.

**Comment by KevZawacki** [comment]
Hi @Saallen @caltrider 

Historically, the tagline has described that year's theme -- and so it changes each year. e.g. [the "One Web" tagline was used in 2016](https://www.flickr.com/photos/mozfest/30003179653/in/album-72157672259755823/), when the theme was digital inclusion. The tagline is mainly communicated to people already participating in the festival, so there is an existing understanding of what the festival is about. For that reason, I like "Data Done Right" and "Your Data and You" for 2018.

That said, I really love "Web Meets World." Perhaps we can use this turn of phrase with audiences like press, who don't have an inherent understanding of the festival.

**Comment by caltrider** [comment]
Thanks @KevZawacki, the clarification on how these tag lines are used helps.

@Saallen Given that the theme tag line is designed more for communication with people already participating in the festival, what do you think of keeping the "Where Web Meets World" on the landing page header as a way to welcome folks who might be new and give them an idea of Mozfest upon landing on the page? 

Then, next week as we dig into the user journey and redesign elements of the landing and about pages (and beyond) we can really think about how best to incorporate the theme around data to people who move past the initial landing page and into learning more or signing up to participate in the festival?

And I second Kevin, I like "Data Done Right".

**Comment by Saallen** [comment]
Sure- I just want it to be clear for those submitting sessions and those browsing the wesbite before they buy a ticket that the theme for 2018 is Data. So if we can encorporate that in other elements  I am happy- thanks

**Comment by sabrinang** [comment]
@Saallen Are we good to go with `Where Web Meets World` then and the language seen on staging? Please review: http://mozillafestival-org-staging.herokuapp.com/

**Comment by Saallen** [comment]
Yes -looks great

**Comment by sabrinang** [comment]
Closing - this work is continued on https://github.com/mozilla/mozillafestival.org/issues/963
