### ISSUE TITLE
What to expect page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#849]
Update to [what to expect](https://mozillafestival.org/expect)

- [ ] Sarah to update what is MozFest like 
- [ ] Accessibility blurb and blog link

**Comment by Saallen** [comment]
Closing this issue as other issues have replaced @sabrinang

**Comment by sabrinang** [comment]
refer to issue: https://github.com/mozilla/mozillafestival.org/issues/966
