### ISSUE TITLE
Space Narratives/Descriptions

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#850]
Space wranglers will submit a space narrative/description for their space. These submitted descriptions will be reviewed and will go on the Spaces & Experience page and on the call for proposals form for reference.

- [x] Draft of Questions for Call @Saallen 
- [x] Collect space descriptions from wranglers 16th May
- [x] Copy review and edit as lightly as possible so they read with a consistent voice

**Comment by sabrinang** [comment]
These will appear or be linked on the CFP form https://github.com/mozilla/mozillafestival.org/issues/863

**Comment by Saallen** [comment]
Drafts to collect

- [ ] Decentralization
- [ ] Web Literacy
- [ ] Openness
- [ ] Privacy and Security
- [ ] Digital Inclusion
- [ ] Youth Zone
- [ ] Queering MozFest

@kevin can you please link location or drop confirmed drafts into this issue

**Comment by Saallen** [comment]
Update- we will get Youth zone on Friday but all others collected- @KevZawacki will share edited and final descriptions

**Comment by KevZawacki** [comment]
@Saallen @sabrinang Here are the finalized descriptions for all spaces except Youth Zone: https://docs.google.com/document/d/1pCU_D90f7InJjVGcG-xBwAe7_j3D8sqrUCXliLbKirY/edit
