### ISSUE TITLE
Spaces & Experience page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#851]
Website updates for https://mozillafestival.org/spaces

- [x] Include “Propose a session” CTA
- [x] Update Space Narratives/Descriptions from https://github.com/mozilla/mozillafestival.org/issues/850
  - [ ] include link to artist open web: https://foundation.mozilla.org/opportunity/artists-open-web/
- [x] Update Space Wranglers names (no links, just plain text until we have bios https://github.com/mozilla/mozillafestival.org/issues/853)

**Comment by mmmavis** [comment]
@sabrinang wondering what the status is for this ticket. Is it ready for implementation?

**Comment by sabrinang** [comment]
@mmmavis Yes, youth zone description is included now. Please use space/experience text here: https://github.com/mozilla/mozillafestival.org/issues/850#issuecomment-390704087

Names from mozfest team sheet: https://docs.google.com/spreadsheets/d/1LAec8JWTO-lGlpNDRNgQBq1oyQrJ3IZrtiAwWgs5D60/edit#gid=318931669

**Comment by mmmavis** [comment]
@sabrinang Awesome! Thanks! Do you know where we wanna include `“Propose a session” CTA` and `link to artist open web`?

**Comment by sabrinang** [comment]
@mmmavis I'm thinking we can include the CTA button after the space intro.
![cta-location](https://user-images.githubusercontent.com/2492510/40631204-3e3afd6c-628f-11e8-9293-6770661ade24.jpg)

For the Artist Open Web link, let's include a text link after the description _(you can use the description paragraph from the website itself)_.
![link-location](https://user-images.githubusercontent.com/2492510/40631213-52cd34ca-628f-11e8-8232-c2de51cc6113.jpg)

**Comment by mmmavis** [comment]
@sabrinang cool that's helpful!

**Comment by mmmavis** [comment]
Done! 

I've only updated sections of the spaces & exp that are doing open curation. (Artist Open Web isn't one of them)

https://mozillafestival-org-sta-pr-894.herokuapp.com/spaces
https://mozillafestival-org-sta-pr-894.herokuapp.com/team/wranglers (this page is pretty bare though since we only have wranglers names for now. Not sure if it's worth coming up with an interim design solution...)
