### ISSUE TITLE
Space Wrangler Profiles (Bio & Photo)

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#852]
Space wranglers will submit a short bio, twitter handle and headshot photo for their profile. These will be reviewed and will be used on the Festival Team page [Wranglers section](https://mozillafestival.org/team/wranglers) and in the [printed festival handbook](https://issuu.com/mozfest/docs/mozfest_2017_festival_guide/18). We also mentioned the idea that wranglers create a profile on [Mozilla Pulse](www.mozillapulse.org) so we can link to that too.

- [x] Collect Wrangler bios
- [x] Collect hi-res headshot photo for print
- [x] Collect Twitter handle
- [ ] Collect Pulse profile

Please note that on Mozilla Pulse the bio limit is maximum 140 characters for wrangler bios it is 50 word max.

**Comment by sabrinang** [comment]
Space wrangler bio and photo spreadsheet here: https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit?usp=sharing

**Comment by sabrinang** [comment]
Looping @alanmoo & @xmatthewx to this ticket as @Saallen mentioned you have this discussed bios and Pulse. For the past wrangler bios, they use a a 50 word limit (pulse's limit is 140 char limit) and they are reviewed for consistency in tone/length and approved for the site and printed guide. A concern @mmmavis and I had is that wranglers would be able to change their bio anytime and it'd be too short. An idea is that we can link to the pulse profile similarly to how we link to twitter currently on the site (not printed guide).

Would love to hear thoughts and suggestions before we start collecting bios!

**Comment by xmatthewx** [comment]
Thanks @sabrinang. I think we should use Pulse bios since they give us dynamic profiles with links and projects and curated favs that wranglers can update. We can use the extended profile like we do with fellows for the official longer bio that we'll also put in print. They aren't yet displayed on Pulse but should be soonish ... and we should be able to pull them to a page on that website.

**Comment by mmmavis** [comment]
@xmatthewx If we decide to rely on Pulse profiles... will we be creating profiles on wranglers' behalves and curate their profiles ourselves? Or will we be asking wranglers to create their own profile?

**Comment by xmatthewx** [comment]
Similar to fellows .... ideally they create a bio and then we added the extended bio info on our end.

**Comment by sabrinang** [comment]
Shared out the spreadsheet to start collecting bios from today's wrangler call. We will use this static info until extended profile features is more complete/displayed and the UX seems strange to update on behalf of someone (unless they do not see it at all and it is editorial info we tie to profiles behind the scenes) but I think we should further chat about this and how we communicate this out to wranglers as their bios are submitted and will communicate out to create a profile in future calls. @xmatthewx @mmmavis

**Comment by sabrinang** [comment]
@KevZawacki Can you review these wrangler bios we have collected? https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit?usp=sharing

We may be missing 4 still so unsure if you want to lock edit access just yet but tagging you as we would like to update what we have.

**Comment by KevZawacki** [comment]
@sabrinang Certainly. I just reviewed and edited (small stuff -- commas, consistent capitalization, etc.).

I'll check in over the coming days to edit the outstanding bios.

**Comment by KevZawacki** [comment]
Hi @sabrinang, certainly. I've just reviewed + edited — everything in there is now final. 

I'll keep an eye our for tickets about the outstanding bios.

**Comment by mmmavis** [comment]
I'm gonna close this ticket since most bios and photos have been collected and the spreadsheet is now locked.

We can always create new tickets for future edits if needed. 😉
