### ISSUE TITLE
Festival Team page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#853]
Website updates for https://mozillafestival.org/team

- [x] Update year in titles to 2018

## Production Tab
- [x] Remove Erika, Chris, Marc, Esme and Dan
- [x] Add Sabrina and Mavis
- [x] Update sarah's  profile with [ text to follow]
- [x] @KevZawacki profile --@KevZawacki any updates other than the final sentence " 2018 will be Kevin's fifth MozFest."??
- [x] Update ziggys profile "Ziggy is one of the volunteer coordinators for MozFest 2018 and has been involved with the Festival since 2011. "

## Wrangler Tab
 https://github.com/mozilla/mozillafestival.org/issues/852 Update wrangler profiles (bio, photo, twitter, pulse)

## Partners Tab
- [x] Update Partners (or hide to go live during summer if we do not have them yet)

**Comment by sabrinang** [comment]
@Saallen do you want @mmmavis and I to submit a photo and bio for the Production section? Also this production team section might be related to the Pulse discussion regarding bios as well.

**Comment by mmmavis** [comment]
@Saallen 

I have a PR up already for removing Erika, Chris, Marc, Esme and Dan from the production team tab. Let me know if I can push it live first and tackle the rest of the todos in this ticket as a followup PR.

**Comment by mmmavis** [comment]
@Saallen just a reminder that we should come up with a "content being updated" type of message on those tabs we wanna hide. 🙈

**Comment by Saallen** [comment]
@sabrinang  and @mmmavis we should discuss if we want this page to reflect the wrangler page and link out to Network pulse pages??

**Comment by Saallen** [comment]
- [ ] Update sarah's  profile with [ text to follow

- [ ] @KevZawacki profile

@KevZawacki any updates other than the final sentence " 2018 will be Kevin's fifth MozFest."??

**Comment by Saallen** [comment]
Sarahs new bio
Sarah Allen is MozFest's Executive Director. She is passionate about designing learning and collaboration experiences that use art, culture and convenings to explore Internet health. Sarah draws her experience from a diverse events background in theatre, global sporting events and local community festivals. 2018 will be Sarah's 6th festival.

**Comment by rtsayles** [comment]
@saallen I am okay with my current bio.  Thank you for the opportunity again to be involved.  Blue Skies

**Comment by sabrinang** [comment]
Sabrina's bio for @mmmavis 

Photo: https://drive.google.com/open?id=1eSh2Q-5V_gC2EnT_feKtbBYioCBkRu1D

**Sabrina Ng**
_Creative Design Lead_

Sabrina is a user experience and interface designer for the Mozilla Foundation. She has led the design direction and production for the past two years and 2018 will be her sixth MozFest. She enjoys designing experiences that help build and connect communities.

**Comment by mmmavis** [comment]
@Saallen can you proof read / revise mine as well?

Mavis Ou
Festival Lead Engineer

Mavis Ou is Front-end Engineer for the Mozilla Foundation. She enjoys implementing user-facing features, and is always keen to make user experience in the software world better. 2018 will be Mavis' 6th MozFest.

**Comment by Saallen** [comment]
Sure
Mavis Ou is Front-end Engineer for the Mozilla Foundation. She enjoys
implementing user-facing features, and is always keen to make user
experience at Mozfest, and in the software world better. 2018 will be
Mavis' sixth MozFest.

What do you think?

**Comment by mmmavis** [comment]
@Saallen thanks for the edit! I'll get Sabrina's and my bios in now!

**Comment by sabrinang** [comment]
Filed #935, #936 and #937 for production page bio revisions in the next round. Closing this May ticket.
