### ISSUE TITLE
CFP Email: Write confirmation email for session proposal

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#857]
After people submit their MozFest session proposal via the website, we send them an automated confirmation email that contains: 

- confirmation message that session was successfully submitted
- Github ticket number
- Context for why and how you might engage on Github
- Instructions on how to get started on github
- Reminder that sessions will be curated until end of August

- [x]  decide l10n requirements

____________________
### Reference from Previous Years:

2017 email text: https://github.com/mozilla/mozillafestival.org/issues/563#issuecomment-304702191
2016 email text: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/28#issuecomment-220396714

**Comment by sabrinang** [comment]
**Update:** Since we decided to keep the call for proposal form https://github.com/mozilla/mozillafestival.org/issues/863 written in English only we do not need to localize this automated confirmation email to go along with it.

**Comment by Saallen** [comment]
Confirmation email

Hi <First Name>,

Thank you for submitting a session proposal for MozFest!

All proposals will be reviewed and curated on Github in the [MozFest 2018 program repo] (insert link) Curation will begin in August when the Call for Proposals closes. In early September, you’ll be notified whether your session has been accepted or not

Your session is documented in this issue: <Session name>[link to ticket].

We encourage you to follow the curation process on Github. You can chat with Space Wranglers (the people who curate sessions for each MozFest space), ask questions and share additional information in the comments section of your issue. 

If you're new to Github, this 45 second <video> [https://egghead.io/lessons/javascript-introduction-to-github]  will walk you through signing up for a free account.

Questions? Please reach out to festival@mozilla.org

Best,
The MozFest Team

PS - MozFest curation takes place in the open. This means some information, like your name and details about your proposed session, are visible in <your Github ticket> [link to ticket]. If you would like this information removed,  please let us know at festival@mozilla.org

cc @caltrider for review

**Comment by sabrinang** [comment]
@KGorr Please review https://github.com/mozilla/mozillafestival.org/issues/857#issuecomment-390659377 so @Saallen can finalize this text this week as we need time next week to implement it https://github.com/mozilla/mozillafestival.org/issues/858

**Comment by KGorr** [comment]
@sabrinang sorry for the delay, I wasn't notified about the tag! My only edit is to add the word "video" in the below sentence. It's currently missing above.

"If you're new to Github, this 45 second **video** [https://egghead.io/lessons/javascript-introduction-to-github] will walk you through signing up for a free account."

**Comment by mmmavis** [comment]
Cool. Thanks, team! 🌷 I'll have the email template updated!
