### ISSUE TITLE
CFP Email: Set up automated confirmation email for session proposal

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#858]
After people submit their MozFest session proposal via the website, we send them a confirmation email that contains copy from https://github.com/mozilla/mozillafestival.org/issues/857
____________________
### Reference from Previous Years:

2017 issue: https://github.com/mozilla/mozillafestival.org/issues/574
2016 issue: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/47

**Comment by mmmavis** [comment]
DevOps ticket filed to make sure Hatchet is still working: https://github.com/MozillaFoundation/mofo-devops/issues/591

**Comment by Saallen** [comment]
Proposed confirmation email for submissions -

Hi <First Name>,

Thank you for submitting a session proposal for MozFest!

All proposals will be reviewed and curated on Github in the [MozFest 2018 program repo] (insert link) Curation will begin in August when the Call for Proposals closes. In early September, you’ll be notified whether your session has been accepted or not

Your session is documented in this issue: <Session name>[link to ticket].

We encourage you to follow the curation process on Github. You can chat with Space Wranglers (the people who curate sessions for each MozFest space), ask questions and share additional information in the comments section of your issue. 

If you're new to Github, this 45 second <video> [https://egghead.io/lessons/javascript-introduction-to-github]  will walk you through signing up for a free account.

Questions? Please reach out to festival@mozilla.org

Best,
The MozFest Team

PS - MozFest curation takes place in the open. This means some information, like your name and details about your proposed session, are visible in <your Github ticket> [link to ticket]. If you would like this information removed,  please let us know at festival@mozilla.org


cc @caltrider for her review

**Comment by mmmavis** [comment]
Just tested it on staging and I did receive a confirmation email after submitting a proposal.

See screencap below (notice that `name of my sessions!` is actually the name I entered as a testing proposal name)

<img width="1025" alt="screen shot 2018-05-31 at 11 31 36 am" src="https://user-images.githubusercontent.com/2896608/40800904-78f6bb4c-64c6-11e8-8672-0a6d138459fc.png">
