### ISSUE TITLE
CFP Cheat Sheet: Write communication cheat sheet

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#860]
This is a public facing Call For Proposals communication cheat sheet for anyone to reference for sample tweets, email, and photos to share.
____________________
### Reference from Previous Years:

2017 Cheat Sheet: https://docs.google.com/document/d/1vBmHO7KGRub9DUV2XynQTAHOnURbh4Ijs9z-iDsK-uo/edit
2016 Cheat Sheet: https://docs.google.com/document/d/1H5SaffExxFdh5pOEBVKzARnS7eF5Cez9AFHzzgmB8y0/edit#

**Comment by Saallen** [comment]
assigned @KGorr as she has already begun working on this

**Comment by KGorr** [comment]
1st draft is here but still missing a lot of info and awaiting edits from the team: https://docs.google.com/document/d/1n9-EpBoRL8NkptSMd195U19vw5JZdIBhHvvjlHV77O8/edit#heading=h.mc4khivad8cs

**Comment by sabrinang** [comment]
@KGorr Is the communication cheat sheet copy complete? It needs to be review and finalized before passed to the localisation team. I filed a separate l10n issue here #903

**Comment by KGorr** [comment]
@sabrinang - yes, it's final! There was one open comment, just closed it. And thanks for making the new ticket.

**Comment by KGorr** [comment]
I edited the above link to be correct - sorry, it was originally pointing to an incorrect document but is now correct.

**Comment by sabrinang** [comment]
[Communication cheat sheet 2018](https://docs.google.com/document/d/1-_dszm-7RjtKn8KOF56HDv8NKOmWFWz_2QFEonAfrP4/edit#) is complete - closing ticket!
