### ISSUE TITLE
Mozilla Wiki: Create MozFest 2018 event and update content

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#861]
Update the Mozilla Festival Wiki https://wiki.mozilla.org/Mozilla_Festival

- [x] Create 2018 Event
- [x] Write vision & narrative 2018
- [x] Update space descriptions from https://github.com/mozilla/mozillafestival.org/issues/850
- [x] Write roadmap 2018
- [x] Update volunteer link

**Comment by Saallen** [comment]
@marcwalsh  its great to have you back 🎆

**Comment by sabrinang** [comment]
@Saallen Can you approve and publish? I currently do not see 2018
![image](https://user-images.githubusercontent.com/2492510/42785040-d21939a8-8905-11e8-9921-ece865e81bbd.png)

**Comment by sabrinang** [comment]
After looking into it the URL https://wiki.mozilla.org/Mozfest/2018 is live but is not linked from https://wiki.mozilla.org/Mozilla_Festival

**Comment by marcwalsh** [comment]
@sabrinang - it's all ready to be linked to on the parent page once it's signed off. 

I can make those changes once Sarah is back

**Comment by sabrinang** [comment]
@Saallen Please review so it can be linked from parent page

**Comment by marcwalsh** [comment]
Linked! 🌈
