### ISSUE TITLE
Artists Open Web page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#865]
This will be a new page featuring art projects curated by the mozilla artist studio team. Ideas and discussions are noted on this [gdoc](https://docs.google.com/document/d/1wSfCZiRsYmrp3-6GNWWIB6mgluLnxMDq3JrPWxtCGw8/edit?ts=5ad77769#heading=h.j7r07li6xsx4) but needs further discussion.

- [x] Scope out with Alan/Mw
- [x] Luca to submit project entries on Pulse

**Comment by sabrinang** [comment]
Luca has submitted entries into pulse https://www.mozillapulse.org/profile/504

From the google doc and previous discussion it seems like we want this to live on the foundation site with a simple index of the projects by year. Wireframe example:
![artist open web wireframe 2x](https://user-images.githubusercontent.com/2492510/39884239-fee46748-543d-11e8-9304-3e8f71e7b91b.jpg)

@xmatthewx @mmmavis @Saallen Can we meet to chat about next steps or if I should file this request in the foundation repo to get it in the queue? Let me know how I can help move this forward.

**Comment by mmmavis** [comment]
Hey @sabrinang , just realized you weren't cc'ed on the email thread. tl;dr @alanmoo has set up an opportunity page for Artist Open Web and it lives on https://foundation.mozilla.org/opportunity/artists-open-web/ 

I'll forward that email thread to you in case you wanna learn about the context.

**Comment by sabrinang** [comment]
@mmmavis Ah great, thank you for the update! Does this fulfill Luca's needs? Is there anything else that needs to be done or is this ticket complete?

**Comment by mmmavis** [comment]
Luca didn't mention anything in his latest reply so I assume everything is good for now?

**Comment by mmmavis** [comment]
> Great. I don't think we can build filters for this use case. We could make separate pages, if the pulse component could have a date range added to it. I'll add that to that discussion. Not sure how feasible that is...

@xmatthewx the `2018` `2017` labels are actually Pulse tags. But yea I don't know much about the Pulse project component on Foundation so I can't tell if that component can pull things based on tags.

**Comment by xmatthewx** [comment]
Ah okay. The component uses search, but search looks at tags. So that can work. Gavin will be iterating on the component for more granular control.

**Comment by Saallen** [comment]
Hey
I would like to amend the text and add an email address- I dont want this page to be passive but invite contributions through network pulse and conversations on the email thread. I will work with Luca next week to confirm text. If we are inviting other artists to upload to Network pulse- what should the ask be? Do we want them just to upload under tags or do we want them to create a profile? cc @xmatthewx @sabrinang @mmmavis

**Comment by xmatthewx** [comment]
It's always best for people to create a profile and post things themselves, that we have data on the areas of interest, links to social, so other people can connect with them. In the not too distant future, a site page could pull profiles of people, like it can currently pull projects. You can ask users to use a specific tag. If they don't do it right, we can always update it on the backend. When that's not possible, we can post things on people's behalf, like Luca did.

**Comment by alanmoo** [comment]
To add to that, the open artists page will pull in entries using the `Artists Open Web` automatically.
