### ISSUE TITLE
Proposals page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#866]
Website updates for https://mozillafestival.org/proposals

- [x] create form from https://github.com/mozilla/mozillafestival.org/issues/863 content
- [x] include proposals link in Top Nav
- [x] link in blogs and suitable examples

**Comment by sabrinang** [comment]
**Timeline:**
May 22-25 - Build
May 28-31 - QA / Buffer time
May 31 - Push Live
June 1 - Call for Proposals open

**Comment by sabrinang** [comment]
@Saallen Which blogs and suitable examples do you want to include on this proposals page?

**Comment by mmmavis** [comment]
# 2017 proposal page 

<img src="https://user-images.githubusercontent.com/2896608/39336759-0db0e132-496e-11e8-9dfe-38b3106d74e5.jpg">

**Comment by Saallen** [comment]
Blogs I would like are
* https://medium.com/mozilla-festival/what-makes-a-great-mozilla-festival-session-529dff105185
* Amira will be making a blog post or webinar - will be ready in next two weeks

**Comment by mmmavis** [comment]
@Saallen Where in the top nav do we wanna add link to Proposals page? As the first item? or?

**Comment by mmmavis** [comment]
Form is ready for QA: https://mozillafestival-org-sta-pr-894.herokuapp.com/proposals
Proposals will go to this testing repo and the sheet included in this README: https://github.com/MozillaFestival/test-mozfest-program-2018

@Saallen have we decided what blogs and examples we wanna include in the intro section?
