### ISSUE TITLE
Localization Strategies and Decisions

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#867]
We need to sort out localization decisions and conversations first before we dive deep into content that is dependent on it. 

- [ ] review results from l10n content and determine capacity to support l10n
- [x] l10n chat with Theo

**Comment by sabrinang** [comment]
cc/ @mmmavis @amirad

**Comment by mmmavis** [comment]
# Spanish version of proposal page (as of 2017-07-31)
### was on  `http://mozillafestival.org/proposals/espanol`

![screenshot-2018-4-26 mozilla festival 1](https://user-images.githubusercontent.com/2896608/39336807-4ac07e5c-496e-11e8-82c6-e21a58121d7c.jpg)

**Comment by mmmavis** [comment]
# French version of proposal page (as of 2017-07-31)
### was on  `http://mozillafestival.org/proposals/francais`

![screenshot-2018-4-26 mozilla festival 2](https://user-images.githubusercontent.com/2896608/39336844-716cd6e0-496e-11e8-8f82-2207de5affae.jpg)

**Comment by mmmavis** [comment]
# German version of proposal page (as of 2017-07-31)
### was on  `http://mozillafestival.org/proposals/deutsch`

![screenshot-2018-4-26 mozilla festival 3](https://user-images.githubusercontent.com/2896608/39336871-8ce69a8c-496e-11e8-864a-ab7085cf83b2.jpg)

**Comment by sabrinang** [comment]
L10n chat with Theo, Sarah & Mavis today and here is a recap.

### Decisions
- **Call for Proposals:** We decided to keep the call for proposal form in English only but Sarah will include an option in the form to submit a proposal in their language and to indicate the language.
### Ideas
- **Registering Tickets:** We discussed that we want to ask attendees about their language preference and will have this information in late August. 
- **Hiring live or consecutive translators:** We discussed that we can help set expectations that English is the default but can try to support 1-2 other languages in the Dialogues & Debates space based on preferences indicated. These interpreters will need to be professionals not volunteers and will need to budget for it.

**Comment by Saallen** [comment]
Hi

- [x]  lets continue to localise tweets- we have a very geographically spread wrangler team so we can use them to help but would also be really nice for them to be able to tweet about this event in their locals.

- [ ] Let me double check that the participation guidelines have not changed but if not, lets stick with same text

- [x] Yes lets print 7 predetermined languages. French, Spanish, German, Hindu, Swahili definitely- you can choose the last 2 

-[x] Yes, lets localise these posters and choose the top languages from submission labels of last year, which were French, German, Spanish and Hindu. I am going to add Swahili too as we have three wranglers that speak that language

**Comment by Saallen** [comment]
cc @sabrinang all confirmed for this page

**Comment by Saallen** [comment]
cc @KGorr
