### ISSUE TITLE
Update sponsors page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#872]
Update sponsor page and allocate work

- [x]  Juan and Jesse to review [content](https://mozillafestival.org/team/sponsors)
- [x]  https://github.com/mozilla/mozillafestival.org/issues/879 fix email sponsor@mozilla.org and replace with festival@mozilla.org in the meantime
- [x] Host kick off meeting with 🥇 team

CC @sabrinang & @stephwright for info

**Comment by sabrinang** [comment]
**Sponsorship Meeting Recap** _(with Juan, Stephanie, Jessie)_
* Website update:
    * Juan has new text
    * 2018 will have different category names    
    * move 2017 sponsors down to make room for 2018 on top
    * look for photo of sponsors to include _(in context around people or swag)_
    * Consider including text explaining _what is the difference between partners and sponsors?_
        * partners are helping us to build mozfest (not monetary) and support in different ways
        * we can consider update the Partners tab instead too

@jcbarajas Please provide any new text for the sponsor page 
@Saallen or I to look for photos of sponsors

**Comment by stephwright** [comment]
Should we include some pictures of what sponsorship looks like?  Like these?
1. https://westraco.pixieset.com/mozfest2017/f/5542242/?pid=1477552117&id=5&h=MjM5NjIzMjUwMw 
2. https://westraco.pixieset.com/mozfest2017/f/5542242/?pid=1477938803&id=6&h=MzYzMjAzNjgwMQ 
3. https://westraco.pixieset.com/mozfest2017/f/5542242/?pid=1477938998&id=7&h=NDA3NDQwNTk1Mw 

I was looking for one of coffee stands but didn't see one from last year... maybe previous years?

**Comment by Saallen** [comment]
@sabrinang Can you choose what photo you want here as this is the only piece missing from this page to be updated. please apply whatever design you want

**Comment by sabrinang** [comment]
This photo is good: https://westraco.pixieset.com/mozfest2017/p/MTQ3NzUwMjg4MA==-MjM5ODY2MTYwNQ/ (it is also available on the gdrive [here](https://drive.google.com/file/d/196AyS_iyI7EDmJN-JQjn1BJmwhcWc-LJ/view?usp=sharing))

It can be placed near the bullets to break up the long section of copy.

![mozilla-festival_sponsors-page](https://user-images.githubusercontent.com/2492510/42065248-b4fc32f0-7aee-11e8-98c3-4a09514168dd.jpg)

**Comment by Saallen** [comment]
Looks great - goood to update

**Comment by sabrinang** [comment]
Closing - this will continue on implementation issue https://github.com/mozilla/mozillafestival.org/issues/981
