### ISSUE TITLE
Write Readme for 2018 Program (Curation) Repo

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#877]
### Reference from Previous Years:

2017: https://github.com/MozillaFoundation/mozfest-program-2017/blob/master/README.md
2016: https://github.com/MozillaFoundation/mozfest-program-2016/blob/master/README.md

**Comment by Saallen** [comment]
✨ Done- updated text and added some new content. In good shape to open the call for proposals.
