### ISSUE TITLE
Set Up 2018 Program (Curation) Repo

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#878]
**Suggested name:** mozfest-program-2018

This keeps with convention set last year and the year before. This will use readme copy from https://github.com/mozilla/mozillafestival.org/issues/877

____________________
### Reference from Previous Years:

2017: https://github.com/MozillaFoundation/mozfest-program-2017
2016:  https://github.com/MozillaFoundation/mozfest-program-2016

**Comment by sabrinang** [comment]
@Saallen Please review copy for `ISSUE_TEMPLATE.md`

**Comment by mmmavis** [comment]
@Saallen thanks for adding in the updated README! For `ISSUE_TEMPLATE.md` do you think we can reuse what we had last year? See https://github.com/mozilla/mozillafestival.org/issues/878#issuecomment-385557695 for context 😉

**Comment by mmmavis** [comment]
@Saallen cool I will have it added to the 2018 repo.

**Comment by mmmavis** [comment]
Done! https://github.com/MozillaFoundation/mozfest-program-2018/issues/new

<img width="1008" alt="screen shot 2018-05-14 at 5 41 02 pm" src="https://user-images.githubusercontent.com/2896608/40030186-0674dbb0-579e-11e8-8abc-2fa4b7e55e3a.png">
