### ISSUE TITLE
QA Sponsors Page Email

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#879]
@Saallen mentioned that sponsor@mozilla.org is not working. Juan has mentioned [Mike Poessy](mpoessy@mozilla.com) has set up this email with Erika.

@mmmavis Can you find out what is wrong with the email or if it is misspelled? In the meantime, can you change email to be festival@mozilla.org?

**Comment by mmmavis** [comment]
@sabrinang by "not working" did you mean we are not receiving emails sent to sponsor@mozilla.org???

Spelling looks right on the site (sponsor@mozilla.org) so I'm not sure what went wrong. I will change it to festival@mozilla.org until the issue gets resolved.

**Comment by Saallen** [comment]
when I email sponsors@ I get error messages and unable to deliver messages

**Comment by Saallen** [comment]
@mmmavis already filed. Jlin looking into it

**Comment by mmmavis** [comment]
@Saallen alrighty good to know!

**Comment by mmmavis** [comment]
Email updated on the site: https://mozillafestival.org/team/sponsors

@sabrinang I'll let you decide if we can close this ticket.

**Comment by Saallen** [comment]
@mmmavis sponsor@mozilla.org is now up and running-
Can you please amend ? 🌷

**Comment by mmmavis** [comment]
Ah good (bad) timing! I just got it changed to festival@mozilla.org but I'll change it back to sponsor@mozilla.org .

**Comment by Saallen** [comment]
I know- SORRY about that

**Comment by mmmavis** [comment]
Done! Changed it back to sponsor@ 

https://mozillafestival.org/team/sponsors
