### ISSUE TITLE
Write Design Contractor Posting

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#880]
Write a posting for a design contractor to help with MozFest design assets. It would include:

- responsibilities
- qualifications 
- timeline
- location

I will look for previous postings as reference.

___________
### Reference from Previous Years:
2016: 
- review assets https://github.com/MozillaFoundation/Mozfest2016_production/issues/11
- scope of work https://github.com/MozillaFoundation/Mozfest2016_production/issues/12
- write description https://github.com/MozillaFoundation/Mozfest2016_production/issues/45
- advertise, shortlist, contract https://github.com/MozillaFoundation/Mozfest2016_production/issues/23

**Comment by sabrinang** [comment]
I'm working on the posting here: https://docs.google.com/document/d/1gsW3Nr-Tb8xzFtPQYow8p6Q6yd2_LNWF_JdXzrbQ-ic/edit

**Comment by sabrinang** [comment]
@Saallen @xmatthewx Can you give me feedback and review this posting for the graphic design position: https://docs.google.com/document/d/1gsW3Nr-Tb8xzFtPQYow8p6Q6yd2_LNWF_JdXzrbQ-ic/edit

**Comment by sabrinang** [comment]
I've updated the posting https://docs.google.com/document/d/1gsW3Nr-Tb8xzFtPQYow8p6Q6yd2_LNWF_JdXzrbQ-ic/edit and used Textio and got 90 score https://textio.com/?l=wljqqnz

**Comment by xmatthewx** [comment]
Looks great! Nice job with textio score! Just added one small suggestion to the doc.

**Comment by sabrinang** [comment]
The doc was updated with _how to apply_ and _deadline_ details and final post is here: https://textio.com/?l=bglkjcn It has been shared with Stephen and Mandy last week to kick off the process along with posting board urls, timeline and salary suggestions.
