### ISSUE TITLE
List of potential photos to use in Website

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#885]
@sabrinang 
list of photos to grab and use for website page updates

1. [Christine talking to a crowd](https://goo.gl/GN35Ch)
2. [(Science Fair pitch](https://goo.gl/o2g8f7)
3. [science fair w Erase all kittens]( https://westraco.pixieset.com/mozfest2017/p/MTQ3NzUwODQzMw==-MzUwMDQ3Njc0NA/)
4. [Solana on stage](https://westraco.pixieset.com/mozfest2017/p/MTQ3NzUwNjE0Nw==-MTk5OTQ1MTMzNg/)
5. [audience participation](https://westraco.pixieset.com/mozfest2017/?pid=1477502609&id=51&h=Mjc0MDgxNjA4Ng)
6. [africacodeweek](https://westraco.pixieset.com/mozfest2017/?pid=1477494353&id=85&h=MTYyODQ2OTg2Mg)
 [postitmagic] (https://westraco.pixieset.com/mozfest2017/?pid=1477490904&id=99&h=MjQ5Mjg5OTAwMA)

**Comment by sabrinang** [comment]
note to self: document this in design doc

**Comment by sabrinang** [comment]
set of photos noted - closing.
