### ISSUE TITLE
Investigate GitHub Orgs and GitHub Teams

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#887]
See if we can create GitHub Teams for each Space wrangler team. Find out what potential risks there are gonna be (e.g., Does inviting non-staff to Foundation's GitHub org give those people full access to all the repos we own etc)

---

## Benefits of using GitHub Team:

1. we can tag each team on our curation repo by `@MozillaFoundation/name-of-the-team` (say Person A, B, C are on the same team, by `@MozillaFoundation/name-of-the-team` these 3 people will all get tagged/notified
2. when a proposal ticket gets posted on GitHub, we can cc the team in that ticket (so every wrangler on that team is aware of the activities happening in that proposal ticket)
3. each Team will have its own "space" like https://github.com/orgs/MavisTest/teams/team-yvr where they can post discussion and stuff (note everything there is visible to public)

## Possible risks
1. need to check if we can add non-staff to MozillaFoundation GitHub org
2. need to check if by doing this we are giving wrangler full access to all our Foundation repos

**Comment by sabrinang** [comment]
@mmmavis Yup!
![mozilla-festival-2017_profile](https://user-images.githubusercontent.com/2492510/40394335-e3d59e6a-5dd7-11e8-90c0-27a012a2451e.jpg)

**Comment by mmmavis** [comment]
Done! 

Our MozFest GitHub Org: https://github.com/MozillaFestival
Teams have been also created.
