### ISSUE TITLE
Call For Proposals Outreach List

### ISSUE THREAD

**Issue by zee-moz** [mozilla/mozillafestival.org#888]

**Comment by amirad** [comment]
List of people to do 1-1 outreach initiatives with:
Clubs (I can message our channels and we can ask Christos to email other clubs list)
Hives (we can ask messaging to be shared on their new mailing lists)
Reps (direct email and call)
L10N (direct email and post on discourse)
MDN (direct email and post on discourse)
Techwomen (direct email to all past Moz TW)
Open Leaders (Abby to sent direct email) --> do we set up call?
Mozsprint (Zannah to send direct email) --> do we set up call?

@zee-moz - how's that for a start?

**Comment by sabrinang** [comment]
Any updates on this ticket? Can we close if emails have been sent @amirad ?

**Comment by amirad** [comment]
Yes, actually. All of those emails have been sent!
