### ISSUE TITLE
Let's gather an FAQ for Session Proposals

### ISSUE THREAD

**Issue by zee-moz** [mozilla/mozillafestival.org#889]

**Comment by Saallen** [comment]
@amirad  do you have the link ready for the call for proposals page??
cc @mmmavis

**Comment by amirad** [comment]
Yup, sorry. Was in the middle of writing it but you have the link for publishing purposes 
https://docs.google.com/document/d/16I55way_DQeFXII1CLtY--p8BXcIMb9bhPQAavWZmLY/edit?usp=sharing

**Comment by Saallen** [comment]
AWESOME - 🌷 

@mmmavis please add to other links

**Comment by mmmavis** [comment]
FAQ link added! http://mozillafestival-org-staging.herokuapp.com/proposals
