### ISSUE TITLE
Call for Proposals Graphic

### ISSUE THREAD

**Issue by KGorr** [mozilla/mozillafestival.org#890]
It would be great to have a graphic to include in email communications and social media for the Call for Proposals. 

Communications will be distributed the week of June 4.

Last year's graphics for reference: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eLURVNVEtNVhGQ3M

**Comment by KGorr** [comment]
cc: @Saallen

**Comment by Saallen** [comment]
assigning Sabrina here. 
@sabrinang do you think can can make a graphic as per request?

**Comment by sabrinang** [comment]
@KGorr What text do you want on these CFP graphics if any? Are we using text from last year or are we using something from https://github.com/mozilla/mozillafestival.org/issues/859 ?

**Comment by Saallen** [comment]
Yes!

**Comment by KGorr** [comment]
@sabrinang - last minute change regarding the language. Instead of "call for proposals," we need it to say "submit a session"

Thanks!

**Comment by sabrinang** [comment]
@KGorr Ok, I will only use the `Submit a session for MozFest` copy only then and it was localised last year (in German, Spanish, French): https://l10n.mozilla-community.org/langchecker/?website=6&file=social/2017/mozfest.lang&action=translate&show so I'll refer to this as well

**Comment by KGorr** [comment]
@sabrinang Thanks so much! We'll see if @TheoChevalier can get translations for Hindu, Swahili as well to add to the mix.

**Comment by sabrinang** [comment]
@KGorr Thanks for pointing out the other two languages and I have filed the l10n issue separately here https://github.com/mozilla/mozillafestival.org/issues/904

**Comment by KGorr** [comment]
@sabrinang - We're sending out a handful of CFP emails next week. Is there a graphic we can use for those? If not, totally cool - I'll just pull a festival image from last year for those. Thanks!

**Comment by sabrinang** [comment]
Work is tracked on https://github.com/MozillaFoundation/mozfest-design-2018/issues/4 - closing ticket.
