### ISSUE TITLE
QA- Spaces page- Decentralization

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#897]
Two ways of spelling decentralization here? We as a festival use the z - cc@kevin for response
CC @mmmavis for changes

Decentralization

Can the world be decentralised?

In this parallel dimension, people self-organise into open groups that create art, write code, and even build cities. Their technology runs on consensus and their society is fuelled by data. But data is not just a resource — it’s an extension of individual identity and collective culture. People give informed consent to data gathering and enjoy transparency of use.

Journey to a new world and bring back powerful, resilient technology; explore radical, paradigm-shifting ideas; and take part in cutting-edge discourse. Explore protocols like DAT, IPFS and ActivityPub, alongside ideas such as net neutrality and proof of stake. Experience decentralised platforms like Matrix and Mastodon, and support the equal commons of all.

Let’s discover this wonderland, together.

**Comment by KevZawacki** [comment]
Hi @Saallen & @mmmavis 

Per a similar issue -- let's use "s" instead of "z" in all instances. And, capitalize "Internet." Latest updates [here](https://docs.google.com/document/d/1pCU_D90f7InJjVGcG-xBwAe7_j3D8sqrUCXliLbKirY/edit). 

Pardon the confusion!

**Comment by Saallen** [comment]
For Internet health report Decentralization is with the z- last year we aligned- and took the z in this instance (and only one :)) Do we want to differ?

**Comment by KevZawacki** [comment]
@Saallen For consistency, I'm okay with using "s" throughout this year

**Comment by mmmavis** [comment]
Fixed on the website!
