### ISSUE TITLE
QA- Spaces page- Youth zone

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#898]
QA- Internet here is spelt with a small i- please change to a capital I @mmmavis 
CC @KevZawacki 

The future of the **internet** is in our hands.

Young people and those who support them are excited to build a healthier **internet** that empowers us to solve problems and achieve our dreams. We see a future that defies expectations and promises more inclusion, agency, and shared ownership online. By learning and playing with all kinds of potential solutions in this space, we young people and our allies will share what we think of the **internet** and work to make it better.

Join us for a weekend of hands-on experiences that immerse participants in young people's ideas about what the internet can be. Participants will bring home new creations, new understandings of **internet** health, and ways to stay connected via youth-led conversations and projects.

**Comment by mmmavis** [comment]
Fixed
