### ISSUE TITLE
CFP Cheat Sheet: Localise communication cheat sheet

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#903]
Based on content in issue https://github.com/mozilla/mozillafestival.org/issues/860

We are requesting that the communication cheat sheets be localised in 5 languages (French, Spanish, German, Hindu, Swahili).

/cc @KGorr @Saallen

**Comment by sabrinang** [comment]
Final communication cheat sheet copy here: https://docs.google.com/document/d/1-_dszm-7RjtKn8KOF56HDv8NKOmWFWz_2QFEonAfrP4/edit#

**Comment by TheoChevalier** [comment]
Translation is ongoing, status can be checked here https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2018/mozfest.lang

**Comment by KGorr** [comment]
@TheoChevalier - Please note that the theme for MozFest was tweaked since writing the cheat sheet. It is now "Data Done Right" instead of "Data And You". Within the english cheat sheet, I have adjusted both the email subject line and the theme reference in the 3rd paragraph in the email. Can you please have it adjusted in the work being done to localize as well? Thank you and sorry for the inconvenience.

**Comment by TheoChevalier** [comment]
Thanks @KGorr , strings updated!

**Comment by sabrinang** [comment]
@KGorr Any updates on this issue?

**Comment by TheoChevalier** [comment]
Hi, here’s the latest status:

Locales fully ready: de, fr, it, pt-BR, sw

es is missing 4 strings (Data done right seem challenging in Spanish)
hi-IN is missing 13 strings

Detailed status: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2018/mozfest.lang (Note it also includes the 3 strings just added in https://github.com/mozilla/mozillafestival.org/issues/992)

Translations: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2018/mozfest.lang&action=translate&show

**Comment by sabrinang** [comment]
The status looks like 3 locales are still in progress, moving to this heartbeat

**Comment by sabrinang** [comment]
@KGorr Can we close? It seems like sharing out the comms cheatsheet has passed

**Comment by sabrinang** [comment]
Since CFP is over, we are closing this issue.
