### ISSUE TITLE
CFP Social: Localise Call for Proposal language for graphic

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#904]
We want to localise this English copy in Hindu & Swahili.
en | `Submit a session for MozFest`

We also already have it in German, Spanish and French from last year https://l10n.mozilla-community.org/langchecker/?website=6&file=social/2017/mozfest.lang&action=translate&show:

de | `Schlagen Sie eine Sitzung für das MozFest vor`
es | `Enviar una sesión para MozFest`
fr  | `Proposez une session pour le MozFest`

cc/ @KGorr @Saallen

**Comment by TheoChevalier** [comment]
And to confirm here too, I’ve imported the existing translations and exposed the string for other locales. It’s the first string here https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2018/mozfest.lang&action=translate&show

**Comment by KGorr** [comment]
@sabrinang - A Space Wrangler requested we create the graphic in Portuguese and provided the text.

Submit a session => Envie uma sessão
for MozFest => para MozFest

Is this a request we can fulfill? Thanks!

**Comment by barrosgeraldo** [comment]
Hi @KGorr, thank you for move this forward, I forgot to add one more element of the translation, I'm sorry, rewriting here with the complete sentence now.
` pt-br | Envie uma sessão para o MozFest`

**Comment by sabrinang** [comment]
Graphics are finished in https://github.com/MozillaFoundation/mozfest-design-2018/issues/4 with all 7 languages.
