### ISSUE TITLE
QA- Production page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#908]
In kevins bio please amend the last line
Change- 2017 will be Kevin's fourth MozFest.

TO- 2018 will be Kevin's fIfth MozFest.

**Comment by Saallen** [comment]
Plus where are you pair @sabrinang and @mmmavis ???

**Comment by mmmavis** [comment]
@Saallen kk will update Kevin's bio! I can add mine in today if short bio's okay. 😂 Where in the list should we add ourselves? Before the 3 volunteer coordinators?

**Comment by mmmavis** [comment]
k i updated Kevin's bio and added my bio in.

**Comment by mmmavis** [comment]
Done!
