### ISSUE TITLE
Guidelines page: Raising Issues at MozFest

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#915]
Met with @trallard and @chadsansing today to talk about D&I at MozFest.
Current reporting structure is to festival@mozilla.org- with Gunner and myself as sole receipients.

Festival reporting structure is
* Festival@
* info desk onsite
* phone number

@trallard has some suggestions for updating the reporting structure to be more transparent.

**Comment by marcwalsh** [comment]
@Saallen I think it's a good idea to make the reporting structure more transparent. If it is just you and Gunner as sole recipients, I would recommend having a different mailbox set up other than festival@ as it's the 'reply to' and main site linked to ticketing and contacting about general enquires about the festival which might be busy over the weekend for pieces that are not about incident reporting / can be handled by other members of the team.
