### ISSUE TITLE
Short description about MozFest to help boost up SEO for our site

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#918]
Let's add a short description about MozFest as page meta (this is not visible on the page but is used for search engines to crawl info) to help boost up SEO. Ideally it should include the word Mozilla Festival AND MozFest so help drive both search terms to our site.

For ref - this is what we currently have for the About page 

> Mozilla's annual, hands-on festival (affectionately known as MozFest) is dedicated to forging the future of the open Web.

and What to Expect page

> MozFest is an annual celebration of the world’s most valuable public resource: the open Web.

I think this can probably explain why these pages showed up as top 2 results when I searched "MozFest" on Google because both of descriptions include the word "MozFest".

---

(Home page's description meta currently is `Three days of building a truly global web together. Come with an idea, leave with a community.`)

**Comment by mmmavis** [comment]
@Saallen could you help tag the right person to come up with copy for this?

**Comment by Saallen** [comment]
Hey @caltrider - the mystery is solved- do you want to write copy for this?
would be great to update asap

**Comment by caltrider** [comment]
Here you go @mmmavis and @Saallen 
Approved by Sarah Allen: 
- [ ] 

Home Page Meta:
MozFest brings the world together to leave the internet better than we found it. Mozilla, the non-profit behind the Firefox browser, invites you to our annual festival in London, England.  Come shape our best future online.

And I think we should leave the About Page Meta as is for now until we can get the updates done. It's working as is and then once we've updated, we can update the meta description to better describe it.

**Comment by Saallen** [comment]
Returning @caltrider 👀  to this ticket- thanks for the updated copy but
I missed @mmmavis key question though- should we use two key words mozFest and mozilla festival?? Should we use both words here?

cc @zee-moz for comments also

**Comment by zee-moz** [comment]
my 2 cents: I would try to get Mozilla Festival in there if that's a common search term.
not sure about "leave the internet better than we found it" -- I like the direction, although to me "leave" is kind of a passive a verb, and it implies we're doing stuff and then going away, offline...  whereas we want more engagement, more communities, more creativity, more activism, more awesomeness.

I really like "come shape our best future online." 

Are there other search terms, like or "interactive festival" or "technology conference"  or "internet festival" that would bring people to the site who aren't specifically looking for MozFest? I don't know anything about SEO but it seems like it might be good to be listed in searches for these topics....

**Comment by Saallen** [comment]
Taking on board all feedback

Final copy -

MozFest brings the world together to leave the internet better than we found it. Mozilla, the non-profit behind the Firefox browser, invites you to our annual interactive festival in London, England. Come shape our best future online.

**Comment by Saallen** [comment]
cc @mmmavis for changes

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/

Expect the changes to show up in search result after a few days/weeks delay though as search engines usually cache site meta.
