### ISSUE TITLE
New wrangler additions

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#922]
Hold  changes until confirmed

- [x] Add Brehan Taye under Web literacy
- [x] Add Tendai Tirivanhu to Decentralisation
- [x] Remove Emma Humphries from Queering MozFest
- [ ] Update Tom Farrow bios

**Comment by mmmavis** [comment]
@Saallen you meant `Berhan Taye`, right? (assuming `Brehan` was a typo)

**Comment by Saallen** [comment]
Yes @mmmavis 

I put Dennis in the wrong space- can you move him under Openness?
He is not part of web literacy

**Comment by mmmavis** [comment]
@Saallen 

https://mozillafestival.org/team/wranglers#Dennis-Ndegwa

Dannis is already under Openness on the Team page! 👍

**Comment by mmmavis** [comment]
There's a separate ticket for updating Tom Farrow's bio.

I'm closing this ticket now.
