### ISSUE TITLE
Theme: Localise tagline for MozFest 2018

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#923]
Based on https://github.com/mozilla/mozillafestival.org/issues/862

The official tagline for MozFest 2018 is ` Data Done Right`

We are requesting for this to be localised in 5 languages: French, Spanish, German, Hindu & Swahili.

/cc @Saallen @KGorr

**Comment by sabrinang** [comment]
Hi @barrosgeraldo, would you be able to help translate this in pt-br Portuguese?

**Comment by TheoChevalier** [comment]
Exposing this string on Pontoon in a bit. @sabrinang is there any length requirement? Is this integrated in a specific graphic?

**Comment by sabrinang** [comment]
@TheoChevalier This will be used for a combined tagline poster with all translations. No length requirement but if they are roughly similar lengths that would be great.

Here are references from previous years if it helps:
2017 (combined poster): https://redpen.io/sz54fe6ed81c7f8dd3
2016 (separate poster): https://redpen.io/p/dx247add31f0157531

**Comment by TheoChevalier** [comment]
Thanks! String exposed, translations will appear right under “Submit a session for MozFest” https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2018/mozfest.lang&action=translate&show

**Comment by barrosgeraldo** [comment]
`pt-BR | Dados: do jeito certo`

**Comment by sabrinang** [comment]
@TheoChevalier any updates on hi-IN for `Data Done Right`? The only translation we are missing

**Comment by TheoChevalier** [comment]
Hi @sabrinang, it’s currently stuck in review, but the team should be done with it by the end of the week

**Comment by TheoChevalier** [comment]
Actually this string has been approved yesterday, so we’re good to go here!

**Comment by sabrinang** [comment]
Thanks Theo!

https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2018/mozfest.lang&action=translate&show#string2 is complete - closing issue
