### ISSUE TITLE
Master Ticket Page Issue

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#924]
This is a master ticket for updates to https://mozillafestival.org/tickets
Copy issue: #927
Design issue: #1002
Implementation issue: #926

______________

~~https://mozillafestival.org/tickets~~

~~We need to update the language, links and dates on this page.~~

~~Things to consider:~~
~~- do we continue using the abbreviation MozFest or include Mozilla Festival?~~
~~- do we need tickets for MozFest House?~~

**Comment by Saallen** [comment]
Moving heart beats

**Comment by Saallen** [comment]
Updating this ticket with key actions for this heartbeat
- [ ] @consuelamckenzie and @marcwalsh to share copy for tickets
- [ ] @caltrider and @zee-moz approve copy
Once two actions are complete @sabrinang will update content for webpage
- [ ]  Sabrina updates [webpage](https://mozillafestival.org/tickets)for approval on redpen
- [ ]  @consuelamckenzie approves redpen
- [ ] @mmmavis updates page

**Comment by sabrinang** [comment]
Please note to file new tickets as it changes scope of tickets assigned to heartbeats and the initial intent of tickets and keep in mind assignees do not get notified of edited comments.

I’ll be updating issue name and description as this issue has altered to track work correctly.

**Comment by sabrinang** [comment]
Updates for https://mozillafestival.org/tickets is live - closing issue.
