### ISSUE TITLE
Tickets page: Copy 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#927]
~~https://ti.to/Mozilla/mozilla-festival-2018~~

~~When ticket sales are open we need to update the ticket descriptions and copy.~~

We need to update the language for https://mozillafestival.org/tickets page.

**Comment by sabrinang** [comment]
@Saallen Will start this and hand off to production manager when hired.

**Comment by Saallen** [comment]
Working on this now
Almost ready about from full legal review and GDPR compliancy
Moving to heart beat

**Comment by Saallen** [comment]
Ok- we are just confirming what tickets to sell so once we agree @marcwalsh @consuelamckenzie

we will loop in kevin for edits

**Comment by zee-moz** [comment]
I also made some copy editing suggestions, and some comments on formatting and order.

**Comment by Saallen** [comment]
Update- @marcwalsh @consuelamckenzie will make amendments to this page by Tuesday 10th as we have new formatting for tickets- TITO PAGE WILL be live by EOD tues, for massive promotional mail out with @KGorr

**Comment by sabrinang** [comment]
Sorry for the confusion regarding this copy ticket as it was initially for the ti.to ticket page https://ti.to/Mozilla/mozilla-festival-2018 but I think copy was completed directly in the implementation ticket here https://github.com/mozilla/mozillafestival.org/issues/929 so this should of closed.

This looks like it has become the copy issue for the /tickets page here https://mozillafestival.org/tickets which was initially here https://github.com/mozilla/mozillafestival.org/issues/924 but it has also changed into a master ticket. 

I’ll be updating issue name and description as this issue deliverable use has altered to track work correctly.

**Comment by sabrinang** [comment]
Please refer to mockup options in https://github.com/mozilla/mozillafestival.org/issues/1002#issuecomment-405757146 to help inform and finalize this ticket copy.

**Comment by sabrinang** [comment]
Copy updated from comments: https://docs.google.com/document/d/1Yz0xET9I5fji9MFEt3ri0YC4vdRQesKZkt2YzjgxGis/edit#

- Bullet points currently follows after paragraph (can align if they have similar length paragraphs above and have similar comparable points for each) so these sections may need to be reworked (example: benefactor does not have points)

**Comment by Saallen** [comment]
Final copy for ticket page

asking @KevZawacki to review for final editting and proofing [here](https://docs.google.com/document/d/1Yz0xET9I5fji9MFEt3ri0YC4vdRQesKZkt2YzjgxGis/edit#)

**Comment by Saallen** [comment]
@sabrinang I made two content changes to be updated in redpen

**Comment by sabrinang** [comment]
Copy updates on latest mockups for reference on https://github.com/mozilla/mozillafestival.org/issues/1002#issuecomment-407521199

Final copy review for https://docs.google.com/document/d/1Yz0xET9I5fji9MFEt3ri0YC4vdRQesKZkt2YzjgxGis/edit# ? 
(@Saallen I left some questions/comments on the doc)

**Comment by Saallen** [comment]
Edits made and all approved
Just waiting on @KevZawacki for final copy review ✏️

**Comment by KevZawacki** [comment]
@Saallen Made a few small tweaks

@sabrinang All set! 👍

**Comment by Saallen** [comment]
Great @KevZawacki-- thanks

**Comment by sabrinang** [comment]
Thanks Kevin! 👍
