### ISSUE TITLE
Ti.to tickets page: Graphic Banner

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#928]
https://ti.to/Mozilla/mozilla-festival-2018

We can use an image with a photo treatment or wordmark to brighten up this page.

**Comment by sabrinang** [comment]
I will reassign milestone once style guide colours are established

**Comment by gideonthomas** [comment]
Anything needed to be done here @sabrinang?

**Comment by sabrinang** [comment]
It already has a photo so I'm assuming we would want to include some colour and/or the wordmark. Would it need any text on it?

**Comment by gideonthomas** [comment]
@marcwalsh (I think?) to provide input here. @sabrinang, I assume this isn't high priority?

**Comment by gideonthomas** [comment]
It might be too late for this (and probably not worth it now)...can we close this @sabrinang?

**Comment by gideonthomas** [comment]
Closing, we can reopen if we really need this
