### ISSUE TITLE
Ti.to tickets page: Update Changes Live

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#929]
https://ti.to/Mozilla/mozilla-festival-2018

Dependent on content from #927 & #928, update the page for attendees.

@Saallen Who is responsible and has access to update the ti.to page? Is it Marc?

**Comment by Saallen** [comment]
For now lets make a production assignee and I can alloccate the work when the team start

**Comment by Saallen** [comment]
Update @marcwalsh is confirming all ti.to updates.

**Comment by marcwalsh** [comment]
I've made updates to the content on ti.to/mozilla/mozilla-festival-2018 based on the [Google Doc](https://docs.google.com/document/d/1Yz0xET9I5fji9MFEt3ri0YC4vdRQesKZkt2YzjgxGis/edit#) in #927 . The only change I needed to make was from bullet points to paragraphs as the tickets are vertically stacked.

**Comment by marcwalsh** [comment]
Closing for now and will reopen if needs further changes.
