### ISSUE TITLE
Partners page: Collect Logos and Apply Treatment

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#931]
Logos are linked on column G in Wrangler bio spreadsheet: https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0

Collect these in google drive and apply a similar colour treatment (greyscale?) and export as PNGs.

**Comment by sabrinang** [comment]
I have collected and edited the 9 logos found in the [spreadsheet](https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0) to be in grayscale:

![image](https://user-images.githubusercontent.com/2492510/41688204-fee19914-749f-11e8-9ea3-1d9ae2695645.png)

They are in gdrive folder here: https://drive.google.com/drive/folders/1AnaSO48BMWpRoZsvJZq6QjlUweK63qMV?usp=sharing

@Saallen Can you review that these are all approved partners seen on the spreadsheet and that I have not missed any?

**Comment by Saallen** [comment]
Hello @sabrinang 
you are missing two logos- more so as they have not been added so I emailed those two groups.
All other logos look great and are ready to be added to partners page.

I have outlined missing logos here and will share once i receive them

Missing logos
- [ ] Open Tech Institute
- [ ] Ada, National College for Digital Skills

**Comment by Saallen** [comment]
Hi @sabrinang nothing back from OTI so just ada to be added to the partner list

**Comment by sabrinang** [comment]
The folder has been updated with Ada, National College for Digital Skills so all 10 logo are found here: 
https://drive.google.com/drive/u/1/folders/1AnaSO48BMWpRoZsvJZq6QjlUweK63qMV
