### ISSUE TITLE
Partners page: Update content

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#932]
https://mozillafestival.org/team/partners/

Update content to be live on the partners page. This includes:
- [x] updating copy from https://github.com/mozilla/mozillafestival.org/issues/930
- [x] adding new partner logos from https://github.com/mozilla/mozillafestival.org/issues/931
- [x] linking partner logos by referring to column H on https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0

**Comment by sabrinang** [comment]
@mmmavis https://github.com/mozilla/mozillafestival.org/issues/931#issuecomment-401118959 logos are in grayscale and exported

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team/partners
