### ISSUE TITLE
Wrangler page: Collect Photos and Apply Treatment

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#933]
https://mozillafestival.org/team/wranglers

Collect wrangler bio photos on google drive and crop or apply treatment if necessary.
Link to photos on column D: https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0

**Comment by Saallen** [comment]
Hi @sabrinang any update here?
