### ISSUE TITLE
Production page: Review/Revise Mark's Bio 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#935]
https://mozillafestival.org/team/production#Mark-Surman

This is Mark's current bio from previous years on the site:

> **Mark Surman**
> _Festival Director_
>
> Mark is Executive Director of the Mozilla Foundation, a global community that does everything from making Firefox to taking stands on issues like privacy and net neutrality. Mark’s main job is to build the movement side of Mozilla, rallying the citizens of the web, building alliances with like-minded organizations and leaders, and growing the open internet movement.

Do we need to update this or is it good to go for this year?

**Comment by KevZawacki** [comment]
Hi @sabrinang, let's change "the Mozilla Foundation" to simply "Mozilla." Otherwise, good to go!

**Comment by mmmavis** [comment]
Thanks @KevZawacki ! I will have that updated!

**Comment by mmmavis** [comment]
Updated! https://mozillafestival.org/team

**Comment by Saallen** [comment]
Reopening this phi asked for new picture. Please use the one found here 
https://www.mozilla.org/en-US/about/leadership/
@mmmavis can you please update

**Comment by sabrinang** [comment]
@mmmavis Mark's photo is in website the asset folder: https://drive.google.com/open?id=1B83671ZiLAoBHp5LzZcuVaCMWC-ZqSSZ

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team/production
