### ISSUE TITLE
Production page: Review/Revise Gunner's Bio 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#936]
https://mozillafestival.org/team/production#Allen-%22Gunner%22-Gunn

This is Gunner's current bio from previous years on the site:

> **Allen “Gunner” Gunn**
> _Co-designer and Emcee_
>
> Gunner is Executive Director of Aspiration in San Francisco, USA, and works to help NGOs, activists, foundations and software developers make more effective use of technology for social change. He is an experienced facilitator with a passion for designing collaborative open learning processes.

Confirm if we need to update this or if it is good as is.

**Comment by Saallen** [comment]
I will take this and check with Gunner

**Comment by Saallen** [comment]
No changes needed @sabrinang
