### ISSUE TITLE
Production page: Revise Robert's Bio

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#937]
https://mozillafestival.org/team/production#Robert-Sayles

This is Robert's current bio from previous years on the site:

> **Robert Sayles**
> _Volunteer Coordinator_
>
> Robby is a Mozilla Rep Mentor based out of Dallas, Texas. He loves volunteering and a big web and aviation feel.

Revise Robert's photo.

**Comment by rtsayles** [comment]
@Saallen Can you update my photo on the website when you have a moment? 
![sayles](https://user-images.githubusercontent.com/5620826/41137226-a5b17fee-6a9f-11e8-8957-a51678819fa8.jpg)

**Comment by sabrinang** [comment]
I changed this ticket so it is for you @rtsayles instead of Tom's. Is your bio text up to date and you just need your photo updated?

**Comment by rtsayles** [comment]
@sabrinang No change from my bio, but can you add Senior Volunteer Coordinator :)

**Comment by Saallen** [comment]
Great photo- how about we add this to your bio @rtsayles ?
Robby is a Mozilla Rep Mentor based out of Dallas, Texas. He loves volunteering and a big web and aviation feel. Long time contributor to Mozilla and MozFest

**Comment by mmmavis** [comment]
> Robby is a Mozilla Rep Mentor based out of Dallas, Texas. He loves volunteering and a big web and aviation feel. Long time contributor to Mozilla and MozFest.

@KevZawacki  Can you help polish up this copy? It seems to be a bit odd to have an incomplete sentence in the end but English is my weakness so I'm hoping to get some help from you 😄

**Comment by mmmavis** [comment]
@KevZawacki awesome thank you!

**Comment by mmmavis** [comment]
@rtsayles does this updated bio look good to you? 😃

**Comment by mmmavis** [comment]
@rtsayles I'm gonna make the call here and update your bio on the site. Do let me know if you don't like your slightly edited bio - I'll change it back immediately :)

**Comment by rtsayles** [comment]
@Saallen <https://github.com/Saallen> @KevZawacki
<https://github.com/KevZawacki> @sabrinang <https://github.com/sabrinang>
@mmmavis <https://github.com/mmmavis>, Love the revised bio, sorry for not
responding sooner.

Robby

**Comment by mmmavis** [comment]
@rtsayles no problem at all! 😉

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team
