### ISSUE TITLE
Production page: Add Production Coordinator and International Travel Event Coordinator Bio

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#939]
The Production Assistant will start in the upcoming months. Add their bio to the page.

**Comment by Saallen** [comment]
@consuelamckenzie can you update this?

**Comment by consuelamckenzie** [comment]
@gideonthomas 
Production Coodinator 
Stephanie is MozFest’s Production Coordinator. Enthused by the contribution she has made to exceptional executions of large-scale international events, through the process of; data analysis, ideation and planning. Stephanie’s analytical mind complimented by her creativity will directly impact and help ensure a seamless and engaging MozFest experience. 

The photograph is to follow.

**Comment by gideonthomas** [comment]
@consuelamckenzie have we confirmed that Stephanie's title is Production Coordinator and not Production Assistant?

**Comment by KevZawacki** [comment]
Hi @gideonthomas, certainly. Slightly edited version below: 

Stephanie is MozFest’s Production Coordinator. She has contributed to several large-scale international events over the years, from data analysis to ideation and planning. Stephanie brings both an analytical mind and deep creativity to her work, and is dedicated to creating a seamless and engaging MozFest experience.

**Comment by gideonthomas** [comment]
Thanks @KevZawacki! @consuelamckenzie I'll get the bio and photo from Amanda. Leaving you assigned to provide Stephanie's photo.

**Comment by gideonthomas** [comment]
@consuelamckenzie any updates on the photo from Stephanie?

**Comment by consuelamckenzie** [comment]
Hi Gideon,

We have two choices;

[Photo 1][https://drive.google.com/open?id=0B0_l7CrAmxgBOFhYSDBBQWdLblN5WjlYeC1VdzFBN2c4S0N3]

[Photo 2](https://drive.google.com/open?id=0B0_l7CrAmxgBZGR0ZXJaMGd1X1NYRC1NNDQxWmFxWi1ySnR3)

Whichever fits best in the circle please.

Many thanks,
Consuela

**Comment by consuelamckenzie** [comment]
Hi @gideonthomas,

We have two choices;

[Photo 1][https://drive.google.com/open?id=0B0_l7CrAmxgBOFhYSDBBQWdLblN5WjlYeC1VdzFBN2c4S0N3]

[Photo 2](https://drive.google.com/open?id=0B0_l7CrAmxgBZGR0ZXJaMGd1X1NYRC1NNDQxWmFxWi1ySnR3)

Whichever fits best in the circle please.

Many thanks,
Consuela

**Comment by consuelamckenzie** [comment]
Hi @gideonthomas 

We have two choices;

[Photo 1](https://drive.google.com/open?id=0B0_l7CrAmxgBOFhYSDBBQWdLblN5WjlYeC1VdzFBN2c4S0N3)
[Photo 2](https://drive.google.com/open?id=0B0_l7CrAmxgBZGR0ZXJaMGd1X1NYRC1NNDQxWmFxWi1ySnR3)

Whichever fits best in the circle please.

Many thanks,
Consuela

**Comment by gideonthomas** [comment]
Thanks @consuelamckenzie! Filed as part of implementation ticket here: https://github.com/mozilla/mozillafestival.org/issues/1116
