### ISSUE TITLE
Production page: Revise Tom's Bio

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#940]
https://mozillafestival.org/team/production#Tom-Farrow

This is Tom's current bio from previous years on the site:

> **Tom Farrow**
> _Volunteer Coordinator_
>
> Tom co-ordinates process, governance and logistics for a number of community teams across Mozilla. With experience in technology and process management, Tom is joining this year's volunteer co-ordinator team. He aims to empower volunteers to feel effective and welcomed over the weekend by bringing in a process and people mindset.

This needs to be revised for this year.

**Comment by sabrinang** [comment]
Hi @TomFarrow 
Please let us know if your bio or photo needs to be revised this year.

**Comment by Saallen** [comment]
@TomFarrow last chance to make changes

**Comment by TomFarrow** [comment]
Hey,
Tom is a second year volunteer co-ordinator for Mozilla Festival, experienced across a large portion of Mozilla's breadth. He primarily handles the planning and local communications for the volunteer program. 

Photo can stay the same :)

Tom

**Comment by TomFarrow** [comment]
![tom farrow](https://user-images.githubusercontent.com/1648878/41872615-52c81a12-78ba-11e8-8175-fdd73b729784.jpg)
actually, why not an update....

also, so sorry it took me so long to get to this!! my email filtering (destroying github) and my time availability got the better of me.

**Comment by Saallen** [comment]
Great photo @TomFarrow 
@kevin can you quickly review this bio?

Tom is a second year volunteer co-ordinator for Mozilla Festival, experienced across a large portion of Mozilla's breadth. He primarily handles the planning and local communications for the volunteer program.

**Comment by sabrinang** [comment]
@KevZawacki Can you review bio above?

**Comment by KevZawacki** [comment]
@sabrinang Sure. Here's the final copy:

Tom is a second-year volunteer coordinator for MozFest, with experience across a large portion of the festival programming. Tom primarily handles planning and local communications for the volunteer program.

**Comment by sabrinang** [comment]
👍
