### ISSUE TITLE
Add new blog post to Call for Proposals page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#941]
Hey can you amend  @mmmavis 
Before you submit:
    Ensure you know which Space you will submit your proposal under
    Get some great tips for desiging your session, read [7 steps ](https://medium.com/mozilla-festival/7-steps-to-a-great-mozfest-proposal-eff4f1cee6fe) and [what makes a great MozFest session](https://medium.com/mozilla-festival/what-makes-a-great-mozilla-festival-session-529dff105185)
    Checked if our FAQ can help with any outstanding questions you might have

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/proposals
