### ISSUE TITLE
Volunteer page: Copy and Links

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#942]
https://mozillafestival.org/volunteer

Update volunteer content.

**Comment by Saallen** [comment]
Volunteers are integral to what we do at Mozilla, and MozFest is no different. The annual festival could not take place without the time, dedication and love of our volunteers.

Volunteer roles are diverse, from registering participants, and running welcome desks on each floor to arranging swag bags and helping with speakers. We do our very best to place people in roles they're most interested in, and we rotate volunteers over the weekend in various roles.

We host monthly meet ups in the Mozilla London office, so volunteers can learn more about the festival, receive training and get to know each other.

Volunteers are asked to share four hours of their time. As a thank you, we’ll cover the festival’s ticket cost. Volunteers also receive meals and a MozFest t-shirt. Unfortunately, we cannot cover travel to and from the event or provide accommodation.  Read more on our volunteer wiki.

Application process for MozFest volunteers is now open


CC @kevinz for review on copy

**Comment by Saallen** [comment]
Pushing back this issue as it wont be ready this heart beat

**Comment by Saallen** [comment]
cc @marcwalsh @consuelamckenzie for review

**Comment by marcwalsh** [comment]
Made a couple of ammends below: mostly just having a more obvious link of where to go to sign up to apply. @KevZawacki @consuelamckenzie is there anything you'd want to change?

Volunteers are integral to what we do at Mozilla, and MozFest is no different. The annual festival could not take place without the time, dedication and love of our volunteers.

Volunteer roles are diverse, from registering participants, and running welcome desks on each floor to arranging swag bags and helping with speakers. We do our very best to place people in roles they're most interested in, and we rotate volunteers over the weekend in various roles.

We host monthly meet ups in the Mozilla London office, so volunteers can learn more about the festival, receive training and get to know each other.

Volunteers are asked to share four hours of their time and as a thank you, we’ll cover the festival’s ticket cost. Volunteers also receive meals while on-site and a MozFest t-shirt. Unfortunately, we cannot cover travel to and from the event or provide accommodation. Read more on our volunteer wiki.

You can apply to be a Mozilla Festival Volunteer [here](link).

**Comment by consuelamckenzie** [comment]
A couple of small changes to aid the word flow.

Volunteers are integral to what we do at Mozilla, and MozFest is no different. The annual festival could not take place without the time, dedication and love of our volunteers.

Volunteer roles are diverse, from registering participants and running welcome desks on each floor to arranging swag bags and helping with speakers. We do our very best to place people in roles they're most interested in and rotate volunteers over the weekend in various roles.

We host monthly meetups in the Mozilla London office, so volunteers can learn more about the festival, receive training and get to know each other.

Volunteers are asked to share four hours of their time and as a thank you, we’ll cover the festival’s ticket cost. Volunteers also receive meals while on-site and a MozFest t-shirt. Unfortunately, we cannot cover travel to and from the event or provide accommodation. 
Read more on our volunteer wiki.

You can apply to be a Mozilla Festival Volunteer [here.](https://github.com/mozilla/mozillafestival.org/issues/link)

**Comment by KevZawacki** [comment]
The version above is great! Just needs a link to the volunteer wiki.

**Comment by sabrinang** [comment]
@marcwalsh 

Can you confirm that this is the volunteer application link: https://ti.to/mozfestvolunteers/mozfest-volunteer-program-2018
and can you confirm this is the volunteer wiki link (currently empty): https://wiki.mozilla.org/Mozfest/2018/Volunteers

**Comment by marcwalsh** [comment]
@sabrinang yes both correct! :)

**Comment by sabrinang** [comment]
**Final Copy**

Volunteers are integral to what we do at Mozilla, and MozFest is no different. The annual festival could not take place without the time, dedication and love of our volunteers.

Volunteer roles are diverse, from registering participants and running welcome desks on each floor to arranging swag bags and helping with speakers. We do our very best to place people in roles they're most interested in and rotate volunteers over the weekend in various roles.

We host monthly meetups in the Mozilla London office, so volunteers can learn more about the festival, receive training and get to know each other.

Volunteers are asked to share four hours of their time and as a thank you, we’ll cover the festival’s ticket cost. Volunteers also receive meals while on-site and a MozFest t-shirt. Unfortunately, we cannot cover travel to and from the event or provide accommodation.
Read more on our [volunteer wiki](https://wiki.mozilla.org/Mozfest/2018/Volunteers).

You can apply to be a Mozilla Festival Volunteer [here](https://ti.to/mozfestvolunteers/mozfest-volunteer-program-2018).
