### ISSUE TITLE
Volunteer page: Graphic Banner

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#943]
https://mozillafestival.org/volunteer

We an change the photo to something more recent.

**Comment by Saallen** [comment]
@sabrinang when you amend the banner for this page can you add this same banner to the tito page for consistancy??
https://ti.to/mozfestvolunteers/mozfest-volunteer-program-2018/admin/settings/homepage

**Comment by sabrinang** [comment]
I will reassign milestone once style guide colours are established
