### ISSUE TITLE
Ti.to volunteer page: URL & Copy

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#944]
Last year's ti.to volunteer page as reference: https://ti.to/mozfestvolunteers/mozfest-volunteer-program-2017

If it has not been made already create a new ti.to page URL for 2018. Create copy for volunteer landing page.

**Comment by Saallen** [comment]
@TomFarrow waiting on the volunteer at Mozfest ti,to page
Do you think it will be done by the end of this week?

**Comment by TomFarrow** [comment]
Hey @Saallen -

Let me check in with Fuzzy. There was some talk about using our volunteer management system for the initial sign up to help with the application, weighting etc. If we can't get that in time (or I don't have an answer tomorrow), then I'll put together a ti.to, and we can feed data back through.

Tom

**Comment by Saallen** [comment]
Hi @tomfarrow please use Tito for sign ups not another platform.

**Comment by TomFarrow** [comment]
Okay, expect a ti.to by tomorrow morning.

**Comment by TomFarrow** [comment]
Hey @Saallen 
Sorry for delay

https://ti.to/mozfestvolunteers/mozfest-volunteer-program-2018

For GDPR I imagine we need to provide
1) Overall responsibility (Mozilla Foundation, E Evelyn?)
2) Point of contact for questions (do we have one?)
3) Privacy Policy (Mozilla's usual one?)
4) Retention Policy (do we include this in PP?)

I don't know Mozilla's position on GDPR compliance, but this is certainly the information I'd provide. Looks like ti.to has a feature to publish it to the signup too.

Also, are we using same branding as last year?

**Comment by Saallen** [comment]
Hi @TomFarrow 

Once the page is set we will ask Legal to review and provide valid links. I am meeting with them today
@sabrinang will be updating branding

Do you mind if I make some edits? As we spoke earlier in the year that this year people would apply to be a volunteer its not a sign up only any more- We need this language stronger on the page so if you agree, I will edit?

Also in your question section- shouldnt we add MozFest house dates??

**Comment by Saallen** [comment]
Photo for tito page 
https://www.flickr.com/photos/mozfest/37312486824/in/album-72157686681997682/

**Comment by Saallen** [comment]
Hi @TomFarrow and @sabrinang 
I amended the page so its reflective as an application process rather than sign up.

I need to update the GDPR piece and will have information for this piece next week

**Comment by Saallen** [comment]
Pushing back this page till next heart beat

**Comment by TomFarrow** [comment]
Sorry, thought I had replied to say I would look at this more today!! Just cleared 1-2 hours each day for working on MozFest, so my availability should be better.

I'm happy with any changes we want to make. Do you have some GDPR info?

Small changelog from today:
- Added T-Shirt Size question
- Fixed years volunteer question, input box didn't make sense
- Prefixed "Apply to" to the ticket description
- Add banner image
- Add festival logo
- Adding a note about this being an application process to the home description

Let me know if you're happy with the changes?

Once we have GDPR covered, I'd be happy personally to open applications @ZiggyMaes @rtsayles 

Tom

**Comment by rtsayles** [comment]
Hi Tom,

I'm ok with opening the application process, we just need to verify if we
have the GDPR covered?

Robby

**Comment by Saallen** [comment]
@TomFarrow @rtsayles 
we are still waiting on legal to confirm the final elements to the data protection-
Once we have full legal compliance @marcwalsh will update your page and confirm here that this link can go live

**Comment by rtsayles** [comment]
Thank you @saallen :)

**Comment by marcwalsh** [comment]
You're fully complied...

✌🏼

**Comment by rtsayles** [comment]
Thank you, Marc 😃
