### ISSUE TITLE
Mozilla Wiki: Volunteer page copy

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#945]
2017 reference: https://wiki.mozilla.org/Mozfest/2017/Volunteers

Dependent on https://github.com/mozilla/mozillafestival.org/issues/861 to create the wiki itself. Update the /volunteers page to be linked on the https://mozillafestival.org/volunteer page.

**Comment by Saallen** [comment]
@rtsayles can you work with the rest of the vol team to update this page in time for the July2nd volunteer sign up opening date

**Comment by rtsayles** [comment]
Absolutely, I'm setting up a meeting next week sp we can update the wiki for 2018 @saallen :)

**Comment by sabrinang** [comment]
any updates on this @TomFarrow @ZiggyMaes ?

**Comment by rtsayles** [comment]
We're meeting tomorrow so we'll help you with the outcome, sorry for the
delay.

**Comment by sabrinang** [comment]
any updates on this piece?

**Comment by TomFarrow** [comment]
hi @sabrinang 

we have a draft in Google Drive - I've added some content to it and will continue to do so. Can we set a date of Friday for the full copy??

Tom

**Comment by sabrinang** [comment]
@TomFarrow or @rtsayles Please provide a google doc draft link for @marcwalsh to review.

**Comment by sabrinang** [comment]
Note: This copy will be published on this URL here: https://wiki.mozilla.org/Mozfest/2018/Volunteers

**Comment by rtsayles** [comment]
Hi @sabrinang, we're meeting this week with @marcwalsh @tomfarrow to go
over this.

**Comment by sabrinang** [comment]
Sounds good, thank you for the issue update @rtsayles!

**Comment by Saallen** [comment]
Hi @rtsayles any update on this page?

**Comment by rtsayles** [comment]
Hey @saallen Do you have access to the Google Drive?   Here's what we have
so far, do you mind taking a look?  If you're ok with it, we can publish it
to the wiki:

https://docs.google.com/document/d/18b9C3Gqa42SZJcQXwPcdzReTMcMAXB-LroN2t3rAMdk/edit#
(Volunteer instructions)
https://docs.google.com/document/d/1FCaiDkPQVixgY6yqtXx6z6AHCOTs5dbPwUPlKm7JGpY/edit
(Volunteer Roles)

CC @Tom Farrow <tom@mozilla.org.uk> @Ziggy Maes
<ziggy.maes@mozilla.org.uk> @Marc
Walsh <marc@mozillafoundation.org> @William Duyck <fuzzyfox0@gmail.com>

**Comment by marcwalsh** [comment]
@rtsayles would you be able to grant me access please? Thanks! :)

**Comment by rtsayles** [comment]
Yes sir.....let me know if you received the email

**Comment by Saallen** [comment]
@rtsayles can I have access too please?

**Comment by rtsayles** [comment]
Hi @saallan, sorry for the delay, I was traveling today but I've share the
docs with you (smiles). Can you review and add any comments. We're meeting
on Sunday to finalize the wiki content, let me know if you have any
questions.

Robby

**Comment by ZiggyMaes** [comment]
Hi all

We just published the first part of the wiki: https://wiki.mozilla.org/Mozfest/2018/Volunteers . We'll continue to expand it as we have more information to share.

**Comment by marcwalsh** [comment]
Thanks @ZiggyMaes - I'll close this issue

**Comment by Saallen** [comment]
Re-opening this ticket
There are some edits required on this page as some of the wording is not correct.
Is this page finalised??

**Comment by sabrinang** [comment]
@marcwalsh Copy review?

**Comment by rtsayles** [comment]
@saallen you should be able to access the wiki to make any changes.  I also notice we're missing the Volunteer roles on the wiki.   @ZiggyMaes @marcwalsh, do we approve the content for that page?

**Comment by marcwalsh** [comment]
I've reviewed and made a couple of small changes and added links to external sites. 

Closing as there's nothing else to add at this time until additional pieces of content (eg. timings) are confirmed.
