### ISSUE TITLE
Volunteer page: Update content

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#946]
https://mozillafestival.org/volunteer

Update content to be live on the volunteers page. This includes:
- updating copy and links from #942 
   - including links to ti.to #944 and wiki #945
- replacing banner to #943

**Comment by Saallen** [comment]
I will write first draft and share with the Vol Coord

**Comment by mmmavis** [comment]
Applying back "blocked" label since banner image is not ready (#943) yet.

**Comment by marcwalsh** [comment]
Both #944 and #945 are complete and live ready for when the volunteers page is updated. 

@mmmavis do you think we'd be able to make this page live by the end of the week?

**Comment by mmmavis** [comment]
@marcwalsh yup I just pushed the changes live: https://mozillafestival.org/volunteer
