### ISSUE TITLE
Fringe page: Create new spreadsheet for fringe events

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#949]
https://mozillafestival.org/fringe

Create a new spreadsheet for the fringe event form submissions for 2018.

**Comment by Saallen** [comment]
@mmmavis let me review last years form before you create a new one. I might change the questions

**Comment by mmmavis** [comment]
2017's form (at the bottom of the page)
 
![screenshot-2018-6-20 mozilla festival](https://user-images.githubusercontent.com/2896608/41671912-57da8ad6-746d-11e8-99e5-b9aaed81c15e.jpg)

**Comment by mmmavis** [comment]
ping @Saallen in case you missed my post above 😉

**Comment by Saallen** [comment]
Hey @mmmavis can you give me access to last years form? I cannot find it myself

**Comment by mmmavis** [comment]
@Saallen https://docs.google.com/spreadsheets/d/1DMl4u2Xxn0wl-SgtxZMb2R2sTpTfSJKcBpBEl1Hb0lQ/edit#gid=0

**Comment by Saallen** [comment]
Assigning @marcwalsh to this ticket,
Marc can you build the fringe event form?

cc @consuelamckenzie for information

**Comment by mmmavis** [comment]
@Saallen @marcwalsh just wanted to clarify there's * no * Google Form behind this.

There are

- a form lives on our site's Fringe page
- a Google Spreadsheet to collect all the event submitted on the Fringe page. There will be a column in that spreadsheet called `approved` and that gets to control what events get to show on the Fringe page.

If you could give me a list of questions and copy I should be able to create a form on our site & spreadsheet.

**Comment by marcwalsh** [comment]
@sabrinang @mmmavis - Looking at the 2017 layout, if it isn't being redesigned, could we try having three columns as we had quite a long list last year?

**Comment by mmmavis** [comment]
# 3-column

It's possible to have 3-column layout but we will end up having narrow, long cards.

![screenshot_2018-07-13 screenshot 1](https://user-images.githubusercontent.com/2896608/42713617-ebc3b5c6-86a4-11e8-8718-3b6733726fe8.png)

# Full-row cards, 2-column layout within each event card

I'm thinking we can change the cards so that they take a full row each, but within the card we can display meta on the left side and description on the right. Although this solution doesn't make the list shorter, I like it because it makes the list more scannable and digestible.

![screenshot_2018-07-13 screenshot 3](https://user-images.githubusercontent.com/2896608/42713626-ef457b58-86a4-11e8-9723-38e862fc0092.png)

Thoughts? @sabrinang @marcwalsh

**Comment by sabrinang** [comment]
@mmmavis I prefer the _Full-row cards, 2-column layout within each event card_ style and I agree it is a lot easier to scan with less empty card space trapped in between since the height adjusts to the variations of event description lengths. 

I'd discourage having the 3-column's as it is too narrow for the variation of description length. If the list is very long, having it sorted by date could be helpful.

**Comment by mmmavis** [comment]
@marcwalsh are you okay with the new design we proposed? It's the "Full-row cards, 2-column layout within each event card" design I attached in this [comment](https://github.com/mozilla/mozillafestival.org/issues/949#issuecomment-404953701).

**Comment by marcwalsh** [comment]
@mmmavis yeah I really like it! I do think we should ensure it sticks at 1 paragraph without line breaks otherwise the list could end up being very long.

**Comment by mmmavis** [comment]
Done. 

### Fringe events spreadsheet
This [sheet](https://docs.google.com/spreadsheets/d/1FiWFtSjiYKmHiQojQ0ZTEsLt9zx4whauV_4gvwG9Xj8/edit#gid=0) controls what get to show on https://mozillafestival.org/fringe . Simply mark the `approved` column with `y` or `yes` on the events you want to show.

### Example screencap for the events section & form

![screenshot_2018-07-17 https mozillafestival-org-staging herokuapp com](https://user-images.githubusercontent.com/2896608/42846072-aed409b0-89cc-11e8-81c9-a8ee8a7976d5.png)

**Comment by mmmavis** [comment]
Updated! https://mozillafestival.org/fringe
