### ISSUE TITLE
Take screenshots of all pages from 2017 CFP phase

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#951]
- take screenshots of all pages on the website from 2017 CFP phase
- share the screenshots with Sarah and Sabrina for future references

**Comment by sabrinang** [comment]
Please post screenshots in this ticket and put in a google drive folder

**Comment by mmmavis** [comment]
@sabrinang where in the google drive should I place the screencaps in?

**Comment by mmmavis** [comment]
Screencaps have been uploaded to https://drive.google.com/drive/folders/1EM9BwrR6K_0NbD-gPtTXE-66KMmXs2EG !
