### ISSUE TITLE
Ti.to MozFest House: Create multiple pages & copy

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#953]
Create Mozilla Festival House pages for various events (e.g. MisinfoCon). 

Create or update the copy on these pages.

**Comment by Saallen** [comment]
Steps for creating new ti.to pages

- [ ] Create standard ticket copy with questions
- [ ] Duplicate per event
- [ ] Find information as per House event listing
- [ ] Share with event manager
