### ISSUE TITLE
Ti.to MozFest House: Graphic banners for main page & multiple events

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#954]
Design a Mozilla Festival House banner for the ti.to page as well as a template to pair with various event partners (e.g. MisinfoCon)

**Comment by sabrinang** [comment]
I will reassign milestone once style guide colours are established

**Comment by sabrinang** [comment]
I made three banner versions for MozFest House event hosts on google slides as a template for them to customize: https://docs.google.com/presentation/d/11xxswOqdsmFf5G9o-2knw0e6tuHKFHDeMoBUOhIhmwU/edit?usp=sharing

It includes instructions to how to use the template and I thought text would be useful to include text and made up some default text:
`Mozilla Festival’s Pre-Week Events`
`October 22-26, 2018 @ Royal Society of Arts`

Ready for review @gideonthomas

**Comment by gideonthomas** [comment]
Thanks @sabrinang, @Saallen, would you be able to review this by tomorrow?

**Comment by Saallen** [comment]
Hey @gideonthomas 
Looks great but could the banner say

MozFest House partnered events
October 22- 26, 2018 @......

**Comment by gideonthomas** [comment]
Thanks @Saallen, so quick :)

@sabrinang would you be able to update that?

**Comment by sabrinang** [comment]
Yes, updated to `Mozilla Festival’s Partnered Events`

**Comment by gideonthomas** [comment]
This is done, link is here: https://docs.google.com/presentation/d/11xxswOqdsmFf5G9o-2knw0e6tuHKFHDeMoBUOhIhmwU/edit?usp=sharing.

Assigning to @lucieclick to utilize as needed (if this Github issue can be closed, feel free to do so).

**Comment by Saallen** [comment]
@marcwalsh made a great point about the dates on the banner- can they be amend to be relevant to the event date in question? @sabrinang @gideonthomas

**Comment by gideonthomas** [comment]
@sabrinang, would you be able to make that an editable field?

**Comment by sabrinang** [comment]
@gideonthomas Yes follow the instructions and it documented in step 4: 

`Optional: Choose Placeholder text banners to place desired text`
<img width="401" alt="image" src="https://user-images.githubusercontent.com/2492510/45374797-0a7e9080-b5a8-11e8-8c6c-df48b5e559db.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/2492510/45374697-ba9fc980-b5a7-11e8-8c33-6e65d4a5a2e6.png">
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/2492510/45374739-d905c500-b5a7-11e8-87c5-45fe01f464fc.png">

**Comment by gideonthomas** [comment]
@Saallen, what you're referring to is the example banner that isn't editable anymore. We changed the template so that only one example is shown and it now clearly mentions that it is an example, to create your own banner, create a new slide.
The new slide layouts for the banners include two sections for the event name and time/date.

Let us know what you think!

**Comment by Saallen** [comment]
Closing this ticket
