### ISSUE TITLE
MozFest House: Event Package

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#955]
Create an event package with information for event partners.

**Comment by Saallen** [comment]
Hey @lucieclick welcome back to github.
@sabrinang is going to get some assets ready for you to use in the new brochure.

**Comment by sabrinang** [comment]
Logo asset links can be found on https://github.com/mozilla/mozillafestival.org/issues/956.
MozFest house design assets will be produced after visual direction is established and after we have scoped out what assets are needed separately.

**Comment by Saallen** [comment]
Closing this issue as assets linked above
