### ISSUE TITLE
MozFest House page: Create new speadsheet for house events

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#957]
https://mozillafestival.org/house

Create a new spreadsheet for the mozfest house event for 2018. This spreadsheet informs the event list that appears on the page.

**Comment by mmmavis** [comment]
Here's [the 2018 sheet](https://docs.google.com/spreadsheets/d/13M_GgrmvC_2CIjfNS15eUiCPuFb_W62dRFIJWK2o8mA/edit#gid=0) cloned from [our 2017 sheet](https://docs.google.com/spreadsheets/d/1YNHtYe_9lowzTAx0mj5XD2DaX3UZX785rVvTt7Vjpps) .
