### ISSUE TITLE
MozFest House page: Add 2018 events section

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#959]
https://mozillafestival.org/house

Add the 2018 house events to the listing after we remove 2017 and create the spreadsheet.

Related issue: #957

**Comment by mmmavis** [comment]
Done! The displaying functionality is there. I turned the switch off for now since we have no events to show at the moment and it will be weird to show an empty section with a big "MozFest House 2018" heading. Once we have events to show, just ping me and I'll toggle the switch on.

**Comment by mmmavis** [comment]
This is what the **Event** section will look when we have events to show.

![screenshot_2018-07-11 mozilla festival 1](https://user-images.githubusercontent.com/2896608/42666730-b216d730-85fb-11e8-9e9c-e9a5e8cdbff9.png)
