### ISSUE TITLE
MozFest House page: Update content

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#961]
https://mozillafestival.org/house

Update content to be live on the MozFest House page. This includes:

- [x] updating copy #960 
- [x] removing 2017 events list #921
- [x] adding 2018 events list #959

**Comment by sabrinang** [comment]
@mmmavis when we have events this can be updated

**Comment by mmmavis** [comment]
Closing this ticket since the checklist included in this ticket has been completed and implementation has been pushed live.

I will create a new ticket for us to add House events to spreadsheet.
