### ISSUE TITLE
Home page: Design mockups

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#962]
Based on https://github.com/mozilla/mozillafestival.org/issues/963

We want to simplify the page and consider: 

- simplifying the banner 
- using video clip more effectively perhaps as a hero background
-  D&D video links are more obvious and simplify this section as "hall of fame" concept

**Comment by sabrinang** [comment]
**Option 1 - Home Page Mockup (separate video style)** 
redpen: https://redpen.io/nk011a4ed19ee0977b
- hero image is a gradient with subtle photo treatment
- excluded CTA bar at the top because these updates will be live when CFP closes

**Option 2 - Home Page Mockup (integrated video banner style)** 
redpen: https://redpen.io/cs6aa0082d55d20d65
- excluded CTA bar at the top because these updates will be live when CFP closes
- hero image is a video with overlay 
- MozFest in Action section removed and replaced with play button (lightbox video launched when pressed)
- event description switched location with dates 
- date section suggestion "Mozilla Festival" instead of "MozFest" to help with SEO etc.
- suggested idea to add "tickets" as a CTA button

Example of motion:
![mozilla-festival_home-hero-example](https://user-images.githubusercontent.com/2492510/42916617-09cc87ea-8abb-11e8-9b3d-202eb26c5939.gif)

Note:
- excluded _MozFest News_ as content is not ready
- left _MozFest Speakers Hall of Fame_ unchanged as it has been updated previously https://github.com/mozilla/mozillafestival.org/issues/964 already but maybe we should include "past" in the title to indicate it is not this year

**Comment by mmmavis** [comment]
Reopening -

@sabrinang the video file is way too big (121M). If we are planning to autoplay video in the background we need to have a shorter clip for that and keep the clip file as small as possible. For reference I checked some reference sites you sent me and the video file sizes are all under 15mb with duration under 20 secs.

Another question - What happens after users click on the play button?

**Comment by sabrinang** [comment]
@mmmavis Thanks for the specs, I made a cut (20 sec) and quality 720p (14.8 mb) for the video that loops: https://drive.google.com/file/d/1OPYaq_hyvnQbBBBUJw-O44SR_G6ac52o/view?usp=sharing

When users click the play button, the background transitions (black opacity 0.9 overlay) to have the video above:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/2492510/43169262-4913f462-8f55-11e8-80a9-ca79420142fd.png">
close button svg: https://drive.google.com/file/d/1OVbYFv7BQfJpkR8FLgpWifbX5DIKZJEc/view

**Comment by sabrinang** [comment]
@mmmavis Good point I didn't try the white version on all the other pages to ensure it is legible. Let's just keep the black 2018 lockup on the homepage for this revision then for consistency. 👍

**Comment by sabrinang** [comment]
@sabrinang update video play button + ticket CTA text at bottom
