### ISSUE TITLE
Home page: "Speaker Hall of Fame" section

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#964]
Based on [June 5th meeting notes](https://docs.google.com/document/d/1Vwk3kezXyaZthe1EIKd2lcmmrR97g4p9-ZDuynPSfhM/edit#) 

We want to simplify the Dialogue and Debates section: 
- decide which speakers we want to feature (and Kevin to decide how many)
     - provide name, topic & bio (short copy that appears underneath photo)
     - provide corresponding photo and youtube recording link

**Comment by Saallen** [comment]
Looks great to me 📸

**Comment by mmmavis** [comment]
Assigning this to myself for implementation.

**Comment by mmmavis** [comment]
Live on https://mozillafestival.org/ 🎉 🎉 🎉 🎉 🎉  🍻

**Comment by Saallen** [comment]
Whhop
