### ISSUE TITLE
About page: Copy & content planning

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#965]
Based on [June 5th meeting notes](https://docs.google.com/document/d/1Vwk3kezXyaZthe1EIKd2lcmmrR97g4p9-ZDuynPSfhM/edit#) 

https://mozillafestival.org/about

We want to rethink what people want on an about page. There may be some overlap with the what to expect page too.

**Comment by sabrinang** [comment]
Meeting doc from today: https://docs.google.com/document/d/1qAF9n2jRRjDHUiaYLcfhiEM85gUofMYiEFREv4OaI0s/edit?usp=sharing

**Rough dates mentioned in call:**
Draft by June 25 
Review starts June 26
Revisions by June 27
Due end of milestone on June 29

/cc @KevZawacki

**Comment by Saallen** [comment]
Approved and reviewed- ready to be added to website @sabrinang 

marks edited letter has been updated and approved by Mark

**Comment by sabrinang** [comment]
Closing - continue on design phase in issue #983
