### ISSUE TITLE
What to Expect page: Copy & content planning

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#966]
Based on [June 5th meeting notes](https://docs.google.com/document/d/1Vwk3kezXyaZthe1EIKd2lcmmrR97g4p9-ZDuynPSfhM/edit#) 

https://mozillafestival.org/expect

We want to rethink what people want on the What to Expect page. There may be some overlap with the about page too.

Related issue #965

**Comment by sabrinang** [comment]
Meeting doc from today: https://docs.google.com/document/d/1qAF9n2jRRjDHUiaYLcfhiEM85gUofMYiEFREv4OaI0s/edit?usp=sharing

Rough dates mentioned in call:
Draft by June 25
Review starts June 26
Revisions by June 27
Due end of milestone on June 29

/cc @KevZawacki

**Comment by caltrider** [comment]
Hey @Saallen @KevZawacki @sabrinang @mmmavis

Here's the updates and copy for the "what to expect" page from @zee-moz and I.

FINAL APPROVAL:
- [ ]     @Saallen

https://docs.google.com/document/d/1DWV7XX0qXiG8nREsOYSAyJ6jTa6tlznlo12yFDQHR_M/edit

**Comment by Saallen** [comment]
Just waiting on two response from @zee-moz and @caltrider  in the doc before I approve

**Comment by caltrider** [comment]
Update made @Saallen

**Comment by sabrinang** [comment]
Closing - continue on design phase in issue #982
