### ISSUE TITLE
ti.to ticketing: Terms set for tickets

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#976]
New addition to tickets on tickets is adding term sets. I am proposing this term set for all tickets at MozFest weekend and house. 
Asking for feedback from #abigailphillips and @trallard 

cc for info @chadsansing and @emmairwin

_By purchasing a ticket to MozFest 22-28 Oct you are agreeing to respect (Mozilla community participation guidelines) {https://www.mozilla.org/en-US/about/governance/policies/participation/].  These guidelines cover our behaviour as participants, facilitators, wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

How to treat each other:
Be respectful and value each other’s ideas, styles and viewpoints.
Be direct but professional; we cannot withhold hard truths.
Be inclusive and help new perspectives be heard.
Appreciate and accommodate our many cultural practices, attitudes and beliefs.
Be open to learning from others.
Lead by example and match your actions with your words.

The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

If you don't respect these guidelines you understand that you will be asked to leave the venue and will not recieve a refund for any ticket purchased._

**Comment by sabrinang** [comment]
@Saallen has done this already - closing.
