### ISSUE TITLE
Sponsors page: Add photo

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#981]
Based on approved design from https://github.com/mozilla/mozillafestival.org/issues/872#issuecomment-401201961

Update sponsors page with photo to break up the section of text. 

Photo: https://westraco.pixieset.com/mozfest2017/p/MTQ3NzUwMjg4MA==-MjM5ODY2MTYwNQ/ (it is also available on the gdrive [here](https://drive.google.com/file/d/196AyS_iyI7EDmJN-JQjn1BJmwhcWc-LJ/view?usp=sharing))

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team/sponsors
