### ISSUE TITLE
What to Expect page: Design Mockups

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#982]
Based on content from https://github.com/mozilla/mozillafestival.org/issues/966

https://mozillafestival.org/expect

Create revised design mockups to be approved before we implement it on the website.

**Comment by sabrinang** [comment]
@Saallen Please review and leave any specific comments on redpen here: https://redpen.io/dnc152cb247c41348d

**Comment by Saallen** [comment]
cc @marcwalsh @consuelamckenzie please review ahead of our meeting today but do not comment on the redpen

**Comment by Saallen** [comment]
Edits added for @sabrinang

**Comment by consuelamckenzie** [comment]
@sabrinang Hi Sabrina, here is a suggested table edit. Excuse the poor sketch....

**Comment by consuelamckenzie** [comment]
@sabrinang Here is a suggested table edit. Apologies for the poor sketch.... <img width="801" alt="screen shot 2018-07-11 at 15 52 36" src="https://user-images.githubusercontent.com/40797384/42580451-7b2beb5e-8522-11e8-9b07-eda4ade288e8.png">

**Comment by sabrinang** [comment]
**Revisions**
- Top 7 Reasons section: copy "innovations" and "at our Dialogue and Debate"
- Week at a Glance: separated schedule with event and venue heading, copy "Programs begin"

**Note**
- I'd suggest we put an end time for programs for MozFest House schedule so attendees know when it closes

Copy question for @KevZawacki, Sarah asked if list items in [Top 7 Reasons section](https://redpen.io/dnc152cb247c41348d/2?showing_comment=3114457) needs full stops?
____________________

Final approval: 
- [ ] @Saallen 
Mockup revision on redpen here: https://redpen.io/dnc152cb247c41348d

**Comment by sabrinang** [comment]
@Saallen Also, since the title is changed what title do you want on the navigation bar? 

For example, _About MozFest_ becomes "About". Did you want the full title (may be repetitive) or shorten this (may sound odd)?

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/2492510/42658038-fcf79618-85d8-11e8-8da9-31aa4a302bda.png">

**Comment by consuelamckenzie** [comment]
@sabrinang @Saallen; The title on the navigation bar seems fine as 'why come to Mozfest'. Perhaps when the schedule is inserted we can change this to 'why come?', to allow for additional spacing needs on the title bar.

In terms of graphics and visual the spacing is certainly better presently with the first option. The repetition doesn't matter here.

**Comment by KevZawacki** [comment]
Hi @sabrinang, no need for periods at the ends of 'Top 7 Reason' sentences

**Comment by sabrinang** [comment]
@consuelamckenzie Thanks for the feedback on the nav bar will keep it as "why come to MozFest"
@KevZawacki Thanks for the feedback and I changed double hyphens to em dashes here too.

I updated the redpen to reflect these. Closing this issue and dev work will continue on https://github.com/mozilla/mozillafestival.org/issues/1001

Since @Saallen is away we will get her final approval there before the page goes live.

**Comment by sabrinang** [comment]
note: redpen https://redpen.io/dnc152cb247c41348d revised with comments from https://github.com/mozilla/mozillafestival.org/issues/1004

**Comment by sabrinang** [comment]
Assets exported on gdrive here: https://drive.google.com/open?id=1MqDo8xqUzrFg0Vh-nz-yIMGvKtay7GtT

Colour: #362FC1
<img width="510" alt="image" src="https://user-images.githubusercontent.com/2492510/42972122-4ed9188c-8b63-11e8-99df-ded5785596ab.png">
