### ISSUE TITLE
About page: Design Mockups

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#983]
Based on content from https://github.com/mozilla/mozillafestival.org/issues/965

https://mozillafestival.org/about

Create revised design mockups to be approved before we implement it on the website.

**Comment by sabrinang** [comment]
@Saallen Please review and leave any specific comments on redpen here: https://redpen.io/xp5216f8cdd1a599f5

**Comment by Saallen** [comment]
@marcwalsh  and @consuelamckenzie please review ahead of our meeting today but dont comment on the red pen

**Comment by Saallen** [comment]
approved with edit requests @sabrinang

**Comment by sabrinang** [comment]
**Revisions**
- Top Bar: copy changed to "Submit your session now for the MozFest 2018 weekend! Sumissions deadline is August 1"
- Lead text added “and beyond.” 

**Note**
- Make top bar link to https://mozillafestival.org/proposals

Copy questions for @KevZawacki, Sarah asked if descriptions in [Spaces section](https://redpen.io/xp5216f8cdd1a599f5?showing_comment=3114445) needs full stops? and are [-- seen in the copy](https://redpen.io/xp5216f8cdd1a599f5?showing_comment=3115230) em dashes —?
____________________

Final approval: 
- [ ] @Saallen 
Mockup revision on redpen here: https://redpen.io/xp5216f8cdd1a599f5

**Comment by KevZawacki** [comment]
Hi @sabrinang 

No need to full stops in the Space descriptions. And, yes, let's use em (—) dashes.

**Comment by sabrinang** [comment]
@KevZawacki Thanks for the review! 

I updated the redpen so _Open Innovation_ is _Openness_ and using em dashes. Closing this issue and dev work will continue on https://github.com/mozilla/mozillafestival.org/issues/1000.

Since @Saallen is away we will get her final approval there before the page goes live.

**Comment by mmmavis** [comment]
@sabrinang can you export all the assets and include the link to download them here? Thanks!

**Comment by sabrinang** [comment]
Assets exported on gdrive here: https://drive.google.com/open?id=1MMqLdqEfTaBtYUlSv4uQRPmpbn0Rx1Us

Background Colours:

opacity: 0.1

orange #FF9700
yellow #F9EE08
pink #FF40FF
green #00FF6D
cyan #00FAFF
purple #8336FF

**Comment by mmmavis** [comment]
thanks!
