### ISSUE TITLE
Partners page: missing links & logos might need to be re-processed

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#985]
https://mozillafestival.org/team/partners

# Site Links

@Saallen just wanted to double check - I wasn't sure if we wanna link the following organizations to their websites since no URLs were provided. 

- Universidade Federal de Alagoas
- Media Party
- UAL

# Logos

![screenshot_2018-07-04 mozilla festival](https://user-images.githubusercontent.com/2896608/42289346-cace9ddc-7f73-11e8-9a1c-5949a36f0bb2.png)

@sabrinang logos of the following organizations have white background. Do we wanna turn them into transparent or the white background was by design?

- Aletheia
- Media Party
- UAL

**Comment by sabrinang** [comment]
@mmmavis Let's remove the grey box so the white jpeg issue won't be an issue

**Comment by mmmavis** [comment]
as discussed in today's meeting - let's not worry about the missing links.

**Comment by sabrinang** [comment]
@mmmavis I uploaded bbc r&d and ravensbourne logo in the folder with white or transparent bg: https://drive.google.com/open?id=1AnaSO48BMWpRoZsvJZq6QjlUweK63qMV

**Comment by mmmavis** [comment]
Done! https://mozillafestival.org/team/partners
