### ISSUE TITLE
TITO- GDPR and new terms layout

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#986]
Now every person looking to purchase a mozfest ticket must agree with the following question
![screen shot 2018-07-04 at 19 22 00](https://user-images.githubusercontent.com/10194015/42291543-3fa0d38c-7fc4-11e8-9310-d6ff3d36dab1.png)

**Comment by Saallen** [comment]
Then within the next stage our terms and conditions are highlighted
![screen shot 2018-07-04 at 18 16 33](https://user-images.githubusercontent.com/10194015/42291576-788f9cd2-7fc4-11e8-929c-77f79293823d.png)

**Comment by Saallen** [comment]
![screen shot 2018-07-04 at 19 22 13](https://user-images.githubusercontent.com/10194015/42291594-918000c4-7fc4-11e8-9721-9745870ea25e.png)

**Comment by sabrinang** [comment]
@Saallen Any updates or details on how to close this issue?

**Comment by marcwalsh** [comment]
@sabrinang - I'm closing as it's currently being talked through with legal on email.
