### ISSUE TITLE
Production page: Add Production Manager Bio

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#991]
https://mozillafestival.org/team/production

Consuela, please provide a short bio and a photo for the production page.

**Comment by Saallen** [comment]
@consuelamckenzie please add a short bio for the website, and a picture

**Comment by consuelamckenzie** [comment]
Writing about yourself in the third person is always interesting!...

Either of these?

Consuela is the Production Manager of Mozfest, she has managed hundreds of varied media and event productions and adds to the team two decades in senior company roles for a diverse group of startup media businesses and established worldwide brands. For the festival her focus is primarily on providing a streamlined event and inclusive collaborative hub to the Moz fest community by continuing the creation of an environment where freedom of expression, innovation, and creativity can thrive.  

Consuela travels around the globe frequently and is inspired by passion and creativity in music and the arts all over the world. She is an avid supporter and participator in the charitable sector.

![unnamed](https://user-images.githubusercontent.com/40797384/42524509-9f89cf9e-8468-11e8-831d-bd40d9591994.jpg)

A new face and energy to the production team, always looking for new ideas and innovative ways to produce projects. Consuela is joining the Mozfest team this year as our Production Manager.

**Comment by sabrinang** [comment]
@consuelamckenzie Can you reduce the bio length so it is approximately 3 sentences? 
See other bios for length reference here: https://mozillafestival.org/team

**Comment by sabrinang** [comment]
@KevZawacki Can you review and choose a bio above?

**Comment by KevZawacki** [comment]
@sabrinang & @consuelamckenzie Sure! How about:

Consuela is MozFest production manager. She has headed hundreds of media productions and events, and is an advocate for events as a tool to bring people together to share in purposeful experiences. Consuela seeks to create a festival where freedom of expression, innovation, and creativity can thrive.

**Comment by consuelamckenzie** [comment]
@KevZawacki @sabrinang 
The only thing I would say apart from the apostrophe after Mozfest is from my understanding the festival has this environment already, hence the "continues in the creation'. Otherwise looks good to me...and is 3 lines!

**Comment by sabrinang** [comment]
Ok thanks @KevZawacki & @consuelamckenzie I added the apostrophe and included the _continues_ wording. 

**Final Copy:**

Consuela is MozFest's production manager. She has headed hundreds of media productions and events, and is an advocate for events as a tool to bring people together to share in purposeful experiences. Consuela continues to create a festival where freedom of expression, innovation, and creativity can thrive.
