### ISSUE TITLE
CFP - Data Protection Updates

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/mozillafestival.org#996]
I talked to Abigail from Legal who had a few recommendations for updates to Call For Proposals page.

- [x] In opening paragraph, add 'Country' to the list of private information.

- [x] At the bottom of the opening paragraph add of text add a line to explain if users proposals are accepted that we will add this information onto Guidebook.

- [x] Add a checkbox for users agreeing for us to handle their information in accordance with the Mozilla Privacy Policy.

- [x] ~~Add a checkbox for users who want to sign up to Mozilla Festival updates.~~

Abigail will be sending through some copy for this soon, I'll comment below once I have it.

**Comment by marcwalsh** [comment]
@mmmavis - Are you happy for these to be in HB2?

**Comment by marcwalsh** [comment]
**Copy update below for the top paragraph:**

Remove this sentence (“All information you submit here, apart from email and Twitter handle will be seen publicly”) from the second paragraph at the top, and add two new bullet points at the top or bottom of the bullet list:

- The information you submit here will be made publicly available on Github, except for your email address, Twitter handle, and country of residence.  

- If your submission is successful, your name and session information will be added to the MozFest schedule in Guidebook, and you will be issued a ticket to MozFest through our ticketing platform, Tito. Mozilla will provide Tito with your name and email address for this purpose.

**Comment by marcwalsh** [comment]
The Guidebook line will need to include Twitter Handle if we plan on including this in Guidebook also.

**Comment by marcwalsh** [comment]
** Additions To Form **

Above the “Submit” button at the bottom of the form, please add a tickbox with: “I’m okay with Mozilla handling this information in accordance with its privacy policy and the bullets at the top of this form.”

Another checkbox will also need to be added for the mailing list sign up.

**Comment by marcwalsh** [comment]
@mmmavis 

- It should be a required field
- I'll check in with legal regarding the wording again
- It's a non-required checkbox, they can choose whether we send them the MozFest newsletters that go out, however this isn't priority as it's not something we normally add into ti.to unless we give them a ticket, when they'll be asked during their ticket allocation if they'd like to sign up.

**Comment by marcwalsh** [comment]
@mmmavis - The existing question is perfect, thanks! maybe but if you have any questions please contact the Festival Team with a link to festival@mozilla.org. 

Just incase there is an instance of someone not wanting the data going onto GitHub.

**Comment by marcwalsh** [comment]
@mmmavis - Could you change the last bullet point to just this:

If your submission is successful, your name and session information will be added to the MozFest schedule in Guidebook.

Would it be possible for you to make these changes live as soon as possible as we'll be getting a lot of sign ups in the last few days. :)

**Comment by Saallen** [comment]
@marcwalsh  we are still missing your response to the second request as per the mailing list

suggestion for Marc- could the question be ??
- [ ] I understand and agree that the data collected will be used by Mozilla in accordance with our Privacy Policy, and we will email you about your session and MozFest 2018

**Comment by mmmavis** [comment]
(a note for myself: remove "Twitter handle" from opening section - we won't show people's Twitter handles on Guidebook)

**Comment by marcwalsh** [comment]
@Saallen yes that works!

**Comment by marcwalsh** [comment]
@Saallen I think we need to separate it considering we will need to email people to let them know if they are successful. 

So changing the first question to:

- [ ] I’m okay with Mozilla handling this information in accordance with its privacy policy and the bullets at the top of this form as well as to be emailed reguarding the outcome of my proposal. 

and then adding...

- [ ] I would like to be kept up to date about MozFest 2018 and future Mozilla events.

**Comment by Saallen** [comment]
Yes - happy with this copy. Just link the privacy policy
Please update @mmmavis

**Comment by marcwalsh** [comment]
Thanks @Saallen! @mmmavis I've listed all the additional changes we need below! :)

- [ ] Change copy of first privacy question to: `I’m okay with Mozilla handling this information in accordance with its privacy policy and the bullets at the top of this form as well as to be emailed reguarding the outcome of my proposal.`
- [ ] Ensure first question is a required field.
- [ ] Change error message if left unchecked to: `Please check this box if you would like like to proceed, if you have a question please email festival@mozilla.org.`
- [ ] Add additional privacy question (not required): `I would like to be kept up to date about MozFest 2018 and future Mozilla events.`
- [ ] Remove "Twitter handle" from opening section.

**Comment by Saallen** [comment]
Thanks @marcwalsh 
@mmmavis Can we make this update top priority please as we are a week from closing the call?

**Comment by mmmavis** [comment]
Done. https://mozillafestival.org/proposals
