### ISSUE TITLE
QA: Outstanding Wrangler Bio and Photos

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#998]
Even though the deadline passed, I'll be assigning corresponding missing pieces of content to owners so they providing missing content. 

Missing content may be problematic when design the festival guide and website as it looks incomplete and unfinished. https://mozillafestival.org/team/wranglers

Missing content in the spreadsheet here: https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0

**Comment by marcwalsh** [comment]
Assigning myself to collect these. 

@zee-moz & @Saallen - just want to check that you haven't been in contract with the outstanding people already?

**Comment by sabrinang** [comment]
@marcwalsh I have only assigned their emails to the spreadsheet cell of content they are missing but have not contacted them otherwise.

**Written Bios we are missing:**
- Joseph Thomas

**Photos we are missing:**
- Mark Boas
- Kade Morton
- Natasha Pillai
- Tendai Tirivanhu
- Victor Sansing
- Joseph Thomas

A headshot is highly preferred to match the other bio photos for our guide and for attendees to recognize them. If they do not have one, can they supply an avatar image that represents themselves or take a phone photo of themselves?

**Comment by sabrinang** [comment]
@kevzawacki 
Can you please review the [spreadsheet](https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0) comments that contain wranglers bios from:

- Natasha Pillai
- Jon Tutcher
- Tina Gotschi (this appears added to the cell but not reviewed)

Can you add them to the cell itself once it is reviewed?

**Comment by sabrinang** [comment]
Updated 500x500 cropped bio photos:
- Jon Tutcher: https://drive.google.com/file/d/1NQB9u6hCKyLBMhrShD98PuZq3HnFw1A0/view
- Mandy Rawlings: https://drive.google.com/file/d/1NL7jln_qaHXRjjuV1c28l0-ksfNKgUxA/view
- Juma Baldeh: https://drive.google.com/file/d/1N-lRtqfADLlcMCgUsim6IDxR_jZ-l9Fs/view

Which are added to the rest of the [500x500 photos folder](https://drive.google.com/drive/folders/1Bf6Jts4aVP5O8bcA8fZoYcuM9PdM5Nk7)

**Comment by KevZawacki** [comment]
Hi @sabrinang, reviewed and added 👍

**Comment by sabrinang** [comment]
Thanks Kevin for the review!

@marcwalsh any updates on collecting
written bios from:
- Joseph Thomas

photos from:
- Mark Boas
- Kade Morton
- Natasha Pillai
- Tendai Tirivanhu
- Victor Sansing
- Joseph Thomas

I am also missing bios and photos from the Gaming MozFest experience wranglers but I don't have any of their emails so it would be great if you can help collect those too.

**Comment by marcwalsh** [comment]
@sabrinang Just chased almost everyone (including gaming experiene wranglers) and given them the deadline of the end of this week.

I don't have Victor's email so haven't been able to add him yet. I've noticed he is in high school and it says [No Photo] in the comment box. Does this mean we're not able to add an image of him online?

**Comment by Saallen** [comment]
Exactly @marcwalsh he doesnt want his picture on the site

**Comment by marcwalsh** [comment]
@sabrinang I've updated the Google Doc with image links and commented where I've added them.

Joseph's bio is also in there and I've tagged Kevin for approval / copy changes.

**Comment by KevZawacki** [comment]
@sabrinang bio approved 👍

**Comment by Saallen** [comment]
@zee-moz can you add your bio here - you are working really hard with the wranglers and it would be great to celebrate with a picture too

**Comment by Saallen** [comment]
Winnie would like us to remove this line from her bio
"She is currently a safety supervisor at Mpesa Foundation Academy, Kenya"

**Comment by Saallen** [comment]
Hello
I have more details for new wranglers in the queering space and names for the gaming space- can I please have access to the doc @sabrinang

**Comment by zee-moz** [comment]
@Saallen @sabrinang Here is my bio:

Zannah is an artist, writer, and experience designer. She’s created interactive museum exhibits about everything from ancient gods to cold war spies to black bears. Zannah lives in Gainesville, Florida where she draws comics, rides bikes, and keeps backyard chickens. She’s a member of Mozilla’s Open Leadership and Events team. 

What are the size/resolution requirements for the photo?

**Comment by sabrinang** [comment]
@zee-moz Great! I’ll be cropping it so it can roughly follow this:

- 500x500px for screen (after crop to a headshot for consistency)
- 2x2in 300dpi for print (most likely it will show up ~1” in the guide due to space limitations but larger if you have just in case)

Let me know which section it should be added in (wrangler or production)?

**Comment by sabrinang** [comment]
@Saallen Can you leave the new info as comments in corresponding cells so we know what has not yet been reviewed? It will get included in the cell itself after by Kevin once he has reviewed the content

**Comment by Saallen** [comment]
@marcwalsh  we have two new wranglers for Queering MozFest- will send you their details separately

**Comment by Saallen** [comment]
@mmavis can you edit Winnies request to remove the line from her bio as above?
"She is currently a safety supervisor at Mpesa Foundation Academy, Kenya"

If you could do this today as she is anxious to see it editted. Thanks

**Comment by mmmavis** [comment]
@Saallen k doing that edit now. @Saallen if it's something urgent it'd be better to have a separate ticket and have it assigned to me. That way I will notice the ping sooner since I don't usually check GitHub tickets that aren't assigned to me as my inbox gets pretty crazy every day with all the GitHub notifications. 😉

**Comment by gideonthomas** [comment]
cc @gideonthomas

**Comment by gideonthomas** [comment]
Hi @marcwalsh, thanks for being proactive with this. Would you be able to update the following in the spreadsheet as soon as possible, latest by the end of the week?

1. Photo for Mark Boas
2. Photo for Zannah Marsh (I've also reached out personally)
3. Photo for Edoardo Viola needs to be accessible (I'm getting a permission issue)
4. Photo from Mariano Blejman is incorrect
5. Photo for Simone Ram needs to be accessible (I'm getting a permission issue)
6. Photo for Stéphanie Ouillon is incorrect
7. Photo for Kevin Zawacki
8. Photos and bios for the 2 new wranglers for Queering Mozfest
9. Photos and bios for the Gaming Mozfest wranglers

**Comment by zee-moz** [comment]
@gideonthomas I sent my photo to @sabrinang last week! 
will forward to you

**Comment by sabrinang** [comment]
@gideonthomas Sorry I haven't updated this issue I have exported cropped photos of:
- Kade Morton
- Natasha Pillai
- Tendai Tirivanhu
- Zannah Marsh
- Simone Ram (I got access)
- Edoardo Viola (I got access)
- Mariano Blejman (found same one online)
- Stéphanie Ouillon (photo from last year)
- we have Kevin’s photo from production team page

The 500x500 cropped versions can be found with the others here: https://drive.google.com/open?id=1Bf6Jts4aVP5O8bcA8fZoYcuM9PdM5Nk7

Missing: 
- Mark Boas 
- Photos and bios for the 2 new wranglers for Queering Mozfest
- Photos and bios for the Gaming Mozfest wranglers

**Comment by gideonthomas** [comment]
Perfect, thanks for the clarification @sabrinang, @marcwalsh are those three doable by the end of the week?

**Comment by marcwalsh** [comment]
@gideonthomas I've sent out emails to everyone asking for a bio and photo by the end of the week. I'll update the spreadsheet and list below as they are coming through.

---

- [ ] Mark Boas (Photo)
- [x] Sarah Aoun (Bio and Photo)
- [ ] Marnie Pasciuto Wood (Bio and Photo)
- [ ] Ashlyn Sparrow (Bio and Photo)
- [ ] Rebecca Ricks (Bio and Photo)
- [ ] Hang Do Thi Duc (Bio and Photo)

**Comment by gideonthomas** [comment]
That's great, thanks @marcwalsh! We can evaluate what's remaining by the end of the week and add them in the next heartbeat if necessary

**Comment by gideonthomas** [comment]
Thanks for all the updates @marcwalsh! Filed the final implementation ticket: https://github.com/mozilla/mozillafestival.org/issues/1095. If there are any other updates that need to happen (e.g. photo for Mark Boas), please feel free to file a new ticket with the content. I'm going to close this ticket for brevity.
